# -*- coding: utf-8 -*-
"""Translations for strings that only exist in the Plasmai app (Plasma Mobile / Android)
and in the vendored kirigami-addons. Merged with the per-language dictionaries by fill_po.py.

Column order: en, de, fr, es, it, nl, pt_BR, pl, uk, ru, ja, zh_CN
"""

LANGS = ["en", "de", "fr", "es", "it", "nl", "pt_BR", "pl", "uk", "ru", "ja", "zh_CN"]

ROWS = [
    ("Add",
     "Hinzufügen", "Ajouter", "Añadir", "Aggiungi", "Toevoegen", "Adicionar", "Dodaj", "Додати", "Добавить", "追加", "添加"),
    ("Use this",
     "Verwenden", "Utiliser", "Usar este", "Usa questo", "Gebruiken", "Usar este", "Użyj", "Використати", "Использовать", "これを使用", "使用此项"),
    ("Active: %1",
     "Aktiv: %1", "Actif : %1", "Activo: %1", "Attivo: %1", "Actief: %1", "Ativo: %1", "Aktywny: %1", "Активний: %1", "Активен: %1", "有効: %1", "当前: %1"),
    ("Provider:",
     "Anbieter:", "Fournisseur :", "Proveedor:", "Provider:", "Aanbieder:", "Provedor:", "Dostawca:", "Постачальник:", "Провайдер:", "プロバイダー:", "服务商:"),
    ("https://your-server.com",
     "https://ihr-server.de", "https://votre-serveur.com", "https://su-servidor.com", "https://il-tuo-server.com", "https://uw-server.nl", "https://seu-servidor.com", "https://twoj-serwer.pl", "https://ваш-сервер.com", "https://ваш-сервер.com", "https://your-server.com", "https://your-server.com"),
    ("API Token:",
     "API-Token:", "Jeton API :", "Token de API:", "Token API:", "API-token:", "Token da API:", "Token API:", "API-токен:", "API-токен:", "APIトークン:", "API 令牌:"),
    ("Token stored.",
     "Token gespeichert.", "Jeton enregistré.", "Token guardado.", "Token salvato.", "Token opgeslagen.", "Token armazenado.", "Token zapisany.", "Токен збережено.", "Токен сохранён.", "トークンは保存済みです。", "令牌已存储。"),
    ("No token stored.",
     "Kein Token gespeichert.", "Aucun jeton enregistré.", "No hay token guardado.", "Nessun token salvato.", "Geen token opgeslagen.", "Nenhum token armazenado.", "Brak zapisanego tokenu.", "Токен не збережено.", "Токен не сохранён.", "トークンが保存されていません。", "未存储令牌。"),
    ("Enter API token…",
     "API-Token eingeben…", "Saisir le jeton API…", "Introduce el token de API…", "Inserisci il token API…", "API-token invoeren…", "Insira o token da API…", "Wpisz token API…", "Введіть API-токен…", "Введите API-токен…", "APIトークンを入力…", "输入 API 令牌…"),
    ("Token saved.",
     "Token gespeichert.", "Jeton enregistré.", "Token guardado.", "Token salvato.", "Token opgeslagen.", "Token salvo.", "Token zapisany.", "Токен збережено.", "Токен сохранён.", "トークンを保存しました。", "令牌已保存。"),
    ("Failed to save",
     "Speichern fehlgeschlagen", "Échec de l’enregistrement", "Error al guardar", "Salvataggio non riuscito", "Opslaan mislukt", "Falha ao salvar", "Nie udało się zapisać", "Не вдалося зберегти", "Не удалось сохранить", "保存に失敗しました", "保存失败"),
    ("Clear",
     "Löschen", "Effacer", "Borrar", "Cancella", "Wissen", "Limpar", "Wyczyść", "Очистити", "Очистить", "クリア", "清除"),
    ("Token removed.",
     "Token entfernt.", "Jeton supprimé.", "Token eliminado.", "Token rimosso.", "Token verwijderd.", "Token removido.", "Token usunięty.", "Токен видалено.", "Токен удалён.", "トークンを削除しました。", "令牌已移除。"),
    ("Failed",
     "Fehlgeschlagen", "Échec", "Error", "Non riuscito", "Mislukt", "Falhou", "Niepowodzenie", "Помилка", "Ошибка", "失敗しました", "失败"),
    ("Test",
     "Testen", "Tester", "Probar", "Prova", "Testen", "Testar", "Testuj", "Перевірити", "Проверить", "テスト", "测试"),
    ("Testing…",
     "Teste…", "Test en cours…", "Probando…", "Test in corso…", "Testen…", "Testando…", "Testowanie…", "Перевірка…", "Проверка…", "テスト中…", "正在测试…"),
    ("Testing… (%1)",
     "Teste… (%1)", "Test en cours… (%1)", "Probando… (%1)", "Test in corso… (%1)", "Testen… (%1)", "Testando… (%1)", "Testowanie… (%1)", "Перевірка… (%1)", "Проверка… (%1)", "テスト中… (%1)", "正在测试… (%1)"),
    ("Connection OK!",
     "Verbindung OK!", "Connexion OK !", "¡Conexión correcta!", "Connessione OK!", "Verbinding OK!", "Conexão OK!", "Połączenie OK!", "З’єднання OK!", "Подключение OK!", "接続OK！", "连接正常！"),
    ("Missing URL or token (type: %1)",
     "URL oder Token fehlt (Typ: %1)", "URL ou jeton manquant (type : %1)", "Falta la URL o el token (tipo: %1)", "URL o token mancante (tipo: %1)", "URL of token ontbreekt (type: %1)", "URL ou token ausente (tipo: %1)", "Brak adresu URL lub tokenu (typ: %1)", "Бракує URL або токена (тип: %1)", "Отсутствует URL или токен (тип: %1)", "URLまたはトークンがありません (種類: %1)", "缺少 URL 或令牌（类型：%1）"),
    ("Tap a project to see its activities, then pin the ones you use often.",
     "Tippe auf ein Projekt, um dessen Tätigkeiten zu sehen, und pinne die, die du oft nutzt.",
     "Touchez un projet pour voir ses activités, puis épinglez celles que vous utilisez souvent.",
     "Toca un proyecto para ver sus actividades y fija las que uses con frecuencia.",
     "Tocca un progetto per vedere le sue attività, poi fissa quelle che usi spesso.",
     "Tik op een project om de activiteiten te zien en maak de vaak gebruikte favoriet.",
     "Toque em um projeto para ver suas atividades e fixe as que você mais usa.",
     "Dotknij projektu, aby zobaczyć jego aktywności, a następnie przypnij te, których często używasz.",
     "Торкніться проєкту, щоб побачити його активності, і закріпіть ті, якими часто користуєтеся.",
     "Коснитесь проекта, чтобы увидеть его активности, и закрепите те, что используете часто.",
     "プロジェクトをタップしてアクティビティを表示し、よく使うものをピン留めします。",
     "点按项目查看其活动，然后固定常用的活动。"),
    ("Connect a time tracker first",
     "Verbinde zuerst einen Zeiterfassungsdienst", "Connectez d’abord un service de suivi du temps", "Conecta primero un servicio de control de tiempo", "Collega prima un servizio di tracciamento del tempo", "Verbind eerst een tijdregistratiedienst", "Conecte primeiro um serviço de controle de tempo", "Najpierw połącz usługę śledzenia czasu", "Спершу підключіть сервіс обліку часу", "Сначала подключите сервис учёта времени", "先に時間管理サービスを接続してください", "请先连接时间追踪服务"),
    ("Day",
     "Tag", "Jour", "Día", "Giorno", "Dag", "Dia", "Dzień", "День", "День", "日", "日"),
    ("Month",
     "Monat", "Mois", "Mes", "Mese", "Maand", "Mês", "Miesiąc", "Місяць", "Месяц", "月", "月"),
    ("Year",
     "Jahr", "Année", "Año", "Anno", "Jaar", "Ano", "Rok", "Рік", "Год", "年", "年"),
    ("Go Previous",
     "Zurück", "Précédent", "Anterior", "Precedente", "Vorige", "Anterior", "Wstecz", "Назад", "Назад", "前へ", "上一页"),
    ("Jump to today",
     "Zu heute springen", "Aller à aujourd’hui", "Ir a hoy", "Vai a oggi", "Naar vandaag", "Ir para hoje", "Przejdź do dziś", "Перейти до сьогодні", "Перейти к сегодня", "今日へ移動", "跳转到今天"),
    ("Go Next",
     "Weiter", "Suivant", "Siguiente", "Successivo", "Volgende", "Próximo", "Dalej", "Далі", "Вперёд", "次へ", "下一页"),
    ("Hours",
     "Stunden", "Heures", "Horas", "Ore", "Uren", "Horas", "Godziny", "Години", "Часы", "時", "小时"),
    (":",
     ":", ":", ":", ":", ":", ":", ":", ":", ":", ":", ":"),
    ("Minutes",
     "Minuten", "Minutes", "Minutos", "Minuti", "Minuten", "Minutos", "Minuty", "Хвилини", "Минуты", "分", "分钟"),
    ("Start tracking when you begin work.",
     "Starte die Zeiterfassung, wenn du mit der Arbeit beginnst.", "Démarrez le suivi quand vous commencez à travailler.", "Inicia el seguimiento cuando empieces a trabajar.", "Avvia il tracciamento quando inizi a lavorare.", "Start de tijdregistratie wanneer je begint met werken.", "Inicie o rastreamento quando começar a trabalhar.", "Włącz śledzenie czasu, gdy zaczynasz pracę.", "Почніть відстеження, коли починаєте роботу.", "Запустите учёт времени, когда начинаете работу.", "作業を始めるときに計測を開始します。", "开始工作时开始计时。"),
    ("%1h %2m",
     "%1h %2m", "%1h %2m", "%1h %2m", "%1h %2m", "%1u %2m", "%1h %2m", "%1h %2m", "%1 год %2 хв", "%1 ч %2 мин", "%1時間%2分", "%1小时%2分"),
    ("%1m %2s",
     "%1m %2s", "%1m %2s", "%1m %2s", "%1m %2s", "%1m %2s", "%1m %2s", "%1m %2s", "%1 хв %2 с", "%1 мин %2 с", "%1分%2秒", "%1分%2秒"),
    ("Stopped",
     "Gestoppt", "Arrêté", "Detenido", "Interrotto", "Gestopt", "Parado", "Zatrzymano", "Зупинено", "Остановлено", "停止しました", "已停止"),
    ("Started",
     "Gestartet", "Démarré", "Iniciado", "Avviato", "Gestart", "Iniciado", "Rozpoczęto", "Розпочато", "Запущено", "開始しました", "已开始"),
    ("%1m ago",
     "vor %1 Min.", "il y a %1 min", "hace %1 min", "%1 min fa", "%1 min geleden", "há %1 min", "%1 min temu", "%1 хв тому", "%1 мин назад", "%1分前", "%1分钟前"),
    ("%1h ago",
     "vor %1 Std.", "il y a %1 h", "hace %1 h", "%1 h fa", "%1 u geleden", "há %1 h", "%1 godz. temu", "%1 год тому", "%1 ч назад", "%1時間前", "%1小时前"),
    ("%1d ago",
     "vor %1 T.", "il y a %1 j", "hace %1 d", "%1 g fa", "%1 d geleden", "há %1 d", "%1 d temu", "%1 дн. тому", "%1 дн. назад", "%1日前", "%1天前"),
    ("Timer",
     "Timer", "Minuteur", "Temporizador", "Timer", "Timer", "Cronômetro", "Stoper", "Таймер", "Таймер", "タイマー", "计时器"),
    ("Add Entry",
     "Eintrag hinzufügen", "Ajouter une entrée", "Añadir entrada", "Aggiungi voce", "Invoer toevoegen", "Adicionar registro", "Dodaj wpis", "Додати запис", "Добавить запись", "エントリを追加", "添加条目"),
    ("Settings",
     "Einstellungen", "Paramètres", "Ajustes", "Impostazioni", "Instellingen", "Configurações", "Ustawienia", "Налаштування", "Настройки", "設定", "设置"),
    ("Refresh interval:",
     "Aktualisierungsintervall:", "Intervalle d’actualisation :", "Intervalo de actualización:", "Intervallo di aggiornamento:", "Vernieuwingsinterval:", "Intervalo de atualização:", "Interwał odświeżania:", "Інтервал оновлення:", "Интервал обновления:", "更新間隔:", "刷新间隔:"),
    ("Recent entries:",
     "Letzte Einträge:", "Entrées récentes :", "Entradas recientes:", "Voci recenti:", "Recente invoeren:", "Registros recentes:", "Ostatnie wpisy:", "Останні записи:", "Недавние записи:", "最近のエントリ:", "最近条目:"),
    ("Timer view:",
     "Timer-Ansicht:", "Vue du minuteur :", "Vista del temporizador:", "Vista del timer:", "Timerweergave:", "Exibição do cronômetro:", "Widok stopera:", "Вигляд таймера:", "Вид таймера:", "タイマー表示:", "计时器视图:"),
    ("Show work summary (today / week totals)",
     "Arbeitsübersicht anzeigen (Summe heute / Woche)", "Afficher le résumé du travail (totaux jour / semaine)", "Mostrar resumen de trabajo (totales de hoy / semana)", "Mostra riepilogo del lavoro (totali oggi / settimana)", "Werkoverzicht tonen (totalen vandaag / week)", "Mostrar resumo do trabalho (totais de hoje / semana)", "Pokaż podsumowanie pracy (sumy z dziś / tygodnia)", "Показувати підсумок роботи (сьогодні / тиждень)", "Показывать сводку работы (итоги за сегодня / неделю)", "作業サマリーを表示 (今日／週の合計)", "显示工作摘要（今日/本周合计）"),
    ("Show recent entries",
     "Letzte Einträge anzeigen", "Afficher les entrées récentes", "Mostrar entradas recientes", "Mostra voci recenti", "Recente invoeren tonen", "Mostrar registros recentes", "Pokaż ostatnie wpisy", "Показувати останні записи", "Показывать недавние записи", "最近のエントリを表示", "显示最近条目"),
    ("Show favorites",
     "Favoriten anzeigen", "Afficher les favoris", "Mostrar favoritos", "Mostra preferiti", "Favorieten tonen", "Mostrar favoritos", "Pokaż ulubione", "Показувати обране", "Показывать избранное", "お気に入りを表示", "显示收藏"),
    ("Show \"Continue\" button",
     "Schaltfläche „Fortsetzen“ anzeigen", "Afficher le bouton « Continuer »", "Mostrar el botón «Continuar»", "Mostra il pulsante «Continua»", "Knop „Doorgaan” tonen", "Mostrar o botão «Continuar»", "Pokaż przycisk „Kontynuuj”", "Показувати кнопку «Продовжити»", "Показывать кнопку «Продолжить»", "「続ける」ボタンを表示", "显示“继续”按钮"),
    ("Show start / switch activity controls",
     "Steuerung zum Starten / Wechseln der Tätigkeit anzeigen", "Afficher les commandes de démarrage / changement d’activité", "Mostrar controles para iniciar / cambiar actividad", "Mostra i controlli per avviare / cambiare attività", "Bediening voor starten / wisselen van activiteit tonen", "Mostrar controles para iniciar / mudar atividade", "Pokaż elementy startu / zmiany aktywności", "Показувати керування запуском / зміною активності", "Показывать элементы запуска / смены активности", "アクティビティの開始／切り替え操作を表示", "显示开始/切换活动控件"),
    ("Show day sparkline",
     "Tagesverlauf anzeigen", "Afficher le graphique de la journée", "Mostrar gráfico del día", "Mostra grafico della giornata", "Dagverloop tonen", "Mostrar gráfico do dia", "Pokaż wykres dnia", "Показувати графік дня", "Показывать график дня", "1日のグラフを表示", "显示当日走势图"),
    ("Confirmations:",
     "Bestätigungen:", "Confirmations :", "Confirmaciones:", "Conferme:", "Bevestigingen:", "Confirmações:", "Potwierdzenia:", "Підтвердження:", "Подтверждения:", "確認:", "确认:"),
    ("Confirm before stopping tracking",
     "Vor dem Stoppen der Zeiterfassung bestätigen", "Confirmer avant d’arrêter le suivi", "Confirmar antes de detener el seguimiento", "Conferma prima di interrompere il tracciamento", "Bevestigen voor het stoppen van de registratie", "Confirmar antes de parar o rastreamento", "Potwierdzaj przed zatrzymaniem śledzenia", "Підтверджувати перед зупинкою відстеження", "Подтверждать перед остановкой учёта", "計測を停止する前に確認する", "停止计时前确认"),
    ("When editing the running timer, the previous entry's end is shown. Saving an earlier start asks for confirmation.",
     "Beim Bearbeiten des laufenden Timers wird das Ende des vorherigen Eintrags angezeigt. Ein früherer Start muss beim Speichern bestätigt werden.",
     "Lors de la modification du minuteur en cours, la fin de l’entrée précédente est affichée. Enregistrer un début antérieur demande une confirmation.",
     "Al editar el temporizador en curso se muestra el final de la entrada anterior. Guardar un inicio anterior pide confirmación.",
     "Durante la modifica del timer in corso viene mostrata la fine della voce precedente. Salvare un inizio anteriore richiede conferma.",
     "Bij het bewerken van de lopende timer wordt het einde van de vorige invoer getoond. Een eerdere start opslaan vraagt om bevestiging.",
     "Ao editar o cronômetro em andamento, o fim do registro anterior é exibido. Salvar um início anterior pede confirmação.",
     "Podczas edycji działającego stopera pokazywany jest koniec poprzedniego wpisu. Zapisanie wcześniejszego początku wymaga potwierdzenia.",
     "Під час редагування активного таймера показується кінець попереднього запису. Збереження раннішого початку потребує підтвердження.",
     "При редактировании запущенного таймера показывается конец предыдущей записи. Сохранение более раннего начала требует подтверждения.",
     "実行中のタイマーを編集すると、前のエントリの終了時刻が表示されます。より早い開始時刻を保存するときは確認が必要です。",
     "编辑正在运行的计时器时会显示上一条目的结束时间。保存更早的开始时间时需要确认。"),
    ("Begin:",
     "Beginn:", "Début :", "Inicio:", "Inizio:", "Begin:", "Início:", "Początek:", "Початок:", "Начало:", "開始:", "开始:"),
    ("End:",
     "Ende:", "Fin :", "Fin:", "Fine:", "Einde:", "Fim:", "Koniec:", "Кінець:", "Конец:", "終了:", "结束:"),
    ("Location (sun / moon accuracy)",
     "Standort (Genauigkeit für Sonne / Mond)", "Position (précision soleil / lune)", "Ubicación (precisión de sol / luna)", "Posizione (precisione sole / luna)", "Locatie (nauwkeurigheid zon / maan)", "Localização (precisão de sol / lua)", "Lokalizacja (dokładność słońca / księżyca)", "Розташування (точність сонця / місяця)", "Местоположение (точность солнца / луны)", "場所 (太陽／月の精度)", "位置（日出日落/月相精度）"),
    ("Current:",
     "Aktuell:", "Actuel :", "Actual:", "Attuale:", "Huidig:", "Atual:", "Bieżąca:", "Поточне:", "Текущее:", "現在:", "当前:"),
    ("%1, %2",
     "%1, %2", "%1, %2", "%1, %2", "%1, %2", "%1, %2", "%1, %2", "%1, %2", "%1, %2", "%1, %2", "%1, %2", "%1，%2"),
    ("Search city:",
     "Stadt suchen:", "Rechercher une ville :", "Buscar ciudad:", "Cerca città:", "Stad zoeken:", "Buscar cidade:", "Szukaj miasta:", "Пошук міста:", "Поиск города:", "都市を検索:", "搜索城市:"),
    ("Search for a city…",
     "Nach einer Stadt suchen…", "Rechercher une ville…", "Buscar una ciudad…", "Cerca una città…", "Zoek een stad…", "Buscar uma cidade…", "Szukaj miasta…", "Знайти місто…", "Найти город…", "都市を検索…", "搜索城市…"),
    ("Idle detection",
     "Leerlauferkennung", "Détection d’inactivité", "Detección de inactividad", "Rilevamento inattività", "Inactiviteitsdetectie", "Detecção de ociosidade", "Wykrywanie bezczynności", "Виявлення простою", "Обнаружение простоя", "アイドル検出", "空闲检测"),
    ("Enable:",
     "Aktivieren:", "Activer :", "Activar:", "Abilita:", "Inschakelen:", "Ativar:", "Włącz:", "Увімкнути:", "Включить:", "有効化:", "启用:"),
    ("Prompt after being idle while tracking",
     "Nach Leerlauf während der Zeiterfassung nachfragen", "Demander après une inactivité pendant le suivi", "Preguntar tras inactividad durante el seguimiento", "Chiedi dopo un periodo di inattività durante il tracciamento", "Vragen na inactiviteit tijdens het registreren", "Perguntar após ociosidade durante o rastreamento", "Pytaj po bezczynności podczas śledzenia", "Запитувати після простою під час відстеження", "Спрашивать после простоя во время учёта", "計測中にアイドル状態になったら確認する", "计时期间空闲后进行询问"),
    ("Idle after:",
     "Leerlauf nach:", "Inactif après :", "Inactivo después de:", "Inattivo dopo:", "Inactief na:", "Ocioso após:", "Bezczynność po:", "Простій після:", "Простой после:", "アイドルになるまで:", "空闲时间:"),
    ("%1 min",
     "%1 Min.", "%1 min", "%1 min", "%1 min", "%1 min", "%1 min", "%1 min", "%1 хв", "%1 мин", "%1分", "%1 分钟"),
    ("Notifications",
     "Benachrichtigungen", "Notifications", "Notificaciones", "Notifiche", "Meldingen", "Notificações", "Powiadomienia", "Сповіщення", "Уведомления", "通知", "通知"),
    ("Notify on:",
     "Benachrichtigen bei:", "Notifier pour :", "Notificar en:", "Notifica per:", "Melden bij:", "Notificar em:", "Powiadamiaj o:", "Сповіщати про:", "Уведомлять о:", "通知するとき:", "通知时机:"),
    ("Idle stop",
     "Stopp bei Leerlauf", "Arrêt sur inactivité", "Detención por inactividad", "Stop per inattività", "Stop bij inactiviteit", "Parada por ociosidade", "Zatrzymanie przy bezczynności", "Зупинка через простій", "Остановка при простое", "アイドルによる停止", "空闲停止"),
    ("Forgot to start tracking",
     "Start der Zeiterfassung vergessen", "Oubli de démarrer le suivi", "Olvido de iniciar el seguimiento", "Tracciamento non avviato", "Vergeten te starten met registreren", "Esqueceu de iniciar o rastreamento", "Nie uruchomiono śledzenia", "Забули почати відстеження", "Забыли запустить учёт", "計測の開始忘れ", "忘记开始计时"),
    ("Settings sync with the Plasma widget via shared.json on the same machine.",
     "Einstellungen werden auf demselben Gerät über shared.json mit dem Plasma-Widget synchronisiert.", "Les paramètres se synchronisent avec le widget Plasma via shared.json sur la même machine.", "Los ajustes se sincronizan con el widget de Plasma mediante shared.json en el mismo equipo.", "Le impostazioni si sincronizzano con il widget Plasma tramite shared.json sullo stesso computer.", "Instellingen synchroniseren met de Plasma-widget via shared.json op dezelfde machine.", "As configurações são sincronizadas com o widget do Plasma via shared.json na mesma máquina.", "Ustawienia synchronizują się z widżetem Plasma przez shared.json na tym samym komputerze.", "Налаштування синхронізуються з віджетом Plasma через shared.json на тому самому пристрої.", "Настройки синхронизируются с виджетом Plasma через shared.json на том же устройстве.", "設定は同じマシン上の shared.json を介して Plasma ウィジェットと同期されます。", "设置通过同一设备上的 shared.json 与 Plasma 小部件同步。"),
    ("Unpin from favorites",
     "Von Favoriten lösen", "Retirer des favoris", "Quitar de favoritos", "Rimuovi dai preferiti", "Van favorieten losmaken", "Remover dos favoritos", "Odepnij z ulubionych", "Відкріпити з обраного", "Открепить из избранного", "お気に入りから外す", "取消固定收藏"),
    ("Pin as favorite",
     "Als Favorit pinnen", "Épingler en favori", "Fijar como favorito", "Fissa come preferito", "Als favoriet vastmaken", "Fixar como favorito", "Przypnij jako ulubione", "Закріпити як обране", "Закрепить как избранное", "お気に入りにピン留め", "固定为收藏"),
    ("Connecting…",
     "Verbinde…", "Connexion…", "Conectando…", "Connessione…", "Verbinden…", "Conectando…", "Łączenie…", "З’єднання…", "Подключение…", "接続中…", "正在连接…"),
    ("Add your service, server URL (if needed), and API token to start tracking.",
     "Füge deinen Dienst, die Server-URL (falls nötig) und den API-Token hinzu, um die Zeiterfassung zu starten.", "Ajoutez votre service, l’URL du serveur (si nécessaire) et le jeton API pour commencer le suivi.", "Añade tu servicio, la URL del servidor (si hace falta) y el token de API para empezar a registrar.", "Aggiungi il tuo servizio, l’URL del server (se necessario) e il token API per iniziare il tracciamento.", "Voeg je dienst, de server-URL (indien nodig) en het API-token toe om te starten met registreren.", "Adicione seu serviço, a URL do servidor (se necessário) e o token da API para começar o rastreamento.", "Dodaj usługę, adres URL serwera (jeśli potrzeba) i token API, aby rozpocząć śledzenie.", "Додайте сервіс, URL сервера (за потреби) та API-токен, щоб почати відстеження.", "Добавьте сервис, URL сервера (при необходимости) и API-токен, чтобы начать учёт.", "サービス、サーバーURL (必要な場合)、APIトークンを追加して計測を始めましょう。", "添加服务、服务器 URL（如需要）和 API 令牌即可开始计时。"),
    ("Description…",
     "Beschreibung…", "Description…", "Descripción…", "Descrizione…", "Beschrijving…", "Descrição…", "Opis…", "Опис…", "Описание…", "説明…", "描述…"),
    ("No activity. Tap a favorite to start.",
     "Keine Tätigkeit. Tippe auf einen Favoriten zum Starten.", "Aucune activité. Touchez un favori pour démarrer.", "Sin actividad. Toca un favorito para iniciar.", "Nessuna attività. Tocca un preferito per iniziare.", "Geen activiteit. Tik op een favoriet om te starten.", "Sem atividade. Toque em um favorito para iniciar.", "Brak aktywności. Dotknij ulubionej, aby rozpocząć.", "Немає активності. Торкніться обраного, щоб почати.", "Нет активности. Коснитесь избранного, чтобы начать.", "アクティビティがありません。お気に入りをタップして開始します。", "无活动。点按收藏项即可开始。"),
    ("No activity.",
     "Keine Tätigkeit.", "Aucune activité.", "Sin actividad.", "Nessuna attività.", "Geen activiteit.", "Sem atividade.", "Brak aktywności.", "Немає активності.", "Нет активности.", "アクティビティがありません。", "无活动。"),
    ("Pin an entry from Recent to add it to your favorites.",
     "Pinne einen Eintrag aus „Zuletzt“, um ihn zu deinen Favoriten hinzuzufügen.", "Épinglez une entrée de « Récents » pour l’ajouter à vos favoris.", "Fija una entrada de Recientes para añadirla a tus favoritos.", "Fissa una voce da Recenti per aggiungerla ai preferiti.", "Maak een invoer uit Recent vast om hem aan je favorieten toe te voegen.", "Fixe um registro de Recentes para adicioná-lo aos favoritos.", "Przypnij wpis z listy Ostatnie, aby dodać go do ulubionych.", "Закріпіть запис із «Нещодавні», щоб додати його до обраного.", "Закрепите запись из «Недавние», чтобы добавить её в избранное.", "「最近」からエントリをピン留めすると、お気に入りに追加されます。", "在“最近”中固定条目即可将其加入收藏。"),
    ("Stop %1 · %2?",
     "%1 · %2 stoppen?", "Arrêter %1 · %2 ?", "¿Detener %1 · %2?", "Interrompere %1 · %2?", "%1 · %2 stoppen?", "Parar %1 · %2?", "Zatrzymać %1 · %2?", "Зупинити %1 · %2?", "Остановить %1 · %2?", "%1 · %2 を停止しますか？", "停止 %1 · %2？"),
    ("Really delete this entry?",
     "Diesen Eintrag wirklich löschen?", "Vraiment supprimer cette entrée ?", "¿Seguro que quieres eliminar esta entrada?", "Eliminare davvero questa voce?", "Deze invoer echt verwijderen?", "Realmente excluir este registro?", "Na pewno usunąć ten wpis?", "Справді видалити цей запис?", "Действительно удалить эту запись?", "このエントリを本当に削除しますか？", "确定要删除此条目吗？"),
    ("Switch to %1 · %2?",
     "Zu %1 · %2 wechseln?", "Passer à %1 · %2 ?", "¿Cambiar a %1 · %2?", "Passare a %1 · %2?", "Overschakelen naar %1 · %2?", "Mudar para %1 · %2?", "Przełączyć na %1 · %2?", "Перейти до %1 · %2?", "Переключиться на %1 · %2?", "%1 · %2 に切り替えますか？", "切换到 %1 · %2？"),
    ("Split at:",
     "Teilen bei:", "Diviser à :", "Dividir en:", "Dividi alle:", "Splitsen op:", "Dividir em:", "Podziel o:", "Розділити о:", "Разделить в:", "分割位置:", "拆分于:"),
    ("You were idle for %1. Keep this time, discard it, or discard and continue?",
     "Du warst %1 im Leerlauf. Zeit behalten, verwerfen oder verwerfen und weitermachen?", "Vous étiez inactif pendant %1. Garder ce temps, l’ignorer, ou l’ignorer et continuer ?", "Estuviste inactivo durante %1. ¿Conservar este tiempo, descartarlo o descartarlo y continuar?", "Sei stato inattivo per %1. Tenere questo tempo, scartarlo o scartarlo e continuare?", "Je was %1 inactief. Deze tijd behouden, verwerpen of verwerpen en doorgaan?", "Você ficou ocioso por %1. Manter esse tempo, descartá-lo ou descartar e continuar?", "Byłeś bezczynny przez %1. Zachować ten czas, odrzucić go czy odrzucić i kontynuować?", "Ви були бездіяльні %1. Залишити цей час, відкинути його чи відкинути й продовжити?", "Вы были неактивны %1. Оставить это время, отбросить его или отбросить и продолжить?", "%1 間アイドル状態でした。この時間を残しますか、破棄しますか、それとも破棄して続けますか？", "你已空闲 %1。保留这段时间、丢弃，还是丢弃并继续？"),
]


def build():
    """Return {lang: {msgid: msgstr}} for all languages."""
    out = {lang: {} for lang in LANGS}
    for row in ROWS:
        msgid, *vals = row
        assert len(vals) == len(LANGS) - 1, msgid
        for lang, val in zip(LANGS[1:], vals):
            out[lang][msgid] = val
        out["en"][msgid] = msgid
    return out


T_BY_LANG = build()
