# -*- coding: utf-8 -*-
T = {
    'Project-specific': 'Projektspezifisch',
    'Global activities': 'Globale Tätigkeiten',
    'Plasmai': 'Plasmai',
    'Toggle Plasmai tracking': 'Plasmai-Zeiterfassung umschalten',
    'Stop Plasmai tracking': 'Plasmai-Zeiterfassung stoppen',
    'Loading…': 'Wird geladen…',
    'Not configured — right-click to configure': 'Nicht konfiguriert — Rechtsklick zum Einrichten',
    'just now': 'gerade eben',
    'yesterday': 'gestern',
    'Not configured': 'Nicht konfiguriert',
    'Connecting to %1…': 'Verbinde mit %1…',
    'Connection problem': 'Verbindungsproblem',
    'Connected to %1 (%2)': 'Verbunden mit %1 (%2)',
    'Connected to %1': 'Verbunden mit %1',
    'Enter valid begin and end date/time.': 'Gültiges Start- und Enddatum/-zeit eingeben.',
    'End must be after begin.': 'Ende muss nach dem Beginn liegen.',
    'Entry added': 'Eintrag hinzugefügt',
    'Manual time entry': 'Manueller Zeiteintrag',
    '%1 left today': '%1 heute übrig',
    '%1 over today': '%1 heute drüber',
    '%1 left this week': '%1 diese Woche übrig',
    '%1 over this week': '%1 diese Woche drüber',
    'Today %1': 'Heute %1',
    'Week %1': 'Woche %1',
    'Tracking started': 'Zeiterfassung gestartet',
    'Switched activity': 'Tätigkeit gewechselt',
    'Tracking stopped (idle)': 'Zeiterfassung gestoppt (Leerlauf)',
    'Tracking stopped': 'Zeiterfassung gestoppt',
    'Stop the current timer before starting another': 'Stoppe den aktuellen Timer, bevor du einen neuen startest',
    'Stop tracking?': 'Zeiterfassung stoppen?',
    'Stop tracking %1 · %2?': 'Zeiterfassung für %1 · %2 stoppen?',
    'Statistics': 'Statistik',
    'Add entry': 'Eintrag hinzufügen',
    'Add a manual time entry': 'Manuellen Zeiteintrag hinzufügen',
    'Show statistics': 'Statistik anzeigen',
    'Back to timer': 'Zurück zum Timer',
    'Connect a time tracker': 'Zeiterfassungsdienst verbinden',
    'Add your service, server URL (if needed), and API token to start tracking from the panel.': 'Füge deinen Dienst, die Server-URL (falls nötig) und das API-Token hinzu, um die Zeiterfassung vom Panel aus zu starten.',
    'Configure Plasmai': 'Plasmai einrichten',
    'Retry': 'Erneut versuchen',
    'Configure': 'Einrichten',
    'Not tracking': 'Keine aktive Erfassung',
    'Description': 'Beschreibung',
    'Save description': 'Beschreibung speichern',
    'Stop': 'Stopp',
    'Continue · %1 · %2': 'Fortsetzen · %1 · %2',
    'Favorites': 'Favoriten',
    'No favorites yet': 'Noch keine Favoriten',
    'Pin frequent project/activity pairs in the widget settings.': 'Häufige Projekt-/Tätigkeitspaare in den Widget-Einstellungen anheften.',
    'Configure favorites': 'Favoriten einrichten',
    '+%1 more in settings': '+%1 weitere in den Einstellungen',
    'Recent': 'Zuletzt',
    'No recent activities': 'Keine kürzlichen Tätigkeiten',
    'Start tracking to build your recent list.': 'Starte die Zeiterfassung, um die Liste zu füllen.',
    'Switch to another activity…': 'Zu anderer Tätigkeit wechseln…',
    'Start something else…': 'Etwas anderes starten…',
    'Switch activity': 'Tätigkeit wechseln',
    'New activity': 'Neue Tätigkeit',
    'Select project…': 'Projekt wählen…',
    'Select activity…': 'Tätigkeit wählen…',
    'Description (optional)': 'Beschreibung (optional)',
    'Start': 'Start',
    'Switch': 'Wechseln',
    'Cancel': 'Abbrechen',
    'Unknown error': 'Unbekannter Fehler',
    'URL and API token are required': 'URL und API-Token sind erforderlich',
    'Configure your time tracker URL and API token': 'URL und API-Token deines Zeiterfassungsdienstes einrichten',
    'This action is not supported for the selected service yet.': 'Diese Aktion wird für den gewählten Dienst noch nicht unterstützt.',
    'Cannot reach the server. Check your network, URL, or TLS certificate.': 'Server nicht erreichbar. Prüfe Netzwerk, URL oder TLS-Zertifikat.',
    'Authentication failed. Check your API token.': 'Authentifizierung fehlgeschlagen. Prüfe dein API-Token.',
    'Server not found. Check your URL.': 'Server nicht gefunden. Prüfe deine URL.',
    'Access denied. Your token may lack required permissions.': 'Zugriff verweigert. Deinem Token fehlen möglicherweise Rechte.',
    'Server error (%1).': 'Serverfehler (%1).',
    'Request failed: %1': 'Anfrage fehlgeschlagen: %1',
    'Request failed (%1).': 'Anfrage fehlgeschlagen (%1).',
    'Connection': 'Verbindung',
    'Configure a time-tracking profile. Choose Kimai, Clockify, Toggl Track, or SolidTime.': 'Richte ein Zeiterfassungsprofil ein. Wähle Kimai, Clockify, Toggl Track oder SolidTime.',
    'Profile:': 'Profil:',
    'Profile name:': 'Profilname:',
    'Service:': 'Dienst:',
    'Server URL:': 'Server-URL:',
    'API token:': 'API-Token:',
    'Paste token to save in KWallet': 'Token einfügen, um es in KWallet zu speichern',
    'Add profile': 'Profil hinzufügen',
    'Profile %1': 'Profil %1',
    'Remove': 'Entfernen',
    'Use this profile': 'Dieses Profil verwenden',
    'none': 'keines',
    'Active profile: %1': 'Aktives Profil: %1',
    'Saving…': 'Speichern…',
    'Save token': 'Token speichern',
    'Token saved to KWallet for this profile.': 'Token für dieses Profil in KWallet gespeichert.',
    'Failed to save token': 'Token konnte nicht gespeichert werden',
    'Clear token': 'Token löschen',
    'Token removed from KWallet.': 'Token aus KWallet entfernt.',
    'Failed to clear token': 'Token konnte nicht gelöscht werden',
    'Test connection': 'Verbindung testen',
    'Testing connection…': 'Verbindung wird getestet…',
    'No API token stored. Save a token first.': 'Kein API-Token gespeichert. Speichere zuerst ein Token.',
    'ok': 'ok',
    'Connected to %1 (%2).': 'Verbunden mit %1 (%2).',
    'Configure a Kimai URL on the Connection tab first.': 'Richte zuerst eine Kimai-URL im Reiter Verbindung ein.',
    'Loading projects…': 'Projekte werden geladen…',
    'Save an API token on the Connection tab first.': 'Speichere zuerst ein API-Token im Reiter Verbindung.',
    'Loaded %1 projects.': '%1 Projekte geladen.',
    'Select a project to pin activities.': 'Wähle ein Projekt, um Tätigkeiten anzuheften.',
    'Failed to load projects.': 'Projekte konnten nicht geladen werden.',
    'Loading activities…': 'Tätigkeiten werden geladen…',
    'No API token available.': 'Kein API-Token verfügbar.',
    '%1 project-specific, %2 global': '%1 projektspezifisch, %2 global',
    'Failed to load activities.': 'Tätigkeiten konnten nicht geladen werden.',
    'Projects': 'Projekte',
    'Reload': 'Neu laden',
    'Activities — %1': 'Tätigkeiten — %1',
    'Activities': 'Tätigkeiten',
    'Enter a city or place name to search.': 'Gib einen Stadt- oder Ortsnamen zum Suchen ein.',
    'Searching…': 'Speichern…',
    'Location search failed. Check your network connection.': 'Ortssuche fehlgeschlagen. Prüfe deine Netzwerkverbindung.',
    'No places found.': 'Keine Orte gefunden.',
    'Display': 'Anzeige',
    'Refresh interval (seconds):': 'Aktualisierungsintervall (Sekunden):',
    'Recent activities shown:': 'Angezeigte kürzliche Tätigkeiten:',
    'Appearance:': 'Darstellung:',
    'Use desktop blur (translucent background)': 'Desktop-Unschärfe nutzen (durchscheinender Hintergrund)',
    'Usual work day start:': 'Start der üblichen Arbeitszeit:',
    'Usual work day end:': 'Ende der üblichen Arbeitszeit:',
    'Day sparkline': 'Tages-Sparkline',
    'Find location': 'Ort suchen',
    'Search for a city or place to set sunrise/sunset coloring. Powered by OpenStreetMap Nominatim.': 'Suche nach einer Stadt oder einem Ort für die Sonnenauf-/untergangsfärbung. Nutzt OpenStreetMap Nominatim.',
    'City, region, or address…': 'Stadt, Region oder Adresse…',
    'Search': 'Suchen',
    'Using %1': 'Verwende %1',
    'Current place: %1': 'Aktueller Ort: %1',
    'Custom coordinates': 'Eigene Koordinaten',
    'Latitude:': 'Breitengrad:',
    'Longitude:': 'Längengrad:',
    'Used to color the sparkline for sunrise and sunset at your location.': 'Wird verwendet, um die Sparkline nach Sonnenauf- und -untergang an deinem Standort einzufärben.',
    'Panel (taskbar)': 'Panel (Taskleiste)',
    'Show:': 'Anzeigen:',
    'Elapsed time': 'Vergangene Zeit',
    'Project name': 'Projektname',
    'Activity name': 'Tätigkeitsname',
    'Panel flyout': 'Panel-Flyout',
    'Work summary (today / week / remaining)': 'Arbeitsübersicht (heute / Woche / Rest)',
    'Recent list': 'Liste der letzten Einträge',
    'Continue last activity': 'Letzte Tätigkeit fortsetzen',
    'Start / switch activity controls': 'Steuerung zum Starten / Wechseln',
    'Desktop widget': 'Desktop-Widget',
    'New activity picker': 'Auswahl für neue Tätigkeit',
    'Behavior': 'Verhalten',
    'Tracking:': 'Erfassung:',
    'Confirm before stopping the timer': 'Vor dem Stoppen des Timers bestätigen',
    'Idle detection:': 'Leerlauferkennung:',
    'Stop timer when idle': 'Timer bei Leerlauf stoppen',
    'Idle threshold (minutes):': 'Leerlauf-Schwelle (Minuten):',
    'Notifications:': 'Benachrichtigungen:',
    'Notify when tracking starts': 'Benachrichtigen, wenn die Erfassung startet',
    'Notify when tracking stops': 'Benachrichtigen, wenn die Erfassung stoppt',
    'Notify when stopped due to idle': 'Benachrichtigen bei Stopp wegen Leerlauf',
    'Idle detection requires xprintidle (X11/XWayland). It may not work on pure Wayland sessions.': 'Leerlauferkennung erfordert xprintidle (X11/XWayland). Unter reinen Wayland-Sitzungen funktioniert sie möglicherweise nicht.',
    'Back': 'Zurück',
    'Create a finished entry with project, activity, and time range.': 'Erstelle einen abgeschlossenen Eintrag mit Projekt, Tätigkeit und Zeitraum.',
    'Begin': 'Beginn',
    'End': 'Ende',
    'Duration: %1': 'Dauer: %1',
    'Duration: —': 'Dauer: —',
    'Duration: invalid range': 'Dauer: ungültiger Zeitraum',
    'Save entry': 'Eintrag speichern',
    'All': 'Alle',
    'Billable': 'Abrechenbar',
    'Non-billable': 'Nicht abrechenbar',
    'Charts for power users. Tracking stays on the main screen.': 'Diagramme für Power-User. Die Zeiterfassung bleibt auf dem Hauptbildschirm.',
    'Show': 'Anzeigen',
    'Today': 'Heute',
    'This week': 'Diese Woche',
    'Time by hour': 'Zeit nach Stunde',
    'Previous day': 'Vorheriger Tag',
    'Yesterday': 'Gestern',
    'Next day': 'Nächster Tag',
    'No time logged this day': 'An diesem Tag keine Zeit erfasst',
    'Projects by day': 'Projekte nach Tag',
    'Previous week': 'Vorherige Woche',
    'Next week': 'Nächste Woche',
    'No time logged this week': 'In dieser Woche keine Zeit erfasst',
    'Projects by hour': 'Projekte nach Stunde',
    'Weekdays and weekend — segments placed by clock time.': 'Wochentage und Wochenende — Segmente nach Uhrzeit.',
    'Weekdays — segments placed by clock time. Weekend appears when tracked.': 'Wochentage — Segmente nach Uhrzeit. Wochenende erscheint bei erfasster Zeit.',
    'Axis shows business hours (%1–%2); expands if work falls outside.': 'Achse zeigt Arbeitszeiten (%1–%2); erweitert sich, wenn Arbeit außerhalb liegt.',
    'Activity distribution': 'Tätigkeitsverteilung',
    'No activities today': 'Heute keine Tätigkeiten',
    'No activities this week': 'Diese Woche keine Tätigkeiten',
    'Time': 'Zeit',
    'Pick date': 'Datum wählen',
    'Pick time': 'Uhrzeit wählen',
    'Hours : Minutes': 'Stunden : Minuten',
    'Select': 'Auswählen',
    'Today\'s tracked time across 24 hours': 'Heute erfasste Zeit über 24 Stunden',
    'Clockify cloud API is prefilled. Change only for a regional endpoint (e.g. euc1).': 'Clockify-Cloud-API ist vorausgefüllt. Nur für einen regionalen Endpunkt ändern (z. B. euc1).',
    'Toggl Track cloud API is prefilled. Use your personal API token from Profile settings.': 'Toggl-Track-Cloud-API ist vorausgefüllt. Nutze dein persönliches API-Token aus den Profileinstellungen.',
    'SolidTime cloud API is prefilled. For self-hosting, replace with your instance base URL.': 'SolidTime-Cloud-API ist vorausgefüllt. Bei Self-Hosting durch die Basis-URL deiner Instanz ersetzen.',
    'Self-hosted Kimai or the official hosted service (kimai.cloud). Paste the instance URL.': 'Selbst gehostetes Kimai oder der offizielle Hosting-Dienst (kimai.cloud). Instanz-URL einfügen.',
    'API URL:': 'API-URL:',
    'https://api.solidtime.io or https://time.example.com': 'https://api.solidtime.io oder https://time.example.com',
    'https://kimai.example.com or https://www.kimai.cloud': 'https://kimai.example.com oder https://www.kimai.cloud',
    'API key:': 'API-Schlüssel:',
    'Colors:': 'Farben:',
    'Make similar colors distinctive within each category': 'Ähnliche Farben innerhalb jeder Kategorie unterscheidbar machen',
    'Similarity threshold (%):': 'Ähnlichkeitsschwelle (%):',
    'Higher similarity values treat more colors as too close. Clashing items get vivid, well-spaced replacement colors (not washed hue-shifts). If too many items cannot fit, the threshold is lowered automatically down to 12%. See Maintenance for clash groups.': 'Höhere Ähnlichkeitswerte behandeln mehr Farben als zu nah. Kollidierende Einträge erhalten kräftige, gut verteilte Ersatzfarben (keine blassen Farbtonverschiebungen). Wenn zu viele Einträge nicht passen, wird die Schwelle automatisch bis 12 % gesenkt. Siehe Wartung für Konfliktgruppen.',
    'Configure a server URL on the Connection tab first.': 'Konfiguriere zuerst eine Server-URL im Reiter Verbindung.',
    'Loading customers, projects, and activities…': 'Lade Kunden, Projekte und Tätigkeiten…',
    'Color distinction is off. Enable it in Display settings to see clash groups.': 'Farbunterscheidung ist aus. Aktiviere sie in den Anzeige-Einstellungen, um Konfliktgruppen zu sehen.',
    'Loaded %1 customers, %2 projects, %3 activities. No similar colors within a category.': '%1 Kunden, %2 Projekte, %3 Tätigkeiten geladen. Keine ähnlichen Farben innerhalb einer Kategorie.',
    'Loaded %1 customers, %2 projects, %3 activities. %4 clash group(s), %5 color(s) shifted.': '%1 Kunden, %2 Projekte, %3 Tätigkeiten geladen. %4 Konfliktgruppe(n), %5 Farbe(n) verschoben.',
    'Only colors that clash within a category are listed. Each group starts with the entry that kept the Kimai color; shifted variants follow. Unique colors are hidden.': 'Nur Farben, die innerhalb einer Kategorie kollidieren, werden aufgeführt. Jede Gruppe beginnt mit dem Eintrag, der die Kimai-Farbe behielt; verschobene Varianten folgen. Einzigartige Farben sind ausgeblendet.',
    'Reload from server': 'Vom Server neu laden',
    'Distinction on · configured %1% · effective customers %2% / projects %3% / activities %4%': 'Unterscheidung an · konfiguriert %1% · effektiv Kunden %2% / Projekte %3% / Tätigkeiten %4%',
    'Distinction off — enable it in Display settings.': 'Unterscheidung aus — in den Anzeige-Einstellungen aktivieren.',
    'Customers': 'Kunden',
    'No similar colors in this category.': 'Keine ähnlichen Farben in dieser Kategorie.',
    'kept': 'behalten',
    'shifted': 'verschoben',
    'Maintenance': 'Wartung',
    'Edit': 'Bearbeiten',
    'Edit start, project, and activity': 'Start, Projekt und Tätigkeit bearbeiten',
    'Edit start time, project, and activity for the running entry.': 'Startzeit, Projekt und Tätigkeit des laufenden Eintrags bearbeiten.',
    'Elapsed time updates from the new start.': 'Die Laufzeit wird anhand der neuen Startzeit berechnet.',
    'Start must be a valid time not in the future.': 'Start muss eine gültige Zeit sein und darf nicht in der Zukunft liegen.',
    'This provider cannot update the running entry.': 'Dieser Anbieter kann den laufenden Eintrag nicht aktualisieren.',
    'Enter a valid start date/time.': 'Gültiges Startdatum/-zeit eingeben.',
    'Start must not be in the future.': 'Start darf nicht in der Zukunft liegen.',
    'Save': 'Speichern',

    'Current': 'Aktuell',
    'Switch to': 'Wechseln zu',
    'Already tracking this activity': 'Diese Tätigkeit läuft bereits',
    'Could not resolve project or activity for that entry': 'Projekt oder Tätigkeit für diesen Eintrag konnte nicht aufgelöst werden',
    'Switch activity?': 'Tätigkeit wechseln?',
}

PLURALS = {
    '%1 minute ago': ['vor %1 Minute', 'vor %1 Minuten'],
    '%1 hour ago': ['vor %1 Stunde', 'vor %1 Stunden'],
    '%1 day ago': ['vor %1 Tag', 'vor %1 Tagen'],
    '%1 place found.': ['%1 Ort gefunden.', '%1 Orte gefunden.'],
}
