# -*- coding: utf-8 -*-
T = {
    'Project-specific': 'Project-specific',
    'Global activities': 'Global activities',
    'Plasmai': 'Plasmai',
    'Toggle Plasmai tracking': 'Toggle Plasmai tracking',
    'Stop Plasmai tracking': 'Stop Plasmai tracking',
    'Loading…': 'Loading…',
    'Not configured — right-click to configure': 'Not configured — right-click to configure',
    'just now': 'just now',
    'yesterday': 'yesterday',
    'Not configured': 'Not configured',
    'Connecting to %1…': 'Connecting to %1…',
    'Connection problem': 'Connection problem',
    'Connected to %1 (%2)': 'Connected to %1 (%2)',
    'Connected to %1': 'Connected to %1',
    'Enter valid begin and end date/time.': 'Enter valid begin and end date/time.',
    'End must be after begin.': 'End must be after begin.',
    'Entry added': 'Entry added',
    'Manual time entry': 'Manual time entry',
    '%1 left today': '%1 left today',
    '%1 over today': '%1 over today',
    '%1 left this week': '%1 left this week',
    '%1 over this week': '%1 over this week',
    'Today %1': 'Today %1',
    'Week %1': 'Week %1',
    'Tracking started': 'Tracking started',
    'Switched activity': 'Switched activity',
    'Tracking stopped (idle)': 'Tracking stopped (idle)',
    'Tracking stopped': 'Tracking stopped',
    'Stop the current timer before starting another': 'Stop the current timer before starting another',
    'Stop tracking?': 'Stop tracking?',
    'Stop tracking %1 · %2?': 'Stop tracking %1 · %2?',
    'Statistics': 'Statistics',
    'Add entry': 'Add entry',
    'Add a manual time entry': 'Add a manual time entry',
    'Show statistics': 'Show statistics',
    'Back to timer': 'Back to timer',
    'Connect a time tracker': 'Connect a time tracker',
    'Add your service, server URL (if needed), and API token to start tracking from the panel.': 'Add your service, server URL (if needed), and API token to start tracking from the panel.',
    'Configure Plasmai': 'Configure Plasmai',
    'Retry': 'Retry',
    'Configure': 'Configure',
    'Not tracking': 'Not tracking',
    'Description': 'Description',
    'Save description': 'Save description',
    'Stop': 'Stop',
    'Continue · %1 · %2': 'Continue · %1 · %2',
    'Favorites': 'Favorites',
    'No favorites yet': 'No favorites yet',
    'Pin frequent project/activity pairs in the widget settings.': 'Pin frequent project/activity pairs in the widget settings.',
    'Configure favorites': 'Configure favorites',
    '+%1 more in settings': '+%1 more in settings',
    'Recent': 'Recent',
    'No recent activities': 'No recent activities',
    'Start tracking to build your recent list.': 'Start tracking to build your recent list.',
    'Switch to another activity…': 'Switch to another activity…',
    'Start something else…': 'Start something else…',
    'Switch activity': 'Switch activity',
    'New activity': 'New activity',
    'Select project…': 'Select project…',
    'Select activity…': 'Select activity…',
    'Description (optional)': 'Description (optional)',
    'Start': 'Start',
    'Switch': 'Switch',
    'Cancel': 'Cancel',
    'Unknown error': 'Unknown error',
    'URL and API token are required': 'URL and API token are required',
    'Configure your time tracker URL and API token': 'Configure your time tracker URL and API token',
    'This action is not supported for the selected service yet.': 'This action is not supported for the selected service yet.',
    'Cannot reach the server. Check your network, URL, or TLS certificate.': 'Cannot reach the server. Check your network, URL, or TLS certificate.',
    'Authentication failed. Check your API token.': 'Authentication failed. Check your API token.',
    'Server not found. Check your URL.': 'Server not found. Check your URL.',
    'Access denied. Your token may lack required permissions.': 'Access denied. Your token may lack required permissions.',
    'Server error (%1).': 'Server error (%1).',
    'Request failed: %1': 'Request failed: %1',
    'Request failed (%1).': 'Request failed (%1).',
    'Connection': 'Connection',
    'Configure a time-tracking profile. Choose Kimai, Clockify, Toggl Track, or SolidTime.': 'Configure a time-tracking profile. Choose Kimai, Clockify, Toggl Track, or SolidTime.',
    'Profile:': 'Profile:',
    'Profile name:': 'Profile name:',
    'Service:': 'Service:',
    'Server URL:': 'Server URL:',
    'API token:': 'API token:',
    'Paste token to save in KWallet': 'Paste token to save in KWallet',
    'Add profile': 'Add profile',
    'Profile %1': 'Profile %1',
    'Remove': 'Remove',
    'Use this profile': 'Use this profile',
    'none': 'none',
    'Active profile: %1': 'Active profile: %1',
    'Saving…': 'Saving…',
    'Save token': 'Save token',
    'Token saved to KWallet for this profile.': 'Token saved to KWallet for this profile.',
    'Failed to save token': 'Failed to save token',
    'Clear token': 'Clear token',
    'Token removed from KWallet.': 'Token removed from KWallet.',
    'Failed to clear token': 'Failed to clear token',
    'Test connection': 'Test connection',
    'Testing connection…': 'Testing connection…',
    'No API token stored. Save a token first.': 'No API token stored. Save a token first.',
    'ok': 'ok',
    'Connected to %1 (%2).': 'Connected to %1 (%2).',
    'Configure a Kimai URL on the Connection tab first.': 'Configure a Kimai URL on the Connection tab first.',
    'Loading projects…': 'Loading projects…',
    'Save an API token on the Connection tab first.': 'Save an API token on the Connection tab first.',
    'Loaded %1 projects.': 'Loaded %1 projects.',
    'Select a project to pin activities.': 'Select a project to pin activities.',
    'Failed to load projects.': 'Failed to load projects.',
    'Loading activities…': 'Loading activities…',
    'No API token available.': 'No API token available.',
    '%1 project-specific, %2 global': '%1 project-specific, %2 global',
    'Failed to load activities.': 'Failed to load activities.',
    'Projects': 'Projects',
    'Reload': 'Reload',
    'Activities — %1': 'Activities — %1',
    'Activities': 'Activities',
    'Enter a city or place name to search.': 'Enter a city or place name to search.',
    'Searching…': 'Searching…',
    'Location search failed. Check your network connection.': 'Location search failed. Check your network connection.',
    'No places found.': 'No places found.',
    'Display': 'Display',
    'Refresh interval (seconds):': 'Refresh interval (seconds):',
    'Recent activities shown:': 'Recent activities shown:',
    'Appearance:': 'Appearance:',
    'Use desktop blur (translucent background)': 'Use desktop blur (translucent background)',
    'Usual work day start:': 'Usual work day start:',
    'Usual work day end:': 'Usual work day end:',
    'Day sparkline': 'Day sparkline',
    'Find location': 'Find location',
    'Search for a city or place to set sunrise/sunset coloring. Powered by OpenStreetMap Nominatim.': 'Search for a city or place to set sunrise/sunset coloring. Powered by OpenStreetMap Nominatim.',
    'City, region, or address…': 'City, region, or address…',
    'Search': 'Search',
    'Using %1': 'Using %1',
    'Current place: %1': 'Current place: %1',
    'Custom coordinates': 'Custom coordinates',
    'Latitude:': 'Latitude:',
    'Longitude:': 'Longitude:',
    'Used to color the sparkline for sunrise and sunset at your location.': 'Used to color the sparkline for sunrise and sunset at your location.',
    'Panel (taskbar)': 'Panel (taskbar)',
    'Show:': 'Show:',
    'Elapsed time': 'Elapsed time',
    'Project name': 'Project name',
    'Activity name': 'Activity name',
    'Panel flyout': 'Panel flyout',
    'Work summary (today / week / remaining)': 'Work summary (today / week / remaining)',
    'Recent list': 'Recent list',
    'Continue last activity': 'Continue last activity',
    'Start / switch activity controls': 'Start / switch activity controls',
    'Desktop widget': 'Desktop widget',
    'New activity picker': 'New activity picker',
    'Behavior': 'Behavior',
    'Tracking:': 'Tracking:',
    'Confirm before stopping the timer': 'Confirm before stopping the timer',
    'Idle detection:': 'Idle detection:',
    'Stop timer when idle': 'Stop timer when idle',
    'Idle threshold (minutes):': 'Idle threshold (minutes):',
    'Notifications:': 'Notifications:',
    'Notify when tracking starts': 'Notify when tracking starts',
    'Notify when tracking stops': 'Notify when tracking stops',
    'Notify when stopped due to idle': 'Notify when stopped due to idle',
    'Idle detection requires xprintidle (X11/XWayland). It may not work on pure Wayland sessions.': 'Idle detection requires xprintidle (X11/XWayland). It may not work on pure Wayland sessions.',
    'Back': 'Back',
    'Create a finished entry with project, activity, and time range.': 'Create a finished entry with project, activity, and time range.',
    'Begin': 'Begin',
    'End': 'End',
    'Duration: %1': 'Duration: %1',
    'Duration: —': 'Duration: —',
    'Duration: invalid range': 'Duration: invalid range',
    'Save entry': 'Save entry',
    'All': 'All',
    'Billable': 'Billable',
    'Non-billable': 'Non-billable',
    'Charts for power users. Tracking stays on the main screen.': 'Charts for power users. Tracking stays on the main screen.',
    'Show': 'Show',
    'Today': 'Today',
    'This week': 'This week',
    'Time by hour': 'Time by hour',
    'Previous day': 'Previous day',
    'Yesterday': 'Yesterday',
    'Next day': 'Next day',
    'No time logged this day': 'No time logged this day',
    'Projects by day': 'Projects by day',
    'Previous week': 'Previous week',
    'Next week': 'Next week',
    'No time logged this week': 'No time logged this week',
    'Projects by hour': 'Projects by hour',
    'Weekdays and weekend — segments placed by clock time.': 'Weekdays and weekend — segments placed by clock time.',
    'Weekdays — segments placed by clock time. Weekend appears when tracked.': 'Weekdays — segments placed by clock time. Weekend appears when tracked.',
    'Axis shows business hours (%1–%2); expands if work falls outside.': 'Axis shows business hours (%1–%2); expands if work falls outside.',
    'Activity distribution': 'Activity distribution',
    'No activities today': 'No activities today',
    'No activities this week': 'No activities this week',
    'Time': 'Time',
    'Pick date': 'Pick date',
    'Pick time': 'Pick time',
    'Hours : Minutes': 'Hours : Minutes',
    'Select': 'Select',
    'Today\'s tracked time across 24 hours': 'Today\'s tracked time across 24 hours',
    'Clockify cloud API is prefilled. Change only for a regional endpoint (e.g. euc1).': 'Clockify cloud API is prefilled. Change only for a regional endpoint (e.g. euc1).',
    'Toggl Track cloud API is prefilled. Use your personal API token from Profile settings.': 'Toggl Track cloud API is prefilled. Use your personal API token from Profile settings.',
    'SolidTime cloud API is prefilled. For self-hosting, replace with your instance base URL.': 'SolidTime cloud API is prefilled. For self-hosting, replace with your instance base URL.',
    'Self-hosted Kimai or the official hosted service (kimai.cloud). Paste the instance URL.': 'Self-hosted Kimai or the official hosted service (kimai.cloud). Paste the instance URL.',
    'API URL:': 'API URL:',
    'https://api.solidtime.io or https://time.example.com': 'https://api.solidtime.io or https://time.example.com',
    'https://kimai.example.com or https://www.kimai.cloud': 'https://kimai.example.com or https://www.kimai.cloud',
    'API key:': 'API key:',
    'Colors:': 'Colors:',
    'Make similar colors distinctive within each category': 'Make similar colors distinctive within each category',
    'Similarity threshold (%):': 'Similarity threshold (%):',
    'Higher similarity values treat more colors as too close. Clashing items get vivid, well-spaced replacement colors (not washed hue-shifts). If too many items cannot fit, the threshold is lowered automatically down to 12%. See Maintenance for clash groups.': 'Higher similarity values treat more colors as too close. Clashing items get vivid, well-spaced replacement colors (not washed hue-shifts). If too many items cannot fit, the threshold is lowered automatically down to 12%. See Maintenance for clash groups.',
    'Configure a server URL on the Connection tab first.': 'Configure a server URL on the Connection tab first.',
    'Loading customers, projects, and activities…': 'Loading customers, projects, and activities…',
    'Color distinction is off. Enable it in Display settings to see clash groups.': 'Color distinction is off. Enable it in Display settings to see clash groups.',
    'Loaded %1 customers, %2 projects, %3 activities. No similar colors within a category.': 'Loaded %1 customers, %2 projects, %3 activities. No similar colors within a category.',
    'Loaded %1 customers, %2 projects, %3 activities. %4 clash group(s), %5 color(s) shifted.': 'Loaded %1 customers, %2 projects, %3 activities. %4 clash group(s), %5 color(s) shifted.',
    'Only colors that clash within a category are listed. Each group starts with the entry that kept the Kimai color; shifted variants follow. Unique colors are hidden.': 'Only colors that clash within a category are listed. Each group starts with the entry that kept the Kimai color; shifted variants follow. Unique colors are hidden.',
    'Reload from server': 'Reload from server',
    'Distinction on · configured %1% · effective customers %2% / projects %3% / activities %4%': 'Distinction on · configured %1% · effective customers %2% / projects %3% / activities %4%',
    'Distinction off — enable it in Display settings.': 'Distinction off — enable it in Display settings.',
    'Customers': 'Customers',
    'No similar colors in this category.': 'No similar colors in this category.',
    'kept': 'kept',
    'shifted': 'shifted',
    'Maintenance': 'Maintenance',
    'Edit': 'Edit',
    'Edit start, project, and activity': 'Edit start, project, and activity',
    'Edit start time, project, and activity for the running entry.': 'Edit start time, project, and activity for the running entry.',
    'Elapsed time updates from the new start.': 'Elapsed time updates from the new start.',
    'Start must be a valid time not in the future.': 'Start must be a valid time not in the future.',
    'This provider cannot update the running entry.': 'This provider cannot update the running entry.',
    'Enter a valid start date/time.': 'Enter a valid start date/time.',
    'Start must not be in the future.': 'Start must not be in the future.',
    'Save': 'Save',

}

PLURALS = {
    '%1 minute ago': ['%1 minute ago', '%1 minutes ago'],
    '%1 hour ago': ['%1 hour ago', '%1 hours ago'],
    '%1 day ago': ['%1 day ago', '%1 days ago'],
    '%1 place found.': ['%1 place found.', '%1 places found.'],
}
