# -*- coding: utf-8 -*-
T = {
    'Project-specific': 'Específico del proyecto',
    'Global activities': 'Actividades globales',
    'Plasmai': 'Plasmai',
    'Toggle Plasmai tracking': 'Alternar seguimiento de Plasmai',
    'Stop Plasmai tracking': 'Detener seguimiento de Plasmai',
    'Loading…': 'Cargando…',
    'Not configured — right-click to configure': 'Sin configurar — clic derecho para configurar',
    'just now': 'ahora mismo',
    'yesterday': 'ayer',
    'Not configured': 'Sin configurar',
    'Connecting to %1…': 'Conectando a %1…',
    'Connection problem': 'Problema de conexión',
    'Connected to %1 (%2)': 'Conectado a %1 (%2)',
    'Connected to %1': 'Conectado a %1',
    'Enter valid begin and end date/time.': 'Introduce una fecha/hora de inicio y fin válidas.',
    'End must be after begin.': 'El fin debe ser posterior al inicio.',
    'Entry added': 'Entrada añadida',
    'Manual time entry': 'Entrada manual de tiempo',
    '%1 left today': '%1 restante hoy',
    '%1 over today': '%1 de exceso hoy',
    '%1 left this week': '%1 restante esta semana',
    '%1 over this week': '%1 de exceso esta semana',
    'Today %1': 'Hoy %1',
    'Week %1': 'Semana %1',
    'Tracking started': 'Seguimiento iniciado',
    'Switched activity': 'Actividad cambiada',
    'Tracking stopped (idle)': 'Seguimiento detenido (inactividad)',
    'Tracking stopped': 'Seguimiento detenido',
    'Stop the current timer before starting another': 'Detén el temporizador actual antes de iniciar otro',
    'Stop tracking?': '¿Detener el seguimiento?',
    'Stop tracking %1 · %2?': '¿Detener el seguimiento de %1 · %2?',
    'Statistics': 'Estadísticas',
    'Add entry': 'Añadir entrada',
    'Add a manual time entry': 'Añadir una entrada manual de tiempo',
    'Show statistics': 'Mostrar estadísticas',
    'Back to timer': 'Volver al temporizador',
    'Connect a time tracker': 'Conectar un rastreador de tiempo',
    'Add your service, server URL (if needed), and API token to start tracking from the panel.': 'Añade tu servicio, la URL del servidor (si es necesario) y el token de API para iniciar el seguimiento desde el panel.',
    'Configure Plasmai': 'Configurar Plasmai',
    'Retry': 'Reintentar',
    'Configure': 'Configurar',
    'Not tracking': 'Sin seguimiento activo',
    'Description': 'Descripción',
    'Save description': 'Guardar descripción',
    'Stop': 'Detener',
    'Continue · %1 · %2': 'Continuar · %1 · %2',
    'Favorites': 'Favoritos',
    'No favorites yet': 'Aún no hay favoritos',
    'Pin frequent project/activity pairs in the widget settings.': 'Fija pares frecuentes de proyecto/actividad en la configuración del widget.',
    'Configure favorites': 'Configurar favoritos',
    '+%1 more in settings': '+%1 más en la configuración',
    'Recent': 'Recientes',
    'No recent activities': 'No hay actividades recientes',
    'Start tracking to build your recent list.': 'Inicia el seguimiento para crear tu lista reciente.',
    'Switch to another activity…': 'Cambiar a otra actividad…',
    'Start something else…': 'Iniciar otra cosa…',
    'Switch activity': 'Cambiar actividad',
    'New activity': 'Nueva actividad',
    'Select project…': 'Seleccionar proyecto…',
    'Select activity…': 'Seleccionar actividad…',
    'Description (optional)': 'Descripción (opcional)',
    'Start': 'Iniciar',
    'Switch': 'Cambiar',
    'Cancel': 'Cancelar',
    'Unknown error': 'Error desconocido',
    'URL and API token are required': 'Se requieren la URL y el token de API',
    'Configure your time tracker URL and API token': 'Configura la URL y el token de API de tu rastreador de tiempo',
    'This action is not supported for the selected service yet.': 'Esta acción aún no está soportada para el servicio seleccionado.',
    'Cannot reach the server. Check your network, URL, or TLS certificate.': 'No se puede alcanzar el servidor. Comprueba tu red, la URL o el certificado TLS.',
    'Authentication failed. Check your API token.': 'Error de autenticación. Comprueba tu token de API.',
    'Server not found. Check your URL.': 'Servidor no encontrado. Comprueba tu URL.',
    'Access denied. Your token may lack required permissions.': 'Acceso denegado. Tu token puede no tener los permisos necesarios.',
    'Server error (%1).': 'Error del servidor (%1).',
    'Request failed: %1': 'Solicitud fallida: %1',
    'Request failed (%1).': 'Solicitud fallida (%1).',
    'Connection': 'Conexión',
    'Configure a time-tracking profile. Choose Kimai, Clockify, Toggl Track, or SolidTime.': 'Configura un perfil de seguimiento de tiempo. Elige Kimai, Clockify, Toggl Track o SolidTime.',
    'Profile:': 'Perfil:',
    'Profile name:': 'Nombre del perfil:',
    'Service:': 'Servicio:',
    'Server URL:': 'URL del servidor:',
    'API token:': 'Token de API:',
    'Paste token to save in KWallet': 'Pega el token para guardarlo en KWallet',
    'Add profile': 'Añadir perfil',
    'Profile %1': 'Perfil %1',
    'Remove': 'Eliminar',
    'Use this profile': 'Usar este perfil',
    'none': 'ninguno',
    'Active profile: %1': 'Perfil activo: %1',
    'Saving…': 'Guardando…',
    'Save token': 'Guardar token',
    'Token saved to KWallet for this profile.': 'Token guardado en KWallet para este perfil.',
    'Failed to save token': 'Error al guardar el token',
    'Clear token': 'Borrar token',
    'Token removed from KWallet.': 'Token eliminado de KWallet.',
    'Failed to clear token': 'Error al borrar el token',
    'Test connection': 'Probar conexión',
    'Testing connection…': 'Probando conexión…',
    'No API token stored. Save a token first.': 'No hay token de API guardado. Guarda un token primero.',
    'ok': 'ok',
    'Connected to %1 (%2).': 'Conectado a %1 (%2).',
    'Configure a Kimai URL on the Connection tab first.': 'Configura primero una URL de Kimai en la pestaña Conexión.',
    'Loading projects…': 'Cargando proyectos…',
    'Save an API token on the Connection tab first.': 'Guarda primero un token de API en la pestaña Conexión.',
    'Loaded %1 projects.': '%1 proyectos cargados.',
    'Select a project to pin activities.': 'Selecciona un proyecto para fijar actividades.',
    'Failed to load projects.': 'Error al cargar los proyectos.',
    'Loading activities…': 'Cargando actividades…',
    'No API token available.': 'No hay token de API disponible.',
    '%1 project-specific, %2 global': '%1 específico del proyecto, %2 global',
    'Failed to load activities.': 'Error al cargar las actividades.',
    'Projects': 'Proyectos',
    'Reload': 'Recargar',
    'Activities — %1': 'Actividades — %1',
    'Activities': 'Actividades',
    'Enter a city or place name to search.': 'Introduce el nombre de una ciudad o lugar para buscar.',
    'Searching…': 'Buscando…',
    'Location search failed. Check your network connection.': 'Error en la búsqueda de ubicación. Comprueba tu conexión de red.',
    'No places found.': 'No se encontraron lugares.',
    'Display': 'Visualización',
    'Refresh interval (seconds):': 'Intervalo de actualización (segundos):',
    'Recent activities shown:': 'Actividades recientes mostradas:',
    'Appearance:': 'Apariencia:',
    'Use desktop blur (translucent background)': 'Usar desenfoque del escritorio (fondo translúcido)',
    'Usual work day start:': 'Inicio habitual de la jornada laboral:',
    'Usual work day end:': 'Fin habitual de la jornada laboral:',
    'Day sparkline': 'Minigráfico del día',
    'Find location': 'Buscar ubicación',
    'Search for a city or place to set sunrise/sunset coloring. Powered by OpenStreetMap Nominatim.': 'Busca una ciudad o lugar para el color del amanecer/atardecer. Con tecnología de OpenStreetMap Nominatim.',
    'City, region, or address…': 'Ciudad, región o dirección…',
    'Search': 'Buscar',
    'Using %1': 'Usando %1',
    'Current place: %1': 'Lugar actual: %1',
    'Custom coordinates': 'Coordenadas personalizadas',
    'Latitude:': 'Latitud:',
    'Longitude:': 'Longitud:',
    'Used to color the sparkline for sunrise and sunset at your location.': 'Se usa para colorear el minigráfico según el amanecer y atardecer en tu ubicación.',
    'Panel (taskbar)': 'Panel (barra de tareas)',
    'Show:': 'Mostrar:',
    'Elapsed time': 'Tiempo transcurrido',
    'Project name': 'Nombre del proyecto',
    'Activity name': 'Nombre de la actividad',
    'Panel flyout': 'Menú desplegable del panel',
    'Work summary (today / week / remaining)': 'Resumen de trabajo (hoy / semana / restante)',
    'Recent list': 'Lista reciente',
    'Continue last activity': 'Continuar la última actividad',
    'Start / switch activity controls': 'Controles de inicio / cambio de actividad',
    'Desktop widget': 'Widget de escritorio',
    'New activity picker': 'Selector de nueva actividad',
    'Behavior': 'Comportamiento',
    'Tracking:': 'Seguimiento:',
    'Confirm before stopping the timer': 'Confirmar antes de detener el temporizador',
    'Idle detection:': 'Detección de inactividad:',
    'Stop timer when idle': 'Detener el temporizador en inactividad',
    'Idle threshold (minutes):': 'Umbral de inactividad (minutos):',
    'Notifications:': 'Notificaciones:',
    'Notify when tracking starts': 'Notificar al iniciar el seguimiento',
    'Notify when tracking stops': 'Notificar al detener el seguimiento',
    'Notify when stopped due to idle': 'Notificar al detenerse por inactividad',
    'Idle detection requires xprintidle (X11/XWayland). It may not work on pure Wayland sessions.': 'La detección de inactividad requiere xprintidle (X11/XWayland). Puede no funcionar en sesiones Wayland puras.',
    'Back': 'Atrás',
    'Create a finished entry with project, activity, and time range.': 'Crear una entrada finalizada con proyecto, actividad y rango horario.',
    'Begin': 'Inicio',
    'End': 'Fin',
    'Duration: %1': 'Duración: %1',
    'Duration: —': 'Duración: —',
    'Duration: invalid range': 'Duración: rango no válido',
    'Save entry': 'Guardar entrada',
    'All': 'Todos',
    'Billable': 'Facturable',
    'Non-billable': 'No facturable',
    'Charts for power users. Tracking stays on the main screen.': 'Gráficos para usuarios avanzados. El seguimiento permanece en la pantalla principal.',
    'Show': 'Mostrar',
    'Today': 'Hoy',
    'This week': 'Esta semana',
    'Time by hour': 'Tiempo por hora',
    'Previous day': 'Día anterior',
    'Yesterday': 'Ayer',
    'Next day': 'Día siguiente',
    'No time logged this day': 'No hay tiempo registrado este día',
    'Projects by day': 'Proyectos por día',
    'Previous week': 'Semana anterior',
    'Next week': 'Semana siguiente',
    'No time logged this week': 'No hay tiempo registrado esta semana',
    'Projects by hour': 'Proyectos por hora',
    'Weekdays and weekend — segments placed by clock time.': 'Días laborables y fin de semana: segmentos según la hora del reloj.',
    'Weekdays — segments placed by clock time. Weekend appears when tracked.': 'Días laborables: segmentos según la hora. El fin de semana aparece si hay registro.',
    'Axis shows business hours (%1–%2); expands if work falls outside.': 'El eje muestra el horario laboral (%1–%2); se amplía si el trabajo queda fuera.',
    'Activity distribution': 'Distribución de actividades',
    'No activities today': 'No hay actividades hoy',
    'No activities this week': 'No hay actividades esta semana',
    'Time': 'Tiempo',
    'Pick date': 'Elegir fecha',
    'Pick time': 'Elegir hora',
    'Hours : Minutes': 'Horas : Minutos',
    'Select': 'Seleccionar',
    'Today\'s tracked time across 24 hours': 'Tiempo registrado de hoy a lo largo de 24 horas',
    'Clockify cloud API is prefilled. Change only for a regional endpoint (e.g. euc1).': 'La API en la nube de Clockify está rellenada. Cámbiela solo para un endpoint regional (p. ej. euc1).',
    'Toggl Track cloud API is prefilled. Use your personal API token from Profile settings.': 'La API en la nube de Toggl Track está rellenada. Usa tu token API personal de la configuración del perfil.',
    'SolidTime cloud API is prefilled. For self-hosting, replace with your instance base URL.': 'La API en la nube de SolidTime está rellenada. En autoalojamiento, sustitúyela por la URL base de tu instancia.',
    'Self-hosted Kimai or the official hosted service (kimai.cloud). Paste the instance URL.': 'Kimai autoalojado o el servicio oficial alojado (kimai.cloud). Pega la URL de la instancia.',
    'API URL:': 'URL de la API:',
    'https://api.solidtime.io or https://time.example.com': 'https://api.solidtime.io o https://time.example.com',
    'https://kimai.example.com or https://www.kimai.cloud': 'https://kimai.example.com o https://www.kimai.cloud',
    'API key:': 'Clave API:',
    'Colors:': 'Colores:',
    'Make similar colors distinctive within each category': 'Hacer distintivos los colores similares dentro de cada categoría',
    'Similarity threshold (%):': 'Umbral de similitud (%):',
    'Higher similarity values treat more colors as too close. Clashing items get vivid, well-spaced replacement colors (not washed hue-shifts). If too many items cannot fit, the threshold is lowered automatically down to 12%. See Maintenance for clash groups.': 'Valores de similitud más altos tratan más colores como demasiado cercanos. Los elementos en conflicto reciben colores de reemplazo vivos y bien espaciados (no leves cambios de tono). Si hay demasiados elementos, el umbral baja automáticamente hasta el 12%. Consulta Mantenimiento para los grupos en conflicto.',
    'Configure a server URL on the Connection tab first.': 'Configura primero una URL de servidor en la pestaña Conexión.',
    'Loading customers, projects, and activities…': 'Cargando clientes, proyectos y actividades…',
    'Color distinction is off. Enable it in Display settings to see clash groups.': 'La distinción de colores está desactivada. Actívala en Visualización para ver los grupos en conflicto.',
    'Loaded %1 customers, %2 projects, %3 activities. No similar colors within a category.': 'Cargados %1 clientes, %2 proyectos, %3 actividades. No hay colores similares en una categoría.',
    'Loaded %1 customers, %2 projects, %3 activities. %4 clash group(s), %5 color(s) shifted.': 'Cargados %1 clientes, %2 proyectos, %3 actividades. %4 grupo(s) en conflicto, %5 color(es) desplazado(s).',
    'Only colors that clash within a category are listed. Each group starts with the entry that kept the Kimai color; shifted variants follow. Unique colors are hidden.': 'Solo se listan los colores que chocan dentro de una categoría. Cada grupo empieza con la entrada que conservó el color de Kimai; siguen las variantes desplazadas. Los colores únicos se ocultan.',
    'Reload from server': 'Recargar desde el servidor',
    'Distinction on · configured %1% · effective customers %2% / projects %3% / activities %4%': 'Distinción activa · configurado %1% · efectivo clientes %2% / proyectos %3% / actividades %4%',
    'Distinction off — enable it in Display settings.': 'Distinción desactivada: actívala en Visualización.',
    'Customers': 'Clientes',
    'No similar colors in this category.': 'No hay colores similares en esta categoría.',
    'kept': 'conservado',
    'shifted': 'desplazado',
    'Maintenance': 'Mantenimiento',
}

PLURALS = {
    '%1 minute ago': ['hace %1 minuto', 'hace %1 minutos'],
    '%1 hour ago': ['hace %1 hora', 'hace %1 horas'],
    '%1 day ago': ['hace %1 día', 'hace %1 días'],
    '%1 place found.': ['%1 lugar encontrado.', '%1 lugares encontrados.'],
}
