# -*- coding: utf-8 -*-
T = {
    'Project-specific': 'Específico del proyecto',
    'Global activities': 'Actividades globales',
    'Plasmai': 'Plasmai',
    'Loading…': 'Cargando…',
    'Not configured — right-click to configure': 'Sin configurar — clic derecho para configurar',
    'just now': 'ahora mismo',
    'yesterday': 'ayer',
    'Not configured': 'Sin configurar',
    'Connecting to %1…': 'Conectando a %1…',
    'Connection problem': 'Problema de conexión',
    'Connected to %1 (%2)': 'Conectado a %1 (%2)',
    'Connected to %1': 'Conectado a %1',
    'Enter valid begin and end date/time.': 'Introduce una fecha/hora de inicio y fin válidas.',
    'End must be after begin.': 'El fin debe ser posterior al inicio.',
    'Entry added': 'Entrada añadida',
    'Manual time entry': 'Entrada manual de tiempo',
    '%1 left today': '%1 restante hoy',
    '%1 over today': '%1 de exceso hoy',
    '%1 left this week': '%1 restante esta semana',
    '%1 over this week': '%1 de exceso esta semana',
    'Today %1': 'Hoy %1',
    'Week %1': 'Semana %1',
    'Tracking started': 'Seguimiento iniciado',
    'Switched activity': 'Actividad cambiada',
    'Tracking stopped (idle)': 'Seguimiento detenido (inactividad)',
    'Tracking stopped': 'Seguimiento detenido',
    'Stop tracking?': '¿Detener el seguimiento?',
    'Stop tracking %1 · %2?': '¿Detener el seguimiento de %1 · %2?',
    'Statistics': 'Estadísticas',
    'Add entry': 'Añadir entrada',
    'Add a manual time entry': 'Añadir una entrada manual de tiempo',
    'Show statistics': 'Mostrar estadísticas',
    'Back to timer': 'Volver al temporizador',
    'Connect a time tracker': 'Conectar un rastreador de tiempo',
    'Add your service, server URL (if needed), and API token to start tracking from the panel.': 'Añade tu servicio, la URL del servidor (si es necesario) y el token de API para iniciar el seguimiento desde el panel.',
    'Configure Plasmai': 'Configurar Plasmai',
    'Retry': 'Reintentar',
    'Configure': 'Configurar',
    'Not tracking': 'Sin seguimiento activo',
    'Description': 'Descripción',
    'Save description': 'Guardar descripción',
    'Stop': 'Detener',
    'Continue · %1 · %2': 'Continuar · %1 · %2',
    'Favorites': 'Favoritos',
    'No favorites yet': 'Aún no hay favoritos',
    'Pin frequent project/activity pairs in the widget settings.': 'Fija pares frecuentes de proyecto/actividad en la configuración del widget.',
    'Configure favorites': 'Configurar favoritos',
    '+%1 more in settings': '+%1 más en la configuración',
    'Recent': 'Recientes',
    'No recent activities': 'No hay actividades recientes',
    'Start tracking to build your recent list.': 'Inicia el seguimiento para crear tu lista reciente.',
    'Switch to another activity…': 'Cambiar a otra actividad…',
    'Start something else…': 'Iniciar otra cosa…',
    'Switch activity': 'Cambiar actividad',
    'New activity': 'Nueva actividad',
    'Select project…': 'Seleccionar proyecto…',
    'Select activity…': 'Seleccionar actividad…',
    'Description (optional)': 'Descripción (opcional)',
    'Start': 'Iniciar',
    'Switch': 'Cambiar',
    'Cancel': 'Cancelar',
    'Unknown error': 'Error desconocido',
    'URL and API token are required': 'Se requieren la URL y el token de API',
    'Configure your time tracker URL and API token': 'Configura la URL y el token de API de tu rastreador de tiempo',
    'This action is not supported for the selected service yet.': 'Esta acción aún no está soportada para el servicio seleccionado.',
    'Cannot reach the server. Check your network, URL, or TLS certificate.': 'No se puede alcanzar el servidor. Comprueba tu red, la URL o el certificado TLS.',
    'Authentication failed. Check your API token.': 'Error de autenticación. Comprueba tu token de API.',
    'Server not found. Check your URL.': 'Servidor no encontrado. Comprueba tu URL.',
    'Access denied. Your token may lack required permissions.': 'Acceso denegado. Tu token puede no tener los permisos necesarios.',
    'Server error (%1).': 'Error del servidor (%1).',
    'Request failed: %1': 'Solicitud fallida: %1',
    'Request failed (%1).': 'Solicitud fallida (%1).',
    'Connection': 'Conexión',
    'Configure a time-tracking profile. Choose Kimai, Clockify, Toggl Track, or SolidTime.': 'Configura un perfil de seguimiento de tiempo. Elige Kimai, Clockify, Toggl Track o SolidTime.',
    'Profile:': 'Perfil:',
    'Profile name:': 'Nombre del perfil:',
    'Service:': 'Servicio:',
    'Server URL:': 'URL del servidor:',
    'API token:': 'Token de API:',
    'Paste token to save in KWallet': 'Pega el token para guardarlo en KWallet',
    'Add profile': 'Añadir perfil',
    'Profile %1': 'Perfil %1',
    'Remove': 'Eliminar',
    'Use this profile': 'Usar este perfil',
    'none': 'ninguno',
    'Active profile: %1': 'Perfil activo: %1',
    'Saving…': 'Guardando…',
    'Save token': 'Guardar token',
    'Token saved to KWallet for this profile.': 'Token guardado en KWallet para este perfil.',
    'Failed to save token': 'Error al guardar el token',
    'Clear token': 'Borrar token',
    'Token removed from KWallet.': 'Token eliminado de KWallet.',
    'Failed to clear token': 'Error al borrar el token',
    'Test connection': 'Probar conexión',
    'Testing connection…': 'Probando conexión…',
    'No API token stored. Save a token first.': 'No hay token de API guardado. Guarda un token primero.',
    'ok': 'ok',
    'Connected to %1 (%2).': 'Conectado a %1 (%2).',
    'Configure a Kimai URL on the Connection tab first.': 'Configura primero una URL de Kimai en la pestaña Conexión.',
    'Loading projects…': 'Cargando proyectos…',
    'Save an API token on the Connection tab first.': 'Guarda primero un token de API en la pestaña Conexión.',
    'Loaded %1 projects.': '%1 proyectos cargados.',
    'Select a project to pin activities.': 'Selecciona un proyecto para fijar actividades.',
    'Failed to load projects.': 'Error al cargar los proyectos.',
    'Loading activities…': 'Cargando actividades…',
    'No API token available.': 'No hay token de API disponible.',
    '%1 project-specific, %2 global': '%1 específico del proyecto, %2 global',
    'Failed to load activities.': 'Error al cargar las actividades.',
    'Projects': 'Proyectos',
    'Reload': 'Recargar',
    'Activities — %1': 'Actividades — %1',
    'Activities': 'Actividades',
    'Enter a city or place name to search.': 'Introduce el nombre de una ciudad o lugar para buscar.',
    'Searching…': 'Buscando…',
    'Location search failed. Check your network connection.': 'Error en la búsqueda de ubicación. Comprueba tu conexión de red.',
    'No places found.': 'No se encontraron lugares.',
    'Display': 'Visualización',
    'Refresh interval (seconds):': 'Intervalo de actualización (segundos):',
    'Touch optimization:': 'Optimización táctil:',
    'Automatic (follow Plasma tablet mode)': 'Automático (seguir el modo tableta de Plasma)',
    'On': 'Activado',
    'Off': 'Desactivado',
    'Larger tap targets for buttons, lists, pickers, and date/time controls.': 'Objetivos táctiles más grandes para botones, listas, selectores y fecha/hora.',
    'Usual work day start:': 'Inicio habitual de la jornada laboral:',
    'Usual work day end:': 'Fin habitual de la jornada laboral:',
    'Day sparkline': 'Minigráfico del día',
    'City, region, or address…': 'Ciudad, región o dirección…',
    'Search': 'Buscar',
    'Using %1': 'Usando %1',
    'Current place: %1': 'Lugar actual: %1',
    'Latitude:': 'Latitud:',
    'Longitude:': 'Longitud:',
    'Panel (taskbar)': 'Panel (barra de tareas)',
    'Show:': 'Mostrar:',
    'Elapsed time': 'Tiempo transcurrido',
    'Project name': 'Nombre del proyecto',
    'Activity name': 'Nombre de la actividad',
    'Panel flyout': 'Menú desplegable del panel',
    'Work summary (today / week / remaining)': 'Resumen de trabajo (hoy / semana / restante)',
    'Recent list': 'Lista reciente',
    'Continue last activity': 'Continuar la última actividad',
    'Start / switch activity controls': 'Controles de inicio / cambio de actividad',
    'Desktop widget': 'Widget de escritorio',
    'New activity picker': 'Selector de nueva actividad',
    'Behavior': 'Comportamiento',
    'Tracking:': 'Seguimiento:',
    'Confirm before stopping the timer': 'Confirmar antes de detener el temporizador',
    'Idle detection:': 'Detección de inactividad:',
    'Stop timer when idle': 'Detener el temporizador en inactividad',
    'Idle threshold (minutes):': 'Umbral de inactividad (minutos):',
    'Notifications:': 'Notificaciones:',
    'Notify when tracking starts': 'Notificar al iniciar el seguimiento',
    'Notify when tracking stops': 'Notificar al detener el seguimiento',
    'Notify when stopped due to idle': 'Notificar al detenerse por inactividad',
    'Back': 'Atrás',
    'Create a finished entry with project, activity, and time range.': 'Crear una entrada finalizada con proyecto, actividad y rango horario.',
    'Begin': 'Inicio',
    'End': 'Fin',
    'Duration: %1': 'Duración: %1',
    'Duration: —': 'Duración: —',
    'Duration: invalid range': 'Duración: rango no válido',
    'Save entry': 'Guardar entrada',
    'All': 'Todos',
    'Billable': 'Facturable',
    'Non-billable': 'No facturable',
    'Today': 'Hoy',
    'This week': 'Esta semana',
    'Time by hour': 'Tiempo por hora',
    'Previous day': 'Día anterior',
    'Yesterday': 'Ayer',
    'Next day': 'Día siguiente',
    'No time logged this day': 'No hay tiempo registrado este día',
    'Projects by day': 'Proyectos por día',
    'Previous week': 'Semana anterior',
    'Next week': 'Semana siguiente',
    'No time logged this week': 'No hay tiempo registrado esta semana',
    'Projects by hour': 'Proyectos por hora',
    'Weekdays and weekend — segments placed by clock time.': 'Días laborables y fin de semana: segmentos según la hora del reloj.',
    'Weekdays — segments placed by clock time. Weekend appears when tracked.': 'Días laborables: segmentos según la hora. El fin de semana aparece si hay registro.',
    'Axis shows business hours (%1–%2); expands if work falls outside.': 'El eje muestra el horario laboral (%1–%2); se amplía si el trabajo queda fuera.',
    'Activity distribution': 'Distribución de actividades',
    'No activities today': 'No hay actividades hoy',
    'No activities this week': 'No hay actividades esta semana',
    'Time': 'Tiempo',
    'Pick date': 'Elegir fecha',
    'Pick time': 'Elegir hora',
    'Hours : Minutes': 'Horas : Minutos',
    'Select': 'Seleccionar',
    'Clockify cloud API is prefilled. Change only for a regional endpoint (e.g. euc1).': 'La API en la nube de Clockify está rellenada. Cámbiela solo para un endpoint regional (p. ej. euc1).',
    'Toggl Track cloud API is prefilled. Use your personal API token from Profile settings.': 'La API en la nube de Toggl Track está rellenada. Usa tu token API personal de la configuración del perfil.',
    'SolidTime cloud API is prefilled. For self-hosting, replace with your instance base URL.': 'La API en la nube de SolidTime está rellenada. En autoalojamiento, sustitúyela por la URL base de tu instancia.',
    'Self-hosted Kimai or the official hosted service (kimai.cloud). Paste the instance URL.': 'Kimai autoalojado o el servicio oficial alojado (kimai.cloud). Pega la URL de la instancia.',
    'API URL:': 'URL de la API:',
    'https://api.solidtime.io or https://time.example.com': 'https://api.solidtime.io o https://time.example.com',
    'https://kimai.example.com or https://www.kimai.cloud': 'https://kimai.example.com o https://www.kimai.cloud',
    'API key:': 'Clave API:',
    'Make similar colors distinctive within each category': 'Hacer distintivos los colores similares dentro de cada categoría',
    'Similarity threshold (%):': 'Umbral de similitud (%):',
    'Configure a server URL on the Connection tab first.': 'Configura primero una URL de servidor en la pestaña Conexión.',
    'Loading customers, projects, and activities…': 'Cargando clientes, proyectos y actividades…',
    'Color distinction is off. Enable it in Display settings to see clash groups.': 'La distinción de colores está desactivada. Actívala en Visualización para ver los grupos en conflicto.',
    'Loaded %1 customers, %2 projects, %3 activities. No similar colors within a category.': 'Cargados %1 clientes, %2 proyectos, %3 actividades. No hay colores similares en una categoría.',
    'Loaded %1 customers, %2 projects, %3 activities. %4 clash group(s), %5 color(s) shifted.': 'Cargados %1 clientes, %2 proyectos, %3 actividades. %4 grupo(s) en conflicto, %5 color(es) desplazado(s).',
    'Only colors that clash within a category are listed. Each group starts with the entry that kept the Kimai color; shifted variants follow. Unique colors are hidden.': 'Solo se listan los colores que chocan dentro de una categoría. Cada grupo empieza con la entrada que conservó el color de Kimai; siguen las variantes desplazadas. Los colores únicos se ocultan.',
    'Reload from server': 'Recargar desde el servidor',
    'Distinction on · configured %1% · effective customers %2% / projects %3% / activities %4%': 'Distinción activa · configurado %1% · efectivo clientes %2% / proyectos %3% / actividades %4%',
    'Distinction off — enable it in Display settings.': 'Distinción desactivada: actívala en Visualización.',
    'Customers': 'Clientes',
    'No similar colors in this category.': 'No hay colores similares en esta categoría.',
    'kept': 'conservado',
    'shifted': 'desplazado',
    'Maintenance': 'Mantenimiento',
    'Edit': 'Editar',
    'Edit start, project, and activity': 'Editar inicio, proyecto y actividad',
    'Elapsed time updates from the new start.': 'El tiempo transcurrido se actualiza desde el nuevo inicio.',
    'Start must be a valid time not in the future.': 'El inicio debe ser una hora válida y no estar en el futuro.',
    'This provider cannot update the running entry.': 'Este proveedor no puede actualizar la entrada en curso.',
    'Enter a valid start date/time.': 'Introduce una fecha/hora de inicio válida.',
    'Start must not be in the future.': 'El inicio no debe estar en el futuro.',
    'Save': 'Guardar',
    'Current': 'Actual',
    'Switch to': 'Cambiar a',
    'Could not resolve project or activity for that entry': 'No se pudo resolver el proyecto o la actividad de esa entrada',
    'Edit start, project, activity, billable, and tags for the running entry.': 'Editar inicio, proyecto, actividad, facturable y etiquetas de la entrada en curso.',
    'Starts or switches this activity': 'Inicia o cambia a esta actividad',
    'A profile named "%1" already exists.': 'Ya existe un perfil llamado «%1».',
    'Appearance': 'Apariencia',
    'Updates': 'Actualizaciones',
    'Colors': 'Colores',
    'Distinction:': 'Distinción:',
    'Higher similarity values treat more colors as too close. Clashing items get vivid, well-spaced replacement colors. See Maintenance for clash groups.': 'Valores de similitud más altos tratan más colores como demasiado cercanos. Los elementos en conflicto reciben colores de reemplazo vivos y bien espaciados. Véase Mantenimiento para los grupos de conflicto.',
    'Color distinction is available for Kimai profiles (per-customer / project / activity colors).': 'La distinción de colores está disponible para perfiles Kimai (colores por cliente / proyecto / actividad).',
    'Work hours': 'Horario laboral',
    'Used for the sparkline zoom and remaining-time in the work summary.': 'Se usa para el zoom de la sparkline y el tiempo restante en el resumen.',
    'Arcs:': 'Arcos:',
    'Show sun, moon, and work arcs': 'Mostrar arcos de sol, luna y trabajo',
    'Hide the whole sparkline under Panel flyout or Desktop widget below.': 'Ocultar toda la sparkline en el menú del panel o el widget de escritorio más abajo.',
    'Find location:': 'Buscar ubicación:',
    'Search a place or enter coordinates for sunrise/sunset coloring. Powered by OpenStreetMap Nominatim.': 'Busca un lugar o introduce coordenadas para el color de amanecer/anochecer. Con OpenStreetMap Nominatim.',
    'Customer color pill': 'Pastilla de color del cliente',
    'Project color pill': 'Pastilla de color del proyecto',
    'Activities shown:': 'Actividades mostradas:',
    'Applies to both the panel flyout and the desktop widget.': 'Se aplica al menú del panel y al widget de escritorio.',
    'Loading projects': 'Cargando proyectos',
    'Color distinction is only available for Kimai profiles.': 'La distinción de colores solo está disponible para perfiles Kimai.',
    'Color maintenance is for Kimai': 'El mantenimiento de colores es para Kimai',
    'Clockify, Toggl, and SolidTime do not expose Kimai-style customer / project / activity colors, so clash groups and color shifting are hidden for those profiles.': 'Clockify, Toggl y SolidTime no exponen colores de cliente / proyecto / actividad al estilo Kimai, así que los grupos de conflicto y el desplazamiento de color se ocultan en esos perfiles.',
    'Select customer…': 'Seleccionar cliente…',
    'Today\'s tracked time': 'Tiempo registrado hoy',
    'This provider cannot update descriptions.': 'Este proveedor no puede actualizar descripciones.',
    'Open or close the Plasmai popup': 'Abrir o cerrar el menú de Plasmai',
    'Add tag…': 'Añadir etiqueta…',
    'Add tags…': 'Añadir etiquetas…',
    'Tags': 'Etiquetas',
    'Loading tags…': 'Cargando etiquetas…',
    'No tags on the server yet.': 'Aún no hay etiquetas en el servidor.',
    'Create tag “%1”': 'Crear etiqueta «%1»',
    'Already running.': 'Ya en marcha.',
    'Entry actions': 'Acciones de la entrada',
    'Edit entry': 'Editar entrada',
    'Split entry': 'Dividir entrada',
    'Delete entry': 'Eliminar entrada',
    'Idle detection uses the session idle hint on Wayland (loginctl / ScreenSaver) and xprintidle on X11.': 'La detección de inactividad usa la pista de inactividad de sesión en Wayland (loginctl / ScreenSaver) y xprintidle en X11.',
    'While tracking, shutdown and reboot wait like an unsaved file. Closing the lid or sleep is not blocked.': 'Durante el registro, apagar y reiniciar esperan como con un archivo sin guardar. Cerrar la tapa o suspender no se bloquea.',
    'Remind me once if nothing is tracking during work hours': 'Recordarme una vez si no hay nada en marcha en horario laboral',
    'A timer is still running': 'Todavía hay un temporizador en marcha',
    'Idle time discarded': 'Tiempo de inactividad descartado',
    'Nothing is tracking': 'No hay nada en marcha',
    'Work hours have started. Start a timer when you begin.': 'Ha empezado el horario laboral. Inicia un temporizador cuando empieces.',
    'Customer created': 'Cliente creado',
    'Project created': 'Proyecto creado',
    'Activity created': 'Actividad creada',
    'Entry updated': 'Entrada actualizada',
    'Timesheet updated': 'Parte de horas actualizado',
    'This provider cannot update stopped entries.': 'Este proveedor no puede actualizar entradas detenidas.',
    'Tracking in progress': 'Registro en curso',
    'This provider cannot delete entries.': 'Este proveedor no puede eliminar entradas.',
    'Entry deleted': 'Entrada eliminada',
    'Split time must be between begin and end.': 'La hora de división debe estar entre el inicio y el fin.',
    'This provider cannot split entries.': 'Este proveedor no puede dividir entradas.',
    'Entry split': 'Entrada dividida',
    'The first half was saved, but the second half could not be created.': 'Se guardó la primera mitad, pero no se pudo crear la segunda.',
    'Delete entry?': '¿Eliminar entrada?',
    'Delete this finished entry? This cannot be undone.': '¿Eliminar esta entrada finalizada? No se puede deshacer.',
    'Delete "%1 · %2"? This cannot be undone.': '¿Eliminar «%1 · %2»? No se puede deshacer.',
    'The first half keeps the original start. The second half starts at the split time.': 'La primera mitad conserva el inicio original. La segunda empieza a la hora de división.',
    'Split at': 'Dividir en',
    'Both halves will have a positive duration.': 'Ambas mitades tendrán una duración positiva.',
    'Timer still running': 'Temporizador aún en marcha',
    'Stop the timer before shutdown, or shut down anyway and leave it running on the server.': 'Detén el temporizador antes de apagar, o apaga de todos modos y déjalo en el servidor.',
    'Stop timer': 'Detener temporizador',
    'Shut down anyway': 'Apagar de todos modos',
    'You were idle': 'Estabas inactivo',
    'Keep the time, discard the idle gap, or discard and continue the same activity.': 'Conservar el tiempo, descartar el hueco de inactividad, o descartar y continuar la misma actividad.',
    'Keep time': 'Conservar el tiempo',
    'Discard idle': 'Descartar inactividad',
    'Discard and continue': 'Descartar y continuar',
    'Start · %1 · %2': 'Iniciar · %1 · %2',
    'Change project, activity, range, billable, and tags for this finished entry.': 'Cambiar proyecto, actividad, intervalo, facturable y etiquetas de esta entrada finalizada.',
    'Save changes': 'Guardar cambios',
    'Create customer': 'Crear cliente',
    'Create activity': 'Crear actividad',
    'Create project': 'Crear proyecto',
    'Activity will be added to %1.': 'La actividad se añadirá a %1.',
    'Name': 'Nombre',
    'Customer': 'Cliente',
}

PLURALS = {
    '%1 minute ago': ['hace %1 minuto', 'hace %1 minutos'],
    '%1 hour ago': ['hace %1 hora', 'hace %1 horas'],
    '%1 day ago': ['hace %1 día', 'hace %1 días'],
    '%1 place found.': ['%1 lugar encontrado.', '%1 lugares encontrados.'],
}
