# -*- coding: utf-8 -*-
"""Film day (Drehzettel) and trips (Anfahrten) strings for the languages that
had only German so far. Merged by fill_po.py after the per-language
dictionaries (entries there win).

Column order: fr, es, it, nl, pt_BR, pl, uk, ru, ja, zh_CN
"""

LANGS = ["fr", "es", "it", "nl", "pt_BR", "pl", "uk", "ru", "ja", "zh_CN"]

ROWS = [
    ("Film day",
     "Journée de tournage", "Día de rodaje", "Giornata di riprese", "Draaidag", "Dia de filmagem",
     "Dzień zdjęciowy", "Знімальний день", "Съёмочный день", "撮影日", "拍摄日"),
    ("Shooting day saved",
     "Journée de tournage enregistrée", "Día de rodaje guardado", "Giornata di riprese salvata", "Draaidag opgeslagen",
     "Dia de filmagem salvo", "Zapisano dzień zdjęciowy", "Знімальний день збережено", "Съёмочный день сохранён",
     "撮影日を保存しました", "已保存拍摄日"),
    ("Travel day saved.",
     "Journée de voyage enregistrée.", "Día de viaje guardado.", "Giornata di viaggio salvata.", "Reisdag opgeslagen.",
     "Dia de viagem salvo.", "Zapisano dzień podróży.", "День у дорозі збережено.", "День в пути сохранён.",
     "移動日を保存しました。", "已保存旅行日。"),
    ("Log trip",
     "Enregistrer un trajet", "Registrar trayecto", "Registra tragitto", "Rit vastleggen", "Registrar viagem",
     "Zapisz przejazd", "Записати поїздку", "Записать поездку", "移動を記録", "记录行程"),
    ("Saved without the billable change: your Kimai account is not allowed to edit billable.",
     "Enregistré sans modifier « facturable » : votre compte Kimai n’a pas le droit de le modifier.",
     "Guardado sin el cambio de facturable: tu cuenta de Kimai no puede editar facturable.",
     "Salvato senza la modifica di fatturabile: il tuo account Kimai non può modificarlo.",
     "Opgeslagen zonder de wijziging van factureerbaar: je Kimai-account mag dat niet bewerken.",
     "Salvo sem a alteração de faturável: sua conta Kimai não pode editar esse campo.",
     "Zapisano bez zmiany rozliczalności: Twoje konto Kimai nie może jej edytować.",
     "Збережено без зміни «оплачуване»: ваш обліковий запис Kimai не може її редагувати.",
     "Сохранено без изменения «оплачиваемое»: ваша учётная запись Kimai не может его менять.",
     "請求対象の変更なしで保存しました: この Kimai アカウントでは請求対象を編集できません。",
     "已保存，但未更改可计费: 你的 Kimai 账户无权编辑可计费。"),
    ("Trips",
     "Trajets", "Trayectos", "Tragitti", "Ritten", "Viagens", "Przejazdy", "Поїздки", "Поездки", "移動", "行程"),
    ("Trips:",
     "Trajets :", "Trayectos:", "Tragitti:", "Ritten:", "Viagens:", "Przejazdy:", "Поїздки:", "Поездки:", "移動:", "行程:"),
    ("Log trips and show detected trips (Anfahrten plugin)",
     "Enregistrer des trajets et afficher les trajets détectés (plugin Anfahrten)",
     "Registrar trayectos y mostrar los detectados (plugin Anfahrten)",
     "Registra tragitti e mostra quelli rilevati (plugin Anfahrten)",
     "Ritten vastleggen en gedetecteerde ritten tonen (Anfahrten-plugin)",
     "Registrar viagens e mostrar as detectadas (plugin Anfahrten)",
     "Zapisuj przejazdy i pokazuj wykryte (wtyczka Anfahrten)",
     "Записувати поїздки та показувати виявлені (плагін Anfahrten)",
     "Записывать поездки и показывать найденные (плагин Anfahrten)",
     "移動を記録し、検出された移動を表示 (Anfahrten プラグイン)",
     "记录行程并显示检测到的行程 (Anfahrten 插件)"),
    ("No active engagement for this project and day. Only begin and end are saved.",
     "Aucun engagement actif pour ce projet ce jour-là. Seuls le début et la fin sont enregistrés.",
     "No hay contratación activa para este proyecto y día. Solo se guardan el inicio y el fin.",
     "Nessun ingaggio attivo per questo progetto e giorno. Vengono salvati solo inizio e fine.",
     "Geen actieve opdracht voor dit project en deze dag. Alleen begin en einde worden opgeslagen.",
     "Nenhuma contratação ativa para este projeto e dia. Apenas início e fim são salvos.",
     "Brak aktywnego zaangażowania dla tego projektu i dnia. Zapisywany jest tylko początek i koniec.",
     "Немає активного залучення для цього проєкту й дня. Зберігаються лише початок і кінець.",
     "Нет активного ангажемента для этого проекта и дня. Сохраняются только начало и конец.",
     "このプロジェクトと日付に有効な契約がありません。開始と終了のみ保存されます。",
     "此项目当天没有有效聘用。只保存开始和结束时间。"),
    ("You lack the Drehzettel permission on this Kimai server. Only begin and end are saved.",
     "Vous n’avez pas l’autorisation Drehzettel sur ce serveur Kimai. Seuls le début et la fin sont enregistrés.",
     "No tienes el permiso Drehzettel en este servidor Kimai. Solo se guardan el inicio y el fin.",
     "Non hai il permesso Drehzettel su questo server Kimai. Vengono salvati solo inizio e fine.",
     "Je hebt geen Drehzettel-recht op deze Kimai-server. Alleen begin en einde worden opgeslagen.",
     "Você não tem a permissão Drehzettel neste servidor Kimai. Apenas início e fim são salvos.",
     "Nie masz uprawnienia Drehzettel na tym serwerze Kimai. Zapisywany jest tylko początek i koniec.",
     "У вас немає дозволу Drehzettel на цьому сервері Kimai. Зберігаються лише початок і кінець.",
     "У вас нет права Drehzettel на этом сервере Kimai. Сохраняются только начало и конец.",
     "この Kimai サーバーで Drehzettel の権限がありません。開始と終了のみ保存されます。",
     "你在此 Kimai 服务器上没有 Drehzettel 权限。只保存开始和结束时间。"),
    ("Pick a project to load its film day.",
     "Choisissez un projet pour charger sa journée de tournage.", "Elige un proyecto para cargar su día de rodaje.",
     "Scegli un progetto per caricarne la giornata di riprese.", "Kies een project om de draaidag te laden.",
     "Escolha um projeto para carregar o dia de filmagem.", "Wybierz projekt, aby wczytać dzień zdjęciowy.",
     "Виберіть проєкт, щоб завантажити знімальний день.", "Выберите проект, чтобы загрузить съёмочный день.",
     "プロジェクトを選ぶと撮影日を読み込みます。", "选择项目以加载其拍摄日。"),
    ("Auto (from weekday)",
     "Auto (selon le jour)", "Auto (según el día)", "Auto (dal giorno)", "Auto (op weekdag)", "Auto (pelo dia)",
     "Auto (wg dnia tygodnia)", "Авто (за днем тижня)", "Авто (по дню недели)", "自動 (曜日から)", "自动 (按星期)"),
    ("Workday",
     "Jour ouvré", "Día laborable", "Giorno feriale", "Werkdag", "Dia útil", "Dzień roboczy", "Робочий день",
     "Рабочий день", "平日", "工作日"),
    ("Saturday",
     "Samedi", "Sábado", "Sabato", "Zaterdag", "Sábado", "Sobota", "Субота", "Суббота", "土曜日", "星期六"),
    ("Sunday",
     "Dimanche", "Domingo", "Domenica", "Zondag", "Domingo", "Niedziela", "Неділя", "Воскресенье", "日曜日", "星期日"),
    ("Holiday",
     "Jour férié", "Festivo", "Festivo", "Feestdag", "Feriado", "Święto", "Свято", "Праздник", "祝日", "节假日"),
    ("Shooting day",
     "Jour de tournage", "Día de rodaje", "Giorno di riprese", "Draaidag", "Dia de filmagem", "Dzień zdjęciowy",
     "Знімальний день", "Съёмочный день", "撮影日", "拍摄日"),
    ("Travel day",
     "Jour de voyage", "Día de viaje", "Giorno di viaggio", "Reisdag", "Dia de viagem", "Dzień podróży",
     "День у дорозі", "День в пути", "移動日", "旅行日"),
    ("Film day · %1",
     "Journée de tournage · %1", "Día de rodaje · %1", "Giornata di riprese · %1", "Draaidag · %1",
     "Dia de filmagem · %1", "Dzień zdjęciowy · %1", "Знімальний день · %1", "Съёмочный день · %1", "撮影日 · %1",
     "拍摄日 · %1"),
    ("Break",
     "Pause", "Pausa", "Pausa", "Pauze", "Pausa", "Przerwa", "Перерва", "Перерыв", "休憩", "休息"),
    ("Default (%1 min)",
     "Par défaut (%1 min)", "Predeterminado (%1 min)", "Predefinito (%1 min)", "Standaard (%1 min)",
     "Padrão (%1 min)", "Domyślnie (%1 min)", "Типово (%1 хв)", "По умолчанию (%1 мин)", "既定 (%1 分)", "默认 (%1 分钟)"),
    ("Work time: %1",
     "Temps de travail : %1", "Tiempo de trabajo: %1", "Tempo di lavoro: %1", "Werktijd: %1", "Tempo de trabalho: %1",
     "Czas pracy: %1", "Робочий час: %1", "Рабочее время: %1", "作業時間: %1", "工作时间: %1"),
    ("Work time: invalid range",
     "Temps de travail : plage invalide", "Tiempo de trabajo: rango no válido", "Tempo di lavoro: intervallo non valido",
     "Werktijd: ongeldige periode", "Tempo de trabalho: intervalo inválido", "Czas pracy: nieprawidłowy zakres",
     "Робочий час: неправильний проміжок", "Рабочее время: неверный интервал", "作業時間: 範囲が無効です",
     "工作时间: 时间范围无效"),
    ("Merge into one entry",
     "Fusionner en une seule entrée", "Unir en una sola entrada", "Unisci in una sola voce", "Samenvoegen tot één invoer",
     "Mesclar em uma entrada", "Scal w jeden wpis", "Об’єднати в один запис", "Объединить в одну запись",
     "1 件のエントリーにまとめる", "合并为一条记录"),
    ("Day category",
     "Catégorie du jour", "Categoría del día", "Categoria del giorno", "Dagcategorie", "Categoria do dia",
     "Kategoria dnia", "Категорія дня", "Категория дня", "日の区分", "日期类别"),
    ("Catering",
     "Catering", "Catering", "Catering", "Catering", "Catering", "Catering", "Кейтеринг", "Кейтеринг", "ケータリング",
     "餐饮"),
    ("Day type",
     "Type de jour", "Tipo de día", "Tipo di giorno", "Dagtype", "Tipo de dia", "Rodzaj dnia", "Тип дня", "Тип дня",
     "日の種類", "日期类型"),
    ("Production shooting day",
     "Jour de tournage de la production", "Día de rodaje de la producción", "Giorno di riprese della produzione",
     "Draaidag van de productie", "Dia de filmagem da produção", "Dzień zdjęciowy produkcji",
     "Знімальний день виробництва", "Съёмочный день производства", "制作の撮影日", "制作拍摄日"),
    ("Not set",
     "Non défini", "Sin definir", "Non impostato", "Niet ingesteld", "Não definido", "Nie ustawiono", "Не задано",
     "Не задано", "未設定", "未设置"),
    ("Surcharge day (1–7, empty = automatic)",
     "Jour de majoration (1–7, vide = automatique)", "Día de recargo (1–7, vacío = automático)",
     "Giorno di maggiorazione (1–7, vuoto = automatico)", "Toeslagdag (1–7, leeg = automatisch)",
     "Dia de adicional (1–7, vazio = automático)", "Dzień dopłaty (1–7, puste = automatycznie)",
     "День надбавки (1–7, порожньо = автоматично)", "День надбавки (1–7, пусто = автоматически)",
     "割増日 (1–7、空欄 = 自動)", "加价日 (1–7，留空 = 自动)"),
    ("Automatic",
     "Automatique", "Automático", "Automatico", "Automatisch", "Automático", "Automatycznie", "Автоматично",
     "Автоматически", "自動", "自动"),
    ("Extra pay / expenses",
     "Supplément / frais", "Pago extra / gastos", "Extra / spese", "Toeslag / onkosten", "Pagamento extra / despesas",
     "Dodatek / wydatki", "Доплата / витрати", "Доплата / расходы", "追加報酬 / 経費", "额外报酬 / 开支"),
    ("Earnings (non-binding)",
     "Gains (indicatif)", "Ingresos (orientativo)", "Guadagno (indicativo)", "Verdiensten (vrijblijvend)",
     "Ganhos (não vinculativo)", "Zarobek (orientacyjnie)", "Заробіток (орієнтовно)", "Заработок (ориентировочно)",
     "収入 (目安)", "收入 (仅供参考)"),
    ("Day pay from the Drehzettel plugin (as saved on the server, without weekly overtime)",
     "Salaire du jour du plugin Drehzettel (tel qu’enregistré sur le serveur, sans heures sup. hebdomadaires)",
     "Pago del día del plugin Drehzettel (según el servidor, sin horas extra semanales)",
     "Paga giornaliera dal plugin Drehzettel (come salvata sul server, senza straordinari settimanali)",
     "Dagloon uit de Drehzettel-plugin (zoals op de server opgeslagen, zonder wekelijks overwerk)",
     "Pagamento do dia pelo plugin Drehzettel (como salvo no servidor, sem horas extras semanais)",
     "Stawka dzienna z wtyczki Drehzettel (jak zapisano na serwerze, bez nadgodzin tygodniowych)",
     "Денна оплата з плагіна Drehzettel (як збережено на сервері, без тижневих понаднормових)",
     "Дневная оплата из плагина Drehzettel (как сохранено на сервере, без недельных переработок)",
     "Drehzettel プラグインによる日当 (サーバーに保存された値、週の残業を除く)",
     "Drehzettel 插件给出的日薪 (以服务器保存为准，不含每周加班)"),
    ("Needs the Drehzettel plugin on the Kimai server",
     "Nécessite le plugin Drehzettel sur le serveur Kimai", "Requiere el plugin Drehzettel en el servidor Kimai",
     "Richiede il plugin Drehzettel sul server Kimai", "Vereist de Drehzettel-plugin op de Kimai-server",
     "Requer o plugin Drehzettel no servidor Kimai", "Wymaga wtyczki Drehzettel na serwerze Kimai",
     "Потрібен плагін Drehzettel на сервері Kimai", "Нужен плагин Drehzettel на сервере Kimai",
     "Kimai サーバーに Drehzettel プラグインが必要です", "需要 Kimai 服务器安装 Drehzettel 插件"),
    ("Note",
     "Note", "Nota", "Nota", "Notitie", "Nota", "Notatka", "Нотатка", "Заметка", "メモ", "备注"),
    ("%1/%2",
     "%1/%2", "%1/%2", "%1/%2", "%1/%2", "%1/%2", "%1/%2", "%1/%2", "%1/%2", "%1/%2", "%1/%2"),
    ("Note (optional)",
     "Note (facultatif)", "Nota (opcional)", "Nota (facoltativa)", "Notitie (optioneel)", "Nota (opcional)",
     "Notatka (opcjonalnie)", "Нотатка (необов’язково)", "Заметка (необязательно)", "メモ (任意)", "备注 (可选)"),
    ("Save shooting day",
     "Enregistrer la journée", "Guardar día de rodaje", "Salva giornata di riprese", "Draaidag opslaan",
     "Salvar dia de filmagem", "Zapisz dzień zdjęciowy", "Зберегти знімальний день", "Сохранить съёмочный день",
     "撮影日を保存", "保存拍摄日"),
    ("Other",
     "Autre", "Otro", "Altro", "Overig", "Outro", "Inne", "Інше", "Другое", "その他", "其他"),
    ("Trips this week",
     "Trajets cette semaine", "Trayectos esta semana", "Tragitti questa settimana", "Ritten deze week",
     "Viagens nesta semana", "Przejazdy w tym tygodniu", "Поїздки цього тижня", "Поездки на этой неделе",
     "今週の移動", "本周行程"),
    ("%1 km",
     "%1 km", "%1 km", "%1 km", "%1 km", "%1 km", "%1 km", "%1 км", "%1 км", "%1 km", "%1 公里"),
    ("Trips this month",
     "Trajets ce mois-ci", "Trayectos este mes", "Tragitti questo mese", "Ritten deze maand", "Viagens neste mês",
     "Przejazdy w tym miesiącu", "Поїздки цього місяця", "Поездки в этом месяце", "今月の移動", "本月行程"),
    ("Business trip",
     "Déplacement professionnel", "Viaje de trabajo", "Viaggio di lavoro", "Zakenreis", "Viagem a trabalho",
     "Podróż służbowa", "Службова поїздка", "Служебная поездка", "出張", "公务出行"),
    ("Commute",
     "Trajet domicile-travail", "Trayecto al trabajo", "Tragitto casa-lavoro", "Woon-werkverkeer", "Trajeto casa-trabalho",
     "Dojazd do pracy", "Дорога на роботу", "Дорога на работу", "通勤", "通勤"),
    ("Private",
     "Privé", "Privado", "Privato", "Privé", "Particular", "Prywatny", "Приватна", "Личная", "私用", "私人"),
    ("Own car",
     "Voiture personnelle", "Coche propio", "Auto propria", "Eigen auto", "Carro próprio", "Własny samochód",
     "Власне авто", "Личный автомобиль", "自家用車", "私家车"),
    ("Rental car",
     "Voiture de location", "Coche de alquiler", "Auto a noleggio", "Huurauto", "Carro alugado", "Samochód wynajęty",
     "Орендоване авто", "Арендованный автомобиль", "レンタカー", "租赁车"),
    ("Company car",
     "Voiture de fonction", "Coche de empresa", "Auto aziendale", "Leaseauto van de zaak", "Carro da empresa",
     "Samochód służbowy", "Службове авто", "Служебный автомобиль", "社用車", "公司车"),
    ("Motorcycle / scooter",
     "Moto / scooter", "Moto / scooter", "Moto / scooter", "Motor / scooter", "Moto / scooter", "Motocykl / skuter",
     "Мотоцикл / скутер", "Мотоцикл / скутер", "バイク / スクーター", "摩托车 / 踏板车"),
    ("Bicycle",
     "Vélo", "Bicicleta", "Bicicletta", "Fiets", "Bicicleta", "Rower", "Велосипед", "Велосипед", "自転車", "自行车"),
    ("Public transport",
     "Transports en commun", "Transporte público", "Trasporto pubblico", "Openbaar vervoer", "Transporte público",
     "Komunikacja publiczna", "Громадський транспорт", "Общественный транспорт", "公共交通機関", "公共交通"),
    ("No specific vehicle",
     "Aucun véhicule précis", "Ningún vehículo concreto", "Nessun veicolo specifico", "Geen specifiek voertuig",
     "Nenhum veículo específico", "Bez konkretnego pojazdu", "Без конкретного транспорту",
     "Без конкретного транспорта", "特定の車両なし", "无指定车辆"),
    ("This month of the logbook is closed.",
     "Ce mois du carnet de route est clôturé.", "Este mes del libro de viajes está cerrado.",
     "Questo mese del registro di viaggio è chiuso.", "Deze maand van het rittenregister is afgesloten.",
     "Este mês do diário de bordo está fechado.", "Ten miesiąc ewidencji przejazdów jest zamknięty.",
     "Цей місяць журналу поїздок закрито.", "Этот месяц журнала поездок закрыт.",
     "この月の運行記録は締め切られています。", "该月的行车记录已关闭。"),
    ("Enter the distance.",
     "Saisissez la distance.", "Introduce la distancia.", "Inserisci la distanza.", "Voer de afstand in.",
     "Informe a distância.", "Wpisz odległość.", "Введіть відстань.", "Введите расстояние.", "距離を入力してください。",
     "请输入距离。"),
    ("Enter a distance between 0 and %1 km.",
     "Saisissez une distance entre 0 et %1 km.", "Introduce una distancia entre 0 y %1 km.",
     "Inserisci una distanza tra 0 e %1 km.", "Voer een afstand tussen 0 en %1 km in.",
     "Informe uma distância entre 0 e %1 km.", "Wpisz odległość od 0 do %1 km.", "Введіть відстань від 0 до %1 км.",
     "Введите расстояние от 0 до %1 км.", "0〜%1 km の距離を入力してください。", "请输入 0 到 %1 公里之间的距离。"),
    ("Arrival must be after departure.",
     "L’arrivée doit être postérieure au départ.", "La llegada debe ser posterior a la salida.",
     "L’arrivo deve essere dopo la partenza.", "Aankomst moet na vertrek liggen.",
     "A chegada deve ser depois da partida.", "Przyjazd musi być po wyjeździe.",
     "Прибуття має бути після відправлення.", "Прибытие должно быть после отправления.",
     "到着は出発より後にしてください。", "到达时间必须晚于出发时间。"),
    ("At most %1 characters.",
     "%1 caractères au maximum.", "Como máximo %1 caracteres.", "Al massimo %1 caratteri.", "Hoogstens %1 tekens.",
     "No máximo %1 caracteres.", "Najwyżej %1 znaków.", "Не більше %1 символів.", "Не более %1 символов.",
     "%1 文字以内。", "最多 %1 个字符。"),
    ("Invalid value.",
     "Valeur invalide.", "Valor no válido.", "Valore non valido.", "Ongeldige waarde.", "Valor inválido.",
     "Nieprawidłowa wartość.", "Неправильне значення.", "Неверное значение.", "値が無効です。", "值无效。"),
    ("Accept detected trip",
     "Accepter le trajet détecté", "Aceptar trayecto detectado", "Accetta tragitto rilevato", "Gedetecteerde rit accepteren",
     "Aceitar viagem detectada", "Przyjmij wykryty przejazd", "Прийняти виявлену поїздку", "Принять найденную поездку",
     "検出された移動を承認", "接受检测到的行程"),
    ("Edit trip",
     "Modifier le trajet", "Editar trayecto", "Modifica tragitto", "Rit bewerken", "Editar viagem", "Edytuj przejazd",
     "Змінити поїздку", "Изменить поездку", "移動を編集", "编辑行程"),
    ("Date:",
     "Date :", "Fecha:", "Data:", "Datum:", "Data:", "Data:", "Дата:", "Дата:", "日付:", "日期:"),
    ("Purpose:",
     "Motif :", "Motivo:", "Scopo:", "Doel:", "Finalidade:", "Cel:", "Мета:", "Цель:", "目的:", "目的:"),
    ("Means of travel:",
     "Moyen de transport :", "Medio de transporte:", "Mezzo di trasporto:", "Vervoermiddel:", "Meio de transporte:",
     "Środek transportu:", "Транспорт:", "Транспорт:", "交通手段:", "出行方式:"),
    ("Vehicle:",
     "Véhicule :", "Vehículo:", "Veicolo:", "Voertuig:", "Veículo:", "Pojazd:", "Транспортний засіб:",
     "Транспортное средство:", "車両:", "车辆:"),
    ("Distance (one way):",
     "Distance (aller simple) :", "Distancia (solo ida):", "Distanza (solo andata):", "Afstand (enkele reis):",
     "Distância (só ida):", "Odległość (w jedną stronę):", "Відстань (в один бік):", "Расстояние (в одну сторону):",
     "距離 (片道):", "距离 (单程):"),
    ("%1 (from your profile)",
     "%1 (de votre profil)", "%1 (de tu perfil)", "%1 (dal tuo profilo)", "%1 (uit je profiel)", "%1 (do seu perfil)",
     "%1 (z profilu)", "%1 (з вашого профілю)", "%1 (из вашего профиля)", "%1 (プロフィールから)", "%1 (来自个人资料)"),
    ("Distance in kilometers",
     "Distance en kilomètres", "Distancia en kilómetros", "Distanza in chilometri", "Afstand in kilometers",
     "Distância em quilômetros", "Odległość w kilometrach", "Відстань у кілометрах", "Расстояние в километрах",
     "距離 (km)", "距离 (公里)"),
    ("km",
     "km", "km", "km", "km", "km", "km", "км", "км", "km", "公里"),
    ("Round trip (there and back)",
     "Aller-retour", "Ida y vuelta", "Andata e ritorno", "Heen en terug", "Ida e volta", "Tam i z powrotem",
     "Туди й назад", "Туда и обратно", "往復", "往返"),
    ("From:",
     "De :", "Desde:", "Da:", "Van:", "De:", "Skąd:", "Звідки:", "Откуда:", "出発地:", "出发地:"),
    ("To:",
     "À :", "Hasta:", "A:", "Naar:", "Para:", "Dokąd:", "Куди:", "Куда:", "目的地:", "目的地:"),
    ("Departure and arrival times",
     "Heures de départ et d’arrivée", "Horas de salida y llegada", "Orari di partenza e arrivo",
     "Vertrek- en aankomsttijd", "Horários de partida e chegada", "Godziny wyjazdu i przyjazdu",
     "Час відправлення й прибуття", "Время отправления и прибытия", "出発・到着時刻", "出发和到达时间"),
    ("Departure / arrival:",
     "Départ / arrivée :", "Salida / llegada:", "Partenza / arrivo:", "Vertrek / aankomst:", "Partida / chegada:",
     "Wyjazd / przyjazd:", "Відправлення / прибуття:", "Отправление / прибытие:", "出発 / 到着:", "出发 / 到达:"),
    ("Comment:",
     "Commentaire :", "Comentario:", "Commento:", "Opmerking:", "Comentário:", "Komentarz:", "Коментар:",
     "Комментарий:", "コメント:", "备注:"),
    ("Time entry:",
     "Saisie de temps :", "Registro de tiempo:", "Registrazione:", "Tijdregistratie:", "Registro de tempo:",
     "Wpis czasu:", "Запис часу:", "Запись времени:", "時間エントリー:", "时间记录:"),
    ("Unlink",
     "Dissocier", "Desvincular", "Scollega", "Ontkoppelen", "Desvincular", "Odłącz", "Від’єднати", "Отвязать",
     "リンクを解除", "取消关联"),
    ("Do not link this trip to the time entry",
     "Ne pas lier ce trajet à la saisie de temps", "No vincular este trayecto al registro de tiempo",
     "Non collegare questo tragitto alla registrazione", "Deze rit niet aan de tijdregistratie koppelen",
     "Não vincular esta viagem ao registro de tempo", "Nie łącz tego przejazdu z wpisem czasu",
     "Не пов’язувати цю поїздку із записом часу", "Не связывать эту поездку с записью времени",
     "この移動を時間エントリーにリンクしない", "不将此行程关联到时间记录"),
    ("Accept",
     "Accepter", "Aceptar", "Accetta", "Accepteren", "Aceitar", "Przyjmij", "Прийняти", "Принять", "承認", "接受"),
    ("Save trip",
     "Enregistrer le trajet", "Guardar trayecto", "Salva tragitto", "Rit opslaan", "Salvar viagem", "Zapisz przejazd",
     "Зберегти поїздку", "Сохранить поездку", "移動を保存", "保存行程"),
    ("Really delete?",
     "Vraiment supprimer ?", "¿Eliminar de verdad?", "Eliminare davvero?", "Echt verwijderen?", "Excluir mesmo?",
     "Na pewno usunąć?", "Справді видалити?", "Точно удалить?", "本当に削除しますか?", "确定删除？"),
    ("Delete",
     "Supprimer", "Eliminar", "Elimina", "Verwijderen", "Excluir", "Usuń", "Видалити", "Удалить", "削除", "删除"),
    ("Detected trip",
     "Trajet détecté", "Trayecto detectado", "Tragitto rilevato", "Gedetecteerde rit", "Viagem detectada",
     "Wykryty przejazd", "Виявлена поїздка", "Найденная поездка", "検出された移動", "检测到的行程"),
    ("Add this trip to the logbook",
     "Ajouter ce trajet au carnet de route", "Añadir este trayecto al libro de viajes",
     "Aggiungi questo tragitto al registro", "Deze rit aan het rittenregister toevoegen",
     "Adicionar esta viagem ao diário de bordo", "Dodaj ten przejazd do ewidencji", "Додати поїздку до журналу",
     "Добавить поездку в журнал", "この移動を運行記録に追加", "将此行程加入行车记录"),
    ("Edit and accept",
     "Modifier et accepter", "Editar y aceptar", "Modifica e accetta", "Bewerken en accepteren", "Editar e aceitar",
     "Edytuj i przyjmij", "Змінити й прийняти", "Изменить и принять", "編集して承認", "编辑并接受"),
    ("Dismiss",
     "Ignorer", "Descartar", "Ignora", "Negeren", "Descartar", "Odrzuć", "Відхилити", "Отклонить", "破棄", "忽略"),
    ("Dismiss this detected trip",
     "Ignorer ce trajet détecté", "Descartar este trayecto detectado", "Ignora questo tragitto rilevato",
     "Deze gedetecteerde rit negeren", "Descartar esta viagem detectada", "Odrzuć ten wykryty przejazd",
     "Відхилити цю виявлену поїздку", "Отклонить эту найденную поездку", "この検出された移動を破棄", "忽略此检测到的行程"),
    ("Log a trip for this entry",
     "Enregistrer un trajet pour cette entrée", "Registrar un trayecto para esta entrada",
     "Registra un tragitto per questa voce", "Een rit voor deze invoer vastleggen",
     "Registrar uma viagem para esta entrada", "Zapisz przejazd dla tego wpisu", "Записати поїздку для цього запису",
     "Записать поездку для этой записи", "このエントリーの移動を記録", "为此记录添加行程"),
    ("Trip saved: %1 km",
     "Trajet enregistré : %1 km", "Trayecto guardado: %1 km", "Tragitto salvato: %1 km", "Rit opgeslagen: %1 km",
     "Viagem salva: %1 km", "Zapisano przejazd: %1 km", "Поїздку збережено: %1 км", "Поездка сохранена: %1 км",
     "移動を保存しました: %1 km", "已保存行程: %1 公里"),
    ("Trips could not be loaded: %1",
     "Impossible de charger les trajets : %1", "No se pudieron cargar los trayectos: %1",
     "Impossibile caricare i tragitti: %1", "Ritten konden niet worden geladen: %1",
     "Não foi possível carregar as viagens: %1", "Nie udało się wczytać przejazdów: %1",
     "Не вдалося завантажити поїздки: %1", "Не удалось загрузить поездки: %1", "移動を読み込めませんでした: %1",
     "无法加载行程: %1"),
    ("Commute logged: %1 km",
     "Trajet domicile-travail enregistré : %1 km", "Trayecto al trabajo registrado: %1 km",
     "Tragitto casa-lavoro registrato: %1 km", "Woon-werkrit vastgelegd: %1 km", "Trajeto casa-trabalho registrado: %1 km",
     "Zapisano dojazd: %1 km", "Дорогу на роботу записано: %1 км", "Дорога на работу записана: %1 км",
     "通勤を記録しました: %1 km", "已记录通勤: %1 公里"),
    ("The trip could not be accepted: %1",
     "Impossible d’accepter le trajet : %1", "No se pudo aceptar el trayecto: %1", "Impossibile accettare il tragitto: %1",
     "De rit kon niet worden geaccepteerd: %1", "Não foi possível aceitar a viagem: %1",
     "Nie udało się przyjąć przejazdu: %1", "Не вдалося прийняти поїздку: %1", "Не удалось принять поездку: %1",
     "移動を承認できませんでした: %1", "无法接受行程: %1"),
    ("The trip could not be dismissed: %1",
     "Impossible d’ignorer le trajet : %1", "No se pudo descartar el trayecto: %1", "Impossibile ignorare il tragitto: %1",
     "De rit kon niet worden genegeerd: %1", "Não foi possível descartar a viagem: %1",
     "Nie udało się odrzucić przejazdu: %1", "Не вдалося відхилити поїздку: %1", "Не удалось отклонить поездку: %1",
     "移動を破棄できませんでした: %1", "无法忽略行程: %1"),
    ("Commute today",
     "Trajet domicile-travail aujourd’hui", "Trayecto al trabajo hoy", "Tragitto casa-lavoro oggi", "Woon-werk vandaag",
     "Trajeto casa-trabalho hoje", "Dojazd dziś", "Дорога на роботу сьогодні", "Дорога на работу сегодня", "今日の通勤",
     "今日通勤"),
    ("Refresh",
     "Actualiser", "Actualizar", "Aggiorna", "Vernieuwen", "Atualizar", "Odśwież", "Оновити", "Обновить", "更新", "刷新"),
    ("Detected trips",
     "Trajets détectés", "Trayectos detectados", "Tragitti rilevati", "Gedetecteerde ritten", "Viagens detectadas",
     "Wykryte przejazdy", "Виявлені поїздки", "Найденные поездки", "検出された移動", "检测到的行程"),
    ("Previous month",
     "Mois précédent", "Mes anterior", "Mese precedente", "Vorige maand", "Mês anterior", "Poprzedni miesiąc",
     "Попередній місяць", "Предыдущий месяц", "前の月", "上个月"),
    ("Next month",
     "Mois suivant", "Mes siguiente", "Mese successivo", "Volgende maand", "Próximo mês", "Następny miesiąc",
     "Наступний місяць", "Следующий месяц", "次の月", "下个月"),
    ("month closed",
     "mois clôturé", "mes cerrado", "mese chiuso", "maand afgesloten", "mês fechado", "miesiąc zamknięty",
     "місяць закрито", "месяц закрыт", "月締め済み", "本月已关闭"),
    ("No trips this month",
     "Aucun trajet ce mois-ci", "No hay trayectos este mes", "Nessun tragitto questo mese", "Geen ritten deze maand",
     "Nenhuma viagem neste mês", "Brak przejazdów w tym miesiącu", "Цього місяця поїздок немає",
     "В этом месяце поездок нет", "今月の移動はありません", "本月没有行程"),
    ("Time entry #%1",
     "Saisie de temps n° %1", "Registro de tiempo n.º %1", "Registrazione n. %1", "Tijdregistratie #%1",
     "Registro de tempo nº %1", "Wpis czasu nr %1", "Запис часу № %1", "Запись времени № %1", "時間エントリー #%1",
     "时间记录 #%1"),
    ("round trip",
     "aller-retour", "ida y vuelta", "andata e ritorno", "heen en terug", "ida e volta", "tam i z powrotem",
     "туди й назад", "туда и обратно", "往復", "往返"),
    ("Kimai plugins",
     "Plugins Kimai", "Plugins de Kimai", "Plugin di Kimai", "Kimai-plugins", "Plugins do Kimai", "Wtyczki Kimai",
     "Плагіни Kimai", "Плагины Kimai", "Kimai プラグイン", "Kimai 插件"),
    ("Log trips and show detected trips",
     "Enregistrer des trajets et afficher les trajets détectés", "Registrar trayectos y mostrar los detectados",
     "Registra tragitti e mostra quelli rilevati", "Ritten vastleggen en gedetecteerde ritten tonen",
     "Registrar viagens e mostrar as detectadas", "Zapisuj przejazdy i pokazuj wykryte",
     "Записувати поїздки та показувати виявлені", "Записывать поездки и показывать найденные",
     "移動を記録し、検出された移動を表示", "记录行程并显示检测到的行程"),
    ("Only when the Anfahrten plugin (MileageBundle) is installed on the Kimai server and your account may use it.",
     "Uniquement si le plugin Anfahrten (MileageBundle) est installé sur le serveur Kimai et que votre compte peut l’utiliser.",
     "Solo si el plugin Anfahrten (MileageBundle) está instalado en el servidor Kimai y tu cuenta puede usarlo.",
     "Solo se il plugin Anfahrten (MileageBundle) è installato sul server Kimai e il tuo account può usarlo.",
     "Alleen als de Anfahrten-plugin (MileageBundle) op de Kimai-server staat en je account die mag gebruiken.",
     "Somente se o plugin Anfahrten (MileageBundle) estiver instalado no servidor Kimai e sua conta puder usá-lo.",
     "Tylko gdy wtyczka Anfahrten (MileageBundle) jest zainstalowana na serwerze Kimai i Twoje konto może z niej korzystać.",
     "Лише якщо плагін Anfahrten (MileageBundle) встановлено на сервері Kimai і ваш обліковий запис може ним користуватися.",
     "Только если плагин Anfahrten (MileageBundle) установлен на сервере Kimai и вашей учётной записи он доступен.",
     "Kimai サーバーに Anfahrten プラグイン (MileageBundle) があり、アカウントで利用できる場合のみ。",
     "仅当 Kimai 服务器安装了 Anfahrten 插件 (MileageBundle) 且你的账户可以使用时。"),
    ("Trip saved",
     "Trajet enregistré", "Trayecto guardado", "Tragitto salvato", "Rit opgeslagen", "Viagem salva", "Zapisano przejazd",
     "Поїздку збережено", "Поездка сохранена", "移動を保存しました", "已保存行程"),
    ("Trip",
     "Trajet", "Trayecto", "Tragitto", "Rit", "Viagem", "Przejazd", "Поїздка", "Поездка", "移動", "行程"),
    ("Log a shooting day",
     "Saisir une journée de tournage", "Registrar un día de rodaje", "Registra una giornata di riprese",
     "Een draaidag vastleggen", "Registrar um dia de filmagem", "Zapisz dzień zdjęciowy", "Записати знімальний день",
     "Записать съёмочный день", "撮影日を記録", "记录拍摄日"),
    ("Log a trip (Anfahrten plugin)",
     "Enregistrer un trajet (plugin Anfahrten)", "Registrar un trayecto (plugin Anfahrten)",
     "Registra un tragitto (plugin Anfahrten)", "Een rit vastleggen (Anfahrten-plugin)",
     "Registrar uma viagem (plugin Anfahrten)", "Zapisz przejazd (wtyczka Anfahrten)",
     "Записати поїздку (плагін Anfahrten)", "Записать поездку (плагин Anfahrten)", "移動を記録 (Anfahrten プラグイン)",
     "记录行程 (Anfahrten 插件)"),
]

# Plural forms per language: fr/es/it/nl/pt_BR 2, pl/uk/ru 3, ja/zh_CN 1.
PLURALS = {
    "%1 other entry of this day could not be deleted: %2": {
        "fr": ["%1 autre entrée de ce jour n’a pas pu être supprimée : %2", "%1 autres entrées de ce jour n’ont pas pu être supprimées : %2"],
        "es": ["No se pudo eliminar %1 otra entrada de este día: %2", "No se pudieron eliminar %1 otras entradas de este día: %2"],
        "it": ["%1 altra voce di questo giorno non è stata eliminata: %2", "%1 altre voci di questo giorno non sono state eliminate: %2"],
        "nl": ["%1 andere invoer van deze dag kon niet worden verwijderd: %2", "%1 andere invoeren van deze dag konden niet worden verwijderd: %2"],
        "pt_BR": ["Não foi possível excluir %1 outra entrada deste dia: %2", "Não foi possível excluir %1 outras entradas deste dia: %2"],
        "pl": ["Nie udało się usunąć %1 innego wpisu z tego dnia: %2", "Nie udało się usunąć %1 innych wpisów z tego dnia: %2", "Nie udało się usunąć %1 innych wpisów z tego dnia: %2"],
        "uk": ["Не вдалося видалити %1 інший запис цього дня: %2", "Не вдалося видалити %1 інші записи цього дня: %2", "Не вдалося видалити %1 інших записів цього дня: %2"],
        "ru": ["Не удалось удалить %1 другую запись этого дня: %2", "Не удалось удалить %1 другие записи этого дня: %2", "Не удалось удалить %1 других записей этого дня: %2"],
        "ja": ["この日の他の %1 件のエントリーを削除できませんでした: %2"],
        "zh_CN": ["无法删除当天的另外 %1 条记录: %2"],
    },
    "%1 minute": {
        "fr": ["%1 minute", "%1 minutes"], "es": ["%1 minuto", "%1 minutos"], "it": ["%1 minuto", "%1 minuti"],
        "nl": ["%1 minuut", "%1 minuten"], "pt_BR": ["%1 minuto", "%1 minutos"],
        "pl": ["%1 minuta", "%1 minuty", "%1 minut"], "uk": ["%1 хвилина", "%1 хвилини", "%1 хвилин"],
        "ru": ["%1 минута", "%1 минуты", "%1 минут"], "ja": ["%1 分"], "zh_CN": ["%1 分钟"],
    },
    "Saving sets this entry from begin to end and deletes the other entry of this project on this day (%2). Its description and tags are lost.": {
        "fr": ["L’enregistrement étend cette entrée du début à la fin et supprime l’autre entrée de ce projet ce jour-là (%2). Sa description et ses étiquettes sont perdues.",
               "L’enregistrement étend cette entrée du début à la fin et supprime les %1 autres entrées de ce projet ce jour-là (%2). Leurs descriptions et étiquettes sont perdues."],
        "es": ["Al guardar, esta entrada abarca del inicio al fin y se elimina la otra entrada de este proyecto ese día (%2). Se pierden su descripción y etiquetas.",
               "Al guardar, esta entrada abarca del inicio al fin y se eliminan las %1 otras entradas de este proyecto ese día (%2). Se pierden sus descripciones y etiquetas."],
        "it": ["Salvando, questa voce va dall’inizio alla fine e l’altra voce di questo progetto nel giorno (%2) viene eliminata. Descrizione e tag vanno persi.",
               "Salvando, questa voce va dall’inizio alla fine e le %1 altre voci di questo progetto nel giorno (%2) vengono eliminate. Descrizioni e tag vanno persi."],
        "nl": ["Bij opslaan loopt deze invoer van begin tot einde en wordt de andere invoer van dit project op deze dag (%2) verwijderd. De omschrijving en tags gaan verloren.",
               "Bij opslaan loopt deze invoer van begin tot einde en worden de %1 andere invoeren van dit project op deze dag (%2) verwijderd. Hun omschrijvingen en tags gaan verloren."],
        "pt_BR": ["Ao salvar, esta entrada vai do início ao fim e a outra entrada deste projeto no dia (%2) é excluída. A descrição e as tags dela são perdidas.",
                  "Ao salvar, esta entrada vai do início ao fim e as %1 outras entradas deste projeto no dia (%2) são excluídas. As descrições e tags delas são perdidas."],
        "pl": ["Zapis rozciąga ten wpis od początku do końca i usuwa %1 inny wpis tego projektu z tego dnia (%2). Jego opis i tagi przepadają.",
               "Zapis rozciąga ten wpis od początku do końca i usuwa %1 inne wpisy tego projektu z tego dnia (%2). Ich opisy i tagi przepadają.",
               "Zapis rozciąga ten wpis od początku do końca i usuwa %1 innych wpisów tego projektu z tego dnia (%2). Ich opisy i tagi przepadają."],
        "uk": ["Збереження розтягує цей запис від початку до кінця й видаляє %1 інший запис цього проєкту за день (%2). Його опис і теги буде втрачено.",
               "Збереження розтягує цей запис від початку до кінця й видаляє %1 інші записи цього проєкту за день (%2). Їхні описи й теги буде втрачено.",
               "Збереження розтягує цей запис від початку до кінця й видаляє %1 інших записів цього проєкту за день (%2). Їхні описи й теги буде втрачено."],
        "ru": ["Сохранение растягивает эту запись от начала до конца и удаляет %1 другую запись проекта за этот день (%2). Её описание и теги будут потеряны.",
               "Сохранение растягивает эту запись от начала до конца и удаляет %1 другие записи проекта за этот день (%2). Их описания и теги будут потеряны.",
               "Сохранение растягивает эту запись от начала до конца и удаляет %1 других записей проекта за этот день (%2). Их описания и теги будут потеряны."],
        "ja": ["保存すると、このエントリーが開始から終了までになり、この日のこのプロジェクトの他の %1 件のエントリー (%2) は削除されます。説明とタグは失われます。"],
        "zh_CN": ["保存后，此记录将覆盖从开始到结束的时间，并删除该项目当天的另外 %1 条记录 (%2)。其描述和标签将丢失。"],
    },
    "This project has %1 more entry on this day (%2). Saving only updates the entry shown; the work time above does not include the other one.": {
        "fr": ["Ce projet a %1 autre entrée ce jour-là (%2). L’enregistrement ne met à jour que l’entrée affichée ; le temps de travail ci-dessus ne l’inclut pas.",
               "Ce projet a %1 autres entrées ce jour-là (%2). L’enregistrement ne met à jour que l’entrée affichée ; le temps de travail ci-dessus ne les inclut pas."],
        "es": ["Este proyecto tiene %1 entrada más ese día (%2). Al guardar solo se actualiza la entrada mostrada; el tiempo de trabajo no la incluye.",
               "Este proyecto tiene %1 entradas más ese día (%2). Al guardar solo se actualiza la entrada mostrada; el tiempo de trabajo no las incluye."],
        "it": ["Questo progetto ha %1 altra voce in questo giorno (%2). Il salvataggio aggiorna solo la voce mostrata; il tempo di lavoro sopra non la include.",
               "Questo progetto ha altre %1 voci in questo giorno (%2). Il salvataggio aggiorna solo la voce mostrata; il tempo di lavoro sopra non le include."],
        "nl": ["Dit project heeft op deze dag nog %1 invoer (%2). Opslaan werkt alleen de getoonde invoer bij; de werktijd hierboven telt de andere niet mee.",
               "Dit project heeft op deze dag nog %1 invoeren (%2). Opslaan werkt alleen de getoonde invoer bij; de werktijd hierboven telt de andere niet mee."],
        "pt_BR": ["Este projeto tem mais %1 entrada neste dia (%2). Salvar atualiza só a entrada mostrada; o tempo de trabalho acima não a inclui.",
                  "Este projeto tem mais %1 entradas neste dia (%2). Salvar atualiza só a entrada mostrada; o tempo de trabalho acima não as inclui."],
        "pl": ["Ten projekt ma tego dnia %1 dodatkowy wpis (%2). Zapis aktualizuje tylko pokazany wpis; czas pracy powyżej go nie obejmuje.",
               "Ten projekt ma tego dnia %1 dodatkowe wpisy (%2). Zapis aktualizuje tylko pokazany wpis; czas pracy powyżej ich nie obejmuje.",
               "Ten projekt ma tego dnia %1 dodatkowych wpisów (%2). Zapis aktualizuje tylko pokazany wpis; czas pracy powyżej ich nie obejmuje."],
        "uk": ["Цей проєкт має ще %1 запис за цей день (%2). Збереження оновлює лише показаний запис; робочий час вище його не враховує.",
               "Цей проєкт має ще %1 записи за цей день (%2). Збереження оновлює лише показаний запис; робочий час вище їх не враховує.",
               "Цей проєкт має ще %1 записів за цей день (%2). Збереження оновлює лише показаний запис; робочий час вище їх не враховує."],
        "ru": ["У этого проекта есть ещё %1 запись за этот день (%2). Сохранение обновляет только показанную запись; рабочее время выше её не учитывает.",
               "У этого проекта есть ещё %1 записи за этот день (%2). Сохранение обновляет только показанную запись; рабочее время выше их не учитывает.",
               "У этого проекта есть ещё %1 записей за этот день (%2). Сохранение обновляет только показанную запись; рабочее время выше их не учитывает."],
        "ja": ["このプロジェクトにはこの日に他に %1 件のエントリーがあります (%2)。保存で更新されるのは表示中のエントリーのみで、上の作業時間には含まれません。"],
        "zh_CN": ["此项目当天还有 %1 条记录 (%2)。保存只更新当前显示的记录；上面的工作时间不包含其他记录。"],
    },
    "%2 km (1 trip)": {
        "fr": ["%2 km (%1 trajet)", "%2 km (%1 trajets)"], "es": ["%2 km (%1 trayecto)", "%2 km (%1 trayectos)"],
        "it": ["%2 km (%1 tragitto)", "%2 km (%1 tragitti)"], "nl": ["%2 km (%1 rit)", "%2 km (%1 ritten)"],
        "pt_BR": ["%2 km (%1 viagem)", "%2 km (%1 viagens)"],
        "pl": ["%2 km (%1 przejazd)", "%2 km (%1 przejazdy)", "%2 km (%1 przejazdów)"],
        "uk": ["%2 км (%1 поїздка)", "%2 км (%1 поїздки)", "%2 км (%1 поїздок)"],
        "ru": ["%2 км (%1 поездка)", "%2 км (%1 поездки)", "%2 км (%1 поездок)"],
        "ja": ["%2 km (%1 件)"], "zh_CN": ["%2 公里 (%1 次行程)"],
    },
    "+%1 more detected trip": {
        "fr": ["+%1 autre trajet détecté", "+%1 autres trajets détectés"],
        "es": ["+%1 trayecto detectado más", "+%1 trayectos detectados más"],
        "it": ["+%1 altro tragitto rilevato", "+%1 altri tragitti rilevati"],
        "nl": ["+%1 andere gedetecteerde rit", "+%1 andere gedetecteerde ritten"],
        "pt_BR": ["+%1 viagem detectada", "+%1 viagens detectadas"],
        "pl": ["+%1 kolejny wykryty przejazd", "+%1 kolejne wykryte przejazdy", "+%1 kolejnych wykrytych przejazdów"],
        "uk": ["+%1 виявлена поїздка", "+%1 виявлені поїздки", "+%1 виявлених поїздок"],
        "ru": ["+%1 найденная поездка", "+%1 найденные поездки", "+%1 найденных поездок"],
        "ja": ["+ 検出された移動 %1 件"], "zh_CN": ["+ 另外 %1 个检测到的行程"],
    },
    "%2 km in 1 trip": {
        "fr": ["%2 km en %1 trajet", "%2 km en %1 trajets"], "es": ["%2 km en %1 trayecto", "%2 km en %1 trayectos"],
        "it": ["%2 km in %1 tragitto", "%2 km in %1 tragitti"], "nl": ["%2 km in %1 rit", "%2 km in %1 ritten"],
        "pt_BR": ["%2 km em %1 viagem", "%2 km em %1 viagens"],
        "pl": ["%2 km w %1 przejeździe", "%2 km w %1 przejazdach", "%2 km w %1 przejazdach"],
        "uk": ["%2 км за %1 поїздку", "%2 км за %1 поїздки", "%2 км за %1 поїздок"],
        "ru": ["%2 км за %1 поездку", "%2 км за %1 поездки", "%2 км за %1 поездок"],
        "ja": ["%1 件の移動で %2 km"], "zh_CN": ["%1 次行程共 %2 公里"],
    },
}

T_BY_LANG = {lang: {} for lang in LANGS}
for row in ROWS:
    for lang, value in zip(LANGS, row[1:]):
        T_BY_LANG[lang][row[0]] = value
