# -*- coding: utf-8 -*-
T = {
    'Project-specific': 'Spécifique au projet',
    'Global activities': 'Activités globales',
    'Plasmai': 'Plasmai',
    'Toggle Plasmai tracking': 'Activer/désactiver le suivi Plasmai',
    'Stop Plasmai tracking': 'Arrêter le suivi Plasmai',
    'Loading…': 'Chargement…',
    'Not configured — right-click to configure': 'Non configuré — clic droit pour configurer',
    'just now': 'à l’instant',
    'yesterday': 'hier',
    'Not configured': 'Non configuré',
    'Connecting to %1…': 'Connexion à %1…',
    'Connection problem': 'Problème de connexion',
    'Connected to %1 (%2)': 'Connecté à %1 (%2)',
    'Connected to %1': 'Connecté à %1',
    'Enter valid begin and end date/time.': 'Saisissez une date/heure de début et de fin valides.',
    'End must be after begin.': 'La fin doit être postérieure au début.',
    'Entry added': 'Entrée ajoutée',
    'Manual time entry': 'Saisie manuelle du temps',
    '%1 left today': '%1 restant aujourd’hui',
    '%1 over today': '%1 en dépassement aujourd’hui',
    '%1 left this week': '%1 restant cette semaine',
    '%1 over this week': '%1 en dépassement cette semaine',
    'Today %1': 'Aujourd’hui %1',
    'Week %1': 'Semaine %1',
    'Tracking started': 'Suivi démarré',
    'Switched activity': 'Activité changée',
    'Tracking stopped (idle)': 'Suivi arrêté (inactivité)',
    'Tracking stopped': 'Suivi arrêté',
    'Stop the current timer before starting another': 'Arrêtez le minuteur en cours avant d’en démarrer un autre',
    'Stop tracking?': 'Arrêter le suivi ?',
    'Stop tracking %1 · %2?': 'Arrêter le suivi de %1 · %2 ?',
    'Statistics': 'Statistiques',
    'Add entry': 'Ajouter une entrée',
    'Add a manual time entry': 'Ajouter une saisie manuelle du temps',
    'Show statistics': 'Afficher les statistiques',
    'Back to timer': 'Retour au minuteur',
    'Connect a time tracker': 'Connecter un outil de suivi du temps',
    'Add your service, server URL (if needed), and API token to start tracking from the panel.': 'Ajoutez votre service, l’URL du serveur (si nécessaire) et le jeton API pour démarrer le suivi depuis le panneau.',
    'Configure Plasmai': 'Configurer Plasmai',
    'Retry': 'Réessayer',
    'Configure': 'Configurer',
    'Not tracking': 'Aucun suivi en cours',
    'Description': 'Description',
    'Save description': 'Enregistrer la description',
    'Stop': 'Arrêter',
    'Continue · %1 · %2': 'Continuer · %1 · %2',
    'Favorites': 'Favoris',
    'No favorites yet': 'Aucun favori pour l’instant',
    'Pin frequent project/activity pairs in the widget settings.': 'Épinglez les paires projet/activité fréquentes dans les paramètres du widget.',
    'Configure favorites': 'Configurer les favoris',
    '+%1 more in settings': '+%1 de plus dans les paramètres',
    'Recent': 'Récents',
    'No recent activities': 'Aucune activité récente',
    'Start tracking to build your recent list.': 'Démarrez le suivi pour remplir votre liste récente.',
    'Switch to another activity…': 'Passer à une autre activité…',
    'Start something else…': 'Démarrer autre chose…',
    'Switch activity': 'Changer d’activité',
    'New activity': 'Nouvelle activité',
    'Select project…': 'Sélectionner un projet…',
    'Select activity…': 'Sélectionner une activité…',
    'Description (optional)': 'Description (facultatif)',
    'Start': 'Démarrer',
    'Switch': 'Changer',
    'Cancel': 'Annuler',
    'Unknown error': 'Erreur inconnue',
    'URL and API token are required': 'L’URL et le jeton API sont requis',
    'Configure your time tracker URL and API token': 'Configurez l’URL et le jeton API de votre outil de suivi du temps',
    'This action is not supported for the selected service yet.': 'Cette action n’est pas encore prise en charge pour le service sélectionné.',
    'Cannot reach the server. Check your network, URL, or TLS certificate.': 'Impossible d’atteindre le serveur. Vérifiez votre réseau, l’URL ou le certificat TLS.',
    'Authentication failed. Check your API token.': 'Échec de l’authentification. Vérifiez votre jeton API.',
    'Server not found. Check your URL.': 'Serveur introuvable. Vérifiez votre URL.',
    'Access denied. Your token may lack required permissions.': 'Accès refusé. Votre jeton peut ne pas disposer des autorisations requises.',
    'Server error (%1).': 'Erreur serveur (%1).',
    'Request failed: %1': 'Échec de la requête : %1',
    'Request failed (%1).': 'Échec de la requête (%1).',
    'Connection': 'Connexion',
    'Configure a time-tracking profile. Choose Kimai, Clockify, Toggl Track, or SolidTime.': 'Configurez un profil de suivi du temps. Choisissez Kimai, Clockify, Toggl Track ou SolidTime.',
    'Profile:': 'Profil :',
    'Profile name:': 'Nom du profil :',
    'Service:': 'Service :',
    'Server URL:': 'URL du serveur :',
    'API token:': 'Jeton API :',
    'Paste token to save in KWallet': 'Collez le jeton pour l’enregistrer dans KWallet',
    'Add profile': 'Ajouter un profil',
    'Profile %1': 'Profil %1',
    'Remove': 'Supprimer',
    'Use this profile': 'Utiliser ce profil',
    'none': 'aucun',
    'Active profile: %1': 'Profil actif : %1',
    'Saving…': 'Enregistrement…',
    'Save token': 'Enregistrer le jeton',
    'Token saved to KWallet for this profile.': 'Jeton enregistré dans KWallet pour ce profil.',
    'Failed to save token': 'Échec de l’enregistrement du jeton',
    'Clear token': 'Effacer le jeton',
    'Token removed from KWallet.': 'Jeton supprimé de KWallet.',
    'Failed to clear token': 'Échec de la suppression du jeton',
    'Test connection': 'Tester la connexion',
    'Testing connection…': 'Test de la connexion…',
    'No API token stored. Save a token first.': 'Aucun jeton API enregistré. Enregistrez d’abord un jeton.',
    'ok': 'ok',
    'Connected to %1 (%2).': 'Connecté à %1 (%2).',
    'Configure a Kimai URL on the Connection tab first.': 'Configurez d’abord une URL Kimai dans l’onglet Connexion.',
    'Loading projects…': 'Chargement des projets…',
    'Save an API token on the Connection tab first.': 'Enregistrez d’abord un jeton API dans l’onglet Connexion.',
    'Loaded %1 projects.': '%1 projets chargés.',
    'Select a project to pin activities.': 'Sélectionnez un projet pour épingler des activités.',
    'Failed to load projects.': 'Échec du chargement des projets.',
    'Loading activities…': 'Chargement des activités…',
    'No API token available.': 'Aucun jeton API disponible.',
    '%1 project-specific, %2 global': '%1 spécifique au projet, %2 global',
    'Failed to load activities.': 'Échec du chargement des activités.',
    'Projects': 'Projets',
    'Reload': 'Recharger',
    'Activities — %1': 'Activités — %1',
    'Activities': 'Activités',
    'Enter a city or place name to search.': 'Saisissez le nom d’une ville ou d’un lieu pour rechercher.',
    'Searching…': 'Recherche…',
    'Location search failed. Check your network connection.': 'Échec de la recherche de lieu. Vérifiez votre connexion réseau.',
    'No places found.': 'Aucun lieu trouvé.',
    'Display': 'Affichage',
    'Refresh interval (seconds):': 'Intervalle d’actualisation (secondes) :',
    'Recent activities shown:': 'Activités récentes affichées :',
    'Appearance:': 'Apparence :',
    'Use desktop blur (translucent background)': 'Utiliser le flou du bureau (arrière-plan translucide)',
    'Usual work day start:': 'Début habituel de la journée de travail :',
    'Usual work day end:': 'Fin habituelle de la journée de travail :',
    'Day sparkline': 'Mini-graphique du jour',
    'Find location': 'Trouver un lieu',
    'Search for a city or place to set sunrise/sunset coloring. Powered by OpenStreetMap Nominatim.': 'Recherchez une ville ou un lieu pour la coloration lever/coucher du soleil. Propulsé par OpenStreetMap Nominatim.',
    'City, region, or address…': 'Ville, région ou adresse…',
    'Search': 'Rechercher',
    'Using %1': 'Utilisation de %1',
    'Current place: %1': 'Lieu actuel : %1',
    'Custom coordinates': 'Coordonnées personnalisées',
    'Latitude:': 'Latitude :',
    'Longitude:': 'Longitude :',
    'Used to color the sparkline for sunrise and sunset at your location.': 'Utilisé pour colorer le mini-graphique au lever et au coucher du soleil à votre emplacement.',
    'Panel (taskbar)': 'Panneau (barre des tâches)',
    'Show:': 'Afficher :',
    'Elapsed time': 'Temps écoulé',
    'Project name': 'Nom du projet',
    'Activity name': 'Nom de l’activité',
    'Panel flyout': 'Menu déroulant du panneau',
    'Work summary (today / week / remaining)': 'Résumé de travail (aujourd’hui / semaine / restant)',
    'Recent list': 'Liste récente',
    'Continue last activity': 'Reprendre la dernière activité',
    'Start / switch activity controls': 'Contrôles de démarrage / changement d’activité',
    'Desktop widget': 'Widget de bureau',
    'New activity picker': 'Sélecteur de nouvelle activité',
    'Behavior': 'Comportement',
    'Tracking:': 'Suivi :',
    'Confirm before stopping the timer': 'Confirmer avant d’arrêter le minuteur',
    'Idle detection:': 'Détection d’inactivité :',
    'Stop timer when idle': 'Arrêter le minuteur en cas d’inactivité',
    'Idle threshold (minutes):': 'Seuil d’inactivité (minutes) :',
    'Notifications:': 'Notifications :',
    'Notify when tracking starts': 'Notifier au démarrage du suivi',
    'Notify when tracking stops': 'Notifier à l’arrêt du suivi',
    'Notify when stopped due to idle': 'Notifier en cas d’arrêt pour inactivité',
    'Idle detection requires xprintidle (X11/XWayland). It may not work on pure Wayland sessions.': 'La détection d’inactivité nécessite xprintidle (X11/XWayland). Elle peut ne pas fonctionner sur les sessions Wayland pures.',
    'Back': 'Retour',
    'Create a finished entry with project, activity, and time range.': 'Créer une entrée terminée avec projet, activité et plage horaire.',
    'Begin': 'Début',
    'End': 'Fin',
    'Duration: %1': 'Durée : %1',
    'Duration: —': 'Durée : —',
    'Duration: invalid range': 'Durée : plage invalide',
    'Save entry': 'Enregistrer l’entrée',
    'All': 'Tous',
    'Billable': 'Facturable',
    'Non-billable': 'Non facturable',
    'Charts for power users. Tracking stays on the main screen.': 'Graphiques pour utilisateurs avancés. Le suivi reste sur l’écran principal.',
    'Show': 'Afficher',
    'Today': 'Aujourd’hui',
    'This week': 'Cette semaine',
    'Time by hour': 'Temps par heure',
    'Previous day': 'Jour précédent',
    'Yesterday': 'Hier',
    'Next day': 'Jour suivant',
    'No time logged this day': 'Aucun temps enregistré ce jour',
    'Projects by day': 'Projets par jour',
    'Previous week': 'Semaine précédente',
    'Next week': 'Semaine suivante',
    'No time logged this week': 'Aucun temps enregistré cette semaine',
    'Projects by hour': 'Projets par heure',
    'Weekdays and weekend — segments placed by clock time.': 'Jours ouvrés et week-end — segments placés selon l’heure.',
    'Weekdays — segments placed by clock time. Weekend appears when tracked.': 'Jours ouvrés — segments selon l’heure. Le week-end apparaît s’il y a du suivi.',
    'Axis shows business hours (%1–%2); expands if work falls outside.': 'L’axe affiche les heures de travail (%1–%2) ; s’étend si le travail est hors plage.',
    'Activity distribution': 'Répartition des activités',
    'No activities today': 'Aucune activité aujourd’hui',
    'No activities this week': 'Aucune activité cette semaine',
    'Time': 'Temps',
    'Pick date': 'Choisir une date',
    'Pick time': 'Choisir une heure',
    'Hours : Minutes': 'Heures : Minutes',
    'Select': 'Sélectionner',
    'Today\'s tracked time across 24 hours': 'Temps suivi d’aujourd’hui sur 24 heures',
    'Clockify cloud API is prefilled. Change only for a regional endpoint (e.g. euc1).': 'L’API cloud Clockify est préremplie. Modifiez uniquement pour un point de terminaison régional (p. ex. euc1).',
    'Toggl Track cloud API is prefilled. Use your personal API token from Profile settings.': 'L’API cloud Toggl Track est préremplie. Utilisez votre jeton API personnel depuis les paramètres du profil.',
    'SolidTime cloud API is prefilled. For self-hosting, replace with your instance base URL.': 'L’API cloud SolidTime est préremplie. En auto-hébergement, remplacez par l’URL de base de votre instance.',
    'Self-hosted Kimai or the official hosted service (kimai.cloud). Paste the instance URL.': 'Kimai auto-hébergé ou le service hébergé officiel (kimai.cloud). Collez l’URL de l’instance.',
    'API URL:': 'URL de l’API :',
    'https://api.solidtime.io or https://time.example.com': 'https://api.solidtime.io ou https://time.example.com',
    'https://kimai.example.com or https://www.kimai.cloud': 'https://kimai.example.com ou https://www.kimai.cloud',
    'API key:': 'Clé API :',
    'Colors:': 'Couleurs :',
    'Make similar colors distinctive within each category': 'Rendre les couleurs similaires distinctes dans chaque catégorie',
    'Similarity threshold (%):': 'Seuil de similarité (%) :',
    'Higher similarity values treat more colors as too close. Clashing items get vivid, well-spaced replacement colors (not washed hue-shifts). If too many items cannot fit, the threshold is lowered automatically down to 12%. See Maintenance for clash groups.': 'Des valeurs de similarité plus élevées traitent plus de couleurs comme trop proches. Les éléments en conflit reçoivent des couleurs de remplacement vives et bien espacées (pas de légers décalages de teinte). Si trop d’éléments ne tiennent pas, le seuil descend automatiquement jusqu’à 12 %. Voir Maintenance pour les groupes de conflits.',
    'Configure a server URL on the Connection tab first.': 'Configurez d’abord une URL de serveur dans l’onglet Connexion.',
    'Loading customers, projects, and activities…': 'Chargement des clients, projets et activités…',
    'Color distinction is off. Enable it in Display settings to see clash groups.': 'La distinction des couleurs est désactivée. Activez-la dans Affichage pour voir les groupes de conflits.',
    'Loaded %1 customers, %2 projects, %3 activities. No similar colors within a category.': '%1 clients, %2 projets, %3 activités chargés. Aucune couleur similaire dans une catégorie.',
    'Loaded %1 customers, %2 projects, %3 activities. %4 clash group(s), %5 color(s) shifted.': '%1 clients, %2 projets, %3 activités chargés. %4 groupe(s) de conflit, %5 couleur(s) décalée(s).',
    'Only colors that clash within a category are listed. Each group starts with the entry that kept the Kimai color; shifted variants follow. Unique colors are hidden.': 'Seules les couleurs en conflit dans une catégorie sont listées. Chaque groupe commence par l’entrée qui a conservé la couleur Kimai ; les variantes décalées suivent. Les couleurs uniques sont masquées.',
    'Reload from server': 'Recharger depuis le serveur',
    'Distinction on · configured %1% · effective customers %2% / projects %3% / activities %4%': 'Distinction activée · configuré %1% · effectif clients %2% / projets %3% / activités %4%',
    'Distinction off — enable it in Display settings.': 'Distinction désactivée — activez-la dans Affichage.',
    'Customers': 'Clients',
    'No similar colors in this category.': 'Aucune couleur similaire dans cette catégorie.',
    'kept': 'conservé',
    'shifted': 'décalé',
    'Maintenance': 'Maintenance',
    'Edit': 'Modifier',
    'Edit start, project, and activity': 'Modifier début, projet et activité',
    'Edit start time, project, and activity for the running entry.': 'Modifier l’heure de début, le projet et l’activité de l’entrée en cours.',
    'Elapsed time updates from the new start.': 'Le temps écoulé est recalculé à partir du nouveau début.',
    'Start must be a valid time not in the future.': 'Le début doit être une heure valide et ne pas être dans le futur.',
    'This provider cannot update the running entry.': 'Ce fournisseur ne peut pas mettre à jour l’entrée en cours.',
    'Enter a valid start date/time.': 'Saisissez une date/heure de début valide.',
    'Start must not be in the future.': 'Le début ne doit pas être dans le futur.',
    'Save': 'Enregistrer',

}

PLURALS = {
    '%1 minute ago': ['il y a %1 minute', 'il y a %1 minutes'],
    '%1 hour ago': ['il y a %1 heure', 'il y a %1 heures'],
    '%1 day ago': ['il y a %1 jour', 'il y a %1 jours'],
    '%1 place found.': ['%1 lieu trouvé.', '%1 lieux trouvés.'],
}
