# -*- coding: utf-8 -*-
T = {
    'Project-specific': 'Specifico del progetto',
    'Global activities': 'Attività globali',
    'Plasmai': 'Plasmai',
    'Loading…': 'Caricamento…',
    'Not configured — right-click to configure': 'Non configurato — clic destro per configurare',
    'just now': 'proprio ora',
    'yesterday': 'ieri',
    'Not configured': 'Non configurato',
    'Connecting to %1…': 'Connessione a %1…',
    'Connection problem': 'Problema di connessione',
    'Connected to %1 (%2)': 'Connesso a %1 (%2)',
    'Connected to %1': 'Connesso a %1',
    'Enter valid begin and end date/time.': 'Inserisci data/ora di inizio e fine valide.',
    'End must be after begin.': 'La fine deve essere successiva all’inizio.',
    'Entry added': 'Voce aggiunta',
    'Manual time entry': 'Inserimento manuale del tempo',
    '%1 left today': '%1 rimanente oggi',
    '%1 over today': '%1 in eccesso oggi',
    '%1 left this week': '%1 rimanente questa settimana',
    '%1 over this week': '%1 in eccesso questa settimana',
    'Today %1': 'Oggi %1',
    'Week %1': 'Settimana %1',
    'Tracking started': 'Tracciamento avviato',
    'Switched activity': 'Attività cambiata',
    'Tracking stopped (idle)': 'Tracciamento interrotto (inattività)',
    'Tracking stopped': 'Tracciamento interrotto',
    'Stop tracking?': 'Interrompere il tracciamento?',
    'Stop tracking %1 · %2?': 'Interrompere il tracciamento di %1 · %2?',
    'Statistics': 'Statistiche',
    'Add entry': 'Aggiungi voce',
    'Add a manual time entry': 'Aggiungi un inserimento manuale del tempo',
    'Show statistics': 'Mostra statistiche',
    'Back to timer': 'Torna al timer',
    'Connect a time tracker': 'Connetti un tracciatore del tempo',
    'Add your service, server URL (if needed), and API token to start tracking from the panel.': 'Aggiungi il tuo servizio, l’URL del server (se necessario) e il token API per avviare il tracciamento dal pannello.',
    'Configure Plasmai': 'Configura Plasmai',
    'Retry': 'Riprova',
    'Configure': 'Configura',
    'Not tracking': 'Nessun tracciamento attivo',
    'Description': 'Descrizione',
    'Save description': 'Salva descrizione',
    'Stop': 'Interrompi',
    'Continue · %1 · %2': 'Continua · %1 · %2',
    'Favorites': 'Preferiti',
    'No favorites yet': 'Nessun preferito ancora',
    'Pin frequent project/activity pairs in the widget settings.': 'Fissa le coppie progetto/attività frequenti nelle impostazioni del widget.',
    'Configure favorites': 'Configura preferiti',
    '+%1 more in settings': '+%1 altri nelle impostazioni',
    'Recent': 'Recenti',
    'No recent activities': 'Nessuna attività recente',
    'Start tracking to build your recent list.': 'Avvia il tracciamento per compilare l’elenco recente.',
    'Switch to another activity…': 'Passa a un’altra attività…',
    'Start something else…': 'Avvia qualcos’altro…',
    'Switch activity': 'Cambia attività',
    'New activity': 'Nuova attività',
    'Select project…': 'Seleziona progetto…',
    'Select activity…': 'Seleziona attività…',
    'Description (optional)': 'Descrizione (facoltativo)',
    'Start': 'Avvia',
    'Switch': 'Cambia',
    'Cancel': 'Annulla',
    'Unknown error': 'Errore sconosciuto',
    'URL and API token are required': 'URL e token API sono obbligatori',
    'Configure your time tracker URL and API token': 'Configura l’URL e il token API del tuo tracciatore del tempo',
    'This action is not supported for the selected service yet.': 'Questa azione non è ancora supportata per il servizio selezionato.',
    'Cannot reach the server. Check your network, URL, or TLS certificate.': 'Impossibile raggiungere il server. Controlla la rete, l’URL o il certificato TLS.',
    'Authentication failed. Check your API token.': 'Autenticazione fallita. Controlla il tuo token API.',
    'Server not found. Check your URL.': 'Server non trovato. Controlla l’URL.',
    'Access denied. Your token may lack required permissions.': 'Accesso negato. Il token potrebbe non avere i permessi necessari.',
    'Server error (%1).': 'Errore del server (%1).',
    'Request failed: %1': 'Richiesta fallita: %1',
    'Request failed (%1).': 'Richiesta fallita (%1).',
    'Connection': 'Connessione',
    'Configure a time-tracking profile. Choose Kimai, Clockify, Toggl Track, or SolidTime.': 'Configura un profilo di tracciamento del tempo. Scegli Kimai, Clockify, Toggl Track o SolidTime.',
    'Profile:': 'Profilo:',
    'Profile name:': 'Nome profilo:',
    'Service:': 'Servizio:',
    'Server URL:': 'URL del server:',
    'API token:': 'Token API:',
    'Paste token to save in KWallet': 'Incolla il token per salvarlo in KWallet',
    'Add profile': 'Aggiungi profilo',
    'Profile %1': 'Profilo %1',
    'Remove': 'Rimuovi',
    'Use this profile': 'Usa questo profilo',
    'none': 'nessuno',
    'Active profile: %1': 'Profilo attivo: %1',
    'Saving…': 'Salvataggio…',
    'Save token': 'Salva token',
    'Token saved to KWallet for this profile.': 'Token salvato in KWallet per questo profilo.',
    'Failed to save token': 'Impossibile salvare il token',
    'Clear token': 'Cancella token',
    'Token removed from KWallet.': 'Token rimosso da KWallet.',
    'Failed to clear token': 'Impossibile cancellare il token',
    'Test connection': 'Test connessione',
    'Testing connection…': 'Test della connessione…',
    'No API token stored. Save a token first.': 'Nessun token API salvato. Salva prima un token.',
    'ok': 'ok',
    'Connected to %1 (%2).': 'Connesso a %1 (%2).',
    'Configure a Kimai URL on the Connection tab first.': 'Configura prima un URL Kimai nella scheda Connessione.',
    'Loading projects…': 'Caricamento progetti…',
    'Save an API token on the Connection tab first.': 'Salva prima un token API nella scheda Connessione.',
    'Loaded %1 projects.': '%1 progetti caricati.',
    'Select a project to pin activities.': 'Seleziona un progetto per fissare le attività.',
    'Failed to load projects.': 'Impossibile caricare i progetti.',
    'Loading activities…': 'Caricamento attività…',
    'No API token available.': 'Nessun token API disponibile.',
    '%1 project-specific, %2 global': '%1 specifico del progetto, %2 globali',
    'Failed to load activities.': 'Impossibile caricare le attività.',
    'Projects': 'Progetti',
    'Reload': 'Ricarica',
    'Activities — %1': 'Attività — %1',
    'Activities': 'Attività',
    'Enter a city or place name to search.': 'Inserisci il nome di una città o località da cercare.',
    'Searching…': 'Ricerca…',
    'Location search failed. Check your network connection.': 'Ricerca della posizione fallita. Controlla la connessione di rete.',
    'No places found.': 'Nessun luogo trovato.',
    'Display': 'Visualizzazione',
    'Refresh interval (seconds):': 'Intervallo di aggiornamento (secondi):',
    'Touch optimization:': 'Ottimizzazione touch:',
    'Automatic (follow Plasma tablet mode)': 'Automatico (segui la modalità tablet di Plasma)',
    'On': 'Attivo',
    'Off': 'Disattivo',
    'Larger tap targets for buttons, lists, pickers, and date/time controls.': 'Aree tattili più grandi per pulsanti, elenchi, selettori e data/ora.',
    'Usual work day start:': 'Inizio abituale della giornata lavorativa:',
    'Usual work day end:': 'Fine abituale della giornata lavorativa:',
    'Day sparkline': 'Minigrafico del giorno',
    'City, region, or address…': 'Città, regione o indirizzo…',
    'Search': 'Cerca',
    'Using %1': 'Utilizzo di %1',
    'Current place: %1': 'Luogo attuale: %1',
    'Latitude:': 'Latitudine:',
    'Longitude:': 'Longitudine:',
    'Panel (taskbar)': 'Pannello (barra delle applicazioni)',
    'Show:': 'Mostra:',
    'Elapsed time': 'Tempo trascorso',
    'Project name': 'Nome del progetto',
    'Activity name': 'Nome dell’attività',
    'Panel flyout': 'Menu a comparsa del pannello',
    'Work summary (today / week / remaining)': 'Riepilogo lavoro (oggi / settimana / rimanente)',
    'Recent list': 'Elenco recente',
    'Continue last activity': 'Riprendi l’ultima attività',
    'Start / switch activity controls': 'Controlli avvio / cambio attività',
    'Desktop widget': 'Widget desktop',
    'New activity picker': 'Selettore nuova attività',
    'Behavior': 'Comportamento',
    'Tracking:': 'Tracciamento:',
    'Confirm before stopping the timer': 'Conferma prima di interrompere il timer',
    'Idle detection:': 'Rilevamento inattività:',
    'Stop timer when idle': 'Interrompi il timer in caso di inattività',
    'Idle threshold (minutes):': 'Soglia di inattività (minuti):',
    'Notifications:': 'Notifiche:',
    'Notify when tracking starts': 'Notifica all’avvio del tracciamento',
    'Notify when tracking stops': 'Notifica all’interruzione del tracciamento',
    'Notify when stopped due to idle': 'Notifica in caso di interruzione per inattività',
    'Back': 'Indietro',
    'Create a finished entry with project, activity, and time range.': 'Crea una voce completata con progetto, attività e intervallo di tempo.',
    'Begin': 'Inizio',
    'End': 'Fine',
    'Duration: %1': 'Durata: %1',
    'Duration: —': 'Durata: —',
    'Duration: invalid range': 'Durata: intervallo non valido',
    'Save entry': 'Salva voce',
    'All': 'Tutti',
    'Billable': 'Fatturabile',
    'Non-billable': 'Non fatturabile',
    'Today': 'Oggi',
    'This week': 'Questa settimana',
    'Time by hour': 'Tempo per ora',
    'Previous day': 'Giorno precedente',
    'Yesterday': 'Ieri',
    'Next day': 'Giorno successivo',
    'No time logged this day': 'Nessun tempo registrato in questo giorno',
    'Projects by day': 'Progetti per giorno',
    'Previous week': 'Settimana precedente',
    'Next week': 'Settimana successiva',
    'No time logged this week': 'Nessun tempo registrato questa settimana',
    'Projects by hour': 'Progetti per ora',
    'Weekdays and weekend — segments placed by clock time.': 'Giorni feriali e weekend: segmenti posizionati secondo l’orario.',
    'Weekdays — segments placed by clock time. Weekend appears when tracked.': 'Giorni feriali: segmenti secondo l’orario. Il weekend compare se tracciato.',
    'Axis shows business hours (%1–%2); expands if work falls outside.': 'L’asse mostra l’orario di lavoro (%1–%2); si espande se il lavoro è fuori.',
    'Activity distribution': 'Distribuzione delle attività',
    'No activities today': 'Nessuna attività oggi',
    'No activities this week': 'Nessuna attività questa settimana',
    'Time': 'Tempo',
    'Pick date': 'Scegli data',
    'Pick time': 'Scegli ora',
    'Hours : Minutes': 'Ore : Minuti',
    'Select': 'Seleziona',
    'Clockify cloud API is prefilled. Change only for a regional endpoint (e.g. euc1).': 'L’API cloud di Clockify è precompilata. Modifica solo per un endpoint regionale (es. euc1).',
    'Toggl Track cloud API is prefilled. Use your personal API token from Profile settings.': 'L’API cloud di Toggl Track è precompilata. Usa il token API personale dalle impostazioni del profilo.',
    'SolidTime cloud API is prefilled. For self-hosting, replace with your instance base URL.': 'L’API cloud di SolidTime è precompilata. In self-hosting, sostituiscila con l’URL base della tua istanza.',
    'Self-hosted Kimai or the official hosted service (kimai.cloud). Paste the instance URL.': 'Kimai self-hosted o il servizio ospitato ufficiale (kimai.cloud). Incolla l’URL dell’istanza.',
    'API URL:': 'URL API:',
    'https://api.solidtime.io or https://time.example.com': 'https://api.solidtime.io o https://time.example.com',
    'https://kimai.example.com or https://www.kimai.cloud': 'https://kimai.example.com o https://www.kimai.cloud',
    'API key:': 'Chiave API:',
    'Make similar colors distinctive within each category': 'Rendi distintivi i colori simili all’interno di ogni categoria',
    'Similarity threshold (%):': 'Soglia di similarità (%):',
    'Configure a server URL on the Connection tab first.': 'Configura prima un URL del server nella scheda Connessione.',
    'Loading customers, projects, and activities…': 'Caricamento di clienti, progetti e attività…',
    'Color distinction is off. Enable it in Display settings to see clash groups.': 'La distinzione dei colori è disattivata. Attivala in Visualizzazione per vedere i gruppi in conflitto.',
    'Loaded %1 customers, %2 projects, %3 activities. No similar colors within a category.': 'Caricati %1 clienti, %2 progetti, %3 attività. Nessun colore simile in una categoria.',
    'Loaded %1 customers, %2 projects, %3 activities. %4 clash group(s), %5 color(s) shifted.': 'Caricati %1 clienti, %2 progetti, %3 attività. %4 gruppo/i in conflitto, %5 colore/i spostato/i.',
    'Only colors that clash within a category are listed. Each group starts with the entry that kept the Kimai color; shifted variants follow. Unique colors are hidden.': 'Sono elencati solo i colori in conflitto in una categoria. Ogni gruppo inizia con la voce che ha mantenuto il colore Kimai; seguono le varianti spostate. I colori unici sono nascosti.',
    'Reload from server': 'Ricarica dal server',
    'Distinction on · configured %1% · effective customers %2% / projects %3% / activities %4%': 'Distinzione attiva · configurato %1% · effettivo clienti %2% / progetti %3% / attività %4%',
    'Distinction off — enable it in Display settings.': 'Distinzione disattivata — attivala in Visualizzazione.',
    'Customers': 'Clienti',
    'No similar colors in this category.': 'Nessun colore simile in questa categoria.',
    'kept': 'mantenuto',
    'shifted': 'spostato',
    'Maintenance': 'Manutenzione',
    'Edit': 'Modifica',
    'Edit start, project, and activity': 'Modifica inizio, progetto e attività',
    'Elapsed time updates from the new start.': 'Il tempo trascorso viene aggiornato dal nuovo inizio.',
    'Start must be a valid time not in the future.': 'L’inizio deve essere un orario valido e non nel futuro.',
    'This provider cannot update the running entry.': 'Questo provider non può aggiornare la voce in corso.',
    'Enter a valid start date/time.': 'Inserisci una data/ora di inizio valida.',
    'Start must not be in the future.': 'L’inizio non deve essere nel futuro.',
    'Save': 'Salva',
    'Current': 'Attuale',
    'Switch to': 'Passa a',
    'Could not resolve project or activity for that entry': 'Impossibile risolvere progetto o attività per questa voce',
    'Edit start, project, activity, billable, and tags for the running entry.': 'Modifica inizio, progetto, attività, fatturabile e tag della voce in corso.',
    'Starts or switches this activity': 'Avvia o passa a questa attività',
    'A profile named "%1" already exists.': 'Esiste già un profilo chiamato «%1».',
    'Appearance': 'Aspetto',
    'Updates': 'Aggiornamenti',
    'Colors': 'Colori',
    'Distinction:': 'Distinzione:',
    'Higher similarity values treat more colors as too close. Clashing items get vivid, well-spaced replacement colors. See Maintenance for clash groups.': 'Valori di similarità più alti considerano più colori troppo vicini. Gli elementi in conflitto ricevono colori sostitutivi vividi e ben distanziati. Vedi Manutenzione per i gruppi in conflitto.',
    'Color distinction is available for Kimai profiles (per-customer / project / activity colors).': 'La distinzione dei colori è disponibile per i profili Kimai (colori per cliente / progetto / attività).',
    'Work hours': 'Orario di lavoro',
    'Used for the sparkline zoom and remaining-time in the work summary.': 'Usato per lo zoom della sparkline e il tempo restante nel riepilogo.',
    'Arcs:': 'Archi:',
    'Show sun, moon, and work arcs': 'Mostra archi sole, luna e lavoro',
    'Hide the whole sparkline under Panel flyout or Desktop widget below.': 'Nascondi l’intera sparkline nel menu del pannello o nel widget desktop sotto.',
    'Find location:': 'Trova località:',
    'Search a place or enter coordinates for sunrise/sunset coloring. Powered by OpenStreetMap Nominatim.': 'Cerca un luogo o inserisci coordinate per i colori alba/tramonto. Con OpenStreetMap Nominatim.',
    'Customer color pill': 'Pallino colore cliente',
    'Project color pill': 'Pallino colore progetto',
    'Activities shown:': 'Attività mostrate:',
    'Applies to both the panel flyout and the desktop widget.': 'Si applica al menu del pannello e al widget desktop.',
    'Loading projects': 'Caricamento progetti',
    'Color distinction is only available for Kimai profiles.': 'La distinzione dei colori è disponibile solo per i profili Kimai.',
    'Color maintenance is for Kimai': 'La manutenzione colori è per Kimai',
    'Clockify, Toggl, and SolidTime do not expose Kimai-style customer / project / activity colors, so clash groups and color shifting are hidden for those profiles.': 'Clockify, Toggl e SolidTime non espongono colori cliente / progetto / attività in stile Kimai, quindi gruppi di conflitto e spostamento colore sono nascosti per quei profili.',
    'Select customer…': 'Seleziona cliente…',
    'Today\'s tracked time': 'Tempo tracciato oggi',
    'This provider cannot update descriptions.': 'Questo servizio non può aggiornare le descrizioni.',
    'Open or close the Plasmai popup': 'Apri o chiudi il popup di Plasmai',
    'Add tag…': 'Aggiungi tag…',
    'Add tags…': 'Aggiungi tag…',
    'Tags': 'Tag',
    'Loading tags…': 'Caricamento tag…',
    'No tags on the server yet.': 'Nessun tag sul server al momento.',
    'Create tag “%1”': 'Crea tag «%1»',
    'Already running.': 'Già in corso.',
    'Entry actions': 'Azioni voce',
    'Edit entry': 'Modifica voce',
    'Split entry': 'Dividi voce',
    'Delete entry': 'Elimina voce',
    'Idle detection uses the session idle hint on Wayland (loginctl / ScreenSaver) and xprintidle on X11.': 'Il rilevamento inattività usa l’hint di sessione su Wayland (loginctl / ScreenSaver) e xprintidle su X11.',
    'While tracking, shutdown and reboot wait like an unsaved file. Closing the lid or sleep is not blocked.': 'Durante il tracciamento, spegnimento e riavvio attendono come per un file non salvato. Chiudere il coperchio o sospendere non è bloccato.',
    'Remind me once if nothing is tracking during work hours': 'Ricordami una volta se nulla è in tracciamento durante l’orario di lavoro',
    'A timer is still running': 'Un timer è ancora in corso',
    'Idle time discarded': 'Tempo di inattività scartato',
    'Nothing is tracking': 'Niente in tracciamento',
    'Work hours have started. Start a timer when you begin.': 'L’orario di lavoro è iniziato. Avvia un timer quando cominci.',
    'Customer created': 'Cliente creato',
    'Project created': 'Progetto creato',
    'Activity created': 'Attività creata',
    'Entry updated': 'Voce aggiornata',
    'Timesheet updated': 'Foglio ore aggiornato',
    'This provider cannot update stopped entries.': 'Questo servizio non può aggiornare voci fermate.',
    'Tracking in progress': 'Tracciamento in corso',
    'This provider cannot delete entries.': 'Questo servizio non può eliminare voci.',
    'Entry deleted': 'Voce eliminata',
    'Split time must be between begin and end.': 'L’ora di divisione deve essere tra inizio e fine.',
    'This provider cannot split entries.': 'Questo servizio non può dividere voci.',
    'Entry split': 'Voce divisa',
    'The first half was saved, but the second half could not be created.': 'La prima metà è stata salvata, ma la seconda non è stata creata.',
    'Delete entry?': 'Eliminare la voce?',
    'Delete this finished entry? This cannot be undone.': 'Eliminare questa voce conclusa? L’azione non può essere annullata.',
    'Delete "%1 · %2"? This cannot be undone.': 'Eliminare «%1 · %2»? L’azione non può essere annullata.',
    'The first half keeps the original start. The second half starts at the split time.': 'La prima metà mantiene l’inizio originale. La seconda inizia all’ora di divisione.',
    'Split at': 'Dividi a',
    'Both halves will have a positive duration.': 'Entrambe le metà avranno una durata positiva.',
    'Timer still running': 'Timer ancora in corso',
    'Stop the timer before shutdown, or shut down anyway and leave it running on the server.': 'Ferma il timer prima dello spegnimento, oppure spegni comunque e lascialo sul server.',
    'Stop timer': 'Ferma timer',
    'Shut down anyway': 'Spegni comunque',
    'You were idle': 'Eri inattivo',
    'Keep the time, discard the idle gap, or discard and continue the same activity.': 'Tieni il tempo, scarta l’intervallo di inattività, oppure scarta e continua la stessa attività.',
    'Keep time': 'Tieni il tempo',
    'Discard idle': 'Scarta inattività',
    'Discard and continue': 'Scarta e continua',
    'Start · %1 · %2': 'Avvia · %1 · %2',
    'Change project, activity, range, billable, and tags for this finished entry.': 'Cambia progetto, attività, intervallo, fatturabile e tag di questa voce conclusa.',
    'Save changes': 'Salva modifiche',
    'Create customer': 'Crea cliente',
    'Create activity': 'Crea attività',
    'Create project': 'Crea progetto',
    'Activity will be added to %1.': 'L’attività sarà aggiunta a %1.',
    'Name': 'Nome',
    'Customer': 'Cliente',
}

PLURALS = {
    '%1 minute ago': ['%1 minuto fa', '%1 minuti fa'],
    '%1 hour ago': ['%1 ora fa', '%1 ore fa'],
    '%1 day ago': ['%1 giorno fa', '%1 giorni fa'],
    '%1 place found.': ['%1 luogo trovato.', '%1 luoghi trovati.'],
}
