# -*- coding: utf-8 -*-
T = {
    'Project-specific': 'プロジェクト専用',
    'Global activities': 'グローバルアクティビティ',
    'Plasmai': 'Plasmai',
    'Toggle Plasmai tracking': 'Plasmai の記録を切り替え',
    'Stop Plasmai tracking': 'Plasmai の記録を停止',
    'Loading…': '読み込み中…',
    'Not configured — right-click to configure': '未設定 — 右クリックで設定',
    'just now': 'たった今',
    'yesterday': '昨日',
    'Not configured': '未設定',
    'Connecting to %1…': '%1 に接続中…',
    'Connection problem': '接続の問題',
    'Connected to %1 (%2)': '%1 (%2) に接続済み',
    'Connected to %1': '%1 に接続済み',
    'Enter valid begin and end date/time.': '有効な開始・終了日時を入力してください。',
    'End must be after begin.': '終了は開始より後である必要があります。',
    'Entry added': 'エントリを追加しました',
    'Manual time entry': '手動時間エントリ',
    '%1 left today': '今日あと %1',
    '%1 over today': '今日 %1 超過',
    '%1 left this week': '今週あと %1',
    '%1 over this week': '今週 %1 超過',
    'Today %1': '今日 %1',
    'Week %1': '週 %1',
    'Tracking started': '記録を開始しました',
    'Switched activity': 'アクティビティを切り替えました',
    'Tracking stopped (idle)': '記録を停止しました（アイドル）',
    'Tracking stopped': '記録を停止しました',
    'Stop the current timer before starting another': '別のタイマーを開始する前に現在のタイマーを停止してください',
    'Stop tracking?': '記録を停止しますか？',
    'Stop tracking %1 · %2?': '%1 · %2 の記録を停止しますか？',
    'Statistics': '統計',
    'Add entry': 'エントリを追加',
    'Add a manual time entry': '手動時間エントリを追加',
    'Show statistics': '統計を表示',
    'Back to timer': 'タイマーに戻る',
    'Connect a time tracker': '時間記録サービスを接続',
    'Add your service, server URL (if needed), and API token to start tracking from the panel.': 'サービス、サーバー URL（必要な場合）、API トークンを追加してパネルから記録を開始します。',
    'Configure Plasmai': 'Plasmai を設定',
    'Retry': '再試行',
    'Configure': '設定',
    'Not tracking': '記録していません',
    'Description': '説明',
    'Save description': '説明を保存',
    'Stop': '停止',
    'Continue · %1 · %2': '続行 · %1 · %2',
    'Favorites': 'お気に入り',
    'No favorites yet': 'お気に入りはまだありません',
    'Pin frequent project/activity pairs in the widget settings.': 'よく使うプロジェクト/アクティビティの組み合わせをウィジェット設定でピン留めしてください。',
    'Configure favorites': 'お気に入りを設定',
    '+%1 more in settings': '設定にあと %1 件',
    'Recent': '最近',
    'No recent activities': '最近のアクティビティはありません',
    'Start tracking to build your recent list.': '記録を開始して最近のリストを作成してください。',
    'Switch to another activity…': '別のアクティビティに切り替え…',
    'Start something else…': '別の作業を開始…',
    'Switch activity': 'アクティビティを切り替え',
    'New activity': '新しいアクティビティ',
    'Select project…': 'プロジェクトを選択…',
    'Select activity…': 'アクティビティを選択…',
    'Description (optional)': '説明（任意）',
    'Start': '開始',
    'Switch': '切り替え',
    'Cancel': 'キャンセル',
    'Unknown error': '不明なエラー',
    'URL and API token are required': 'URL と API トークンが必要です',
    'Configure your time tracker URL and API token': '時間記録サービスの URL と API トークンを設定してください',
    'This action is not supported for the selected service yet.': '選択したサービスではこの操作はまだサポートされていません。',
    'Cannot reach the server. Check your network, URL, or TLS certificate.': 'サーバーに接続できません。ネットワーク、URL、TLS 証明書を確認してください。',
    'Authentication failed. Check your API token.': '認証に失敗しました。API トークンを確認してください。',
    'Server not found. Check your URL.': 'サーバーが見つかりません。URL を確認してください。',
    'Access denied. Your token may lack required permissions.': 'アクセスが拒否されました。トークンに必要な権限がない可能性があります。',
    'Server error (%1).': 'サーバーエラー (%1)。',
    'Request failed: %1': 'リクエストに失敗しました: %1',
    'Request failed (%1).': 'リクエストに失敗しました (%1)。',
    'Connection': '接続',
    'Configure a time-tracking profile. Choose Kimai, Clockify, Toggl Track, or SolidTime.': '時間記録プロファイルを設定してください。Kimai、Clockify、Toggl Track、SolidTime から選択できます。',
    'Profile:': 'プロファイル:',
    'Profile name:': 'プロファイル名:',
    'Service:': 'サービス:',
    'Server URL:': 'サーバー URL:',
    'API token:': 'API トークン:',
    'Paste token to save in KWallet': 'トークンを貼り付けて KWallet に保存',
    'Add profile': 'プロファイルを追加',
    'Profile %1': 'プロファイル %1',
    'Remove': '削除',
    'Use this profile': 'このプロファイルを使用',
    'none': 'なし',
    'Active profile: %1': 'アクティブなプロファイル: %1',
    'Saving…': '保存中…',
    'Save token': 'トークンを保存',
    'Token saved to KWallet for this profile.': 'このプロファイルのトークンを KWallet に保存しました。',
    'Failed to save token': 'トークンの保存に失敗しました',
    'Clear token': 'トークンをクリア',
    'Token removed from KWallet.': 'トークンを KWallet から削除しました。',
    'Failed to clear token': 'トークンのクリアに失敗しました',
    'Test connection': '接続をテスト',
    'Testing connection…': '接続をテスト中…',
    'No API token stored. Save a token first.': 'API トークンが保存されていません。先にトークンを保存してください。',
    'ok': 'ok',
    'Connected to %1 (%2).': '%1 (%2) に接続しました。',
    'Configure a Kimai URL on the Connection tab first.': '先に「接続」タブで Kimai の URL を設定してください。',
    'Loading projects…': 'プロジェクトを読み込み中…',
    'Save an API token on the Connection tab first.': '先に「接続」タブで API トークンを保存してください。',
    'Loaded %1 projects.': '%1 件のプロジェクトを読み込みました。',
    'Select a project to pin activities.': 'アクティビティをピン留めするプロジェクトを選択してください。',
    'Failed to load projects.': 'プロジェクトの読み込みに失敗しました。',
    'Loading activities…': 'アクティビティを読み込み中…',
    'No API token available.': 'API トークンがありません。',
    '%1 project-specific, %2 global': 'プロジェクト専用 %1 件、グローバル %2 件',
    'Failed to load activities.': 'アクティビティの読み込みに失敗しました。',
    'Projects': 'プロジェクト',
    'Reload': '再読み込み',
    'Activities — %1': 'アクティビティ — %1',
    'Activities': 'アクティビティ',
    'Enter a city or place name to search.': '検索する都市または地名を入力してください。',
    'Searching…': '検索中…',
    'Location search failed. Check your network connection.': '場所の検索に失敗しました。ネットワーク接続を確認してください。',
    'No places found.': '場所が見つかりませんでした。',
    'Display': '表示',
    'Refresh interval (seconds):': '更新間隔（秒）:',
    'Recent activities shown:': '表示する最近のアクティビティ:',
    'Appearance:': '外観:',
    'Use desktop blur (translucent background)': 'デスクトップのぼかし（半透明背景）を使用',
    'Usual work day start:': '通常の勤務開始:',
    'Usual work day end:': '通常の勤務終了:',
    'Day sparkline': '日次スパークライン',
    'Find location': '場所を検索',
    'Search for a city or place to set sunrise/sunset coloring. Powered by OpenStreetMap Nominatim.': '日の出/日の入りの色付けのために都市または場所を検索します。OpenStreetMap Nominatim を使用。',
    'City, region, or address…': '都市、地域、または住所…',
    'Search': '検索',
    'Using %1': '%1 を使用中',
    'Current place: %1': '現在の場所: %1',
    'Custom coordinates': 'カスタム座標',
    'Latitude:': '緯度:',
    'Longitude:': '経度:',
    'Used to color the sparkline for sunrise and sunset at your location.': 'お住まいの地域の日の出と日の入りに応じてスパークラインを色付けするために使用します。',
    'Panel (taskbar)': 'パネル（タスクバー）',
    'Show:': '表示:',
    'Elapsed time': '経過時間',
    'Project name': 'プロジェクト名',
    'Activity name': 'アクティビティ名',
    'Panel flyout': 'パネルのフライアウト',
    'Work summary (today / week / remaining)': '作業概要（今日 / 週 / 残り）',
    'Recent list': '最近のリスト',
    'Continue last activity': '前回のアクティビティを続行',
    'Start / switch activity controls': '開始 / アクティビティ切り替えコントロール',
    'Desktop widget': 'デスクトップウィジェット',
    'New activity picker': '新しいアクティビティ選択',
    'Behavior': '動作',
    'Tracking:': '記録:',
    'Confirm before stopping the timer': 'タイマー停止前に確認',
    'Idle detection:': 'アイドル検出:',
    'Stop timer when idle': 'アイドル時にタイマーを停止',
    'Idle threshold (minutes):': 'アイドル閾値（分）:',
    'Notifications:': '通知:',
    'Notify when tracking starts': '記録開始時に通知',
    'Notify when tracking stops': '記録停止時に通知',
    'Notify when stopped due to idle': 'アイドルによる停止時に通知',
    'Idle detection requires xprintidle (X11/XWayland). It may not work on pure Wayland sessions.': 'アイドル検出には xprintidle（X11/XWayland）が必要です。純粋な Wayland セッションでは動作しない場合があります。',
    'Back': '戻る',
    'Create a finished entry with project, activity, and time range.': 'プロジェクト、アクティビティ、時間範囲で完了済みのエントリを作成します。',
    'Begin': '開始',
    'End': '終了',
    'Duration: %1': '時間: %1',
    'Duration: —': '時間: —',
    'Duration: invalid range': '時間: 無効な範囲',
    'Save entry': 'エントリを保存',
    'All': 'すべて',
    'Billable': '請求対象',
    'Non-billable': '請求対象外',
    'Charts for power users. Tracking stays on the main screen.': 'パワーユーザー向けチャート。追跡はメイン画面のままです。',
    'Show': '表示',
    'Today': '今日',
    'This week': '今週',
    'Time by hour': '時間帯別の時間',
    'Previous day': '前日',
    'Yesterday': '昨日',
    'Next day': '翌日',
    'No time logged this day': 'この日の記録はありません',
    'Projects by day': '日別プロジェクト',
    'Previous week': '前週',
    'Next week': '翌週',
    'No time logged this week': '今週の記録はありません',
    'Projects by hour': '時間帯別プロジェクト',
    'Weekdays and weekend — segments placed by clock time.': '平日と週末 — 時刻に沿ってセグメントを配置。',
    'Weekdays — segments placed by clock time. Weekend appears when tracked.': '平日 — 時刻に沿ってセグメント。記録があれば週末も表示。',
    'Axis shows business hours (%1–%2); expands if work falls outside.': '軸は勤務時間（%1–%2）を表示。範囲外の作業があれば拡張します。',
    'Activity distribution': 'アクティビティの分布',
    'No activities today': '今日のアクティビティはありません',
    'No activities this week': '今週のアクティビティはありません',
    'Time': '時間',
    'Pick date': '日付を選択',
    'Pick time': '時刻を選択',
    'Hours : Minutes': '時 : 分',
    'Select': '選択',
    'Today\'s tracked time across 24 hours': '今日の24時間にわたる記録時間',
    'Clockify cloud API is prefilled. Change only for a regional endpoint (e.g. euc1).': 'ClockifyクラウドAPIは事前入力済みです。リージョン用エンドポイント（例: euc1）のときだけ変更してください。',
    'Toggl Track cloud API is prefilled. Use your personal API token from Profile settings.': 'Toggl TrackクラウドAPIは事前入力済みです。プロフィール設定の個人APIトークンを使用してください。',
    'SolidTime cloud API is prefilled. For self-hosting, replace with your instance base URL.': 'SolidTimeクラウドAPIは事前入力済みです。セルフホストの場合はインスタンスのベースURLに置き換えてください。',
    'Self-hosted Kimai or the official hosted service (kimai.cloud). Paste the instance URL.': 'セルフホストのKimai、または公式ホストサービス（kimai.cloud）。インスタンスURLを貼り付けてください。',
    'API URL:': 'API URL:',
    'https://api.solidtime.io or https://time.example.com': 'https://api.solidtime.io または https://time.example.com',
    'https://kimai.example.com or https://www.kimai.cloud': 'https://kimai.example.com または https://www.kimai.cloud',
    'API key:': 'APIキー:',
    'Colors:': '色:',
    'Make similar colors distinctive within each category': '各カテゴリ内で似た色を区別しやすくする',
    'Similarity threshold (%):': '類似度のしきい値 (%):',
    'Higher similarity values treat more colors as too close. Clashing items get vivid, well-spaced replacement colors (not washed hue-shifts). If too many items cannot fit, the threshold is lowered automatically down to 12%. See Maintenance for clash groups.': '類似度を高くすると、より多くの色が近すぎるとみなされます。衝突する項目には鮮やかで間隔の開いた代替色が割り当てられます（薄い色相シフトではありません）。収まらない項目が多すぎる場合、しきい値は自動的に12%まで下げられます。衝突グループはメンテナンスを参照してください。',
    'Configure a server URL on the Connection tab first.': '先に接続タブでサーバーURLを設定してください。',
    'Loading customers, projects, and activities…': '顧客、プロジェクト、アクティビティを読み込み中…',
    'Color distinction is off. Enable it in Display settings to see clash groups.': '色の区別はオフです。衝突グループを見るには表示設定で有効にしてください。',
    'Loaded %1 customers, %2 projects, %3 activities. No similar colors within a category.': '%1件の顧客、%2件のプロジェクト、%3件のアクティビティを読み込みました。カテゴリ内に類似色はありません。',
    'Loaded %1 customers, %2 projects, %3 activities. %4 clash group(s), %5 color(s) shifted.': '%1件の顧客、%2件のプロジェクト、%3件のアクティビティを読み込みました。衝突グループ %4、色シフト %5。',
    'Only colors that clash within a category are listed. Each group starts with the entry that kept the Kimai color; shifted variants follow. Unique colors are hidden.': 'カテゴリ内で衝突する色のみ表示されます。各グループはKimaiの色を維持した項目から始まり、シフトされたものが続きます。一意な色は非表示です。',
    'Reload from server': 'サーバーから再読み込み',
    'Distinction on · configured %1% · effective customers %2% / projects %3% / activities %4%': '区別オン · 設定 %1% · 実効 顧客 %2% / プロジェクト %3% / アクティビティ %4%',
    'Distinction off — enable it in Display settings.': '区別オフ — 表示設定で有効にしてください。',
    'Customers': '顧客',
    'No similar colors in this category.': 'このカテゴリに類似色はありません。',
    'kept': '維持',
    'shifted': 'シフト済み',
    'Maintenance': 'メンテナンス',
    'Edit': '編集',
    'Edit start, project, and activity': '開始・プロジェクト・アクティビティを編集',
    'Edit start time, project, and activity for the running entry.': '実行中エントリの開始時刻、プロジェクト、アクティビティを編集します。',
    'Elapsed time updates from the new start.': '経過時間は新しい開始時刻から更新されます。',
    'Start must be a valid time not in the future.': '開始は有効な時刻で、未来であってはなりません。',
    'This provider cannot update the running entry.': 'このプロバイダーは実行中のエントリを更新できません。',
    'Enter a valid start date/time.': '有効な開始日時を入力してください。',
    'Start must not be in the future.': '開始は未来であってはなりません。',
    'Save': '保存',

    'Current': '現在',
    'Switch to': '切り替え先',
    'Already tracking this activity': 'このアクティビティはすでに計測中です',
    'Could not resolve project or activity for that entry': 'そのエントリのプロジェクトまたはアクティビティを解決できませんでした',
    'Switch activity?': 'アクティビティを切り替えますか？',
}

PLURALS = {
    '%1 minute ago': ['%1 分前'],
    '%1 hour ago': ['%1 時間前'],
    '%1 day ago': ['%1 日前'],
    '%1 place found.': ['%1 件の場所が見つかりました。'],
}
