# -*- coding: utf-8 -*-
T = {
    'Project-specific': 'プロジェクト専用',
    'Global activities': 'グローバルアクティビティ',
    'Plasmai': 'Plasmai',
    'Loading…': '読み込み中…',
    'Not configured — right-click to configure': '未設定 — 右クリックで設定',
    'just now': 'たった今',
    'yesterday': '昨日',
    'Not configured': '未設定',
    'Connecting to %1…': '%1 に接続中…',
    'Connection problem': '接続の問題',
    'Connected to %1 (%2)': '%1 (%2) に接続済み',
    'Connected to %1': '%1 に接続済み',
    'Enter valid begin and end date/time.': '有効な開始・終了日時を入力してください。',
    'End must be after begin.': '終了は開始より後である必要があります。',
    'Entry added': 'エントリを追加しました',
    'Manual time entry': '手動時間エントリ',
    '%1 left today': '今日あと %1',
    '%1 over today': '今日 %1 超過',
    '%1 left this week': '今週あと %1',
    '%1 over this week': '今週 %1 超過',
    'Today %1': '今日 %1',
    'Week %1': '週 %1',
    'Tracking started': '記録を開始しました',
    'Switched activity': 'アクティビティを切り替えました',
    'Tracking stopped (idle)': '記録を停止しました（アイドル）',
    'Tracking stopped': '記録を停止しました',
    'Stop tracking?': '記録を停止しますか？',
    'Stop tracking %1 · %2?': '%1 · %2 の記録を停止しますか？',
    'Statistics': '統計',
    'Add entry': 'エントリを追加',
    'Add a manual time entry': '手動時間エントリを追加',
    'Show statistics': '統計を表示',
    'Back to timer': 'タイマーに戻る',
    'Connect a time tracker': '時間記録サービスを接続',
    'Add your service, server URL (if needed), and API token to start tracking from the panel.': 'サービス、サーバー URL（必要な場合）、API トークンを追加してパネルから記録を開始します。',
    'Configure Plasmai': 'Plasmai を設定',
    'Retry': '再試行',
    'Configure': '設定',
    'Not tracking': '記録していません',
    'Description': '説明',
    'Save description': '説明を保存',
    'Stop': '停止',
    'Continue · %1 · %2': '続行 · %1 · %2',
    'Favorites': 'お気に入り',
    'No favorites yet': 'お気に入りはまだありません',
    'Pin frequent project/activity pairs in the widget settings.': 'よく使うプロジェクト/アクティビティの組み合わせをウィジェット設定でピン留めしてください。',
    'Configure favorites': 'お気に入りを設定',
    '+%1 more in settings': '設定にあと %1 件',
    'Recent': '最近',
    'No recent activities': '最近のアクティビティはありません',
    'Start tracking to build your recent list.': '記録を開始して最近のリストを作成してください。',
    'Switch to another activity…': '別のアクティビティに切り替え…',
    'Start something else…': '別の作業を開始…',
    'Switch activity': 'アクティビティを切り替え',
    'New activity': '新しいアクティビティ',
    'Select project…': 'プロジェクトを選択…',
    'Select activity…': 'アクティビティを選択…',
    'Description (optional)': '説明（任意）',
    'Start': '開始',
    'Switch': '切り替え',
    'Cancel': 'キャンセル',
    'Unknown error': '不明なエラー',
    'URL and API token are required': 'URL と API トークンが必要です',
    'Configure your time tracker URL and API token': '時間記録サービスの URL と API トークンを設定してください',
    'This action is not supported for the selected service yet.': '選択したサービスではこの操作はまだサポートされていません。',
    'Cannot reach the server. Check your network, URL, or TLS certificate.': 'サーバーに接続できません。ネットワーク、URL、TLS 証明書を確認してください。',
    'Authentication failed. Check your API token.': '認証に失敗しました。API トークンを確認してください。',
    'Server not found. Check your URL.': 'サーバーが見つかりません。URL を確認してください。',
    'Access denied. Your token may lack required permissions.': 'アクセスが拒否されました。トークンに必要な権限がない可能性があります。',
    'Server error (%1).': 'サーバーエラー (%1)。',
    'Request failed: %1': 'リクエストに失敗しました: %1',
    'Request failed (%1).': 'リクエストに失敗しました (%1)。',
    'Connection': '接続',
    'Configure a time-tracking profile. Choose Kimai, Clockify, Toggl Track, or SolidTime.': '時間記録プロファイルを設定してください。Kimai、Clockify、Toggl Track、SolidTime から選択できます。',
    'Profile:': 'プロファイル:',
    'Profile name:': 'プロファイル名:',
    'Service:': 'サービス:',
    'Server URL:': 'サーバー URL:',
    'API token:': 'API トークン:',
    'Paste token to save in KWallet': 'トークンを貼り付けて KWallet に保存',
    'Add profile': 'プロファイルを追加',
    'Profile %1': 'プロファイル %1',
    'Remove': '削除',
    'Use this profile': 'このプロファイルを使用',
    'none': 'なし',
    'Active profile: %1': 'アクティブなプロファイル: %1',
    'Saving…': '保存中…',
    'Save token': 'トークンを保存',
    'Token saved to KWallet for this profile.': 'このプロファイルのトークンを KWallet に保存しました。',
    'Failed to save token': 'トークンの保存に失敗しました',
    'Clear token': 'トークンをクリア',
    'Token removed from KWallet.': 'トークンを KWallet から削除しました。',
    'Failed to clear token': 'トークンのクリアに失敗しました',
    'Test connection': '接続をテスト',
    'Testing connection…': '接続をテスト中…',
    'No API token stored. Save a token first.': 'API トークンが保存されていません。先にトークンを保存してください。',
    'ok': 'ok',
    'Connected to %1 (%2).': '%1 (%2) に接続しました。',
    'Configure a Kimai URL on the Connection tab first.': '先に「接続」タブで Kimai の URL を設定してください。',
    'Loading projects…': 'プロジェクトを読み込み中…',
    'Save an API token on the Connection tab first.': '先に「接続」タブで API トークンを保存してください。',
    'Loaded %1 projects.': '%1 件のプロジェクトを読み込みました。',
    'Select a project to pin activities.': 'アクティビティをピン留めするプロジェクトを選択してください。',
    'Failed to load projects.': 'プロジェクトの読み込みに失敗しました。',
    'Loading activities…': 'アクティビティを読み込み中…',
    'No API token available.': 'API トークンがありません。',
    '%1 project-specific, %2 global': 'プロジェクト専用 %1 件、グローバル %2 件',
    'Failed to load activities.': 'アクティビティの読み込みに失敗しました。',
    'Projects': 'プロジェクト',
    'Reload': '再読み込み',
    'Activities — %1': 'アクティビティ — %1',
    'Activities': 'アクティビティ',
    'Enter a city or place name to search.': '検索する都市または地名を入力してください。',
    'Searching…': '検索中…',
    'Location search failed. Check your network connection.': '場所の検索に失敗しました。ネットワーク接続を確認してください。',
    'No places found.': '場所が見つかりませんでした。',
    'Display': '表示',
    'Refresh interval (seconds):': '更新間隔（秒）:',
    'Touch optimization:': 'タッチ最適化:',
    'Automatic (follow Plasma tablet mode)': '自動（Plasmaタブレットモードに従う）',
    'On': 'オン',
    'Off': 'オフ',
    'Larger tap targets for buttons, lists, pickers, and date/time controls.': 'ボタン、リスト、ピッカー、日付/時刻コントロールのタップ領域を拡大します。',
    'Usual work day start:': '通常の勤務開始:',
    'Usual work day end:': '通常の勤務終了:',
    'Day sparkline': '日次スパークライン',
    'City, region, or address…': '都市、地域、または住所…',
    'Search': '検索',
    'Using %1': '%1 を使用中',
    'Current place: %1': '現在の場所: %1',
    'Latitude:': '緯度:',
    'Longitude:': '経度:',
    'Panel (taskbar)': 'パネル（タスクバー）',
    'Show:': '表示:',
    'Elapsed time': '経過時間',
    'Project name': 'プロジェクト名',
    'Activity name': 'アクティビティ名',
    'Panel flyout': 'パネルのフライアウト',
    'Work summary (today / week / remaining)': '作業概要（今日 / 週 / 残り）',
    'Recent list': '最近のリスト',
    'Continue last activity': '前回のアクティビティを続行',
    'Start / switch activity controls': '開始 / アクティビティ切り替えコントロール',
    'Desktop widget': 'デスクトップウィジェット',
    'New activity picker': '新しいアクティビティ選択',
    'Behavior': '動作',
    'Tracking:': '記録:',
    'Confirm before stopping the timer': 'タイマー停止前に確認',
    'Ask before a start that overlaps the previous entry': '開始が直前の記録と重なる場合は確認する',
    'When editing the running timer, the previous entry’s end is shown. Saving an earlier start asks for confirmation.': '実行中タイマーの編集では、直前に停止した記録の終了時刻を表示します。より早い開始を保存するには確認が必要です。',
    'Previous entry ended at %1': '直前の記録は %1 に終了',
    'Overlapping start': '開始が重複',
    'The new start is before the previous entry ended (%1). Set it anyway?': '新しい開始は直前の記録の終了（%1）より前です。それでも設定しますか？',
    'Set anyway': 'それでも設定',
    'Idle detection:': 'アイドル検出:',
    'Stop timer when idle': 'アイドル時にタイマーを停止',
    'Idle threshold (minutes):': 'アイドル閾値（分）:',
    'Notifications:': '通知:',
    'Notify when tracking starts': '記録開始時に通知',
    'Notify when tracking stops': '記録停止時に通知',
    'Notify when stopped due to idle': 'アイドルによる停止時に通知',
    'Back': '戻る',
    'Create a finished entry with project, activity, and time range.': 'プロジェクト、アクティビティ、時間範囲で完了済みのエントリを作成します。',
    'Begin': '開始',
    'End': '終了',
    'Duration: %1': '時間: %1',
    'Duration: —': '時間: —',
    'Duration: invalid range': '時間: 無効な範囲',
    'Save entry': 'エントリを保存',
    'All': 'すべて',
    'Billable': '請求対象',
    'Non-billable': '請求対象外',
    'Today': '今日',
    'This week': '今週',
    'Time by hour': '時間帯別の時間',
    'Previous day': '前日',
    'Yesterday': '昨日',
    'Next day': '翌日',
    'No time logged this day': 'この日の記録はありません',
    'Projects by day': '日別プロジェクト',
    'Previous week': '前週',
    'Next week': '翌週',
    'No time logged this week': '今週の記録はありません',
    'Projects by hour': '時間帯別プロジェクト',
    'Weekdays and weekend — segments placed by clock time.': '平日と週末 — 時刻に沿ってセグメントを配置。',
    'Weekdays — segments placed by clock time. Weekend appears when tracked.': '平日 — 時刻に沿ってセグメント。記録があれば週末も表示。',
    'Axis shows business hours (%1–%2); expands if work falls outside.': '軸は勤務時間（%1–%2）を表示。範囲外の作業があれば拡張します。',
    'Activity distribution': 'アクティビティの分布',
    'No activities today': '今日のアクティビティはありません',
    'No activities this week': '今週のアクティビティはありません',
    'Time': '時間',
    'Pick date': '日付を選択',
    'Pick time': '時刻を選択',
    'Hours : Minutes': '時 : 分',
    'Select': '選択',
    'Clockify cloud API is prefilled. Change only for a regional endpoint (e.g. euc1).': 'ClockifyクラウドAPIは事前入力済みです。リージョン用エンドポイント（例: euc1）のときだけ変更してください。',
    'Toggl Track cloud API is prefilled. Use your personal API token from Profile settings.': 'Toggl TrackクラウドAPIは事前入力済みです。プロフィール設定の個人APIトークンを使用してください。',
    'SolidTime cloud API is prefilled. For self-hosting, replace with your instance base URL.': 'SolidTimeクラウドAPIは事前入力済みです。セルフホストの場合はインスタンスのベースURLに置き換えてください。',
    'Self-hosted Kimai or the official hosted service (kimai.cloud). Paste the instance URL.': 'セルフホストのKimai、または公式ホストサービス（kimai.cloud）。インスタンスURLを貼り付けてください。',
    'API URL:': 'API URL:',
    'https://api.solidtime.io or https://time.example.com': 'https://api.solidtime.io または https://time.example.com',
    'https://kimai.example.com or https://www.kimai.cloud': 'https://kimai.example.com または https://www.kimai.cloud',
    'API key:': 'APIキー:',
    'Make similar colors distinctive within each category': '各カテゴリ内で似た色を区別しやすくする',
    'Similarity threshold (%):': '類似度のしきい値 (%):',
    'Configure a server URL on the Connection tab first.': '先に接続タブでサーバーURLを設定してください。',
    'Loading customers, projects, and activities…': '顧客、プロジェクト、アクティビティを読み込み中…',
    'Color distinction is off. Enable it in Display settings to see clash groups.': '色の区別はオフです。衝突グループを見るには表示設定で有効にしてください。',
    'Loaded %1 customers, %2 projects, %3 activities. No similar colors within a category.': '%1件の顧客、%2件のプロジェクト、%3件のアクティビティを読み込みました。カテゴリ内に類似色はありません。',
    'Loaded %1 customers, %2 projects, %3 activities. %4 clash group(s), %5 color(s) shifted.': '%1件の顧客、%2件のプロジェクト、%3件のアクティビティを読み込みました。衝突グループ %4、色シフト %5。',
    'Only colors that clash within a category are listed. Each group starts with the entry that kept the Kimai color; shifted variants follow. Unique colors are hidden.': 'カテゴリ内で衝突する色のみ表示されます。各グループはKimaiの色を維持した項目から始まり、シフトされたものが続きます。一意な色は非表示です。',
    'Reload from server': 'サーバーから再読み込み',
    'Distinction on · configured %1% · effective customers %2% / projects %3% / activities %4%': '区別オン · 設定 %1% · 実効 顧客 %2% / プロジェクト %3% / アクティビティ %4%',
    'Distinction off — enable it in Display settings.': '区別オフ — 表示設定で有効にしてください。',
    'Customers': '顧客',
    'No similar colors in this category.': 'このカテゴリに類似色はありません。',
    'kept': '維持',
    'shifted': 'シフト済み',
    'Maintenance': 'メンテナンス',
    'Edit': '編集',
    'Edit start, project, and activity': '開始・プロジェクト・アクティビティを編集',
    'Elapsed time updates from the new start.': '経過時間は新しい開始時刻から更新されます。',
    'Start must be a valid time not in the future.': '開始は有効な時刻で、未来であってはなりません。',
    'This provider cannot update the running entry.': 'このプロバイダーは実行中のエントリを更新できません。',
    'Enter a valid start date/time.': '有効な開始日時を入力してください。',
    'Start must not be in the future.': '開始は未来であってはなりません。',
    'Save': '保存',
    'Current': '現在',
    'Switch to': '切り替え先',
    'Could not resolve project or activity for that entry': 'そのエントリのプロジェクトまたはアクティビティを解決できませんでした',
    'Edit start, project, activity, billable, and tags for the running entry.': '実行中エントリの開始・プロジェクト・アクティビティ・請求・タグを編集します。',
    'Starts or switches this activity': 'このアクティビティを開始または切り替えます',
    'A profile named "%1" already exists.': '「%1」という名前のプロファイルは既にあります。',
    'Appearance': '外観',
    'Updates': '更新',
    'Colors': '色',
    'Distinction:': '区別:',
    'Higher similarity values treat more colors as too close. Clashing items get vivid, well-spaced replacement colors. See Maintenance for clash groups.': '類似度を高くすると、より多くの色が近すぎると見なされます。衝突する項目は鮮やかで間隔の開いた色に置き換えられます。衝突グループはメンテナンスを参照。',
    'Color distinction is available for Kimai profiles (per-customer / project / activity colors).': '色の区別は Kimai プロファイルで利用できます（顧客・プロジェクト・アクティビティごと）。',
    'Work hours': '勤務時間',
    'Used for the sparkline zoom and remaining-time in the work summary.': 'スパークラインのズームと作業概要の残り時間に使います。',
    'Arcs:': '弧:',
    'Show sun, moon, and work arcs': '太陽・月・勤務の弧を表示',
    'Hide the whole sparkline under Panel flyout or Desktop widget below.': 'パネルのポップアップまたは下のデスクトップウィジェットでスパークライン全体を非表示にします。',
    'Find location:': '場所を検索:',
    'Search a place or enter coordinates for sunrise/sunset coloring. Powered by OpenStreetMap Nominatim.': '場所を検索するか座標を入力して日の出・日の入りの色分けに使います。OpenStreetMap Nominatim を使用。',
    'Customer color pill': '顧客カラーピル',
    'Project color pill': 'プロジェクトカラーピル',
    'Activities shown:': '表示するアクティビティ:',
    'Applies to both the panel flyout and the desktop widget.': 'パネルのポップアップとデスクトップウィジェットの両方に適用されます。',
    'Loading projects': 'プロジェクトを読み込み中',
    'Color distinction is only available for Kimai profiles.': '色の区別は Kimai プロファイルでのみ利用できます。',
    'Color maintenance is for Kimai': '色のメンテナンスは Kimai 向けです',
    'Clockify, Toggl, and SolidTime do not expose Kimai-style customer / project / activity colors, so clash groups and color shifting are hidden for those profiles.': 'Clockify、Toggl、SolidTime は Kimai のような顧客・プロジェクト・アクティビティ色を提供しないため、これらのプロファイルでは衝突グループと色のシフトを非表示にします。',
    'Select customer…': '顧客を選択…',
    'Today\'s tracked time': '今日の記録時間',
    'This provider cannot update descriptions.': 'このプロバイダーは説明を更新できません。',
    'Open or close the Plasmai popup': 'Plasmai のポップアップを開くまたは閉じる',
    'Add tag…': 'タグを追加…',
    'Add tags…': 'タグを追加…',
    'Tags': 'タグ',
    'Loading tags…': 'タグを読み込み中…',
    'No tags on the server yet.': 'サーバー上にまだタグがありません。',
    'Create tag “%1”': 'タグ「%1」を作成',
    'Already running.': 'すでに計測中です。',
    'Entry actions': 'エントリ操作',
    'Edit entry': 'エントリを編集',
    'Split entry': 'エントリを分割',
    'Delete entry': 'エントリを削除',
    'Idle detection uses the session idle hint on Wayland (loginctl / ScreenSaver) and xprintidle on X11.': 'アイドル検出は Wayland ではセッションのアイドルヒント（loginctl / ScreenSaver）、X11 では xprintidle を使います。',
    'Remind me once if nothing is tracking during work hours': '勤務時間中に何も計測していない場合、一度だけ通知する',
    'Idle time discarded': 'アイドル時間を破棄しました',
    'Nothing is tracking': '何も計測していません',
    'Work hours have started. Start a timer when you begin.': '勤務時間が始まりました。始めたらタイマーを開始してください。',
    'Customer created': '顧客を作成しました',
    'Project created': 'プロジェクトを作成しました',
    'Activity created': 'アクティビティを作成しました',
    'Entry updated': 'エントリを更新しました',
    'Timesheet updated': 'タイムシートを更新しました',
    'This provider cannot update stopped entries.': 'このプロバイダーは停止済みエントリを更新できません。',
    'Tracking in progress': '計測中',
    'This provider cannot delete entries.': 'このプロバイダーはエントリを削除できません。',
    'Entry deleted': 'エントリを削除しました',
    'Split time must be between begin and end.': '分割時刻は開始と終了の間である必要があります。',
    'This provider cannot split entries.': 'このプロバイダーはエントリを分割できません。',
    'Entry split': 'エントリを分割しました',
    'The first half was saved, but the second half could not be created.': '前半は保存されましたが、後半を作成できませんでした。',
    'Delete entry?': 'エントリを削除しますか？',
    'Delete this finished entry? This cannot be undone.': 'この完了済みエントリを削除しますか？元に戻せません。',
    'Delete "%1 · %2"? This cannot be undone.': '「%1 · %2」を削除しますか？元に戻せません。',
    'The first half keeps the original start. The second half starts at the split time.': '前半は元の開始時刻のままです。後半は分割時刻から始まります。',
    'Split at': '分割時刻',
    'Both halves will have a positive duration.': '両方の半分は正の時間になります。',
    'You were idle': 'アイドル状態でした',
    'Keep the time, discard the idle gap, or discard and continue the same activity.': '時間を残す、アイドル区間を破棄する、または破棄して同じアクティビティを続けます。',
    'Keep time': '時間を残す',
    'Discard idle': 'アイドルを破棄',
    'Discard and continue': '破棄して続ける',
    'Start · %1 · %2': '開始 · %1 · %2',
    'Change project, activity, range, billable, and tags for this finished entry.': 'この完了済みエントリのプロジェクト・アクティビティ・期間・請求・タグを変更します。',
    'Save changes': '変更を保存',
    'Create customer': '顧客を作成',
    'Create activity': 'アクティビティを作成',
    'Create project': 'プロジェクトを作成',
    'Activity will be added to %1.': 'アクティビティは %1 に追加されます。',
    'Name': '名前',
    'Customer': '顧客',
}

PLURALS = {
    '%1 minute ago': ['%1 分前'],
    '%1 hour ago': ['%1 時間前'],
    '%1 day ago': ['%1 日前'],
    '%1 place found.': ['%1 件の場所が見つかりました。'],
}
