# -*- coding: utf-8 -*-
T = {
    'Project-specific': 'Projectspecifiek',
    'Global activities': 'Globale activiteiten',
    'Plasmai': 'Plasmai',
    'Toggle Plasmai tracking': 'Plasmai-registratie in-/uitschakelen',
    'Stop Plasmai tracking': 'Plasmai-registratie stoppen',
    'Loading…': 'Laden…',
    'Not configured — right-click to configure': 'Niet geconfigureerd — rechtsklik om te configureren',
    'just now': 'zojuist',
    'yesterday': 'gisteren',
    'Not configured': 'Niet geconfigureerd',
    'Connecting to %1…': 'Verbinden met %1…',
    'Connection problem': 'Verbindingsprobleem',
    'Connected to %1 (%2)': 'Verbonden met %1 (%2)',
    'Connected to %1': 'Verbonden met %1',
    'Enter valid begin and end date/time.': 'Voer een geldige begin- en einddatum/-tijd in.',
    'End must be after begin.': 'Einde moet na begin liggen.',
    'Entry added': 'Invoer toegevoegd',
    'Manual time entry': 'Handmatige tijdregistratie',
    '%1 left today': '%1 resterend vandaag',
    '%1 over today': '%1 over vandaag',
    '%1 left this week': '%1 resterend deze week',
    '%1 over this week': '%1 over deze week',
    'Today %1': 'Vandaag %1',
    'Week %1': 'Week %1',
    'Tracking started': 'Registratie gestart',
    'Switched activity': 'Activiteit gewisseld',
    'Tracking stopped (idle)': 'Registratie gestopt (inactief)',
    'Tracking stopped': 'Registratie gestopt',
    'Stop the current timer before starting another': 'Stop de huidige timer voordat je een andere start',
    'Stop tracking?': 'Registratie stoppen?',
    'Stop tracking %1 · %2?': 'Registratie stoppen voor %1 · %2?',
    'Statistics': 'Statistieken',
    'Add entry': 'Invoer toevoegen',
    'Add a manual time entry': 'Handmatige tijdregistratie toevoegen',
    'Show statistics': 'Statistieken tonen',
    'Back to timer': 'Terug naar timer',
    'Connect a time tracker': 'Tijdregistratiedienst verbinden',
    'Add your service, server URL (if needed), and API token to start tracking from the panel.': 'Voeg je dienst, server-URL (indien nodig) en API-token toe om vanuit het paneel te registreren.',
    'Configure Plasmai': 'Plasmai configureren',
    'Retry': 'Opnieuw proberen',
    'Configure': 'Configureren',
    'Not tracking': 'Niet aan het registreren',
    'Description': 'Beschrijving',
    'Save description': 'Beschrijving opslaan',
    'Stop': 'Stop',
    'Continue · %1 · %2': 'Doorgaan · %1 · %2',
    'Favorites': 'Favorieten',
    'No favorites yet': 'Nog geen favorieten',
    'Pin frequent project/activity pairs in the widget settings.': 'Pin veelgebruikte project-/activiteitcombinaties in de widgetinstellingen.',
    'Configure favorites': 'Favorieten configureren',
    '+%1 more in settings': '+%1 meer in instellingen',
    'Recent': 'Recent',
    'No recent activities': 'Geen recente activiteiten',
    'Start tracking to build your recent list.': 'Start met registreren om je recente lijst op te bouwen.',
    'Switch to another activity…': 'Naar een andere activiteit wisselen…',
    'Start something else…': 'Iets anders starten…',
    'Switch activity': 'Activiteit wisselen',
    'New activity': 'Nieuwe activiteit',
    'Select project…': 'Project selecteren…',
    'Select activity…': 'Activiteit selecteren…',
    'Description (optional)': 'Beschrijving (optioneel)',
    'Start': 'Start',
    'Switch': 'Wisselen',
    'Cancel': 'Annuleren',
    'Unknown error': 'Onbekende fout',
    'URL and API token are required': 'URL en API-token zijn verplicht',
    'Configure your time tracker URL and API token': 'Configureer de URL en het API-token van je tijdregistratiedienst',
    'This action is not supported for the selected service yet.': 'Deze actie wordt nog niet ondersteund voor de geselecteerde dienst.',
    'Cannot reach the server. Check your network, URL, or TLS certificate.': 'Kan de server niet bereiken. Controleer je netwerk, URL of TLS-certificaat.',
    'Authentication failed. Check your API token.': 'Authenticatie mislukt. Controleer je API-token.',
    'Server not found. Check your URL.': 'Server niet gevonden. Controleer je URL.',
    'Access denied. Your token may lack required permissions.': 'Toegang geweigerd. Je token heeft mogelijk niet de vereiste rechten.',
    'Server error (%1).': 'Serverfout (%1).',
    'Request failed: %1': 'Verzoek mislukt: %1',
    'Request failed (%1).': 'Verzoek mislukt (%1).',
    'Connection': 'Verbinding',
    'Configure a time-tracking profile. Choose Kimai, Clockify, Toggl Track, or SolidTime.': 'Configureer een tijdregistratieprofiel. Kies Kimai, Clockify, Toggl Track of SolidTime.',
    'Profile:': 'Profiel:',
    'Profile name:': 'Profielnaam:',
    'Service:': 'Dienst:',
    'Server URL:': 'Server-URL:',
    'API token:': 'API-token:',
    'Paste token to save in KWallet': 'Plak token om op te slaan in KWallet',
    'Add profile': 'Profiel toevoegen',
    'Profile %1': 'Profiel %1',
    'Remove': 'Verwijderen',
    'Use this profile': 'Dit profiel gebruiken',
    'none': 'geen',
    'Active profile: %1': 'Actief profiel: %1',
    'Saving…': 'Opslaan…',
    'Save token': 'Token opslaan',
    'Token saved to KWallet for this profile.': 'Token opgeslagen in KWallet voor dit profiel.',
    'Failed to save token': 'Token opslaan mislukt',
    'Clear token': 'Token wissen',
    'Token removed from KWallet.': 'Token verwijderd uit KWallet.',
    'Failed to clear token': 'Token wissen mislukt',
    'Test connection': 'Verbinding testen',
    'Testing connection…': 'Verbinding testen…',
    'No API token stored. Save a token first.': 'Geen API-token opgeslagen. Sla eerst een token op.',
    'ok': 'ok',
    'Connected to %1 (%2).': 'Verbonden met %1 (%2).',
    'Configure a Kimai URL on the Connection tab first.': 'Configureer eerst een Kimai-URL op het tabblad Verbinding.',
    'Loading projects…': 'Projecten laden…',
    'Save an API token on the Connection tab first.': 'Sla eerst een API-token op op het tabblad Verbinding.',
    'Loaded %1 projects.': '%1 projecten geladen.',
    'Select a project to pin activities.': 'Selecteer een project om activiteiten vast te pinnen.',
    'Failed to load projects.': 'Projecten laden mislukt.',
    'Loading activities…': 'Activiteiten laden…',
    'No API token available.': 'Geen API-token beschikbaar.',
    '%1 project-specific, %2 global': '%1 projectspecifiek, %2 globaal',
    'Failed to load activities.': 'Activiteiten laden mislukt.',
    'Projects': 'Projecten',
    'Reload': 'Herladen',
    'Activities — %1': 'Activiteiten — %1',
    'Activities': 'Activiteiten',
    'Enter a city or place name to search.': 'Voer een stad- of plaatsnaam in om te zoeken.',
    'Searching…': 'Zoeken…',
    'Location search failed. Check your network connection.': 'Locatiezoekopdracht mislukt. Controleer je netwerkverbinding.',
    'No places found.': 'Geen plaatsen gevonden.',
    'Display': 'Weergave',
    'Refresh interval (seconds):': 'Verversingsinterval (seconden):',
    'Recent activities shown:': 'Getoonde recente activiteiten:',
    'Appearance:': 'Uiterlijk:',
    'Use desktop blur (translucent background)': 'Desktopvervaging gebruiken (doorschijnende achtergrond)',
    'Touch optimization:': 'Aanraakoptimalisatie:',
    'Automatic (follow Plasma tablet mode)': 'Automatisch (Plasma-tabletmodus volgen)',
    'On': 'Aan',
    'Off': 'Uit',
    'Larger tap targets for buttons, lists, pickers, and date/time controls.': 'Grotere tikdoelen voor knoppen, lijsten, kiezers en datum-/tijdvelden.',
    'Usual work day start:': 'Start gebruikelijke werkdag:',
    'Usual work day end:': 'Einde gebruikelijke werkdag:',
    'Day sparkline': 'Dag-sparkline',
    'Find location': 'Locatie zoeken',
    'Search for a city or place to set sunrise/sunset coloring. Powered by OpenStreetMap Nominatim.': 'Zoek een stad of plaats voor kleurcodering bij zonsopgang/zonsondergang. Mogelijk gemaakt door OpenStreetMap Nominatim.',
    'City, region, or address…': 'Stad, regio of adres…',
    'Search': 'Zoeken',
    'Using %1': '%1 gebruiken',
    'Current place: %1': 'Huidige plaats: %1',
    'Custom coordinates': 'Aangepaste coördinaten',
    'Latitude:': 'Breedtegraad:',
    'Longitude:': 'Lengtegraad:',
    'Used to color the sparkline for sunrise and sunset at your location.': 'Gebruikt om de sparkline te kleuren voor zonsopgang en zonsondergang op je locatie.',
    'Panel (taskbar)': 'Paneel (taakbalk)',
    'Show:': 'Tonen:',
    'Elapsed time': 'Verstreken tijd',
    'Project name': 'Projectnaam',
    'Activity name': 'Activiteitsnaam',
    'Panel flyout': 'Paneel-uitklapmenu',
    'Work summary (today / week / remaining)': 'Werkoverzicht (vandaag / week / resterend)',
    'Recent list': 'Recente lijst',
    'Continue last activity': 'Laatste activiteit voortzetten',
    'Start / switch activity controls': 'Bediening voor starten / wisselen van activiteit',
    'Desktop widget': 'Desktopwidget',
    'New activity picker': 'Kiezer voor nieuwe activiteit',
    'Behavior': 'Gedrag',
    'Tracking:': 'Registratie:',
    'Confirm before stopping the timer': 'Bevestigen voordat de timer wordt gestopt',
    'Idle detection:': 'Inactiviteitsdetectie:',
    'Stop timer when idle': 'Timer stoppen bij inactiviteit',
    'Idle threshold (minutes):': 'Drempel voor inactiviteit (minuten):',
    'Notifications:': 'Meldingen:',
    'Notify when tracking starts': 'Melden wanneer registratie start',
    'Notify when tracking stops': 'Melden wanneer registratie stopt',
    'Notify when stopped due to idle': 'Melden bij stoppen door inactiviteit',
    'Idle detection requires xprintidle (X11/XWayland). It may not work on pure Wayland sessions.': 'Inactiviteitsdetectie vereist xprintidle (X11/XWayland). Werkt mogelijk niet in pure Wayland-sessies.',
    'Back': 'Terug',
    'Create a finished entry with project, activity, and time range.': 'Maak een afgeronde boeking met project, activiteit en tijdsbereik.',
    'Begin': 'Begin',
    'End': 'Einde',
    'Duration: %1': 'Duur: %1',
    'Duration: —': 'Duur: —',
    'Duration: invalid range': 'Duur: ongeldig bereik',
    'Save entry': 'Boeking opslaan',
    'All': 'Alles',
    'Billable': 'Factureerbaar',
    'Non-billable': 'Niet-factureerbaar',
    'Charts for power users. Tracking stays on the main screen.': 'Grafieken voor power users. Tracking blijft op het hoofdscherm.',
    'Show': 'Tonen',
    'Today': 'Vandaag',
    'This week': 'Deze week',
    'Time by hour': 'Tijd per uur',
    'Previous day': 'Vorige dag',
    'Yesterday': 'Gisteren',
    'Next day': 'Volgende dag',
    'No time logged this day': 'Geen tijd geboekt op deze dag',
    'Projects by day': 'Projecten per dag',
    'Previous week': 'Vorige week',
    'Next week': 'Volgende week',
    'No time logged this week': 'Geen tijd geboekt deze week',
    'Projects by hour': 'Projecten per uur',
    'Weekdays and weekend — segments placed by clock time.': 'Weekdagen en weekend — segmenten op kloktijd.',
    'Weekdays — segments placed by clock time. Weekend appears when tracked.': 'Weekdagen — segmenten op kloktijd. Weekend verschijnt bij geboekte tijd.',
    'Axis shows business hours (%1–%2); expands if work falls outside.': 'As toont werktijden (%1–%2); verruimt als werk erbuiten valt.',
    'Activity distribution': 'Verdeling van activiteiten',
    'No activities today': 'Geen activiteiten vandaag',
    'No activities this week': 'Geen activiteiten deze week',
    'Time': 'Tijd',
    'Pick date': 'Datum kiezen',
    'Pick time': 'Tijd kiezen',
    'Hours : Minutes': 'Uren : Minuten',
    'Select': 'Selecteren',
    'Today\'s tracked time across 24 hours': 'Vandaag geboekte tijd over 24 uur',
    'Clockify cloud API is prefilled. Change only for a regional endpoint (e.g. euc1).': 'Clockify-cloud-API is vooraf ingevuld. Wijzig alleen voor een regionaal endpoint (bijv. euc1).',
    'Toggl Track cloud API is prefilled. Use your personal API token from Profile settings.': 'Toggl Track-cloud-API is vooraf ingevuld. Gebruik je persoonlijke API-token uit de profielinstellingen.',
    'SolidTime cloud API is prefilled. For self-hosting, replace with your instance base URL.': 'SolidTime-cloud-API is vooraf ingevuld. Vervang bij self-hosting door de basis-URL van je instantie.',
    'Self-hosted Kimai or the official hosted service (kimai.cloud). Paste the instance URL.': 'Zelfgehoste Kimai of de officiële hosted dienst (kimai.cloud). Plak de instantie-URL.',
    'API URL:': 'API-URL:',
    'https://api.solidtime.io or https://time.example.com': 'https://api.solidtime.io of https://time.example.com',
    'https://kimai.example.com or https://www.kimai.cloud': 'https://kimai.example.com of https://www.kimai.cloud',
    'API key:': 'API-sleutel:',
    'Colors:': 'Kleuren:',
    'Make similar colors distinctive within each category': 'Maak vergelijkbare kleuren onderscheidend binnen elke categorie',
    'Similarity threshold (%):': 'Gelijkenisdrempel (%):',
    'Higher similarity values treat more colors as too close. Clashing items get vivid, well-spaced replacement colors (not washed hue-shifts). If too many items cannot fit, the threshold is lowered automatically down to 12%. See Maintenance for clash groups.': 'Hogere gelijkeniswaarden behandelen meer kleuren als te dichtbij. Conflicterende items krijgen felle, goed gespreide vervangkleuren (geen bleke tintverschuivingen). Als te veel items niet passen, wordt de drempel automatisch verlaagd tot 12%. Zie Onderhoud voor conflictgroepen.',
    'Configure a server URL on the Connection tab first.': 'Stel eerst een server-URL in op het tabblad Verbinding.',
    'Loading customers, projects, and activities…': 'Klanten, projecten en activiteiten laden…',
    'Color distinction is off. Enable it in Display settings to see clash groups.': 'Kleurenonderscheid staat uit. Schakel het in bij Weergave om conflictgroepen te zien.',
    'Loaded %1 customers, %2 projects, %3 activities. No similar colors within a category.': '%1 klanten, %2 projecten, %3 activiteiten geladen. Geen vergelijkbare kleuren binnen een categorie.',
    'Loaded %1 customers, %2 projects, %3 activities. %4 clash group(s), %5 color(s) shifted.': '%1 klanten, %2 projecten, %3 activiteiten geladen. %4 conflictgroep(en), %5 kleur(en) verschoven.',
    'Only colors that clash within a category are listed. Each group starts with the entry that kept the Kimai color; shifted variants follow. Unique colors are hidden.': 'Alleen kleuren die binnen een categorie conflicteren worden getoond. Elke groep begint met de entry die de Kimai-kleur behield; verschoven varianten volgen. Unieke kleuren zijn verborgen.',
    'Reload from server': 'Opnieuw laden vanaf server',
    'Distinction on · configured %1% · effective customers %2% / projects %3% / activities %4%': 'Onderscheid aan · geconfigureerd %1% · effectief klanten %2% / projecten %3% / activiteiten %4%',
    'Distinction off — enable it in Display settings.': 'Onderscheid uit — schakel het in bij Weergave.',
    'Customers': 'Klanten',
    'No similar colors in this category.': 'Geen vergelijkbare kleuren in deze categorie.',
    'kept': 'behouden',
    'shifted': 'verschoven',
    'Maintenance': 'Onderhoud',
    'Edit': 'Bewerken',
    'Edit start, project, and activity': 'Start, project en activiteit bewerken',
    'Edit start time, project, and activity for the running entry.': 'Starttijd, project en activiteit van de lopende invoer bewerken.',
    'Elapsed time updates from the new start.': 'De verstreken tijd wordt vanaf de nieuwe start herberekend.',
    'Start must be a valid time not in the future.': 'Start moet een geldige tijd zijn en mag niet in de toekomst liggen.',
    'This provider cannot update the running entry.': 'Deze provider kan de lopende invoer niet bijwerken.',
    'Enter a valid start date/time.': 'Voer een geldige startdatum/-tijd in.',
    'Start must not be in the future.': 'Start mag niet in de toekomst liggen.',
    'Save': 'Opslaan',

    'Current': 'Huidig',
    'Switch to': 'Wisselen naar',
    'Already tracking this activity': 'Deze activiteit loopt al',
    'Could not resolve project or activity for that entry': 'Project of activiteit voor deze vermelding kon niet worden opgelost',
    'Switch activity?': 'Activiteit wisselen?',
}

PLURALS = {
    '%1 minute ago': ['%1 minuut geleden', '%1 minuten geleden'],
    '%1 hour ago': ['%1 uur geleden', '%1 uur geleden'],
    '%1 day ago': ['%1 dag geleden', '%1 dagen geleden'],
    '%1 place found.': ['%1 plaats gevonden.', '%1 plaatsen gevonden.'],
}
