# -*- coding: utf-8 -*-
T = {
    'Project-specific': 'Projectspecifiek',
    'Global activities': 'Globale activiteiten',
    'Plasmai': 'Plasmai',
    'Loading…': 'Laden…',
    'Not configured — right-click to configure': 'Niet geconfigureerd — rechtsklik om te configureren',
    'just now': 'zojuist',
    'yesterday': 'gisteren',
    'Not configured': 'Niet geconfigureerd',
    'Connecting to %1…': 'Verbinden met %1…',
    'Connection problem': 'Verbindingsprobleem',
    'Connected to %1 (%2)': 'Verbonden met %1 (%2)',
    'Connected to %1': 'Verbonden met %1',
    'Enter valid begin and end date/time.': 'Voer een geldige begin- en einddatum/-tijd in.',
    'End must be after begin.': 'Einde moet na begin liggen.',
    'Entry added': 'Invoer toegevoegd',
    'Manual time entry': 'Handmatige tijdregistratie',
    '%1 left today': '%1 resterend vandaag',
    '%1 over today': '%1 over vandaag',
    '%1 left this week': '%1 resterend deze week',
    '%1 over this week': '%1 over deze week',
    'Today %1': 'Vandaag %1',
    'Week %1': 'Week %1',
    'Tracking started': 'Registratie gestart',
    'Switched activity': 'Activiteit gewisseld',
    'Tracking stopped (idle)': 'Registratie gestopt (inactief)',
    'Tracking stopped': 'Registratie gestopt',
    'Stop tracking?': 'Registratie stoppen?',
    'Stop tracking %1 · %2?': 'Registratie stoppen voor %1 · %2?',
    'Statistics': 'Statistieken',
    'Add entry': 'Invoer toevoegen',
    'Add a manual time entry': 'Handmatige tijdregistratie toevoegen',
    'Show statistics': 'Statistieken tonen',
    'Back to timer': 'Terug naar timer',
    'Connect a time tracker': 'Tijdregistratiedienst verbinden',
    'Add your service, server URL (if needed), and API token to start tracking from the panel.': 'Voeg je dienst, server-URL (indien nodig) en API-token toe om vanuit het paneel te registreren.',
    'Configure Plasmai': 'Plasmai configureren',
    'Retry': 'Opnieuw proberen',
    'Configure': 'Configureren',
    'Not tracking': 'Niet aan het registreren',
    'Description': 'Beschrijving',
    'Save description': 'Beschrijving opslaan',
    'Stop': 'Stop',
    'Continue · %1 · %2': 'Doorgaan · %1 · %2',
    'Favorites': 'Favorieten',
    'No favorites yet': 'Nog geen favorieten',
    'Pin frequent project/activity pairs in the widget settings.': 'Pin veelgebruikte project-/activiteitcombinaties in de widgetinstellingen.',
    'Configure favorites': 'Favorieten configureren',
    '+%1 more in settings': '+%1 meer in instellingen',
    'Recent': 'Recent',
    'No recent activities': 'Geen recente activiteiten',
    'Start tracking to build your recent list.': 'Start met registreren om je recente lijst op te bouwen.',
    'Switch to another activity…': 'Naar een andere activiteit wisselen…',
    'Start something else…': 'Iets anders starten…',
    'Switch activity': 'Activiteit wisselen',
    'New activity': 'Nieuwe activiteit',
    'Select project…': 'Project selecteren…',
    'Select activity…': 'Activiteit selecteren…',
    'Description (optional)': 'Beschrijving (optioneel)',
    'Start': 'Start',
    'Switch': 'Wisselen',
    'Cancel': 'Annuleren',
    'Unknown error': 'Onbekende fout',
    'URL and API token are required': 'URL en API-token zijn verplicht',
    'Configure your time tracker URL and API token': 'Configureer de URL en het API-token van je tijdregistratiedienst',
    'This action is not supported for the selected service yet.': 'Deze actie wordt nog niet ondersteund voor de geselecteerde dienst.',
    'Cannot reach the server. Check your network, URL, or TLS certificate.': 'Kan de server niet bereiken. Controleer je netwerk, URL of TLS-certificaat.',
    'Authentication failed. Check your API token.': 'Authenticatie mislukt. Controleer je API-token.',
    'Server not found. Check your URL.': 'Server niet gevonden. Controleer je URL.',
    'Access denied. Your token may lack required permissions.': 'Toegang geweigerd. Je token heeft mogelijk niet de vereiste rechten.',
    'Server error (%1).': 'Serverfout (%1).',
    'Request failed: %1': 'Verzoek mislukt: %1',
    'Request failed (%1).': 'Verzoek mislukt (%1).',
    'Connection': 'Verbinding',
    'Configure a time-tracking profile. Choose Kimai, Clockify, Toggl Track, or SolidTime.': 'Configureer een tijdregistratieprofiel. Kies Kimai, Clockify, Toggl Track of SolidTime.',
    'Profile:': 'Profiel:',
    'Profile name:': 'Profielnaam:',
    'Service:': 'Dienst:',
    'Server URL:': 'Server-URL:',
    'API token:': 'API-token:',
    'Paste token to save in KWallet': 'Plak token om op te slaan in KWallet',
    'Add profile': 'Profiel toevoegen',
    'Profile %1': 'Profiel %1',
    'Remove': 'Verwijderen',
    'Use this profile': 'Dit profiel gebruiken',
    'none': 'geen',
    'Active profile: %1': 'Actief profiel: %1',
    'Saving…': 'Opslaan…',
    'Save token': 'Token opslaan',
    'Token saved to KWallet for this profile.': 'Token opgeslagen in KWallet voor dit profiel.',
    'Failed to save token': 'Token opslaan mislukt',
    'Clear token': 'Token wissen',
    'Token removed from KWallet.': 'Token verwijderd uit KWallet.',
    'Failed to clear token': 'Token wissen mislukt',
    'Test connection': 'Verbinding testen',
    'Testing connection…': 'Verbinding testen…',
    'No API token stored. Save a token first.': 'Geen API-token opgeslagen. Sla eerst een token op.',
    'ok': 'ok',
    'Connected to %1 (%2).': 'Verbonden met %1 (%2).',
    'Configure a Kimai URL on the Connection tab first.': 'Configureer eerst een Kimai-URL op het tabblad Verbinding.',
    'Loading projects…': 'Projecten laden…',
    'Save an API token on the Connection tab first.': 'Sla eerst een API-token op op het tabblad Verbinding.',
    'Loaded %1 projects.': '%1 projecten geladen.',
    'Select a project to pin activities.': 'Selecteer een project om activiteiten vast te pinnen.',
    'Failed to load projects.': 'Projecten laden mislukt.',
    'Loading activities…': 'Activiteiten laden…',
    'No API token available.': 'Geen API-token beschikbaar.',
    '%1 project-specific, %2 global': '%1 projectspecifiek, %2 globaal',
    'Failed to load activities.': 'Activiteiten laden mislukt.',
    'Projects': 'Projecten',
    'Reload': 'Herladen',
    'Activities — %1': 'Activiteiten — %1',
    'Activities': 'Activiteiten',
    'Enter a city or place name to search.': 'Voer een stad- of plaatsnaam in om te zoeken.',
    'Searching…': 'Zoeken…',
    'Location search failed. Check your network connection.': 'Locatiezoekopdracht mislukt. Controleer je netwerkverbinding.',
    'No places found.': 'Geen plaatsen gevonden.',
    'Display': 'Weergave',
    'Refresh interval (seconds):': 'Verversingsinterval (seconden):',
    'Touch optimization:': 'Aanraakoptimalisatie:',
    'Automatic (follow Plasma tablet mode)': 'Automatisch (Plasma-tabletmodus volgen)',
    'On': 'Aan',
    'Off': 'Uit',
    'Larger tap targets for buttons, lists, pickers, and date/time controls.': 'Grotere tikdoelen voor knoppen, lijsten, kiezers en datum-/tijdvelden.',
    'Usual work day start:': 'Start gebruikelijke werkdag:',
    'Usual work day end:': 'Einde gebruikelijke werkdag:',
    'Day sparkline': 'Dag-sparkline',
    'City, region, or address…': 'Stad, regio of adres…',
    'Search': 'Zoeken',
    'Using %1': '%1 gebruiken',
    'Current place: %1': 'Huidige plaats: %1',
    'Latitude:': 'Breedtegraad:',
    'Longitude:': 'Lengtegraad:',
    'Panel (taskbar)': 'Paneel (taakbalk)',
    'Show:': 'Tonen:',
    'Elapsed time': 'Verstreken tijd',
    'Project name': 'Projectnaam',
    'Activity name': 'Activiteitsnaam',
    'Panel flyout': 'Paneel-uitklapmenu',
    'Work summary (today / week / remaining)': 'Werkoverzicht (vandaag / week / resterend)',
    'Recent list': 'Recente lijst',
    'Continue last activity': 'Laatste activiteit voortzetten',
    'Start / switch activity controls': 'Bediening voor starten / wisselen van activiteit',
    'Desktop widget': 'Desktopwidget',
    'New activity picker': 'Kiezer voor nieuwe activiteit',
    'Behavior': 'Gedrag',
    'Tracking:': 'Registratie:',
    'Confirm before stopping the timer': 'Bevestigen voordat de timer wordt gestopt',
    'Idle detection:': 'Inactiviteitsdetectie:',
    'Stop timer when idle': 'Timer stoppen bij inactiviteit',
    'Idle threshold (minutes):': 'Drempel voor inactiviteit (minuten):',
    'Notifications:': 'Meldingen:',
    'Notify when tracking starts': 'Melden wanneer registratie start',
    'Notify when tracking stops': 'Melden wanneer registratie stopt',
    'Notify when stopped due to idle': 'Melden bij stoppen door inactiviteit',
    'Back': 'Terug',
    'Create a finished entry with project, activity, and time range.': 'Maak een afgeronde boeking met project, activiteit en tijdsbereik.',
    'Begin': 'Begin',
    'End': 'Einde',
    'Duration: %1': 'Duur: %1',
    'Duration: —': 'Duur: —',
    'Duration: invalid range': 'Duur: ongeldig bereik',
    'Save entry': 'Boeking opslaan',
    'All': 'Alles',
    'Billable': 'Factureerbaar',
    'Non-billable': 'Niet-factureerbaar',
    'Today': 'Vandaag',
    'This week': 'Deze week',
    'Time by hour': 'Tijd per uur',
    'Previous day': 'Vorige dag',
    'Yesterday': 'Gisteren',
    'Next day': 'Volgende dag',
    'No time logged this day': 'Geen tijd geboekt op deze dag',
    'Projects by day': 'Projecten per dag',
    'Previous week': 'Vorige week',
    'Next week': 'Volgende week',
    'No time logged this week': 'Geen tijd geboekt deze week',
    'Projects by hour': 'Projecten per uur',
    'Weekdays and weekend — segments placed by clock time.': 'Weekdagen en weekend — segmenten op kloktijd.',
    'Weekdays — segments placed by clock time. Weekend appears when tracked.': 'Weekdagen — segmenten op kloktijd. Weekend verschijnt bij geboekte tijd.',
    'Axis shows business hours (%1–%2); expands if work falls outside.': 'As toont werktijden (%1–%2); verruimt als werk erbuiten valt.',
    'Activity distribution': 'Verdeling van activiteiten',
    'No activities today': 'Geen activiteiten vandaag',
    'No activities this week': 'Geen activiteiten deze week',
    'Time': 'Tijd',
    'Pick date': 'Datum kiezen',
    'Pick time': 'Tijd kiezen',
    'Hours : Minutes': 'Uren : Minuten',
    'Select': 'Selecteren',
    'Clockify cloud API is prefilled. Change only for a regional endpoint (e.g. euc1).': 'Clockify-cloud-API is vooraf ingevuld. Wijzig alleen voor een regionaal endpoint (bijv. euc1).',
    'Toggl Track cloud API is prefilled. Use your personal API token from Profile settings.': 'Toggl Track-cloud-API is vooraf ingevuld. Gebruik je persoonlijke API-token uit de profielinstellingen.',
    'SolidTime cloud API is prefilled. For self-hosting, replace with your instance base URL.': 'SolidTime-cloud-API is vooraf ingevuld. Vervang bij self-hosting door de basis-URL van je instantie.',
    'Self-hosted Kimai or the official hosted service (kimai.cloud). Paste the instance URL.': 'Zelfgehoste Kimai of de officiële hosted dienst (kimai.cloud). Plak de instantie-URL.',
    'API URL:': 'API-URL:',
    'https://api.solidtime.io or https://time.example.com': 'https://api.solidtime.io of https://time.example.com',
    'https://kimai.example.com or https://www.kimai.cloud': 'https://kimai.example.com of https://www.kimai.cloud',
    'API key:': 'API-sleutel:',
    'Make similar colors distinctive within each category': 'Maak vergelijkbare kleuren onderscheidend binnen elke categorie',
    'Similarity threshold (%):': 'Gelijkenisdrempel (%):',
    'Configure a server URL on the Connection tab first.': 'Stel eerst een server-URL in op het tabblad Verbinding.',
    'Loading customers, projects, and activities…': 'Klanten, projecten en activiteiten laden…',
    'Color distinction is off. Enable it in Display settings to see clash groups.': 'Kleurenonderscheid staat uit. Schakel het in bij Weergave om conflictgroepen te zien.',
    'Loaded %1 customers, %2 projects, %3 activities. No similar colors within a category.': '%1 klanten, %2 projecten, %3 activiteiten geladen. Geen vergelijkbare kleuren binnen een categorie.',
    'Loaded %1 customers, %2 projects, %3 activities. %4 clash group(s), %5 color(s) shifted.': '%1 klanten, %2 projecten, %3 activiteiten geladen. %4 conflictgroep(en), %5 kleur(en) verschoven.',
    'Only colors that clash within a category are listed. Each group starts with the entry that kept the Kimai color; shifted variants follow. Unique colors are hidden.': 'Alleen kleuren die binnen een categorie conflicteren worden getoond. Elke groep begint met de entry die de Kimai-kleur behield; verschoven varianten volgen. Unieke kleuren zijn verborgen.',
    'Reload from server': 'Opnieuw laden vanaf server',
    'Distinction on · configured %1% · effective customers %2% / projects %3% / activities %4%': 'Onderscheid aan · geconfigureerd %1% · effectief klanten %2% / projecten %3% / activiteiten %4%',
    'Distinction off — enable it in Display settings.': 'Onderscheid uit — schakel het in bij Weergave.',
    'Customers': 'Klanten',
    'No similar colors in this category.': 'Geen vergelijkbare kleuren in deze categorie.',
    'kept': 'behouden',
    'shifted': 'verschoven',
    'Maintenance': 'Onderhoud',
    'Edit': 'Bewerken',
    'Edit start, project, and activity': 'Start, project en activiteit bewerken',
    'Elapsed time updates from the new start.': 'De verstreken tijd wordt vanaf de nieuwe start herberekend.',
    'Start must be a valid time not in the future.': 'Start moet een geldige tijd zijn en mag niet in de toekomst liggen.',
    'This provider cannot update the running entry.': 'Deze provider kan de lopende invoer niet bijwerken.',
    'Enter a valid start date/time.': 'Voer een geldige startdatum/-tijd in.',
    'Start must not be in the future.': 'Start mag niet in de toekomst liggen.',
    'Save': 'Opslaan',
    'Current': 'Huidig',
    'Switch to': 'Wisselen naar',
    'Could not resolve project or activity for that entry': 'Project of activiteit voor deze vermelding kon niet worden opgelost',
    'Edit start, project, activity, billable, and tags for the running entry.': 'Start, project, activiteit, factureerbaar en tags van de lopende invoer bewerken.',
    'Starts or switches this activity': 'Start of wisselt naar deze activiteit',
    'A profile named "%1" already exists.': 'Er bestaat al een profiel met de naam „%1”.',
    'Appearance': 'Weergave',
    'Updates': 'Updates',
    'Colors': 'Kleuren',
    'Distinction:': 'Onderscheid:',
    'Higher similarity values treat more colors as too close. Clashing items get vivid, well-spaced replacement colors. See Maintenance for clash groups.': 'Hogere gelijkeniswaarden behandelen meer kleuren als te dichtbij. Conflicterende items krijgen levendige, goed gespreide vervangkleuren. Zie Onderhoud voor conflictgroepen.',
    'Color distinction is available for Kimai profiles (per-customer / project / activity colors).': 'Kleuronderscheid is beschikbaar voor Kimai-profielen (kleuren per klant / project / activiteit).',
    'Work hours': 'Werkuren',
    'Used for the sparkline zoom and remaining-time in the work summary.': 'Gebruikt voor de sparkline-zoom en resterende tijd in het overzicht.',
    'Arcs:': 'Bogen:',
    'Show sun, moon, and work arcs': 'Zon-, maan- en werkbogen tonen',
    'Hide the whole sparkline under Panel flyout or Desktop widget below.': 'De hele sparkline verbergen onder paneel-flyout of bureaubladwidget hieronder.',
    'Find location:': 'Locatie zoeken:',
    'Search a place or enter coordinates for sunrise/sunset coloring. Powered by OpenStreetMap Nominatim.': 'Zoek een plaats of voer coördinaten in voor zonsopkomst-/zonsondergangkleuren. Aangedreven door OpenStreetMap Nominatim.',
    'Customer color pill': 'Klantkleur-stip',
    'Project color pill': 'Projectkleur-stip',
    'Activities shown:': 'Getoonde activiteiten:',
    'Applies to both the panel flyout and the desktop widget.': 'Geldt voor de paneel-flyout en de bureaubladwidget.',
    'Loading projects': 'Projecten laden',
    'Color distinction is only available for Kimai profiles.': 'Kleuronderscheid is alleen beschikbaar voor Kimai-profielen.',
    'Color maintenance is for Kimai': 'Kleuronderhoud is voor Kimai',
    'Clockify, Toggl, and SolidTime do not expose Kimai-style customer / project / activity colors, so clash groups and color shifting are hidden for those profiles.': 'Clockify, Toggl en SolidTime bieden geen Kimai-achtige klant-/project-/activiteitskleuren, dus conflictgroepen en kleurverschuiving zijn voor die profielen verborgen.',
    'Select customer…': 'Klant kiezen…',
    'Today\'s tracked time': 'Vandaag bijgehouden tijd',
    'This provider cannot update descriptions.': 'Deze dienst kan beschrijvingen niet bijwerken.',
    'Open or close the Plasmai popup': 'Plasmai-popup openen of sluiten',
    'Add tag…': 'Tag toevoegen…',
    'Add tags…': 'Tags toevoegen…',
    'Tags': 'Tags',
    'Loading tags…': 'Tags laden…',
    'No tags on the server yet.': 'Nog geen tags op de server.',
    'Create tag “%1”': 'Tag „%1” aanmaken',
    'Already running.': 'Al actief.',
    'Entry actions': 'Invoeracties',
    'Edit entry': 'Invoer bewerken',
    'Split entry': 'Invoer splitsen',
    'Delete entry': 'Invoer verwijderen',
    'Idle detection uses the session idle hint on Wayland (loginctl / ScreenSaver) and xprintidle on X11.': 'Inactiviteitsdetectie gebruikt de sessie-idlehint op Wayland (loginctl / ScreenSaver) en xprintidle op X11.',
    'While tracking, shutdown and reboot wait like an unsaved file. Closing the lid or sleep is not blocked.': 'Tijdens bijhouden wachten afsluiten en herstarten zoals bij een niet-opgeslagen bestand. Klep sluiten of slaapstand wordt niet geblokkeerd.',
    'Remind me once if nothing is tracking during work hours': 'Eenmaal herinneren als er tijdens werkuren niets wordt bijgehouden',
    'A timer is still running': 'Er loopt nog een timer',
    'Idle time discarded': 'Inactieve tijd verworpen',
    'Nothing is tracking': 'Er wordt niets bijgehouden',
    'Work hours have started. Start a timer when you begin.': 'De werkuren zijn begonnen. Start een timer wanneer je begint.',
    'Customer created': 'Klant aangemaakt',
    'Project created': 'Project aangemaakt',
    'Activity created': 'Activiteit aangemaakt',
    'Entry updated': 'Invoer bijgewerkt',
    'Timesheet updated': 'Urenstaat bijgewerkt',
    'This provider cannot update stopped entries.': 'Deze dienst kan gestopte invoeren niet bijwerken.',
    'Tracking in progress': 'Bijhouden bezig',
    'This provider cannot delete entries.': 'Deze dienst kan invoeren niet verwijderen.',
    'Entry deleted': 'Invoer verwijderd',
    'Split time must be between begin and end.': 'De splittijd moet tussen begin en einde liggen.',
    'This provider cannot split entries.': 'Deze dienst kan invoeren niet splitsen.',
    'Entry split': 'Invoer gesplitst',
    'The first half was saved, but the second half could not be created.': 'De eerste helft is opgeslagen, maar de tweede helft kon niet worden aangemaakt.',
    'Delete entry?': 'Invoer verwijderen?',
    'Delete this finished entry? This cannot be undone.': 'Deze afgeronde invoer verwijderen? Dit kan niet ongedaan worden gemaakt.',
    'Delete "%1 · %2"? This cannot be undone.': '„%1 · %2” verwijderen? Dit kan niet ongedaan worden gemaakt.',
    'The first half keeps the original start. The second half starts at the split time.': 'De eerste helft behoudt de oorspronkelijke start. De tweede helft start op het splitmoment.',
    'Split at': 'Splitsen op',
    'Both halves will have a positive duration.': 'Beide helften hebben een positieve duur.',
    'Timer still running': 'Timer loopt nog',
    'Stop the timer before shutdown, or shut down anyway and leave it running on the server.': 'Stop de timer vóór het afsluiten, of sluit toch af en laat hem op de server lopen.',
    'Stop timer': 'Timer stoppen',
    'Shut down anyway': 'Toch afsluiten',
    'You were idle': 'Je was inactief',
    'Keep the time, discard the idle gap, or discard and continue the same activity.': 'Tijd behouden, de inactieve periode verwerpen, of verwerpen en dezelfde activiteit voortzetten.',
    'Keep time': 'Tijd behouden',
    'Discard idle': 'Inactiviteit verwerpen',
    'Discard and continue': 'Verwerpen en doorgaan',
    'Start · %1 · %2': 'Start · %1 · %2',
    'Change project, activity, range, billable, and tags for this finished entry.': 'Project, activiteit, bereik, factureerbaar en tags van deze afgeronde invoer wijzigen.',
    'Save changes': 'Wijzigingen opslaan',
    'Create customer': 'Klant aanmaken',
    'Create activity': 'Activiteit aanmaken',
    'Create project': 'Project aanmaken',
    'Activity will be added to %1.': 'De activiteit wordt toegevoegd aan %1.',
    'Name': 'Naam',
    'Customer': 'Klant',
}

PLURALS = {
    '%1 minute ago': ['%1 minuut geleden', '%1 minuten geleden'],
    '%1 hour ago': ['%1 uur geleden', '%1 uur geleden'],
    '%1 day ago': ['%1 dag geleden', '%1 dagen geleden'],
    '%1 place found.': ['%1 plaats gevonden.', '%1 plaatsen gevonden.'],
}
