# -*- coding: utf-8 -*-
"""Offline mode (ROADMAP pillar 6) strings. Merged by fill_po.py after the
per-language dictionaries (entries there win).

Column order: de, fr, es, it, nl, pt_BR, pl, uk, ru, ja, zh_CN
"""

LANGS = ["de", "fr", "es", "it", "nl", "pt_BR", "pl", "uk", "ru", "ja", "zh_CN"]

ROWS = [
    ("Offline · as of %1",
     "Offline · Stand %1", "Hors ligne · état de %1", "Sin conexión · estado de %1", "Offline · stato delle %1",
     "Offline · stand van %1", "Offline · estado de %1", "Offline · stan z %1", "Офлайн · стан на %1",
     "Офлайн · состояние на %1", "オフライン · %1 時点", "离线 · %1 的状态"),
    ("Offline",
     "Offline", "Hors ligne", "Sin conexión", "Offline", "Offline", "Offline", "Offline", "Офлайн", "Офлайн",
     "オフライン", "离线"),
    ("Show",
     "Anzeigen", "Afficher", "Mostrar", "Mostra", "Tonen", "Mostrar", "Pokaż", "Показати", "Показать", "表示", "显示"),
    ("New entry",
     "Neuer Eintrag", "Nouvelle entrée", "Nueva entrada", "Nuova voce", "Nieuwe invoer", "Nova entrada",
     "Nowy wpis", "Новий запис", "Новая запись", "新しいエントリー", "新条目"),
    ("Timer started",
     "Timer gestartet", "Minuteur démarré", "Temporizador iniciado", "Timer avviato", "Timer gestart",
     "Cronômetro iniciado", "Uruchomiono licznik", "Таймер запущено", "Таймер запущен", "タイマーを開始",
     "计时已开始"),
    ("Timer stopped",
     "Timer gestoppt", "Minuteur arrêté", "Temporizador detenido", "Timer fermato", "Timer gestopt",
     "Cronômetro parado", "Zatrzymano licznik", "Таймер зупинено", "Таймер остановлен", "タイマーを停止",
     "计时已停止"),
    ("Entry changed",
     "Eintrag geändert", "Entrée modifiée", "Entrada modificada", "Voce modificata", "Invoer gewijzigd",
     "Entrada alterada", "Zmieniono wpis", "Запис змінено", "Запись изменена", "エントリーを変更", "条目已更改"),
    ("Entry deleted",
     "Eintrag gelöscht", "Entrée supprimée", "Entrada eliminada", "Voce eliminata", "Invoer verwijderd",
     "Entrada excluída", "Usunięto wpis", "Запис видалено", "Запись удалена", "エントリーを削除", "条目已删除"),
    ("Film day details of %1",
     "Drehtag-Angaben vom %1", "Détails de la journée de tournage du %1", "Datos del día de rodaje del %1",
     "Dettagli della giornata di riprese del %1", "Draaidaggegevens van %1", "Detalhes do dia de filmagem de %1",
     "Szczegóły dnia zdjęciowego z %1", "Дані знімального дня %1", "Данные съёмочного дня %1",
     "%1 の撮影日の詳細", "%1 的拍摄日详情"),
    ("Not accepted: %1",
     "Nicht angenommen: %1", "Refusé : %1", "No aceptado: %1", "Non accettato: %1", "Niet geaccepteerd: %1",
     "Não aceito: %1", "Nie przyjęto: %1", "Не прийнято: %1", "Не принято: %1", "受け付けられませんでした: %1",
     "未被接受: %1"),
    ("Changed on the server meanwhile (%1). Overwrite it with this change, or discard this change?",
     "Inzwischen auf dem Server geändert (%1). Mit dieser Änderung überschreiben oder diese Änderung verwerfen?",
     "Modifié entre-temps sur le serveur (%1). L’écraser avec cette modification, ou abandonner cette modification ?",
     "Modificado mientras tanto en el servidor (%1). ¿Sobrescribirlo con este cambio o descartar este cambio?",
     "Nel frattempo modificato sul server (%1). Sovrascriverlo con questa modifica o scartare questa modifica?",
     "Intussen op de server gewijzigd (%1). Overschrijven met deze wijziging of deze wijziging verwerpen?",
     "Alterado no servidor nesse meio-tempo (%1). Sobrescrever com esta alteração ou descartar esta alteração?",
     "W międzyczasie zmieniono na serwerze (%1). Nadpisać tą zmianą czy odrzucić tę zmianę?",
     "Тим часом змінено на сервері (%1). Перезаписати цією зміною чи відкинути цю зміну?",
     "Тем временем изменено на сервере (%1). Перезаписать этим изменением или отменить это изменение?",
     "その間にサーバーで変更されました (%1)。この変更で上書きしますか、それともこの変更を破棄しますか?",
     "服务器上已被更改 (%1)。用此更改覆盖，还是放弃此更改?"),
    ("Waiting for the connection",
     "Wartet auf die Verbindung", "En attente de la connexion", "Esperando la conexión", "In attesa della connessione",
     "Wacht op de verbinding", "Aguardando a conexão", "Oczekuje na połączenie", "Очікує на з’єднання",
     "Ожидает подключения", "接続を待っています", "正在等待连接"),
    ("Everything is synced.",
     "Alles ist synchronisiert.", "Tout est synchronisé.", "Todo está sincronizado.", "Tutto è sincronizzato.",
     "Alles is gesynchroniseerd.", "Tudo está sincronizado.", "Wszystko jest zsynchronizowane.",
     "Усе синхронізовано.", "Всё синхронизировано.", "すべて同期済みです。", "已全部同步。"),
    ("Overwrite",
     "Überschreiben", "Écraser", "Sobrescribir", "Sovrascrivi", "Overschrijven", "Sobrescrever", "Nadpisz",
     "Перезаписати", "Перезаписать", "上書き", "覆盖"),
    ("Discard",
     "Verwerfen", "Abandonner", "Descartar", "Scarta", "Verwerpen", "Descartar", "Odrzuć", "Відкинути",
     "Отменить", "破棄", "放弃"),
    ("Not synced yet",
     "Noch nicht synchronisiert", "Pas encore synchronisé", "Aún no sincronizado", "Non ancora sincronizzato",
     "Nog niet gesynchroniseerd", "Ainda não sincronizado", "Jeszcze nie zsynchronizowano",
     "Ще не синхронізовано", "Ещё не синхронизировано", "未同期", "尚未同步"),
    ("This needs a connection to the server.",
     "Dafür ist eine Verbindung zum Server nötig.", "Cela nécessite une connexion au serveur.",
     "Esto requiere una conexión con el servidor.", "Serve una connessione al server.",
     "Hiervoor is een verbinding met de server nodig.", "Isso precisa de uma conexão com o servidor.",
     "To wymaga połączenia z serwerem.", "Для цього потрібне з’єднання із сервером.",
     "Для этого нужно подключение к серверу.", "サーバーへの接続が必要です。", "这需要连接到服务器。"),
    ("Not synced",
     "Nicht synchronisiert", "Non synchronisé", "Sin sincronizar", "Non sincronizzato", "Niet gesynchroniseerd",
     "Não sincronizado", "Niezsynchronizowane", "Не синхронізовано", "Не синхронизировано", "未同期", "未同步"),
    ("Discarding idle time needs a connection to the server.",
     "Leerlauf verwerfen geht nur mit Verbindung zum Server.",
     "Abandonner le temps d’inactivité nécessite une connexion au serveur.",
     "Descartar el tiempo inactivo requiere una conexión con el servidor.",
     "Per scartare il tempo di inattività serve una connessione al server.",
     "Inactieve tijd verwerpen kan alleen met een verbinding met de server.",
     "Descartar o tempo ocioso precisa de uma conexão com o servidor.",
     "Odrzucenie czasu bezczynności wymaga połączenia z serwerem.",
     "Щоб відкинути час простою, потрібне з’єднання із сервером.",
     "Чтобы отменить время простоя, нужно подключение к серверу.",
     "アイドル時間の破棄にはサーバーへの接続が必要です。", "放弃空闲时间需要连接到服务器。"),
    ("Switching profiles needs a connection to the server.",
     "Profilwechsel geht nur mit Verbindung zum Server.",
     "Changer de profil nécessite une connexion au serveur.",
     "Cambiar de perfil requiere una conexión con el servidor.",
     "Per cambiare profilo serve una connessione al server.",
     "Van profiel wisselen kan alleen met een verbinding met de server.",
     "Trocar de perfil precisa de uma conexão com o servidor.",
     "Zmiana profilu wymaga połączenia z serwerem.",
     "Для зміни профілю потрібне з’єднання із сервером.",
     "Для смены профиля нужно подключение к серверу.",
     "プロファイルの切り替えにはサーバーへの接続が必要です。", "切换配置文件需要连接到服务器。"),
    ("Trip added",
     "Fahrt angelegt", "Trajet ajouté", "Trayecto añadido", "Tragitto aggiunto", "Rit toegevoegd", "Viagem adicionada",
     "Dodano przejazd", "Поїздку додано", "Поездка добавлена", "移動を追加", "已添加行程"),
    ("Trip changed",
     "Fahrt geändert", "Trajet modifié", "Trayecto modificado", "Tragitto modificato", "Rit gewijzigd", "Viagem alterada",
     "Zmieniono przejazd", "Поїздку змінено", "Поездка изменена", "移動を変更", "已更改行程"),
    ("Trip deleted",
     "Fahrt gelöscht", "Trajet supprimé", "Trayecto eliminado", "Tragitto eliminato", "Rit verwijderd", "Viagem excluída",
     "Usunięto przejazd", "Поїздку видалено", "Поездка удалена", "移動を削除", "已删除行程"),
    ("Activity",
     "Tätigkeit", "Activité", "Actividad", "Attività", "Activiteit", "Atividade", "Czynność", "Діяльність",
     "Деятельность", "アクティビティ", "活动"),
]

PLURALS = {
    "%1 change needs your decision": {
        "de": ["%1 Änderung braucht deine Entscheidung", "%1 Änderungen brauchen deine Entscheidung"],
        "fr": ["%1 modification attend ta décision", "%1 modifications attendent ta décision"],
        "es": ["%1 cambio necesita tu decisión", "%1 cambios necesitan tu decisión"],
        "it": ["%1 modifica attende la tua decisione", "%1 modifiche attendono la tua decisione"],
        "nl": ["%1 wijziging wacht op je beslissing", "%1 wijzigingen wachten op je beslissing"],
        "pt_BR": ["%1 alteração precisa da sua decisão", "%1 alterações precisam da sua decisão"],
        "pl": ["%1 zmiana czeka na Twoją decyzję", "%1 zmiany czekają na Twoją decyzję", "%1 zmian czeka na Twoją decyzję"],
        "uk": ["%1 зміна чекає на ваше рішення", "%1 зміни чекають на ваше рішення", "%1 змін чекають на ваше рішення"],
        "ru": ["%1 изменение ждёт вашего решения", "%1 изменения ждут вашего решения", "%1 изменений ждут вашего решения"],
        "ja": ["%1 件の変更に判断が必要です"],
        "zh_CN": ["%1 项更改需要你决定"],
    },
    "%1 change not synced yet": {
        "de": ["%1 Änderung noch nicht synchronisiert", "%1 Änderungen noch nicht synchronisiert"],
        "fr": ["%1 modification pas encore synchronisée", "%1 modifications pas encore synchronisées"],
        "es": ["%1 cambio aún sin sincronizar", "%1 cambios aún sin sincronizar"],
        "it": ["%1 modifica non ancora sincronizzata", "%1 modifiche non ancora sincronizzate"],
        "nl": ["%1 wijziging nog niet gesynchroniseerd", "%1 wijzigingen nog niet gesynchroniseerd"],
        "pt_BR": ["%1 alteração ainda não sincronizada", "%1 alterações ainda não sincronizadas"],
        "pl": ["%1 zmiana jeszcze niezsynchronizowana", "%1 zmiany jeszcze niezsynchronizowane", "%1 zmian jeszcze niezsynchronizowanych"],
        "uk": ["%1 зміна ще не синхронізована", "%1 зміни ще не синхронізовані", "%1 змін ще не синхронізовано"],
        "ru": ["%1 изменение ещё не синхронизировано", "%1 изменения ещё не синхронизированы", "%1 изменений ещё не синхронизировано"],
        "ja": ["%1 件の変更が未同期です"],
        "zh_CN": ["%1 项更改尚未同步"],
    },
}

T_BY_LANG = {lang: {} for lang in LANGS}
for row in ROWS:
    for lang, value in zip(LANGS, row[1:]):
        T_BY_LANG[lang][row[0]] = value
