# -*- coding: utf-8 -*-
T = {
    'Project-specific': 'Specyficzne dla projektu',
    'Global activities': 'Globalne aktywności',
    'Plasmai': 'Plasmai',
    'Loading…': 'Ładowanie…',
    'Not configured — right-click to configure': 'Nie skonfigurowano — kliknij prawym przyciskiem, aby skonfigurować',
    'just now': 'przed chwilą',
    'yesterday': 'wczoraj',
    'Not configured': 'Nie skonfigurowano',
    'Connecting to %1…': 'Łączenie z %1…',
    'Connection problem': 'Problem z połączeniem',
    'Connected to %1 (%2)': 'Połączono z %1 (%2)',
    'Connected to %1': 'Połączono z %1',
    'Enter valid begin and end date/time.': 'Wprowadź prawidłową datę i godzinę rozpoczęcia oraz zakończenia.',
    'End must be after begin.': 'Koniec musi być po rozpoczęciu.',
    'Entry added': 'Wpis dodany',
    'Manual time entry': 'Ręczny wpis czasu',
    '%1 left today': 'Pozostało dziś: %1',
    '%1 over today': 'Przekroczono dziś o %1',
    '%1 left this week': 'Pozostało w tym tygodniu: %1',
    '%1 over this week': 'Przekroczono w tym tygodniu o %1',
    'Today %1': 'Dziś %1',
    'Week %1': 'Tydzień %1',
    'Tracking started': 'Rozpoczęto rejestrowanie',
    'Switched activity': 'Zmieniono aktywność',
    'Tracking stopped (idle)': 'Rejestrowanie zatrzymane (bezczynność)',
    'Tracking stopped': 'Rejestrowanie zatrzymane',
    'Stop tracking?': 'Zatrzymać rejestrowanie?',
    'Stop tracking %1 · %2?': 'Zatrzymać rejestrowanie %1 · %2?',
    'Statistics': 'Statystyki',
    'Add entry': 'Dodaj wpis',
    'Add a manual time entry': 'Dodaj ręczny wpis czasu',
    'Show statistics': 'Pokaż statystyki',
    'Back to timer': 'Wróć do licznika',
    'Connect a time tracker': 'Połącz usługę rejestrowania czasu',
    'Add your service, server URL (if needed), and API token to start tracking from the panel.': 'Dodaj usługę, adres URL serwera (jeśli potrzebny) i token API, aby rozpocząć rejestrowanie z panelu.',
    'Configure Plasmai': 'Skonfiguruj Plasmai',
    'Retry': 'Spróbuj ponownie',
    'Configure': 'Konfiguruj',
    'Not tracking': 'Brak rejestrowania',
    'Description': 'Opis',
    'Save description': 'Zapisz opis',
    'Stop': 'Stop',
    'Continue · %1 · %2': 'Kontynuuj · %1 · %2',
    'Favorites': 'Ulubione',
    'No favorites yet': 'Brak ulubionych',
    'Pin frequent project/activity pairs in the widget settings.': 'Przypnij często używane pary projekt/aktywność w ustawieniach widgetu.',
    'Configure favorites': 'Skonfiguruj ulubione',
    '+%1 more in settings': '+%1 więcej w ustawieniach',
    'Recent': 'Ostatnie',
    'No recent activities': 'Brak ostatnich aktywności',
    'Start tracking to build your recent list.': 'Rozpocznij rejestrowanie, aby utworzyć listę ostatnich.',
    'Switch to another activity…': 'Przełącz na inną aktywność…',
    'Start something else…': 'Rozpocznij coś innego…',
    'Switch activity': 'Zmień aktywność',
    'New activity': 'Nowa aktywność',
    'Select project…': 'Wybierz projekt…',
    'Select activity…': 'Wybierz aktywność…',
    'Description (optional)': 'Opis (opcjonalnie)',
    'Start': 'Start',
    'Switch': 'Zmień',
    'Cancel': 'Anuluj',
    'Unknown error': 'Nieznany błąd',
    'URL and API token are required': 'Adres URL i token API są wymagane',
    'Configure your time tracker URL and API token': 'Skonfiguruj adres URL i token API usługi rejestrowania czasu',
    'This action is not supported for the selected service yet.': 'Ta akcja nie jest jeszcze obsługiwana dla wybranej usługi.',
    'Cannot reach the server. Check your network, URL, or TLS certificate.': 'Nie można połączyć się z serwerem. Sprawdź sieć, adres URL lub certyfikat TLS.',
    'Authentication failed. Check your API token.': 'Uwierzytelnianie nie powiodło się. Sprawdź token API.',
    'Server not found. Check your URL.': 'Nie znaleziono serwera. Sprawdź adres URL.',
    'Access denied. Your token may lack required permissions.': 'Odmowa dostępu. Twój token może nie mieć wymaganych uprawnień.',
    'Server error (%1).': 'Błąd serwera (%1).',
    'Request failed: %1': 'Żądanie nie powiodło się: %1',
    'Request failed (%1).': 'Żądanie nie powiodło się (%1).',
    'Connection': 'Połączenie',
    'Configure a time-tracking profile. Choose Kimai, Clockify, Toggl Track, or SolidTime.': 'Skonfiguruj profil rejestrowania czasu. Wybierz Kimai, Clockify, Toggl Track lub SolidTime.',
    'Profile:': 'Profil:',
    'Profile name:': 'Nazwa profilu:',
    'Service:': 'Usługa:',
    'Server URL:': 'Adres URL serwera:',
    'API token:': 'Token API:',
    'Paste token to save in KWallet': 'Wklej token, aby zapisać w KWallet',
    'Add profile': 'Dodaj profil',
    'Profile %1': 'Profil %1',
    'Remove': 'Usuń',
    'Use this profile': 'Użyj tego profilu',
    'none': 'brak',
    'Active profile: %1': 'Aktywny profil: %1',
    'Saving…': 'Zapisywanie…',
    'Save token': 'Zapisz token',
    'Token saved to KWallet for this profile.': 'Token zapisany w KWallet dla tego profilu.',
    'Failed to save token': 'Nie udało się zapisać tokenu',
    'Clear token': 'Wyczyść token',
    'Token removed from KWallet.': 'Token usunięty z KWallet.',
    'Failed to clear token': 'Nie udało się wyczyścić tokenu',
    'Test connection': 'Testuj połączenie',
    'Testing connection…': 'Testowanie połączenia…',
    'No API token stored. Save a token first.': 'Brak zapisanego tokenu API. Najpierw zapisz token.',
    'ok': 'ok',
    'Connected to %1 (%2).': 'Połączono z %1 (%2).',
    'Configure a Kimai URL on the Connection tab first.': 'Najpierw skonfiguruj adres URL Kimai na karcie Połączenie.',
    'Loading projects…': 'Ładowanie projektów…',
    'Save an API token on the Connection tab first.': 'Najpierw zapisz token API na karcie Połączenie.',
    'Loaded %1 projects.': 'Załadowano %1 projektów.',
    'Select a project to pin activities.': 'Wybierz projekt, aby przypiąć aktywności.',
    'Failed to load projects.': 'Nie udało się załadować projektów.',
    'Loading activities…': 'Ładowanie aktywności…',
    'No API token available.': 'Brak dostępnego tokenu API.',
    '%1 project-specific, %2 global': '%1 specyficznych dla projektu, %2 globalnych',
    'Failed to load activities.': 'Nie udało się załadować aktywności.',
    'Projects': 'Projekty',
    'Reload': 'Odśwież',
    'Activities — %1': 'Aktywności — %1',
    'Activities': 'Aktywności',
    'Enter a city or place name to search.': 'Wprowadź nazwę miasta lub miejsca, aby wyszukać.',
    'Searching…': 'Wyszukiwanie…',
    'Location search failed. Check your network connection.': 'Wyszukiwanie lokalizacji nie powiodło się. Sprawdź połączenie sieciowe.',
    'No places found.': 'Nie znaleziono miejsc.',
    'Display': 'Wyświetlanie',
    'Refresh interval (seconds):': 'Interwał odświeżania (sekundy):',
    'Touch optimization:': 'Optymalizacja dotykowa:',
    'Automatic (follow Plasma tablet mode)': 'Automatycznie (tryb tabletu Plasma)',
    'On': 'Włączone',
    'Off': 'Wyłączone',
    'Larger tap targets for buttons, lists, pickers, and date/time controls.': 'Większe cele dotykowe dla przycisków, list, selektorów oraz daty/czasu.',
    'Usual work day start:': 'Początek zwykłego dnia pracy:',
    'Usual work day end:': 'Koniec zwykłego dnia pracy:',
    'Day sparkline': 'Miniwykres dnia',
    'City, region, or address…': 'Miasto, region lub adres…',
    'Search': 'Szukaj',
    'Using %1': 'Używam %1',
    'Current place: %1': 'Bieżące miejsce: %1',
    'Latitude:': 'Szerokość geograficzna:',
    'Longitude:': 'Długość geograficzna:',
    'Panel (taskbar)': 'Panel (pasek zadań)',
    'Show:': 'Pokaż:',
    'Elapsed time': 'Upływ czasu',
    'Project name': 'Nazwa projektu',
    'Activity name': 'Nazwa aktywności',
    'Panel flyout': 'Menu panelu',
    'Work summary (today / week / remaining)': 'Podsumowanie pracy (dziś / tydzień / pozostało)',
    'Recent list': 'Lista ostatnich',
    'Continue last activity': 'Kontynuuj ostatnią aktywność',
    'Start / switch activity controls': 'Sterowanie startem / zmianą aktywności',
    'Desktop widget': 'Widget pulpitu',
    'New activity picker': 'Wybór nowej aktywności',
    'Behavior': 'Zachowanie',
    'Tracking:': 'Rejestrowanie:',
    'Confirm before stopping the timer': 'Potwierdź przed zatrzymaniem licznika',
    'Idle detection:': 'Wykrywanie bezczynności:',
    'Stop timer when idle': 'Zatrzymaj licznik przy bezczynności',
    'Idle threshold (minutes):': 'Próg bezczynności (minuty):',
    'Notifications:': 'Powiadomienia:',
    'Notify when tracking starts': 'Powiadom, gdy rozpocznie się rejestrowanie',
    'Notify when tracking stops': 'Powiadom, gdy zatrzyma się rejestrowanie',
    'Notify when stopped due to idle': 'Powiadom przy zatrzymaniu z powodu bezczynności',
    'Back': 'Wstecz',
    'Create a finished entry with project, activity, and time range.': 'Utwórz zakończony wpis z projektem, aktywnością i zakresem czasu.',
    'Begin': 'Początek',
    'End': 'Koniec',
    'Duration: %1': 'Czas trwania: %1',
    'Duration: —': 'Czas trwania: —',
    'Duration: invalid range': 'Czas trwania: nieprawidłowy zakres',
    'Save entry': 'Zapisz wpis',
    'All': 'Wszystkie',
    'Billable': 'Płatne',
    'Non-billable': 'Niepłatne',
    'Today': 'Dziś',
    'This week': 'Ten tydzień',
    'Time by hour': 'Czas według godzin',
    'Previous day': 'Poprzedni dzień',
    'Yesterday': 'Wczoraj',
    'Next day': 'Następny dzień',
    'No time logged this day': 'Brak zalogowanego czasu w tym dniu',
    'Projects by day': 'Projekty według dni',
    'Previous week': 'Poprzedni tydzień',
    'Next week': 'Następny tydzień',
    'No time logged this week': 'Brak zalogowanego czasu w tym tygodniu',
    'Projects by hour': 'Projekty według godzin',
    'Weekdays and weekend — segments placed by clock time.': 'Dni robocze i weekend — segmenty według godziny.',
    'Weekdays — segments placed by clock time. Weekend appears when tracked.': 'Dni robocze — segmenty według godziny. Weekend pojawia się przy śledzeniu.',
    'Axis shows business hours (%1–%2); expands if work falls outside.': 'Oś pokazuje godziny pracy (%1–%2); rozszerza się, gdy praca wypada poza.',
    'Activity distribution': 'Rozkład aktywności',
    'No activities today': 'Brak aktywności dziś',
    'No activities this week': 'Brak aktywności w tym tygodniu',
    'Time': 'Czas',
    'Pick date': 'Wybierz datę',
    'Pick time': 'Wybierz godzinę',
    'Hours : Minutes': 'Godziny : Minuty',
    'Select': 'Wybierz',
    'Clockify cloud API is prefilled. Change only for a regional endpoint (e.g. euc1).': 'API chmury Clockify jest wstępnie wypełnione. Zmień tylko dla regionalnego endpointu (np. euc1).',
    'Toggl Track cloud API is prefilled. Use your personal API token from Profile settings.': 'API chmury Toggl Track jest wstępnie wypełnione. Użyj osobistego tokenu API z ustawień profilu.',
    'SolidTime cloud API is prefilled. For self-hosting, replace with your instance base URL.': 'API chmury SolidTime jest wstępnie wypełnione. Przy self-hostingu zamień na bazowy URL swojej instancji.',
    'Self-hosted Kimai or the official hosted service (kimai.cloud). Paste the instance URL.': 'Kimai self-hosted lub oficjalna usługa hostowana (kimai.cloud). Wklej URL instancji.',
    'API URL:': 'URL API:',
    'https://api.solidtime.io or https://time.example.com': 'https://api.solidtime.io lub https://time.example.com',
    'https://kimai.example.com or https://www.kimai.cloud': 'https://kimai.example.com lub https://www.kimai.cloud',
    'API key:': 'Klucz API:',
    'Make similar colors distinctive within each category': 'Uczyń podobne kolory wyróżnialnymi w każdej kategorii',
    'Similarity threshold (%):': 'Próg podobieństwa (%):',
    'Configure a server URL on the Connection tab first.': 'Najpierw skonfiguruj URL serwera w zakładce Połączenie.',
    'Loading customers, projects, and activities…': 'Ładowanie klientów, projektów i aktywności…',
    'Color distinction is off. Enable it in Display settings to see clash groups.': 'Rozróżnianie kolorów jest wyłączone. Włącz je w Ustawieniach wyświetlania, aby zobaczyć grupy konfliktów.',
    'Loaded %1 customers, %2 projects, %3 activities. No similar colors within a category.': 'Załadowano %1 klientów, %2 projektów, %3 aktywności. Brak podobnych kolorów w kategorii.',
    'Loaded %1 customers, %2 projects, %3 activities. %4 clash group(s), %5 color(s) shifted.': 'Załadowano %1 klientów, %2 projektów, %3 aktywności. %4 grup(y) konfliktów, %5 kolor(ów) przesuniętych.',
    'Only colors that clash within a category are listed. Each group starts with the entry that kept the Kimai color; shifted variants follow. Unique colors are hidden.': 'Wyświetlane są tylko kolory konfliktujące w kategorii. Każda grupa zaczyna się od wpisu, który zachował kolor Kimai; potem warianty przesunięte. Unikalne kolory są ukryte.',
    'Reload from server': 'Przeładuj z serwera',
    'Distinction on · configured %1% · effective customers %2% / projects %3% / activities %4%': 'Rozróżnianie włączone · skonfigurowano %1% · efektywnie klienci %2% / projekty %3% / aktywności %4%',
    'Distinction off — enable it in Display settings.': 'Rozróżnianie wyłączone — włącz w Ustawieniach wyświetlania.',
    'Customers': 'Klienci',
    'No similar colors in this category.': 'Brak podobnych kolorów w tej kategorii.',
    'kept': 'zachowany',
    'shifted': 'przesunięty',
    'Maintenance': 'Konserwacja',
    'Edit': 'Edytuj',
    'Edit start, project, and activity': 'Edytuj start, projekt i aktywność',
    'Elapsed time updates from the new start.': 'Czas upływający jest przeliczany od nowego startu.',
    'Start must be a valid time not in the future.': 'Start musi być poprawną godziną i nie może być w przyszłości.',
    'This provider cannot update the running entry.': 'Ten dostawca nie może zaktualizować bieżącego wpisu.',
    'Enter a valid start date/time.': 'Podaj prawidłową datę/godzinę rozpoczęcia.',
    'Start must not be in the future.': 'Start nie może być w przyszłości.',
    'Save': 'Zapisz',
    'Current': 'Bieżąca',
    'Switch to': 'Przełącz na',
    'Could not resolve project or activity for that entry': 'Nie udało się rozpoznać projektu lub aktywności dla tego wpisu',
    'Edit start, project, activity, billable, and tags for the running entry.': 'Edytuj start, projekt, czynność, płatność i tagi bieżącego wpisu.',
    'Starts or switches this activity': 'Uruchamia lub przełącza tę czynność',
    'A profile named "%1" already exists.': 'Profil o nazwie „%1” już istnieje.',
    'Appearance': 'Wygląd',
    'Updates': 'Aktualizacje',
    'Colors': 'Kolory',
    'Distinction:': 'Rozróżnianie:',
    'Higher similarity values treat more colors as too close. Clashing items get vivid, well-spaced replacement colors. See Maintenance for clash groups.': 'Wyższe wartości podobieństwa uznają więcej kolorów za zbyt bliskie. Kolidujące elementy dostają żywe, dobrze rozłożone kolory zastępcze. Zobacz Konserwację dla grup konfliktów.',
    'Color distinction is available for Kimai profiles (per-customer / project / activity colors).': 'Rozróżnianie kolorów jest dostępne dla profili Kimai (kolory klienta / projektu / czynności).',
    'Work hours': 'Godziny pracy',
    'Used for the sparkline zoom and remaining-time in the work summary.': 'Używane do powiększenia sparklina i pozostałego czasu w podsumowaniu.',
    'Arcs:': 'Łuki:',
    'Show sun, moon, and work arcs': 'Pokaż łuki słońca, księżyca i pracy',
    'Hide the whole sparkline under Panel flyout or Desktop widget below.': 'Ukryj cały sparkline w menu panelu lub widgecie pulpitu poniżej.',
    'Find location:': 'Znajdź lokalizację:',
    'Search a place or enter coordinates for sunrise/sunset coloring. Powered by OpenStreetMap Nominatim.': 'Wyszukaj miejsce lub podaj współrzędne do kolorów wschodu/zachodu. Dzięki OpenStreetMap Nominatim.',
    'Customer color pill': 'Kropka koloru klienta',
    'Project color pill': 'Kropka koloru projektu',
    'Activities shown:': 'Pokazywane czynności:',
    'Applies to both the panel flyout and the desktop widget.': 'Dotyczy menu panelu i widgetu pulpitu.',
    'Loading projects': 'Wczytywanie projektów',
    'Color distinction is only available for Kimai profiles.': 'Rozróżnianie kolorów jest dostępne tylko dla profili Kimai.',
    'Color maintenance is for Kimai': 'Konserwacja kolorów dotyczy Kimai',
    'Clockify, Toggl, and SolidTime do not expose Kimai-style customer / project / activity colors, so clash groups and color shifting are hidden for those profiles.': 'Clockify, Toggl i SolidTime nie udostępniają kolorów klienta / projektu / czynności jak Kimai, więc grupy konfliktów i przesunięcia kolorów są ukryte dla tych profili.',
    'Select customer…': 'Wybierz klienta…',
    'Today\'s tracked time': 'Czas zarejestrowany dzisiaj',
    'This provider cannot update descriptions.': 'Ten serwis nie może aktualizować opisów.',
    'Open or close the Plasmai popup': 'Otwórz lub zamknij wyskakujące okno Plasmai',
    'Add tag…': 'Dodaj tag…',
    'Add tags…': 'Dodaj tagi…',
    'Tags': 'Tagi',
    'Loading tags…': 'Wczytywanie tagów…',
    'No tags on the server yet.': 'Na serwerze nie ma jeszcze tagów.',
    'Create tag “%1”': 'Utwórz tag „%1”',
    'Already running.': 'Już trwa.',
    'Entry actions': 'Akcje wpisu',
    'Edit entry': 'Edytuj wpis',
    'Split entry': 'Podziel wpis',
    'Delete entry': 'Usuń wpis',
    'Idle detection uses the session idle hint on Wayland (loginctl / ScreenSaver) and xprintidle on X11.': 'Wykrywanie bezczynności używa wskazówki sesji na Wayland (loginctl / ScreenSaver) i xprintidle na X11.',
    'Remind me once if nothing is tracking during work hours': 'Przypomnij raz, jeśli w godzinach pracy nic nie jest śledzone',
    'Idle time discarded': 'Czas bezczynności odrzucony',
    'Nothing is tracking': 'Nic nie jest śledzone',
    'Work hours have started. Start a timer when you begin.': 'Godziny pracy się zaczęły. Uruchom timer, gdy zaczniesz.',
    'Customer created': 'Utworzono klienta',
    'Project created': 'Utworzono projekt',
    'Activity created': 'Utworzono czynność',
    'Entry updated': 'Zaktualizowano wpis',
    'Timesheet updated': 'Zaktualizowano timesheet',
    'This provider cannot update stopped entries.': 'Ten serwis nie może aktualizować zatrzymanych wpisów.',
    'Tracking in progress': 'Śledzenie w toku',
    'This provider cannot delete entries.': 'Ten serwis nie może usuwać wpisów.',
    'Entry deleted': 'Usunięto wpis',
    'Split time must be between begin and end.': 'Czas podziału musi być między początkiem a końcem.',
    'This provider cannot split entries.': 'Ten serwis nie może dzielić wpisów.',
    'Entry split': 'Podzielono wpis',
    'The first half was saved, but the second half could not be created.': 'Pierwsza połowa została zapisana, ale drugiej nie udało się utworzyć.',
    'Delete entry?': 'Usunąć wpis?',
    'Delete this finished entry? This cannot be undone.': 'Usunąć ten zakończony wpis? Tego nie można cofnąć.',
    'Delete "%1 · %2"? This cannot be undone.': 'Usunąć „%1 · %2”? Tego nie można cofnąć.',
    'The first half keeps the original start. The second half starts at the split time.': 'Pierwsza połowa zachowuje oryginalny start. Druga zaczyna się w chwili podziału.',
    'Split at': 'Podziel o',
    'Both halves will have a positive duration.': 'Obie połowy będą miały dodatni czas trwania.',
    'You were idle': 'Byłeś bezczynny',
    'Keep the time, discard the idle gap, or discard and continue the same activity.': 'Zachowaj czas, odrzuć lukę bezczynności albo odrzuć i kontynuuj tę samą czynność.',
    'Keep time': 'Zachowaj czas',
    'Discard idle': 'Odrzuć bezczynność',
    'Discard and continue': 'Odrzuć i kontynuuj',
    'Start · %1 · %2': 'Start · %1 · %2',
    'Change project, activity, range, billable, and tags for this finished entry.': 'Zmień projekt, czynność, zakres, płatność i tagi tego zakończonego wpisu.',
    'Save changes': 'Zapisz zmiany',
    'Create customer': 'Utwórz klienta',
    'Create activity': 'Utwórz czynność',
    'Create project': 'Utwórz projekt',
    'Activity will be added to %1.': 'Czynność zostanie dodana do %1.',
    'Name': 'Nazwa',
    'Customer': 'Klient',
}

PLURALS = {
    '%1 minute ago': ['%1 minutę temu', '%1 minuty temu', '%1 minut temu'],
    '%1 hour ago': ['%1 godzinę temu', '%1 godziny temu', '%1 godzin temu'],
    '%1 day ago': ['%1 dzień temu', '%1 dni temu', '%1 dni temu'],
    '%1 place found.': ['Znaleziono %1 miejsce.', 'Znaleziono %1 miejsca.', 'Znaleziono %1 miejsc.'],
}
