# -*- coding: utf-8 -*-
T = {
    'Project-specific': 'Específico do projeto',
    'Global activities': 'Atividades globais',
    'Plasmai': 'Plasmai',
    'Loading…': 'Carregando…',
    'Not configured — right-click to configure': 'Não configurado — clique com o botão direito para configurar',
    'just now': 'agora mesmo',
    'yesterday': 'ontem',
    'Not configured': 'Não configurado',
    'Connecting to %1…': 'Conectando a %1…',
    'Connection problem': 'Problema de conexão',
    'Connected to %1 (%2)': 'Conectado a %1 (%2)',
    'Connected to %1': 'Conectado a %1',
    'Enter valid begin and end date/time.': 'Informe data/hora de início e fim válidas.',
    'End must be after begin.': 'O fim deve ser posterior ao início.',
    'Entry added': 'Registro adicionado',
    'Manual time entry': 'Registro manual de tempo',
    '%1 left today': '%1 restantes hoje',
    '%1 over today': '%1 a mais hoje',
    '%1 left this week': '%1 restantes nesta semana',
    '%1 over this week': '%1 a mais nesta semana',
    'Today %1': 'Hoje %1',
    'Week %1': 'Semana %1',
    'Tracking started': 'Registro iniciado',
    'Switched activity': 'Atividade alterada',
    'Tracking stopped (idle)': 'Registro parado (inativo)',
    'Tracking stopped': 'Registro parado',
    'Stop tracking?': 'Parar registro?',
    'Stop tracking %1 · %2?': 'Parar registro de %1 · %2?',
    'Statistics': 'Estatísticas',
    'Add entry': 'Adicionar registro',
    'Add a manual time entry': 'Adicionar registro manual de tempo',
    'Show statistics': 'Mostrar estatísticas',
    'Back to timer': 'Voltar ao cronômetro',
    'Connect a time tracker': 'Conectar um serviço de registro de tempo',
    'Add your service, server URL (if needed), and API token to start tracking from the panel.': 'Adicione seu serviço, URL do servidor (se necessário) e token de API para iniciar o registro pelo painel.',
    'Configure Plasmai': 'Configurar Plasmai',
    'Retry': 'Tentar novamente',
    'Configure': 'Configurar',
    'Not tracking': 'Sem registro ativo',
    'Description': 'Descrição',
    'Save description': 'Salvar descrição',
    'Stop': 'Parar',
    'Continue · %1 · %2': 'Continuar · %1 · %2',
    'Favorites': 'Favoritos',
    'No favorites yet': 'Nenhum favorito ainda',
    'Pin frequent project/activity pairs in the widget settings.': 'Fixe pares frequentes de projeto/atividade nas configurações do widget.',
    'Configure favorites': 'Configurar favoritos',
    '+%1 more in settings': '+%1 a mais nas configurações',
    'Recent': 'Recentes',
    'No recent activities': 'Nenhuma atividade recente',
    'Start tracking to build your recent list.': 'Inicie o registro para montar sua lista de recentes.',
    'Switch to another activity…': 'Mudar para outra atividade…',
    'Start something else…': 'Iniciar outra coisa…',
    'Switch activity': 'Mudar atividade',
    'New activity': 'Nova atividade',
    'Select project…': 'Selecionar projeto…',
    'Select activity…': 'Selecionar atividade…',
    'Description (optional)': 'Descrição (opcional)',
    'Start': 'Iniciar',
    'Switch': 'Mudar',
    'Cancel': 'Cancelar',
    'Unknown error': 'Erro desconhecido',
    'URL and API token are required': 'URL e token de API são obrigatórios',
    'Configure your time tracker URL and API token': 'Configure a URL e o token de API do seu serviço de registro de tempo',
    'This action is not supported for the selected service yet.': 'Esta ação ainda não é suportada para o serviço selecionado.',
    'Cannot reach the server. Check your network, URL, or TLS certificate.': 'Não foi possível alcançar o servidor. Verifique sua rede, URL ou certificado TLS.',
    'Authentication failed. Check your API token.': 'Falha na autenticação. Verifique seu token de API.',
    'Server not found. Check your URL.': 'Servidor não encontrado. Verifique sua URL.',
    'Access denied. Your token may lack required permissions.': 'Acesso negado. Seu token pode não ter as permissões necessárias.',
    'Server error (%1).': 'Erro do servidor (%1).',
    'Request failed: %1': 'Falha na requisição: %1',
    'Request failed (%1).': 'Falha na requisição (%1).',
    'Connection': 'Conexão',
    'Configure a time-tracking profile. Choose Kimai, Clockify, Toggl Track, or SolidTime.': 'Configure um perfil de registro de tempo. Escolha Kimai, Clockify, Toggl Track ou SolidTime.',
    'Profile:': 'Perfil:',
    'Profile name:': 'Nome do perfil:',
    'Service:': 'Serviço:',
    'Server URL:': 'URL do servidor:',
    'API token:': 'Token de API:',
    'Paste token to save in KWallet': 'Cole o token para salvar no KWallet',
    'Add profile': 'Adicionar perfil',
    'Profile %1': 'Perfil %1',
    'Remove': 'Remover',
    'Use this profile': 'Usar este perfil',
    'none': 'nenhum',
    'Active profile: %1': 'Perfil ativo: %1',
    'Saving…': 'Salvando…',
    'Save token': 'Salvar token',
    'Token saved to KWallet for this profile.': 'Token salvo no KWallet para este perfil.',
    'Failed to save token': 'Falha ao salvar token',
    'Clear token': 'Limpar token',
    'Token removed from KWallet.': 'Token removido do KWallet.',
    'Failed to clear token': 'Falha ao limpar token',
    'Test connection': 'Testar conexão',
    'Testing connection…': 'Testando conexão…',
    'No API token stored. Save a token first.': 'Nenhum token de API armazenado. Salve um token primeiro.',
    'ok': 'ok',
    'Connected to %1 (%2).': 'Conectado a %1 (%2).',
    'Configure a Kimai URL on the Connection tab first.': 'Configure primeiro uma URL do Kimai na aba Conexão.',
    'Loading projects…': 'Carregando projetos…',
    'Save an API token on the Connection tab first.': 'Salve primeiro um token de API na aba Conexão.',
    'Loaded %1 projects.': '%1 projetos carregados.',
    'Select a project to pin activities.': 'Selecione um projeto para fixar atividades.',
    'Failed to load projects.': 'Falha ao carregar projetos.',
    'Loading activities…': 'Carregando atividades…',
    'No API token available.': 'Nenhum token de API disponível.',
    '%1 project-specific, %2 global': '%1 específicos do projeto, %2 globais',
    'Failed to load activities.': 'Falha ao carregar atividades.',
    'Projects': 'Projetos',
    'Reload': 'Recarregar',
    'Activities — %1': 'Atividades — %1',
    'Activities': 'Atividades',
    'Enter a city or place name to search.': 'Digite o nome de uma cidade ou local para buscar.',
    'Searching…': 'Buscando…',
    'Location search failed. Check your network connection.': 'Falha na busca de localização. Verifique sua conexão de rede.',
    'No places found.': 'Nenhum local encontrado.',
    'Display': 'Exibição',
    'Refresh interval (seconds):': 'Intervalo de atualização (segundos):',
    'Touch optimization:': 'Otimização para toque:',
    'Automatic (follow Plasma tablet mode)': 'Automático (seguir o modo tablet do Plasma)',
    'On': 'Ativado',
    'Off': 'Desativado',
    'Larger tap targets for buttons, lists, pickers, and date/time controls.': 'Alvos de toque maiores para botões, listas, seletores e data/hora.',
    'Usual work day start:': 'Início do dia de trabalho habitual:',
    'Usual work day end:': 'Fim do dia de trabalho habitual:',
    'Day sparkline': 'Minigráfico do dia',
    'City, region, or address…': 'Cidade, região ou endereço…',
    'Search': 'Buscar',
    'Using %1': 'Usando %1',
    'Current place: %1': 'Local atual: %1',
    'Latitude:': 'Latitude:',
    'Longitude:': 'Longitude:',
    'Panel (taskbar)': 'Painel (barra de tarefas)',
    'Show:': 'Mostrar:',
    'Elapsed time': 'Tempo decorrido',
    'Project name': 'Nome do projeto',
    'Activity name': 'Nome da atividade',
    'Panel flyout': 'Menu do painel',
    'Work summary (today / week / remaining)': 'Resumo de trabalho (hoje / semana / restante)',
    'Recent list': 'Lista de recentes',
    'Continue last activity': 'Continuar última atividade',
    'Start / switch activity controls': 'Controles para iniciar / mudar atividade',
    'Desktop widget': 'Widget da área de trabalho',
    'New activity picker': 'Seletor de nova atividade',
    'Behavior': 'Comportamento',
    'Tracking:': 'Registro:',
    'Confirm before stopping the timer': 'Confirmar antes de parar o cronômetro',
    'Ask before a start that overlaps the previous entry': 'Perguntar se o início sobrepõe a entrada anterior',
    'When editing the running timer, the previous entry’s end is shown. Saving an earlier start asks for confirmation.': 'Ao editar o cronômetro em andamento, o fim da última entrada parada é mostrado. Salvar um início anterior pede confirmação.',
    'Previous entry ended at %1': 'A entrada anterior terminou às %1',
    'Overlapping start': 'Início sobreposto',
    'The new start is before the previous entry ended (%1). Set it anyway?': 'O novo início é anterior ao fim da entrada anterior (%1). Definir mesmo assim?',
    'Set anyway': 'Definir mesmo assim',
    'Idle detection:': 'Detecção de inatividade:',
    'Stop timer when idle': 'Parar cronômetro quando inativo',
    'Idle threshold (minutes):': 'Limite de inatividade (minutos):',
    'Notifications:': 'Notificações:',
    'Notify when tracking starts': 'Notificar quando o registro iniciar',
    'Notify when tracking stops': 'Notificar quando o registro parar',
    'Notify when stopped due to idle': 'Notificar quando parar por inatividade',
    'Back': 'Voltar',
    'Create a finished entry with project, activity, and time range.': 'Criar um lançamento concluído com projeto, atividade e intervalo de tempo.',
    'Begin': 'Início',
    'End': 'Fim',
    'Duration: %1': 'Duração: %1',
    'Duration: —': 'Duração: —',
    'Duration: invalid range': 'Duração: intervalo inválido',
    'Save entry': 'Salvar lançamento',
    'All': 'Todos',
    'Billable': 'Faturável',
    'Non-billable': 'Não faturável',
    'Today': 'Hoje',
    'This week': 'Esta semana',
    'Time by hour': 'Tempo por hora',
    'Previous day': 'Dia anterior',
    'Yesterday': 'Ontem',
    'Next day': 'Próximo dia',
    'No time logged this day': 'Nenhum tempo registrado neste dia',
    'Projects by day': 'Projetos por dia',
    'Previous week': 'Semana anterior',
    'Next week': 'Próxima semana',
    'No time logged this week': 'Nenhum tempo registrado nesta semana',
    'Projects by hour': 'Projetos por hora',
    'Weekdays and weekend — segments placed by clock time.': 'Dias úteis e fim de semana — segmentos pela hora do relógio.',
    'Weekdays — segments placed by clock time. Weekend appears when tracked.': 'Dias úteis — segmentos pela hora. O fim de semana aparece quando houver registro.',
    'Axis shows business hours (%1–%2); expands if work falls outside.': 'O eixo mostra o horário comercial (%1–%2); expande se o trabalho ficar fora.',
    'Activity distribution': 'Distribuição de atividades',
    'No activities today': 'Nenhuma atividade hoje',
    'No activities this week': 'Nenhuma atividade nesta semana',
    'Time': 'Tempo',
    'Pick date': 'Escolher data',
    'Pick time': 'Escolher hora',
    'Hours : Minutes': 'Horas : Minutos',
    'Select': 'Selecionar',
    'Clockify cloud API is prefilled. Change only for a regional endpoint (e.g. euc1).': 'A API em nuvem do Clockify já está preenchida. Altere apenas para um endpoint regional (ex.: euc1).',
    'Toggl Track cloud API is prefilled. Use your personal API token from Profile settings.': 'A API em nuvem do Toggl Track já está preenchida. Use seu token de API pessoal nas configurações do perfil.',
    'SolidTime cloud API is prefilled. For self-hosting, replace with your instance base URL.': 'A API em nuvem do SolidTime já está preenchida. Em auto-hospedagem, substitua pela URL base da sua instância.',
    'Self-hosted Kimai or the official hosted service (kimai.cloud). Paste the instance URL.': 'Kimai auto-hospedado ou o serviço oficial hospedado (kimai.cloud). Cole a URL da instância.',
    'API URL:': 'URL da API:',
    'https://api.solidtime.io or https://time.example.com': 'https://api.solidtime.io ou https://time.example.com',
    'https://kimai.example.com or https://www.kimai.cloud': 'https://kimai.example.com ou https://www.kimai.cloud',
    'API key:': 'Chave de API:',
    'Make similar colors distinctive within each category': 'Tornar cores semelhantes distintivas em cada categoria',
    'Similarity threshold (%):': 'Limite de similaridade (%):',
    'Configure a server URL on the Connection tab first.': 'Configure primeiro uma URL de servidor na aba Conexão.',
    'Loading customers, projects, and activities…': 'Carregando clientes, projetos e atividades…',
    'Color distinction is off. Enable it in Display settings to see clash groups.': 'A distinção de cores está desligada. Ative-a em Exibição para ver grupos de conflito.',
    'Loaded %1 customers, %2 projects, %3 activities. No similar colors within a category.': 'Carregados %1 clientes, %2 projetos, %3 atividades. Nenhuma cor semelhante em uma categoria.',
    'Loaded %1 customers, %2 projects, %3 activities. %4 clash group(s), %5 color(s) shifted.': 'Carregados %1 clientes, %2 projetos, %3 atividades. %4 grupo(s) de conflito, %5 cor(es) deslocada(s).',
    'Only colors that clash within a category are listed. Each group starts with the entry that kept the Kimai color; shifted variants follow. Unique colors are hidden.': 'Só são listadas cores que conflitam em uma categoria. Cada grupo começa com a entrada que manteve a cor do Kimai; seguem as variantes deslocadas. Cores únicas ficam ocultas.',
    'Reload from server': 'Recarregar do servidor',
    'Distinction on · configured %1% · effective customers %2% / projects %3% / activities %4%': 'Distinção ligada · configurado %1% · efetivo clientes %2% / projetos %3% / atividades %4%',
    'Distinction off — enable it in Display settings.': 'Distinção desligada — ative em Exibição.',
    'Customers': 'Clientes',
    'No similar colors in this category.': 'Nenhuma cor semelhante nesta categoria.',
    'kept': 'mantido',
    'shifted': 'deslocado',
    'Maintenance': 'Manutenção',
    'Edit': 'Editar',
    'Edit start, project, and activity': 'Editar início, projeto e atividade',
    'Elapsed time updates from the new start.': 'O tempo decorrido é atualizado a partir do novo início.',
    'Start must be a valid time not in the future.': 'O início deve ser um horário válido e não pode estar no futuro.',
    'This provider cannot update the running entry.': 'Este provedor não pode atualizar a entrada em andamento.',
    'Enter a valid start date/time.': 'Informe uma data/hora de início válida.',
    'Start must not be in the future.': 'O início não pode estar no futuro.',
    'Save': 'Salvar',
    'Current': 'Atual',
    'Switch to': 'Mudar para',
    'Could not resolve project or activity for that entry': 'Não foi possível resolver o projeto ou a atividade dessa entrada',
    'Edit start, project, activity, billable, and tags for the running entry.': 'Editar início, projeto, atividade, faturável e tags da entrada em andamento.',
    'Starts or switches this activity': 'Inicia ou troca para esta atividade',
    'A profile named "%1" already exists.': 'Já existe um perfil chamado "%1".',
    'Appearance': 'Aparência',
    'Updates': 'Atualizações',
    'Colors': 'Cores',
    'Distinction:': 'Distinção:',
    'Higher similarity values treat more colors as too close. Clashing items get vivid, well-spaced replacement colors. See Maintenance for clash groups.': 'Valores de similaridade mais altos tratam mais cores como próximas demais. Itens em conflito recebem cores de substituição vivas e bem espaçadas. Veja Manutenção para os grupos de conflito.',
    'Color distinction is available for Kimai profiles (per-customer / project / activity colors).': 'A distinção de cores está disponível para perfis Kimai (cores por cliente / projeto / atividade).',
    'Work hours': 'Horário de trabalho',
    'Used for the sparkline zoom and remaining-time in the work summary.': 'Usado no zoom da sparkline e no tempo restante do resumo.',
    'Arcs:': 'Arcos:',
    'Show sun, moon, and work arcs': 'Mostrar arcos do sol, da lua e do trabalho',
    'Hide the whole sparkline under Panel flyout or Desktop widget below.': 'Ocultar toda a sparkline no menu do painel ou no widget da área de trabalho abaixo.',
    'Find location:': 'Localizar lugar:',
    'Search a place or enter coordinates for sunrise/sunset coloring. Powered by OpenStreetMap Nominatim.': 'Pesquise um lugar ou informe coordenadas para as cores de nascer/pôr do sol. Powered by OpenStreetMap Nominatim.',
    'Customer color pill': 'Pílula de cor do cliente',
    'Project color pill': 'Pílula de cor do projeto',
    'Activities shown:': 'Atividades exibidas:',
    'Applies to both the panel flyout and the desktop widget.': 'Vale para o menu do painel e o widget da área de trabalho.',
    'Loading projects': 'Carregando projetos',
    'Color distinction is only available for Kimai profiles.': 'A distinção de cores só está disponível para perfis Kimai.',
    'Color maintenance is for Kimai': 'A manutenção de cores é para o Kimai',
    'Clockify, Toggl, and SolidTime do not expose Kimai-style customer / project / activity colors, so clash groups and color shifting are hidden for those profiles.': 'Clockify, Toggl e SolidTime não expõem cores de cliente / projeto / atividade no estilo Kimai, então grupos de conflito e deslocamento de cor ficam ocultos nesses perfis.',
    'Select customer…': 'Selecionar cliente…',
    'Today\'s tracked time': 'Tempo registrado hoje',
    'This provider cannot update descriptions.': 'Este serviço não pode atualizar descrições.',
    'Open or close the Plasmai popup': 'Abrir ou fechar o menu do Plasmai',
    'Add tag…': 'Adicionar tag…',
    'Add tags…': 'Adicionar tags…',
    'Tags': 'Tags',
    'Loading tags…': 'Carregando tags…',
    'No tags on the server yet.': 'Ainda não há tags no servidor.',
    'Create tag “%1”': 'Criar tag “%1”',
    'Already running.': 'Já em andamento.',
    'Entry actions': 'Ações da entrada',
    'Edit entry': 'Editar entrada',
    'Split entry': 'Dividir entrada',
    'Delete entry': 'Excluir entrada',
    'Idle detection uses the session idle hint on Wayland (loginctl / ScreenSaver) and xprintidle on X11.': 'A detecção de ociosidade usa o aviso de ociosidade da sessão no Wayland (loginctl / ScreenSaver) e o xprintidle no X11.',
    'Remind me once if nothing is tracking during work hours': 'Lembrar uma vez se nada estiver em registro no horário de trabalho',
    'Idle time discarded': 'Tempo ocioso descartado',
    'Nothing is tracking': 'Nada está em registro',
    'Work hours have started. Start a timer when you begin.': 'O horário de trabalho começou. Inicie um temporizador quando começar.',
    'Customer created': 'Cliente criado',
    'Project created': 'Projeto criado',
    'Activity created': 'Atividade criada',
    'Entry updated': 'Entrada atualizada',
    'Timesheet updated': 'Timesheet atualizado',
    'This provider cannot update stopped entries.': 'Este serviço não pode atualizar entradas encerradas.',
    'Tracking in progress': 'Registro em andamento',
    'This provider cannot delete entries.': 'Este serviço não pode excluir entradas.',
    'Entry deleted': 'Entrada excluída',
    'Split time must be between begin and end.': 'O horário da divisão deve estar entre o início e o fim.',
    'This provider cannot split entries.': 'Este serviço não pode dividir entradas.',
    'Entry split': 'Entrada dividida',
    'The first half was saved, but the second half could not be created.': 'A primeira metade foi salva, mas a segunda não pôde ser criada.',
    'Delete entry?': 'Excluir entrada?',
    'Delete this finished entry? This cannot be undone.': 'Excluir esta entrada encerrada? Isto não pode ser desfeito.',
    'Delete "%1 · %2"? This cannot be undone.': 'Excluir "%1 · %2"? Isto não pode ser desfeito.',
    'The first half keeps the original start. The second half starts at the split time.': 'A primeira metade mantém o início original. A segunda começa no horário da divisão.',
    'Split at': 'Dividir em',
    'Both halves will have a positive duration.': 'Ambas as metades terão duração positiva.',
    'You were idle': 'Você estava ocioso',
    'Keep the time, discard the idle gap, or discard and continue the same activity.': 'Manter o tempo, descartar o intervalo ocioso, ou descartar e continuar a mesma atividade.',
    'Keep time': 'Manter o tempo',
    'Discard idle': 'Descartar ociosidade',
    'Discard and continue': 'Descartar e continuar',
    'Start · %1 · %2': 'Iniciar · %1 · %2',
    'Change project, activity, range, billable, and tags for this finished entry.': 'Alterar projeto, atividade, intervalo, faturável e tags desta entrada encerrada.',
    'Save changes': 'Salvar alterações',
    'Create customer': 'Criar cliente',
    'Create activity': 'Criar atividade',
    'Create project': 'Criar projeto',
    'Activity will be added to %1.': 'A atividade será adicionada a %1.',
    'Name': 'Nome',
    'Customer': 'Cliente',
}

PLURALS = {
    '%1 minute ago': ['há %1 minuto', 'há %1 minutos'],
    '%1 hour ago': ['há %1 hora', 'há %1 horas'],
    '%1 day ago': ['há %1 dia', 'há %1 dias'],
    '%1 place found.': ['%1 local encontrado.', '%1 locais encontrados.'],
}
