# -*- coding: utf-8 -*-
T = {
    'Project-specific': 'Специфичные для проекта',
    'Global activities': 'Глобальные активности',
    'Plasmai': 'Plasmai',
    'Loading…': 'Загрузка…',
    'Not configured — right-click to configure': 'Не настроено — щёлкните правой кнопкой для настройки',
    'just now': 'только что',
    'yesterday': 'вчера',
    'Not configured': 'Не настроено',
    'Connecting to %1…': 'Подключение к %1…',
    'Connection problem': 'Проблема соединения',
    'Connected to %1 (%2)': 'Подключено к %1 (%2)',
    'Connected to %1': 'Подключено к %1',
    'Enter valid begin and end date/time.': 'Введите корректные дату и время начала и окончания.',
    'End must be after begin.': 'Окончание должно быть позже начала.',
    'Entry added': 'Запись добавлена',
    'Manual time entry': 'Ручная запись времени',
    '%1 left today': 'Сегодня осталось %1',
    '%1 over today': 'Сегодня переработка %1',
    '%1 left this week': 'На этой неделе осталось %1',
    '%1 over this week': 'На этой неделе переработка %1',
    'Today %1': 'Сегодня %1',
    'Week %1': 'Неделя %1',
    'Tracking started': 'Отслеживание начато',
    'Switched activity': 'Активность изменена',
    'Tracking stopped (idle)': 'Отслеживание остановлено (бездействие)',
    'Tracking stopped': 'Отслеживание остановлено',
    'Stop tracking?': 'Остановить отслеживание?',
    'Stop tracking %1 · %2?': 'Остановить отслеживание %1 · %2?',
    'Statistics': 'Статистика',
    'Add entry': 'Добавить запись',
    'Add a manual time entry': 'Добавить ручную запись времени',
    'Show statistics': 'Показать статистику',
    'Back to timer': 'Назад к таймеру',
    'Connect a time tracker': 'Подключить учёт времени',
    'Add your service, server URL (if needed), and API token to start tracking from the panel.': 'Добавьте сервис, URL сервера (при необходимости) и API-токен, чтобы начать отслеживание с панели.',
    'Configure Plasmai': 'Настроить Plasmai',
    'Retry': 'Повторить',
    'Configure': 'Настроить',
    'Not tracking': 'Не отслеживается',
    'Description': 'Описание',
    'Save description': 'Сохранить описание',
    'Stop': 'Остановить',
    'Continue · %1 · %2': 'Продолжить · %1 · %2',
    'Favorites': 'Избранное',
    'No favorites yet': 'Пока нет избранного',
    'Pin frequent project/activity pairs in the widget settings.': 'Закрепите частые пары проект/активность в настройках виджета.',
    'Configure favorites': 'Настроить избранное',
    '+%1 more in settings': '+%1 ещё в настройках',
    'Recent': 'Недавние',
    'No recent activities': 'Нет недавних активностей',
    'Start tracking to build your recent list.': 'Начните отслеживание, чтобы сформировать список недавних.',
    'Switch to another activity…': 'Переключиться на другую активность…',
    'Start something else…': 'Начать что-то другое…',
    'Switch activity': 'Сменить активность',
    'New activity': 'Новая активность',
    'Select project…': 'Выберите проект…',
    'Select activity…': 'Выберите активность…',
    'Description (optional)': 'Описание (необязательно)',
    'Start': 'Начать',
    'Switch': 'Сменить',
    'Cancel': 'Отмена',
    'Unknown error': 'Неизвестная ошибка',
    'URL and API token are required': 'Требуются URL и API-токен',
    'Configure your time tracker URL and API token': 'Настройте URL и API-токен учёта времени',
    'This action is not supported for the selected service yet.': 'Это действие пока не поддерживается для выбранного сервиса.',
    'Cannot reach the server. Check your network, URL, or TLS certificate.': 'Не удаётся связаться с сервером. Проверьте сеть, URL или TLS-сертификат.',
    'Authentication failed. Check your API token.': 'Ошибка аутентификации. Проверьте API-токен.',
    'Server not found. Check your URL.': 'Сервер не найден. Проверьте URL.',
    'Access denied. Your token may lack required permissions.': 'Доступ запрещён. Возможно, у вашего токена нет нужных прав.',
    'Server error (%1).': 'Ошибка сервера (%1).',
    'Request failed: %1': 'Запрос не выполнен: %1',
    'Request failed (%1).': 'Запрос не выполнен (%1).',
    'Connection': 'Подключение',
    'Configure a time-tracking profile. Choose Kimai, Clockify, Toggl Track, or SolidTime.': 'Настройте профиль учёта времени. Выберите Kimai, Clockify, Toggl Track или SolidTime.',
    'Profile:': 'Профиль:',
    'Profile name:': 'Имя профиля:',
    'Service:': 'Сервис:',
    'Server URL:': 'URL сервера:',
    'API token:': 'API-токен:',
    'Paste token to save in KWallet': 'Вставьте токен для сохранения в KWallet',
    'Add profile': 'Добавить профиль',
    'Profile %1': 'Профиль %1',
    'Remove': 'Удалить',
    'Use this profile': 'Использовать этот профиль',
    'none': 'нет',
    'Active profile: %1': 'Активный профиль: %1',
    'Saving…': 'Сохранение…',
    'Save token': 'Сохранить токен',
    'Token saved to KWallet for this profile.': 'Токен сохранён в KWallet для этого профиля.',
    'Failed to save token': 'Не удалось сохранить токен',
    'Clear token': 'Очистить токен',
    'Token removed from KWallet.': 'Токен удалён из KWallet.',
    'Failed to clear token': 'Не удалось очистить токен',
    'Test connection': 'Проверить соединение',
    'Testing connection…': 'Проверка соединения…',
    'No API token stored. Save a token first.': 'API-токен не сохранён. Сначала сохраните токен.',
    'ok': 'ok',
    'Connected to %1 (%2).': 'Подключено к %1 (%2).',
    'Configure a Kimai URL on the Connection tab first.': 'Сначала настройте URL Kimai на вкладке «Подключение».',
    'Loading projects…': 'Загрузка проектов…',
    'Save an API token on the Connection tab first.': 'Сначала сохраните API-токен на вкладке «Подключение».',
    'Loaded %1 projects.': 'Загружено проектов: %1.',
    'Select a project to pin activities.': 'Выберите проект, чтобы закрепить активности.',
    'Failed to load projects.': 'Не удалось загрузить проекты.',
    'Loading activities…': 'Загрузка активностей…',
    'No API token available.': 'API-токен недоступен.',
    '%1 project-specific, %2 global': '%1 для проекта, %2 глобальных',
    'Failed to load activities.': 'Не удалось загрузить активности.',
    'Projects': 'Проекты',
    'Reload': 'Обновить',
    'Activities — %1': 'Активности — %1',
    'Activities': 'Активности',
    'Enter a city or place name to search.': 'Введите название города или места для поиска.',
    'Searching…': 'Поиск…',
    'Location search failed. Check your network connection.': 'Поиск места не удался. Проверьте сетевое соединение.',
    'No places found.': 'Мест не найдено.',
    'Display': 'Отображение',
    'Refresh interval (seconds):': 'Интервал обновления (секунды):',
    'Touch optimization:': 'Оптимизация для касаний:',
    'Automatic (follow Plasma tablet mode)': 'Автоматически (режим планшета Plasma)',
    'On': 'Вкл.',
    'Off': 'Выкл.',
    'Larger tap targets for buttons, lists, pickers, and date/time controls.': 'Увеличенные области касания для кнопок, списков, выбора и даты/времени.',
    'Usual work day start:': 'Начало рабочего дня:',
    'Usual work day end:': 'Конец рабочего дня:',
    'Day sparkline': 'Дневная диаграмма',
    'City, region, or address…': 'Город, регион или адрес…',
    'Search': 'Поиск',
    'Using %1': 'Используется %1',
    'Current place: %1': 'Текущее место: %1',
    'Latitude:': 'Широта:',
    'Longitude:': 'Долгота:',
    'Panel (taskbar)': 'Панель (панель задач)',
    'Show:': 'Показывать:',
    'Elapsed time': 'Прошедшее время',
    'Project name': 'Название проекта',
    'Activity name': 'Название активности',
    'Panel flyout': 'Всплывающее окно панели',
    'Work summary (today / week / remaining)': 'Сводка работы (сегодня / неделя / осталось)',
    'Recent list': 'Список недавних',
    'Continue last activity': 'Продолжить последнюю активность',
    'Start / switch activity controls': 'Управление запуском / сменой активности',
    'Desktop widget': 'Виджет рабочего стола',
    'New activity picker': 'Выбор новой активности',
    'Behavior': 'Поведение',
    'Tracking:': 'Отслеживание:',
    'Confirm before stopping the timer': 'Подтверждать перед остановкой таймера',
    'Idle detection:': 'Обнаружение бездействия:',
    'Stop timer when idle': 'Останавливать таймер при бездействии',
    'Idle threshold (minutes):': 'Порог бездействия (минуты):',
    'Notifications:': 'Уведомления:',
    'Notify when tracking starts': 'Уведомлять о начале отслеживания',
    'Notify when tracking stops': 'Уведомлять об остановке отслеживания',
    'Notify when stopped due to idle': 'Уведомлять об остановке из-за бездействия',
    'Back': 'Назад',
    'Create a finished entry with project, activity, and time range.': 'Создать завершённую запись с проектом, активностью и диапазоном времени.',
    'Begin': 'Начало',
    'End': 'Конец',
    'Duration: %1': 'Длительность: %1',
    'Duration: —': 'Длительность: —',
    'Duration: invalid range': 'Длительность: недопустимый диапазон',
    'Save entry': 'Сохранить запись',
    'All': 'Все',
    'Billable': 'Оплачиваемые',
    'Non-billable': 'Неоплачиваемые',
    'Today': 'Сегодня',
    'This week': 'На этой неделе',
    'Time by hour': 'Время по часам',
    'Previous day': 'Предыдущий день',
    'Yesterday': 'Вчера',
    'Next day': 'Следующий день',
    'No time logged this day': 'В этот день время не записано',
    'Projects by day': 'Проекты по дням',
    'Previous week': 'Предыдущая неделя',
    'Next week': 'Следующая неделя',
    'No time logged this week': 'На этой неделе время не записано',
    'Projects by hour': 'Проекты по часам',
    'Weekdays and weekend — segments placed by clock time.': 'Будни и выходные — сегменты по времени суток.',
    'Weekdays — segments placed by clock time. Weekend appears when tracked.': 'Будни — сегменты по времени. Выходные появляются при наличии записей.',
    'Axis shows business hours (%1–%2); expands if work falls outside.': 'Ось показывает рабочие часы (%1–%2); расширяется, если работа вне диапазона.',
    'Activity distribution': 'Распределение активностей',
    'No activities today': 'Сегодня нет активностей',
    'No activities this week': 'На этой неделе нет активностей',
    'Time': 'Время',
    'Pick date': 'Выбрать дату',
    'Pick time': 'Выбрать время',
    'Hours : Minutes': 'Часы : Минуты',
    'Select': 'Выбрать',
    'Clockify cloud API is prefilled. Change only for a regional endpoint (e.g. euc1).': 'Облачный API Clockify уже заполнен. Меняйте только для региональной конечной точки (напр. euc1).',
    'Toggl Track cloud API is prefilled. Use your personal API token from Profile settings.': 'Облачный API Toggl Track уже заполнен. Используйте личный API-токен из настроек профиля.',
    'SolidTime cloud API is prefilled. For self-hosting, replace with your instance base URL.': 'Облачный API SolidTime уже заполнен. При самостоятельном хостинге замените на базовый URL вашего экземпляра.',
    'Self-hosted Kimai or the official hosted service (kimai.cloud). Paste the instance URL.': 'Самостоятельно размещённый Kimai или официальный хостинг (kimai.cloud). Вставьте URL экземпляра.',
    'API URL:': 'URL API:',
    'https://api.solidtime.io or https://time.example.com': 'https://api.solidtime.io или https://time.example.com',
    'https://kimai.example.com or https://www.kimai.cloud': 'https://kimai.example.com или https://www.kimai.cloud',
    'API key:': 'Ключ API:',
    'Make similar colors distinctive within each category': 'Сделать похожие цвета различимыми внутри каждой категории',
    'Similarity threshold (%):': 'Порог сходства (%):',
    'Configure a server URL on the Connection tab first.': 'Сначала настройте URL сервера на вкладке Подключение.',
    'Loading customers, projects, and activities…': 'Загрузка клиентов, проектов и активностей…',
    'Color distinction is off. Enable it in Display settings to see clash groups.': 'Различение цветов выключено. Включите его в настройках Отображения, чтобы увидеть группы конфликтов.',
    'Loaded %1 customers, %2 projects, %3 activities. No similar colors within a category.': 'Загружено %1 клиентов, %2 проектов, %3 активностей. Нет похожих цветов в категории.',
    'Loaded %1 customers, %2 projects, %3 activities. %4 clash group(s), %5 color(s) shifted.': 'Загружено %1 клиентов, %2 проектов, %3 активностей. %4 групп(ы) конфликтов, %5 цвет(ов) сдвинуто.',
    'Only colors that clash within a category are listed. Each group starts with the entry that kept the Kimai color; shifted variants follow. Unique colors are hidden.': 'Показаны только цвета, конфликтующие в категории. Каждая группа начинается с записи, сохранившей цвет Kimai; далее — сдвинутые варианты. Уникальные цвета скрыты.',
    'Reload from server': 'Перезагрузить с сервера',
    'Distinction on · configured %1% · effective customers %2% / projects %3% / activities %4%': 'Различение включено · настроено %1% · фактически клиенты %2% / проекты %3% / активности %4%',
    'Distinction off — enable it in Display settings.': 'Различение выключено — включите в настройках Отображения.',
    'Customers': 'Клиенты',
    'No similar colors in this category.': 'В этой категории нет похожих цветов.',
    'kept': 'сохранён',
    'shifted': 'сдвинут',
    'Maintenance': 'Обслуживание',
    'Edit': 'Изменить',
    'Edit start, project, and activity': 'Изменить начало, проект и активность',
    'Elapsed time updates from the new start.': 'Прошедшее время пересчитывается от нового начала.',
    'Start must be a valid time not in the future.': 'Начало должно быть корректным временем и не в будущем.',
    'This provider cannot update the running entry.': 'Этот провайдер не может обновить текущую запись.',
    'Enter a valid start date/time.': 'Введите корректные дату/время начала.',
    'Start must not be in the future.': 'Начало не должно быть в будущем.',
    'Save': 'Сохранить',
    'Current': 'Текущая',
    'Switch to': 'Переключиться на',
    'Could not resolve project or activity for that entry': 'Не удалось определить проект или активность для этой записи',
    'Edit start, project, activity, billable, and tags for the running entry.': 'Изменить начало, проект, деятельность, оплачиваемость и теги текущей записи.',
    'Starts or switches this activity': 'Запускает или переключает эту деятельность',
    'A profile named "%1" already exists.': 'Профиль с именем «%1» уже существует.',
    'Appearance': 'Внешний вид',
    'Updates': 'Обновления',
    'Colors': 'Цвета',
    'Distinction:': 'Различение:',
    'Higher similarity values treat more colors as too close. Clashing items get vivid, well-spaced replacement colors. See Maintenance for clash groups.': 'Более высокие значения сходства считают больше цветов слишком близкими. Конфликтующие элементы получают яркие, хорошо разнесённые цвета. См. Обслуживание для групп конфликтов.',
    'Color distinction is available for Kimai profiles (per-customer / project / activity colors).': 'Различение цветов доступно для профилей Kimai (цвета клиента / проекта / деятельности).',
    'Work hours': 'Рабочие часы',
    'Used for the sparkline zoom and remaining-time in the work summary.': 'Для масштаба спарклайна и оставшегося времени в сводке.',
    'Arcs:': 'Дуги:',
    'Show sun, moon, and work arcs': 'Показывать дуги солнца, луны и работы',
    'Hide the whole sparkline under Panel flyout or Desktop widget below.': 'Скрыть весь спарклайн в меню панели или виджете рабочего стола ниже.',
    'Find location:': 'Найти место:',
    'Search a place or enter coordinates for sunrise/sunset coloring. Powered by OpenStreetMap Nominatim.': 'Найдите место или введите координаты для окраски восхода/заката. На базе OpenStreetMap Nominatim.',
    'Customer color pill': 'Цветовая метка клиента',
    'Project color pill': 'Цветовая метка проекта',
    'Activities shown:': 'Показанные деятельности:',
    'Applies to both the panel flyout and the desktop widget.': 'Относится к меню панели и виджету рабочего стола.',
    'Loading projects': 'Загрузка проектов',
    'Color distinction is only available for Kimai profiles.': 'Различение цветов доступно только для профилей Kimai.',
    'Color maintenance is for Kimai': 'Обслуживание цветов относится к Kimai',
    'Clockify, Toggl, and SolidTime do not expose Kimai-style customer / project / activity colors, so clash groups and color shifting are hidden for those profiles.': 'Clockify, Toggl и SolidTime не отдают цвета клиента / проекта / деятельности как Kimai, поэтому группы конфликтов и сдвиг цветов скрыты для этих профилей.',
    'Select customer…': 'Выбрать клиента…',
    'Today\'s tracked time': 'Учёт времени за сегодня',
    'This provider cannot update descriptions.': 'Этот сервис не может обновлять описания.',
    'Open or close the Plasmai popup': 'Открыть или закрыть всплывающее окно Plasmai',
    'Add tag…': 'Добавить тег…',
    'Add tags…': 'Добавить теги…',
    'Tags': 'Теги',
    'Loading tags…': 'Загрузка тегов…',
    'No tags on the server yet.': 'На сервере пока нет тегов.',
    'Create tag “%1”': 'Создать тег «%1»',
    'Already running.': 'Уже запущено.',
    'Entry actions': 'Действия записи',
    'Edit entry': 'Изменить запись',
    'Split entry': 'Разделить запись',
    'Delete entry': 'Удалить запись',
    'Idle detection uses the session idle hint on Wayland (loginctl / ScreenSaver) and xprintidle on X11.': 'Определение простоя использует подсказку сеанса в Wayland (loginctl / ScreenSaver) и xprintidle в X11.',
    'Remind me once if nothing is tracking during work hours': 'Напомнить один раз, если в рабочие часы ничего не учитывается',
    'Idle time discarded': 'Время простоя отброшено',
    'Nothing is tracking': 'Ничего не учитывается',
    'Work hours have started. Start a timer when you begin.': 'Рабочие часы начались. Запустите таймер, когда начнёте.',
    'Customer created': 'Клиент создан',
    'Project created': 'Проект создан',
    'Activity created': 'Деятельность создана',
    'Entry updated': 'Запись обновлена',
    'Timesheet updated': 'Табель обновлён',
    'This provider cannot update stopped entries.': 'Этот сервис не может обновлять остановленные записи.',
    'Tracking in progress': 'Учёт идёт',
    'This provider cannot delete entries.': 'Этот сервис не может удалять записи.',
    'Entry deleted': 'Запись удалена',
    'Split time must be between begin and end.': 'Время разделения должно быть между началом и концом.',
    'This provider cannot split entries.': 'Этот сервис не может разделять записи.',
    'Entry split': 'Запись разделена',
    'The first half was saved, but the second half could not be created.': 'Первая половина сохранена, но вторую создать не удалось.',
    'Delete entry?': 'Удалить запись?',
    'Delete this finished entry? This cannot be undone.': 'Удалить эту завершённую запись? Это нельзя отменить.',
    'Delete "%1 · %2"? This cannot be undone.': 'Удалить «%1 · %2»? Это нельзя отменить.',
    'The first half keeps the original start. The second half starts at the split time.': 'Первая половина сохраняет исходное начало. Вторая начинается в момент разделения.',
    'Split at': 'Разделить в',
    'Both halves will have a positive duration.': 'Обе половины будут иметь положительную длительность.',
    'You were idle': 'Вы были в простое',
    'Keep the time, discard the idle gap, or discard and continue the same activity.': 'Оставить время, отбросить простой или отбросить и продолжить ту же деятельность.',
    'Keep time': 'Оставить время',
    'Discard idle': 'Отбросить простой',
    'Discard and continue': 'Отбросить и продолжить',
    'Start · %1 · %2': 'Старт · %1 · %2',
    'Change project, activity, range, billable, and tags for this finished entry.': 'Изменить проект, деятельность, интервал, оплачиваемость и теги этой завершённой записи.',
    'Save changes': 'Сохранить изменения',
    'Create customer': 'Создать клиента',
    'Create activity': 'Создать деятельность',
    'Create project': 'Создать проект',
    'Activity will be added to %1.': 'Деятельность будет добавлена к %1.',
    'Name': 'Имя',
    'Customer': 'Клиент',
}

PLURALS = {
    '%1 minute ago': ['%1 минуту назад', '%1 минуты назад', '%1 минут назад'],
    '%1 hour ago': ['%1 час назад', '%1 часа назад', '%1 часов назад'],
    '%1 day ago': ['%1 день назад', '%1 дня назад', '%1 дней назад'],
    '%1 place found.': ['Найдено %1 место.', 'Найдено %1 места.', 'Найдено %1 мест.'],
}
