# -*- coding: utf-8 -*-
T = {
    'Project-specific': 'Специфичные для проекта',
    'Global activities': 'Глобальные активности',
    'Plasmai': 'Plasmai',
    'Toggle Plasmai tracking': 'Переключить отслеживание Plasmai',
    'Stop Plasmai tracking': 'Остановить отслеживание Plasmai',
    'Loading…': 'Загрузка…',
    'Not configured — right-click to configure': 'Не настроено — щёлкните правой кнопкой для настройки',
    'just now': 'только что',
    'yesterday': 'вчера',
    'Not configured': 'Не настроено',
    'Connecting to %1…': 'Подключение к %1…',
    'Connection problem': 'Проблема соединения',
    'Connected to %1 (%2)': 'Подключено к %1 (%2)',
    'Connected to %1': 'Подключено к %1',
    'Enter valid begin and end date/time.': 'Введите корректные дату и время начала и окончания.',
    'End must be after begin.': 'Окончание должно быть позже начала.',
    'Entry added': 'Запись добавлена',
    'Manual time entry': 'Ручная запись времени',
    '%1 left today': 'Сегодня осталось %1',
    '%1 over today': 'Сегодня переработка %1',
    '%1 left this week': 'На этой неделе осталось %1',
    '%1 over this week': 'На этой неделе переработка %1',
    'Today %1': 'Сегодня %1',
    'Week %1': 'Неделя %1',
    'Tracking started': 'Отслеживание начато',
    'Switched activity': 'Активность изменена',
    'Tracking stopped (idle)': 'Отслеживание остановлено (бездействие)',
    'Tracking stopped': 'Отслеживание остановлено',
    'Stop the current timer before starting another': 'Остановите текущий таймер перед запуском другого',
    'Stop tracking?': 'Остановить отслеживание?',
    'Stop tracking %1 · %2?': 'Остановить отслеживание %1 · %2?',
    'Statistics': 'Статистика',
    'Add entry': 'Добавить запись',
    'Add a manual time entry': 'Добавить ручную запись времени',
    'Show statistics': 'Показать статистику',
    'Back to timer': 'Назад к таймеру',
    'Connect a time tracker': 'Подключить учёт времени',
    'Add your service, server URL (if needed), and API token to start tracking from the panel.': 'Добавьте сервис, URL сервера (при необходимости) и API-токен, чтобы начать отслеживание с панели.',
    'Configure Plasmai': 'Настроить Plasmai',
    'Retry': 'Повторить',
    'Configure': 'Настроить',
    'Not tracking': 'Не отслеживается',
    'Description': 'Описание',
    'Save description': 'Сохранить описание',
    'Stop': 'Остановить',
    'Continue · %1 · %2': 'Продолжить · %1 · %2',
    'Favorites': 'Избранное',
    'No favorites yet': 'Пока нет избранного',
    'Pin frequent project/activity pairs in the widget settings.': 'Закрепите частые пары проект/активность в настройках виджета.',
    'Configure favorites': 'Настроить избранное',
    '+%1 more in settings': '+%1 ещё в настройках',
    'Recent': 'Недавние',
    'No recent activities': 'Нет недавних активностей',
    'Start tracking to build your recent list.': 'Начните отслеживание, чтобы сформировать список недавних.',
    'Switch to another activity…': 'Переключиться на другую активность…',
    'Start something else…': 'Начать что-то другое…',
    'Switch activity': 'Сменить активность',
    'New activity': 'Новая активность',
    'Select project…': 'Выберите проект…',
    'Select activity…': 'Выберите активность…',
    'Description (optional)': 'Описание (необязательно)',
    'Start': 'Начать',
    'Switch': 'Сменить',
    'Cancel': 'Отмена',
    'Unknown error': 'Неизвестная ошибка',
    'URL and API token are required': 'Требуются URL и API-токен',
    'Configure your time tracker URL and API token': 'Настройте URL и API-токен учёта времени',
    'This action is not supported for the selected service yet.': 'Это действие пока не поддерживается для выбранного сервиса.',
    'Cannot reach the server. Check your network, URL, or TLS certificate.': 'Не удаётся связаться с сервером. Проверьте сеть, URL или TLS-сертификат.',
    'Authentication failed. Check your API token.': 'Ошибка аутентификации. Проверьте API-токен.',
    'Server not found. Check your URL.': 'Сервер не найден. Проверьте URL.',
    'Access denied. Your token may lack required permissions.': 'Доступ запрещён. Возможно, у вашего токена нет нужных прав.',
    'Server error (%1).': 'Ошибка сервера (%1).',
    'Request failed: %1': 'Запрос не выполнен: %1',
    'Request failed (%1).': 'Запрос не выполнен (%1).',
    'Connection': 'Подключение',
    'Configure a time-tracking profile. Choose Kimai, Clockify, Toggl Track, or SolidTime.': 'Настройте профиль учёта времени. Выберите Kimai, Clockify, Toggl Track или SolidTime.',
    'Profile:': 'Профиль:',
    'Profile name:': 'Имя профиля:',
    'Service:': 'Сервис:',
    'Server URL:': 'URL сервера:',
    'API token:': 'API-токен:',
    'Paste token to save in KWallet': 'Вставьте токен для сохранения в KWallet',
    'Add profile': 'Добавить профиль',
    'Profile %1': 'Профиль %1',
    'Remove': 'Удалить',
    'Use this profile': 'Использовать этот профиль',
    'none': 'нет',
    'Active profile: %1': 'Активный профиль: %1',
    'Saving…': 'Сохранение…',
    'Save token': 'Сохранить токен',
    'Token saved to KWallet for this profile.': 'Токен сохранён в KWallet для этого профиля.',
    'Failed to save token': 'Не удалось сохранить токен',
    'Clear token': 'Очистить токен',
    'Token removed from KWallet.': 'Токен удалён из KWallet.',
    'Failed to clear token': 'Не удалось очистить токен',
    'Test connection': 'Проверить соединение',
    'Testing connection…': 'Проверка соединения…',
    'No API token stored. Save a token first.': 'API-токен не сохранён. Сначала сохраните токен.',
    'ok': 'ok',
    'Connected to %1 (%2).': 'Подключено к %1 (%2).',
    'Configure a Kimai URL on the Connection tab first.': 'Сначала настройте URL Kimai на вкладке «Подключение».',
    'Loading projects…': 'Загрузка проектов…',
    'Save an API token on the Connection tab first.': 'Сначала сохраните API-токен на вкладке «Подключение».',
    'Loaded %1 projects.': 'Загружено проектов: %1.',
    'Select a project to pin activities.': 'Выберите проект, чтобы закрепить активности.',
    'Failed to load projects.': 'Не удалось загрузить проекты.',
    'Loading activities…': 'Загрузка активностей…',
    'No API token available.': 'API-токен недоступен.',
    '%1 project-specific, %2 global': '%1 для проекта, %2 глобальных',
    'Failed to load activities.': 'Не удалось загрузить активности.',
    'Projects': 'Проекты',
    'Reload': 'Обновить',
    'Activities — %1': 'Активности — %1',
    'Activities': 'Активности',
    'Enter a city or place name to search.': 'Введите название города или места для поиска.',
    'Searching…': 'Поиск…',
    'Location search failed. Check your network connection.': 'Поиск места не удался. Проверьте сетевое соединение.',
    'No places found.': 'Мест не найдено.',
    'Display': 'Отображение',
    'Refresh interval (seconds):': 'Интервал обновления (секунды):',
    'Recent activities shown:': 'Показывать недавних активностей:',
    'Appearance:': 'Внешний вид:',
    'Use desktop blur (translucent background)': 'Размытие рабочего стола (полупрозрачный фон)',
    'Usual work day start:': 'Начало рабочего дня:',
    'Usual work day end:': 'Конец рабочего дня:',
    'Day sparkline': 'Дневная диаграмма',
    'Find location': 'Найти местоположение',
    'Search for a city or place to set sunrise/sunset coloring. Powered by OpenStreetMap Nominatim.': 'Найдите город или место для окраски восхода/заката. На базе OpenStreetMap Nominatim.',
    'City, region, or address…': 'Город, регион или адрес…',
    'Search': 'Поиск',
    'Using %1': 'Используется %1',
    'Current place: %1': 'Текущее место: %1',
    'Custom coordinates': 'Свои координаты',
    'Latitude:': 'Широта:',
    'Longitude:': 'Долгота:',
    'Used to color the sparkline for sunrise and sunset at your location.': 'Используется для окраски диаграммы по восходу и закату в вашем местоположении.',
    'Panel (taskbar)': 'Панель (панель задач)',
    'Show:': 'Показывать:',
    'Elapsed time': 'Прошедшее время',
    'Project name': 'Название проекта',
    'Activity name': 'Название активности',
    'Panel flyout': 'Всплывающее окно панели',
    'Work summary (today / week / remaining)': 'Сводка работы (сегодня / неделя / осталось)',
    'Recent list': 'Список недавних',
    'Continue last activity': 'Продолжить последнюю активность',
    'Start / switch activity controls': 'Управление запуском / сменой активности',
    'Desktop widget': 'Виджет рабочего стола',
    'New activity picker': 'Выбор новой активности',
    'Behavior': 'Поведение',
    'Tracking:': 'Отслеживание:',
    'Confirm before stopping the timer': 'Подтверждать перед остановкой таймера',
    'Idle detection:': 'Обнаружение бездействия:',
    'Stop timer when idle': 'Останавливать таймер при бездействии',
    'Idle threshold (minutes):': 'Порог бездействия (минуты):',
    'Notifications:': 'Уведомления:',
    'Notify when tracking starts': 'Уведомлять о начале отслеживания',
    'Notify when tracking stops': 'Уведомлять об остановке отслеживания',
    'Notify when stopped due to idle': 'Уведомлять об остановке из-за бездействия',
    'Idle detection requires xprintidle (X11/XWayland). It may not work on pure Wayland sessions.': 'Обнаружение бездействия требует xprintidle (X11/XWayland). Может не работать в чистых Wayland-сессиях.',
    'Back': 'Назад',
    'Create a finished entry with project, activity, and time range.': 'Создать завершённую запись с проектом, активностью и диапазоном времени.',
    'Begin': 'Начало',
    'End': 'Конец',
    'Duration: %1': 'Длительность: %1',
    'Duration: —': 'Длительность: —',
    'Duration: invalid range': 'Длительность: недопустимый диапазон',
    'Save entry': 'Сохранить запись',
    'All': 'Все',
    'Billable': 'Оплачиваемые',
    'Non-billable': 'Неоплачиваемые',
    'Charts for power users. Tracking stays on the main screen.': 'Диаграммы для опытных пользователей. Учёт остаётся на главном экране.',
    'Show': 'Показать',
    'Today': 'Сегодня',
    'This week': 'На этой неделе',
    'Time by hour': 'Время по часам',
    'Previous day': 'Предыдущий день',
    'Yesterday': 'Вчера',
    'Next day': 'Следующий день',
    'No time logged this day': 'В этот день время не записано',
    'Projects by day': 'Проекты по дням',
    'Previous week': 'Предыдущая неделя',
    'Next week': 'Следующая неделя',
    'No time logged this week': 'На этой неделе время не записано',
    'Projects by hour': 'Проекты по часам',
    'Weekdays and weekend — segments placed by clock time.': 'Будни и выходные — сегменты по времени суток.',
    'Weekdays — segments placed by clock time. Weekend appears when tracked.': 'Будни — сегменты по времени. Выходные появляются при наличии записей.',
    'Axis shows business hours (%1–%2); expands if work falls outside.': 'Ось показывает рабочие часы (%1–%2); расширяется, если работа вне диапазона.',
    'Activity distribution': 'Распределение активностей',
    'No activities today': 'Сегодня нет активностей',
    'No activities this week': 'На этой неделе нет активностей',
    'Time': 'Время',
    'Pick date': 'Выбрать дату',
    'Pick time': 'Выбрать время',
    'Hours : Minutes': 'Часы : Минуты',
    'Select': 'Выбрать',
    'Today\'s tracked time across 24 hours': 'Сегодняшнее учтённое время за 24 часа',
    'Clockify cloud API is prefilled. Change only for a regional endpoint (e.g. euc1).': 'Облачный API Clockify уже заполнен. Меняйте только для региональной конечной точки (напр. euc1).',
    'Toggl Track cloud API is prefilled. Use your personal API token from Profile settings.': 'Облачный API Toggl Track уже заполнен. Используйте личный API-токен из настроек профиля.',
    'SolidTime cloud API is prefilled. For self-hosting, replace with your instance base URL.': 'Облачный API SolidTime уже заполнен. При самостоятельном хостинге замените на базовый URL вашего экземпляра.',
    'Self-hosted Kimai or the official hosted service (kimai.cloud). Paste the instance URL.': 'Самостоятельно размещённый Kimai или официальный хостинг (kimai.cloud). Вставьте URL экземпляра.',
    'API URL:': 'URL API:',
    'https://api.solidtime.io or https://time.example.com': 'https://api.solidtime.io или https://time.example.com',
    'https://kimai.example.com or https://www.kimai.cloud': 'https://kimai.example.com или https://www.kimai.cloud',
    'API key:': 'Ключ API:',
    'Colors:': 'Цвета:',
    'Make similar colors distinctive within each category': 'Сделать похожие цвета различимыми внутри каждой категории',
    'Similarity threshold (%):': 'Порог сходства (%):',
    'Higher similarity values treat more colors as too close. Clashing items get vivid, well-spaced replacement colors (not washed hue-shifts). If too many items cannot fit, the threshold is lowered automatically down to 12%. See Maintenance for clash groups.': 'Более высокие значения сходства считают больше цветов слишком близкими. Конфликтующие элементы получают яркие, хорошо разнесённые цвета замены (не бледные сдвиги оттенка). Если слишком много элементов не помещается, порог автоматически снижается до 12%. См. Обслуживание для групп конфликтов.',
    'Configure a server URL on the Connection tab first.': 'Сначала настройте URL сервера на вкладке Подключение.',
    'Loading customers, projects, and activities…': 'Загрузка клиентов, проектов и активностей…',
    'Color distinction is off. Enable it in Display settings to see clash groups.': 'Различение цветов выключено. Включите его в настройках Отображения, чтобы увидеть группы конфликтов.',
    'Loaded %1 customers, %2 projects, %3 activities. No similar colors within a category.': 'Загружено %1 клиентов, %2 проектов, %3 активностей. Нет похожих цветов в категории.',
    'Loaded %1 customers, %2 projects, %3 activities. %4 clash group(s), %5 color(s) shifted.': 'Загружено %1 клиентов, %2 проектов, %3 активностей. %4 групп(ы) конфликтов, %5 цвет(ов) сдвинуто.',
    'Only colors that clash within a category are listed. Each group starts with the entry that kept the Kimai color; shifted variants follow. Unique colors are hidden.': 'Показаны только цвета, конфликтующие в категории. Каждая группа начинается с записи, сохранившей цвет Kimai; далее — сдвинутые варианты. Уникальные цвета скрыты.',
    'Reload from server': 'Перезагрузить с сервера',
    'Distinction on · configured %1% · effective customers %2% / projects %3% / activities %4%': 'Различение включено · настроено %1% · фактически клиенты %2% / проекты %3% / активности %4%',
    'Distinction off — enable it in Display settings.': 'Различение выключено — включите в настройках Отображения.',
    'Customers': 'Клиенты',
    'No similar colors in this category.': 'В этой категории нет похожих цветов.',
    'kept': 'сохранён',
    'shifted': 'сдвинут',
    'Maintenance': 'Обслуживание',
    'Edit': 'Изменить',
    'Edit start, project, and activity': 'Изменить начало, проект и активность',
    'Edit start time, project, and activity for the running entry.': 'Изменить время начала, проект и активность текущей записи.',
    'Elapsed time updates from the new start.': 'Прошедшее время пересчитывается от нового начала.',
    'Start must be a valid time not in the future.': 'Начало должно быть корректным временем и не в будущем.',
    'This provider cannot update the running entry.': 'Этот провайдер не может обновить текущую запись.',
    'Enter a valid start date/time.': 'Введите корректные дату/время начала.',
    'Start must not be in the future.': 'Начало не должно быть в будущем.',
    'Save': 'Сохранить',

}

PLURALS = {
    '%1 minute ago': ['%1 минуту назад', '%1 минуты назад', '%1 минут назад'],
    '%1 hour ago': ['%1 час назад', '%1 часа назад', '%1 часов назад'],
    '%1 day ago': ['%1 день назад', '%1 дня назад', '%1 дней назад'],
    '%1 place found.': ['Найдено %1 место.', 'Найдено %1 места.', 'Найдено %1 мест.'],
}
