# -*- coding: utf-8 -*-
"""First-start wizard (SetupWizard.qml) strings. Merged by fill_po.py after the
per-language dictionaries (entries there win).

Column order: de, fr, es, it, nl, pt_BR, pl, uk, ru, ja, zh_CN
"""

LANGS = ["de", "fr", "es", "it", "nl", "pt_BR", "pl", "uk", "ru", "ja", "zh_CN"]

ROWS = [
    ("More options in the settings",
     "Weitere Optionen in den Einstellungen", "Plus d’options dans les paramètres", "Más opciones en los ajustes",
     "Altre opzioni nelle impostazioni", "Meer opties in de instellingen", "Mais opções nas configurações",
     "Więcej opcji w ustawieniach", "Більше параметрів у налаштуваннях", "Больше параметров в настройках",
     "その他のオプションは設定で", "更多选项请见设置"),
    ("Not configured — click to set up",
     "Nicht eingerichtet – zum Einrichten klicken", "Non configuré — cliquez pour configurer",
     "Sin configurar: haz clic para configurar", "Non configurato — fai clic per configurare",
     "Niet ingesteld — klik om in te stellen", "Não configurado — clique para configurar",
     "Nie skonfigurowano — kliknij, aby skonfigurować", "Не налаштовано — натисніть, щоб налаштувати",
     "Не настроено — нажмите, чтобы настроить", "未設定 — クリックして設定", "未配置 — 点击进行设置"),
    ("System",
     "System", "Système", "Sistema", "Sistema", "Systeem", "Sistema", "System", "Система", "Система", "システム", "系统"),
    ("Service",
     "Dienst", "Service", "Servicio", "Servizio", "Dienst", "Serviço", "Usługa", "Сервіс", "Сервис", "サービス", "服务"),
    ("Access",
     "Zugang", "Accès", "Acceso", "Accesso", "Toegang", "Acesso", "Dostęp", "Доступ", "Доступ", "アクセス", "访问"),
    ("Day",
     "Tag", "Journée", "Día", "Giornata", "Dag", "Dia", "Dzień", "День", "День", "一日", "工作日"),
    ("Check your system",
     "System prüfen", "Vérifier votre système", "Comprueba tu sistema", "Controlla il sistema",
     "Controleer je systeem", "Verifique seu sistema", "Sprawdź system", "Перевірте систему",
     "Проверьте систему", "システムを確認", "检查系统"),
    ("Choose your time tracker",
     "Zeiterfassung wählen", "Choisissez votre outil de suivi du temps",
     "Elige tu herramienta de registro de tiempo", "Scegli il tuo strumento di rilevazione ore",
     "Kies je tijdregistratie", "Escolha sua ferramenta de controle de tempo",
     "Wybierz narzędzie do śledzenia czasu", "Оберіть сервіс обліку часу", "Выберите сервис учёта времени",
     "時間記録サービスを選択", "选择你的工时记录服务"),
    ("Connect to %1",
     "Mit %1 verbinden", "Se connecter à %1", "Conectar con %1", "Connetti a %1", "Verbinden met %1",
     "Conectar ao %1", "Połącz z %1", "Підключитися до %1", "Подключиться к %1", "%1 に接続", "连接到 %1"),
    ("Your work day",
     "Dein Arbeitstag", "Votre journée de travail", "Tu jornada laboral", "La tua giornata lavorativa",
     "Je werkdag", "Seu dia de trabalho", "Twój dzień pracy", "Ваш робочий день", "Ваш рабочий день",
     "あなたの勤務日", "你的工作日"),
    ("In Clockify: Profile settings, Preferences, tab Advanced, Manage API keys.",
     "In Clockify: Profileinstellungen, Präferenzen, Reiter Erweitert, API-Schlüssel verwalten.",
     "Dans Clockify : Paramètres du profil, Préférences, onglet Avancé, Gérer les clés API.",
     "En Clockify: Configuración del perfil, Preferencias, pestaña Avanzado, Gestionar claves API.",
     "In Clockify: Impostazioni profilo, Preferenze, scheda Avanzate, Gestisci chiavi API.",
     "In Clockify: Profielinstellingen, Voorkeuren, tabblad Geavanceerd, API-sleutels beheren.",
     "No Clockify: Configurações do perfil, Preferências, aba Avançado, Gerenciar chaves de API.",
     "W Clockify: Ustawienia profilu, Preferencje, karta Zaawansowane, Zarządzaj kluczami API.",
     "У Clockify: Налаштування профілю, Параметри, вкладка Додатково, Керування ключами API.",
     "В Clockify: Настройки профиля, Предпочтения, вкладка Дополнительно, Управление ключами API.",
     "Clockify：プロフィール設定 → 環境設定 → 詳細タブ → API キーの管理。",
     "在 Clockify 中：个人资料设置 → 偏好设置 → 高级 → 管理 API 密钥。"),
    ("In Toggl Track: Profile settings, at the bottom: API Token.",
     "In Toggl Track: Profileinstellungen, ganz unten: API Token.",
     "Dans Toggl Track : Paramètres du profil, tout en bas : API Token.",
     "En Toggl Track: Configuración del perfil, al final: API Token.",
     "In Toggl Track: Impostazioni profilo, in fondo: API Token.",
     "In Toggl Track: Profielinstellingen, helemaal onderaan: API Token.",
     "No Toggl Track: Configurações do perfil, no final: API Token.",
     "W Toggl Track: Ustawienia profilu, na samym dole: API Token.",
     "У Toggl Track: Налаштування профілю, у самому низу: API Token.",
     "В Toggl Track: Настройки профиля, в самом низу: API Token.",
     "Toggl Track：プロフィール設定の一番下にある API Token。",
     "在 Toggl Track 中：个人资料设置页面底部的 API Token。"),
    ("In SolidTime: open API Tokens from your profile menu and create a token.",
     "In SolidTime: im Profilmenü API Tokens öffnen und einen Token erstellen.",
     "Dans SolidTime : ouvrez API Tokens dans le menu du profil et créez un jeton.",
     "En SolidTime: abre API Tokens en el menú del perfil y crea un token.",
     "In SolidTime: apri API Tokens dal menu del profilo e crea un token.",
     "In SolidTime: open API Tokens in het profielmenu en maak een token aan.",
     "No SolidTime: abra API Tokens no menu do perfil e crie um token.",
     "W SolidTime: otwórz API Tokens w menu profilu i utwórz token.",
     "У SolidTime: відкрийте API Tokens у меню профілю та створіть токен.",
     "В SolidTime: откройте API Tokens в меню профиля и создайте токен.",
     "SolidTime：プロフィールメニューから API Tokens を開き、トークンを作成します。",
     "在 SolidTime 中：从个人资料菜单打开 API Tokens 并创建令牌。"),
    ("In Kimai: open API access from your user menu and create a token.",
     "In Kimai: im Benutzermenü API-Zugang öffnen und einen Token erstellen.",
     "Dans Kimai : ouvrez Accès API dans le menu utilisateur et créez un jeton.",
     "En Kimai: abre Acceso API en el menú de usuario y crea un token.",
     "In Kimai: apri Accesso API dal menu utente e crea un token.",
     "In Kimai: open API-toegang in het gebruikersmenu en maak een token aan.",
     "No Kimai: abra Acesso à API no menu do usuário e crie um token.",
     "W Kimai: otwórz Dostęp API w menu użytkownika i utwórz token.",
     "У Kimai: відкрийте доступ до API в меню користувача та створіть токен.",
     "В Kimai: откройте доступ к API в меню пользователя и создайте токен.",
     "Kimai：ユーザーメニューから API アクセスを開き、トークンを作成します。",
     "在 Kimai 中：从用户菜单打开 API 访问并创建令牌。"),
    ("Enter the server address.",
     "Gib die Serveradresse ein.", "Saisissez l’adresse du serveur.", "Introduce la dirección del servidor.",
     "Inserisci l’indirizzo del server.", "Voer het serveradres in.", "Digite o endereço do servidor.",
     "Wpisz adres serwera.", "Введіть адресу сервера.", "Введите адрес сервера.",
     "サーバーのアドレスを入力してください。", "请输入服务器地址。"),
    ("This is not a web address (https://…).",
     "Das ist keine Webadresse (https://…).", "Ce n’est pas une adresse web (https://…).",
     "Esto no es una dirección web (https://…).", "Questo non è un indirizzo web (https://…).",
     "Dit is geen webadres (https://…).", "Isto não é um endereço web (https://…).",
     "To nie jest adres internetowy (https://…).", "Це не вебадреса (https://…).", "Это не веб-адрес (https://…).",
     "Web アドレスではありません（https://…）。", "这不是网址（https://…）。"),
    ("Paste your API token.",
     "Füge deinen API-Token ein.", "Collez votre jeton API.", "Pega tu token de API.", "Incolla il tuo token API.",
     "Plak je API-token.", "Cole seu token de API.", "Wklej swój token API.", "Вставте свій API-токен.",
     "Вставьте свой API-токен.", "API トークンを貼り付けてください。", "请粘贴你的 API 令牌。"),
    ("The token could not be stored securely: %1",
     "Der Token konnte nicht sicher gespeichert werden: %1", "Le jeton n’a pas pu être enregistré de façon sûre : %1",
     "No se pudo guardar el token de forma segura: %1", "Impossibile salvare il token in modo sicuro: %1",
     "Het token kon niet veilig worden opgeslagen: %1", "Não foi possível guardar o token com segurança: %1",
     "Nie udało się bezpiecznie zapisać tokenu: %1", "Не вдалося безпечно зберегти токен: %1",
     "Не удалось надёжно сохранить токен: %1", "トークンを安全に保存できませんでした: %1", "无法安全保存令牌：%1"),
    ("Is KWallet or another password storage running?",
     "Läuft KWallet oder ein anderer Passwortspeicher?",
     "KWallet ou un autre gestionnaire de mots de passe est-il actif ?",
     "¿Está en marcha KWallet u otro almacén de contraseñas?",
     "KWallet o un altro archivio password è in esecuzione?",
     "Draait KWallet of een andere wachtwoordopslag?",
     "O KWallet ou outro armazenamento de senhas está em execução?",
     "Czy działa KWallet lub inny magazyn haseł?",
     "Чи запущено KWallet або інше сховище паролів?",
     "Запущен ли KWallet или другое хранилище паролей?",
     "KWallet などのパスワード保存サービスは動作していますか？",
     "KWallet 或其他密码存储是否正在运行？"),
    ("Search failed. Check your connection.",
     "Suche fehlgeschlagen. Prüfe deine Verbindung.", "La recherche a échoué. Vérifiez votre connexion.",
     "La búsqueda falló. Comprueba tu conexión.", "Ricerca non riuscita. Controlla la connessione.",
     "Zoeken mislukt. Controleer je verbinding.", "A busca falhou. Verifique sua conexão.",
     "Wyszukiwanie nie powiodło się. Sprawdź połączenie.", "Пошук не вдався. Перевірте з’єднання.",
     "Поиск не удался. Проверьте подключение.", "検索に失敗しました。接続を確認してください。",
     "搜索失败。请检查网络连接。"),
    ("No place found.",
     "Kein Ort gefunden.", "Aucun lieu trouvé.", "No se encontró ningún lugar.", "Nessun luogo trovato.",
     "Geen plaats gevonden.", "Nenhum lugar encontrado.", "Nie znaleziono miejsca.", "Місце не знайдено.",
     "Место не найдено.", "場所が見つかりません。", "未找到地点。"),
    ("Step %1 of %2",
     "Schritt %1 von %2", "Étape %1 sur %2", "Paso %1 de %2", "Passo %1 di %2", "Stap %1 van %2",
     "Etapa %1 de %2", "Krok %1 z %2", "Крок %1 з %2", "Шаг %1 из %2", "ステップ %1/%2", "第 %1 步，共 %2 步"),
    ("Welcome to Plasmai.",
     "Willkommen bei Plasmai.", "Bienvenue dans Plasmai.", "Bienvenido a Plasmai.", "Benvenuto in Plasmai.",
     "Welkom bij Plasmai.", "Bem-vindo ao Plasmai.", "Witaj w Plasmai.", "Ласкаво просимо до Plasmai.",
     "Добро пожаловать в Plasmai.", "Plasmai へようこそ。", "欢迎使用 Plasmai。"),
    ("Plasmai keeps your API token in the system's password storage (KWallet). That needs a few things on your system.",
     "Plasmai legt deinen API-Token im Passwortspeicher des Systems ab (KWallet). Dafür braucht dein System ein paar Dinge.",
     "Plasmai conserve votre jeton API dans le gestionnaire de mots de passe du système (KWallet). Cela demande quelques éléments sur votre système.",
     "Plasmai guarda tu token de API en el almacén de contraseñas del sistema (KWallet). Para ello tu sistema necesita algunas cosas.",
     "Plasmai conserva il token API nell’archivio password del sistema (KWallet). Per questo servono alcune cose sul sistema.",
     "Plasmai bewaart je API-token in de wachtwoordopslag van het systeem (KWallet). Daarvoor heeft je systeem een paar dingen nodig.",
     "O Plasmai guarda seu token de API no armazenamento de senhas do sistema (KWallet). Para isso, seu sistema precisa de algumas coisas.",
     "Plasmai przechowuje token API w systemowym magazynie haseł (KWallet). Wymaga to kilku rzeczy w systemie.",
     "Plasmai зберігає ваш API-токен у системному сховищі паролів (KWallet). Для цього системі потрібно кілька речей.",
     "Plasmai хранит ваш API-токен в системном хранилище паролей (KWallet). Для этого системе нужно несколько вещей.",
     "Plasmai は API トークンをシステムのパスワード保存（KWallet）に保管します。そのためにいくつか必要なものがあります。",
     "Plasmai 将你的 API 令牌保存在系统密码存储（KWallet）中。这需要系统具备以下组件。"),
    ("Missing: needed to store the token.",
     "Fehlt: wird zum Speichern des Tokens gebraucht.", "Manquant : nécessaire pour enregistrer le jeton.",
     "Falta: necesario para guardar el token.", "Mancante: serve per salvare il token.",
     "Ontbreekt: nodig om het token op te slaan.", "Ausente: necessário para guardar o token.",
     "Brak: potrzebne do zapisania tokenu.", "Відсутній: потрібен для збереження токена.",
     "Отсутствует: нужен для сохранения токена.", "見つかりません：トークンの保存に必要です。",
     "缺失：保存令牌需要它。"),
    ("Password storage (KWallet)",
     "Passwortspeicher (KWallet)", "Gestionnaire de mots de passe (KWallet)", "Almacén de contraseñas (KWallet)",
     "Archivio password (KWallet)", "Wachtwoordopslag (KWallet)", "Armazenamento de senhas (KWallet)",
     "Magazyn haseł (KWallet)", "Сховище паролів (KWallet)", "Хранилище паролей (KWallet)",
     "パスワード保存（KWallet）", "密码存储（KWallet）"),
    ("Not running: turn on KDE Wallet in System Settings.",
     "Läuft nicht: KDE-Wallet in den Systemeinstellungen einschalten.",
     "Inactif : activez KDE Wallet dans la Configuration du système.",
     "No está en marcha: activa KDE Wallet en las Preferencias del sistema.",
     "Non attivo: attiva KDE Wallet nelle Impostazioni di sistema.",
     "Draait niet: zet KDE Wallet aan in Systeeminstellingen.",
     "Não está em execução: ative o KDE Wallet nas Configurações do sistema.",
     "Nie działa: włącz KDE Wallet w Ustawieniach systemowych.",
     "Не запущено: увімкніть KDE Wallet у Системних налаштуваннях.",
     "Не запущено: включите KDE Wallet в Параметрах системы.",
     "動作していません：システム設定で KDE ウォレットを有効にしてください。",
     "未运行：请在系统设置中启用 KDE 钱包。"),
    ("Missing: reminders stay silent (optional).",
     "Fehlt: Erinnerungen bleiben stumm (optional).", "Manquant : les rappels restent muets (facultatif).",
     "Falta: los recordatorios no se mostrarán (opcional).", "Mancante: i promemoria restano muti (facoltativo).",
     "Ontbreekt: herinneringen blijven stil (optioneel).", "Ausente: os lembretes ficam silenciosos (opcional).",
     "Brak: przypomnienia się nie pojawią (opcjonalne).",
     "Відсутній: нагадування не з’являтимуться (необов’язково).",
     "Отсутствует: напоминания не появятся (необязательно).",
     "見つかりません：リマインダーは表示されません（任意）。", "缺失：提醒将不会显示（可选）。"),
    ("Ready.",
     "Bereit.", "Prêt.", "Listo.", "Pronto.", "Gereed.", "Pronto.", "Gotowe.", "Готово.", "Готово.", "準備完了。", "就绪。"),
    ("Install it in a terminal, then check again:",
     "Installiere es im Terminal und prüfe dann erneut:", "Installez-le dans un terminal, puis vérifiez à nouveau :",
     "Instálalo en una terminal y vuelve a comprobar:", "Installalo da terminale, poi controlla di nuovo:",
     "Installeer het in een terminal en controleer daarna opnieuw:", "Instale pelo terminal e verifique novamente:",
     "Zainstaluj to w terminalu, a potem sprawdź ponownie:", "Встановіть у терміналі, потім перевірте знову:",
     "Установите в терминале, затем проверьте снова:",
     "ターミナルでインストールしてから、もう一度確認してください：", "请在终端中安装，然后重新检查："),
    ("Install the package that provides secret-tool with your package manager, then check again.",
     "Installiere mit deiner Paketverwaltung das Paket, das secret-tool enthält, und prüfe dann erneut.",
     "Installez avec votre gestionnaire de paquets le paquet qui fournit secret-tool, puis vérifiez à nouveau.",
     "Instala con tu gestor de paquetes el paquete que incluye secret-tool y vuelve a comprobar.",
     "Installa con il gestore pacchetti il pacchetto che fornisce secret-tool, poi controlla di nuovo.",
     "Installeer met je pakketbeheerder het pakket dat secret-tool levert en controleer daarna opnieuw.",
     "Instale com seu gerenciador de pacotes o pacote que fornece o secret-tool e verifique novamente.",
     "Zainstaluj menedżerem pakietów pakiet zawierający secret-tool, a potem sprawdź ponownie.",
     "Встановіть менеджером пакунків пакунок із secret-tool, потім перевірте знову.",
     "Установите менеджером пакетов пакет с secret-tool, затем проверьте снова.",
     "パッケージマネージャーで secret-tool を含むパッケージをインストールしてから、もう一度確認してください。",
     "请用包管理器安装提供 secret-tool 的软件包，然后重新检查。"),
    ("Then check again.",
     "Prüfe dann erneut.", "Puis vérifiez à nouveau.", "Después vuelve a comprobar.", "Poi controlla di nuovo.",
     "Controleer daarna opnieuw.", "Depois verifique novamente.", "Potem sprawdź ponownie.",
     "Потім перевірте знову.", "Затем проверьте снова.", "その後、もう一度確認してください。", "然后重新检查。"),
    ("Copy",
     "Kopieren", "Copier", "Copiar", "Copia", "Kopiëren", "Copiar", "Kopiuj", "Копіювати", "Копировать", "コピー", "复制"),
    ("Which service do you track your time with? More profiles can be added later in the settings.",
     "Mit welchem Dienst erfasst du deine Zeit? Weitere Profile kannst du später in den Einstellungen anlegen.",
     "Avec quel service suivez-vous votre temps ? D’autres profils peuvent être ajoutés plus tard dans les paramètres.",
     "¿Con qué servicio registras tu tiempo? Puedes añadir más perfiles después en los ajustes.",
     "Con quale servizio registri il tuo tempo? Altri profili si possono aggiungere più tardi nelle impostazioni.",
     "Met welke dienst registreer je je tijd? Meer profielen kun je later in de instellingen toevoegen.",
     "Com qual serviço você registra seu tempo? Outros perfis podem ser adicionados depois nas configurações.",
     "Z jakiej usługi korzystasz do śledzenia czasu? Kolejne profile możesz dodać później w ustawieniach.",
     "Яким сервісом ви обліковуєте час? Інші профілі можна додати пізніше в налаштуваннях.",
     "Каким сервисом вы учитываете время? Другие профили можно добавить позже в настройках.",
     "どのサービスで時間を記録していますか？ プロフィールは後から設定で追加できます。",
     "你使用哪个服务记录工时？之后可以在设置中添加更多配置文件。"),
    ("Tested with real accounts.",
     "Mit echten Konten getestet.", "Testé avec de vrais comptes.", "Probado con cuentas reales.",
     "Testato con account reali.", "Getest met echte accounts.", "Testado com contas reais.",
     "Przetestowano na prawdziwych kontach.", "Перевірено на справжніх облікових записах.",
     "Проверено на реальных учётных записях.", "実際のアカウントでテスト済み。", "已用真实账户测试。"),
    ("Experimental: not yet tested with real accounts.",
     "Experimentell: noch nicht mit echten Konten getestet.", "Expérimental : pas encore testé avec de vrais comptes.",
     "Experimental: aún no probado con cuentas reales.", "Sperimentale: non ancora testato con account reali.",
     "Experimenteel: nog niet getest met echte accounts.", "Experimental: ainda não testado com contas reais.",
     "Eksperymentalne: jeszcze nie przetestowano na prawdziwych kontach.",
     "Експериментально: ще не перевірено на справжніх облікових записах.",
     "Экспериментально: ещё не проверено на реальных учётных записях.",
     "試験的：実際のアカウントでは未テスト。", "实验性：尚未用真实账户测试。"),
    ("Server address",
     "Serveradresse", "Adresse du serveur", "Dirección del servidor", "Indirizzo del server", "Serveradres",
     "Endereço do servidor", "Adres serwera", "Адреса сервера", "Адрес сервера", "サーバーアドレス", "服务器地址"),
    ("Shortened to the address of the Kimai instance: %1",
     "Auf die Adresse der Kimai-Instanz gekürzt: %1", "Raccourci à l’adresse de l’instance Kimai : %1",
     "Acortada a la dirección de la instancia de Kimai: %1", "Abbreviato all’indirizzo dell’istanza Kimai: %1",
     "Ingekort tot het adres van de Kimai-instantie: %1", "Encurtado para o endereço da instância do Kimai: %1",
     "Skrócono do adresu instancji Kimai: %1", "Скорочено до адреси екземпляра Kimai: %1",
     "Сокращено до адреса экземпляра Kimai: %1", "Kimai インスタンスのアドレスに短縮しました: %1",
     "已缩短为 Kimai 实例地址：%1"),
    ("This address is not encrypted (http). Your token would travel readable through the network.",
     "Diese Adresse ist nicht verschlüsselt (http). Dein Token ginge lesbar durchs Netz.",
     "Cette adresse n’est pas chiffrée (http). Votre jeton circulerait en clair sur le réseau.",
     "Esta dirección no está cifrada (http). Tu token viajaría legible por la red.",
     "Questo indirizzo non è cifrato (http). Il token viaggerebbe leggibile in rete.",
     "Dit adres is niet versleuteld (http). Je token zou leesbaar over het netwerk gaan.",
     "Este endereço não é criptografado (http). Seu token trafegaria legível pela rede.",
     "Ten adres nie jest szyfrowany (http). Token byłby przesyłany w sieci jawnym tekstem.",
     "Ця адреса не шифрована (http). Токен передаватиметься мережею у відкритому вигляді.",
     "Этот адрес не шифруется (http). Токен будет передаваться по сети в открытом виде.",
     "このアドレスは暗号化されていません（http）。トークンが読める状態でネットワークを流れます。",
     "此地址未加密（http）。你的令牌会以明文在网络中传输。"),
    ("Use another address",
     "Andere Adresse verwenden", "Utiliser une autre adresse", "Usar otra dirección", "Usa un altro indirizzo",
     "Ander adres gebruiken", "Usar outro endereço", "Użyj innego adresu", "Використати іншу адресу",
     "Использовать другой адрес", "別のアドレスを使用", "使用其他地址"),
    ("API key",
     "API-Schlüssel", "Clé API", "Clave de API", "Chiave API", "API-sleutel", "Chave de API", "Klucz API",
     "Ключ API", "Ключ API", "API キー", "API 密钥"),
    ("API token",
     "API-Token", "Jeton API", "Token de API", "Token API", "API-token", "Token de API", "Token API",
     "API-токен", "API-токен", "API トークン", "API 令牌"),
    ("Hide",
     "Verbergen", "Masquer", "Ocultar", "Nascondi", "Verbergen", "Ocultar", "Ukryj", "Сховати", "Скрыть", "隠す", "隐藏"),
    ("The token is kept in the system's password storage, never in a plain file.",
     "Der Token liegt im Passwortspeicher des Systems, nie in einer einfachen Datei.",
     "Le jeton est conservé dans le gestionnaire de mots de passe du système, jamais dans un simple fichier.",
     "El token se guarda en el almacén de contraseñas del sistema, nunca en un archivo normal.",
     "Il token è conservato nell’archivio password del sistema, mai in un file normale.",
     "Het token staat in de wachtwoordopslag van het systeem, nooit in een gewoon bestand.",
     "O token fica no armazenamento de senhas do sistema, nunca em um arquivo comum.",
     "Token jest przechowywany w systemowym magazynie haseł, nigdy w zwykłym pliku.",
     "Токен зберігається в системному сховищі паролів, а не у звичайному файлі.",
     "Токен хранится в системном хранилище паролей, а не в обычном файле.",
     "トークンはシステムのパスワード保存に保管され、通常のファイルには保存されません。",
     "令牌保存在系统密码存储中，绝不写入普通文件。"),
    ("Connected as %1.",
     "Verbunden als %1.", "Connecté en tant que %1.", "Conectado como %1.", "Connesso come %1.",
     "Verbonden als %1.", "Conectado como %1.", "Połączono jako %1.", "Підключено як %1.", "Подключено как %1.",
     "%1 として接続しました。", "已以 %1 身份连接。"),
    ("Connected to %1.",
     "Mit %1 verbunden.", "Connecté à %1.", "Conectado a %1.", "Connesso a %1.", "Verbonden met %1.",
     "Conectado a %1.", "Połączono z %1.", "Підключено до %1.", "Подключено к %1.", "%1 に接続しました。",
     "已连接到 %1。"),
    ("So the day bar and the remaining hours fit you. All of this can be changed later in the settings.",
     "Damit Tagesleiste und Reststunden zu dir passen. Alles lässt sich später in den Einstellungen ändern.",
     "Pour que la barre du jour et les heures restantes vous correspondent. Tout se modifie plus tard dans les paramètres.",
     "Para que la barra del día y las horas restantes se ajusten a ti. Todo se puede cambiar después en los ajustes.",
     "Così la barra del giorno e le ore rimanenti fanno al caso tuo. Tutto si può cambiare più tardi nelle impostazioni.",
     "Zodat de dagbalk en de resterende uren bij je passen. Alles is later in de instellingen te wijzigen.",
     "Para que a barra do dia e as horas restantes combinem com você. Tudo pode ser alterado depois nas configurações.",
     "Aby pasek dnia i pozostałe godziny pasowały do ciebie. Wszystko możesz zmienić później w ustawieniach.",
     "Щоб смуга дня й решта годин відповідали вам. Усе можна змінити пізніше в налаштуваннях.",
     "Чтобы полоса дня и оставшиеся часы подходили вам. Всё можно изменить позже в настройках.",
     "一日のバーと残り時間をあなたに合わせるためです。後から設定でいつでも変更できます。",
     "让日程条和剩余工时符合你的情况。之后都可以在设置中修改。"),
    ("Work day begins",
     "Arbeitstag beginnt", "Début de la journée de travail", "Inicio de la jornada",
     "Inizio della giornata lavorativa", "Werkdag begint", "Início do dia de trabalho", "Początek dnia pracy",
     "Початок робочого дня", "Начало рабочего дня", "勤務開始", "工作日开始"),
    ("Work day ends",
     "Arbeitstag endet", "Fin de la journée de travail", "Fin de la jornada", "Fine della giornata lavorativa",
     "Werkdag eindigt", "Fim do dia de trabalho", "Koniec dnia pracy", "Кінець робочого дня",
     "Конец рабочего дня", "勤務終了", "工作日结束"),
    ("The work day must end after it begins.",
     "Der Arbeitstag muss nach seinem Beginn enden.", "La journée de travail doit finir après son début.",
     "La jornada debe terminar después de empezar.", "La giornata lavorativa deve finire dopo l’inizio.",
     "De werkdag moet na het begin eindigen.", "O dia de trabalho deve terminar depois de começar.",
     "Dzień pracy musi kończyć się po jego rozpoczęciu.", "Робочий день має закінчуватися після початку.",
     "Рабочий день должен заканчиваться после начала.", "勤務終了は開始より後にしてください。",
     "工作日结束时间必须晚于开始时间。"),
    ("Place for sunrise and sunset",
     "Ort für Sonnenauf- und -untergang", "Lieu pour le lever et le coucher du soleil",
     "Lugar para el amanecer y el atardecer", "Luogo per alba e tramonto", "Plaats voor zonsopgang en -ondergang",
     "Local para o nascer e o pôr do sol", "Miejsce dla wschodu i zachodu słońca", "Місце для світанку й заходу сонця",
     "Место для восхода и заката", "日の出・日の入りの場所", "日出日落的地点"),
    ("City",
     "Stadt", "Ville", "Ciudad", "Città", "Stad", "Cidade", "Miasto", "Місто", "Город", "都市", "城市"),
    ("Place",
     "Ort", "Lieu", "Lugar", "Luogo", "Plaats", "Local", "Miejsce", "Місце", "Место", "場所", "地点"),
    ("Current: %1",
     "Aktuell: %1", "Actuel : %1", "Actual: %1", "Attuale: %1", "Huidig: %1", "Atual: %1", "Obecnie: %1",
     "Зараз: %1", "Сейчас: %1", "現在: %1", "当前：%1"),
    ("Remind me on work days when no timer runs",
     "An Arbeitstagen erinnern, wenn kein Timer läuft",
     "Me rappeler les jours de travail quand aucun minuteur ne tourne",
     "Recordarme los días laborables si no hay ningún temporizador en marcha",
     "Ricordamelo nei giorni lavorativi se nessun timer è attivo",
     "Herinner me op werkdagen als er geen timer loopt",
     "Lembrar-me em dias úteis quando nenhum cronômetro estiver rodando",
     "Przypominaj w dni robocze, gdy żaden licznik nie działa",
     "Нагадувати в робочі дні, коли таймер не запущено",
     "Напоминать в рабочие дни, если таймер не запущен",
     "勤務日にタイマーが動いていないときに通知する", "工作日没有计时器运行时提醒我"),
    ("Reminders need notify-send: %1",
     "Erinnerungen brauchen notify-send: %1", "Les rappels ont besoin de notify-send : %1",
     "Los recordatorios necesitan notify-send: %1", "I promemoria richiedono notify-send: %1",
     "Herinneringen hebben notify-send nodig: %1", "Os lembretes precisam do notify-send: %1",
     "Przypomnienia wymagają notify-send: %1", "Для нагадувань потрібен notify-send: %1",
     "Для напоминаний нужен notify-send: %1", "リマインダーには notify-send が必要です: %1", "提醒需要 notify-send：%1"),
    ("Reminders need notify-send (libnotify).",
     "Erinnerungen brauchen notify-send (libnotify).", "Les rappels ont besoin de notify-send (libnotify).",
     "Los recordatorios necesitan notify-send (libnotify).", "I promemoria richiedono notify-send (libnotify).",
     "Herinneringen hebben notify-send (libnotify) nodig.", "Os lembretes precisam do notify-send (libnotify).",
     "Przypomnienia wymagają notify-send (libnotify).", "Для нагадувань потрібен notify-send (libnotify).",
     "Для напоминаний нужен notify-send (libnotify).", "リマインダーには notify-send（libnotify）が必要です。",
     "提醒需要 notify-send（libnotify）。"),
    ("Skip",
     "Überspringen", "Passer", "Omitir", "Salta", "Overslaan", "Pular", "Pomiń", "Пропустити", "Пропустить",
     "スキップ", "跳过"),
    ("Check again",
     "Erneut prüfen", "Vérifier à nouveau", "Volver a comprobar", "Controlla di nuovo", "Opnieuw controleren",
     "Verificar novamente", "Sprawdź ponownie", "Перевірити знову", "Проверить снова", "再確認", "重新检查"),
    ("Next",
     "Weiter", "Suivant", "Siguiente", "Avanti", "Volgende", "Próximo", "Dalej", "Далі", "Далее", "次へ", "下一步"),
    ("Connect",
     "Verbinden", "Se connecter", "Conectar", "Connetti", "Verbinden", "Conectar", "Połącz", "Підключити",
     "Подключить", "接続", "连接"),
    ("Done",
     "Fertig", "Terminé", "Listo", "Fatto", "Klaar", "Concluir", "Gotowe", "Готово", "Готово", "完了", "完成"),
]

T_BY_LANG = {lang: {} for lang in LANGS}
for row in ROWS:
    assert len(row) == len(LANGS) + 1, row[0]
    for lang, value in zip(LANGS, row[1:]):
        T_BY_LANG[lang][row[0]] = value
