# -*- coding: utf-8 -*-
T = {
    'Project-specific': 'Специфічні для проєкту',
    'Global activities': 'Глобальні активності',
    'Plasmai': 'Plasmai',
    'Loading…': 'Завантаження…',
    'Not configured — right-click to configure': 'Не налаштовано — клацніть правою кнопкою для налаштування',
    'just now': 'щойно',
    'yesterday': 'учора',
    'Not configured': 'Не налаштовано',
    'Connecting to %1…': 'Підключення до %1…',
    'Connection problem': 'Проблема з\'єднання',
    'Connected to %1 (%2)': 'Підключено до %1 (%2)',
    'Connected to %1': 'Підключено до %1',
    'Enter valid begin and end date/time.': 'Введіть коректні дату та час початку й кінця.',
    'End must be after begin.': 'Кінець має бути після початку.',
    'Entry added': 'Запис додано',
    'Manual time entry': 'Ручний запис часу',
    '%1 left today': 'Сьогодні залишилось %1',
    '%1 over today': 'Сьогодні перебіг %1',
    '%1 left this week': 'На цьому тижні залишилось %1',
    '%1 over this week': 'На цьому тижні перебіг %1',
    'Today %1': 'Сьогодні %1',
    'Week %1': 'Тиждень %1',
    'Tracking started': 'Відстеження розпочато',
    'Switched activity': 'Активність змінено',
    'Tracking stopped (idle)': 'Відстеження зупинено (бездіяльність)',
    'Tracking stopped': 'Відстеження зупинено',
    'Stop tracking?': 'Зупинити відстеження?',
    'Stop tracking %1 · %2?': 'Зупинити відстеження %1 · %2?',
    'Statistics': 'Статистика',
    'Add entry': 'Додати запис',
    'Add a manual time entry': 'Додати ручний запис часу',
    'Show statistics': 'Показати статистику',
    'Back to timer': 'Назад до таймера',
    'Connect a time tracker': 'Підключити облік часу',
    'Add your service, server URL (if needed), and API token to start tracking from the panel.': 'Додайте сервіс, URL сервера (за потреби) та API-токен, щоб розпочати відстеження з панелі.',
    'Configure Plasmai': 'Налаштувати Plasmai',
    'Retry': 'Повторити',
    'Configure': 'Налаштувати',
    'Not tracking': 'Не відстежується',
    'Description': 'Опис',
    'Save description': 'Зберегти опис',
    'Stop': 'Зупинити',
    'Continue · %1 · %2': 'Продовжити · %1 · %2',
    'Favorites': 'Обране',
    'No favorites yet': 'Ще немає обраного',
    'Pin frequent project/activity pairs in the widget settings.': 'Закріпіть часті пари проєкт/активність у налаштуваннях віджета.',
    'Configure favorites': 'Налаштувати обране',
    '+%1 more in settings': '+%1 більше в налаштуваннях',
    'Recent': 'Нещодавні',
    'No recent activities': 'Немає нещодавніх активностей',
    'Start tracking to build your recent list.': 'Почніть відстеження, щоб сформувати список нещодавніх.',
    'Switch to another activity…': 'Перейти до іншої активності…',
    'Start something else…': 'Почати щось інше…',
    'Switch activity': 'Змінити активність',
    'New activity': 'Нова активність',
    'Select project…': 'Оберіть проєкт…',
    'Select activity…': 'Оберіть активність…',
    'Description (optional)': 'Опис (необов\'язково)',
    'Start': 'Почати',
    'Switch': 'Змінити',
    'Cancel': 'Скасувати',
    'Unknown error': 'Невідома помилка',
    'URL and API token are required': 'Потрібні URL та API-токен',
    'Configure your time tracker URL and API token': 'Налаштуйте URL та API-токен обліку часу',
    'This action is not supported for the selected service yet.': 'Ця дія ще не підтримується для обраного сервісу.',
    'Cannot reach the server. Check your network, URL, or TLS certificate.': 'Не вдається досягти сервера. Перевірте мережу, URL або TLS-сертифікат.',
    'Authentication failed. Check your API token.': 'Помилка автентифікації. Перевірте API-токен.',
    'Server not found. Check your URL.': 'Сервер не знайдено. Перевірте URL.',
    'Access denied. Your token may lack required permissions.': 'Доступ заборонено. Можливо, у вашого токена немає потрібних прав.',
    'Server error (%1).': 'Помилка сервера (%1).',
    'Request failed: %1': 'Запит не вдався: %1',
    'Request failed (%1).': 'Запит не вдався (%1).',
    'Connection': 'З\'єднання',
    'Configure a time-tracking profile. Choose Kimai, Clockify, Toggl Track, or SolidTime.': 'Налаштуйте профіль обліку часу. Оберіть Kimai, Clockify, Toggl Track або SolidTime.',
    'Profile:': 'Профіль:',
    'Profile name:': 'Назва профілю:',
    'Service:': 'Сервіс:',
    'Server URL:': 'URL сервера:',
    'API token:': 'API-токен:',
    'Paste token to save in KWallet': 'Вставте токен для збереження в KWallet',
    'Add profile': 'Додати профіль',
    'Profile %1': 'Профіль %1',
    'Remove': 'Видалити',
    'Use this profile': 'Використовувати цей профіль',
    'none': 'немає',
    'Active profile: %1': 'Активний профіль: %1',
    'Saving…': 'Збереження…',
    'Save token': 'Зберегти токен',
    'Token saved to KWallet for this profile.': 'Токен збережено в KWallet для цього профілю.',
    'Failed to save token': 'Не вдалося зберегти токен',
    'Clear token': 'Очистити токен',
    'Token removed from KWallet.': 'Токен видалено з KWallet.',
    'Failed to clear token': 'Не вдалося очистити токен',
    'Test connection': 'Перевірити з\'єднання',
    'Testing connection…': 'Перевірка з\'єднання…',
    'No API token stored. Save a token first.': 'API-токен не збережено. Спочатку збережіть токен.',
    'ok': 'ok',
    'Connected to %1 (%2).': 'Підключено до %1 (%2).',
    'Configure a Kimai URL on the Connection tab first.': 'Спочатку налаштуйте URL Kimai на вкладці «З\'єднання».',
    'Loading projects…': 'Завантаження проєктів…',
    'Save an API token on the Connection tab first.': 'Спочатку збережіть API-токен на вкладці «З\'єднання».',
    'Loaded %1 projects.': 'Завантажено %1 проєктів.',
    'Select a project to pin activities.': 'Оберіть проєкт, щоб закріпити активності.',
    'Failed to load projects.': 'Не вдалося завантажити проєкти.',
    'Loading activities…': 'Завантаження активностей…',
    'No API token available.': 'API-токен недоступний.',
    '%1 project-specific, %2 global': '%1 для проєкту, %2 глобальних',
    'Failed to load activities.': 'Не вдалося завантажити активності.',
    'Projects': 'Проєкти',
    'Reload': 'Оновити',
    'Activities — %1': 'Активності — %1',
    'Activities': 'Активності',
    'Enter a city or place name to search.': 'Введіть назву міста або місця для пошуку.',
    'Searching…': 'Пошук…',
    'Location search failed. Check your network connection.': 'Пошук місця не вдався. Перевірте мережеве з\'єднання.',
    'No places found.': 'Місць не знайдено.',
    'Display': 'Відображення',
    'Refresh interval (seconds):': 'Інтервал оновлення (секунди):',
    'Touch optimization:': 'Оптимізація для дотику:',
    'Automatic (follow Plasma tablet mode)': 'Автоматично (режим планшета Plasma)',
    'On': 'Увімкнено',
    'Off': 'Вимкнено',
    'Larger tap targets for buttons, lists, pickers, and date/time controls.': 'Більші зони дотику для кнопок, списків, вибору та дати/часу.',
    'Usual work day start:': 'Початок робочого дня:',
    'Usual work day end:': 'Кінець робочого дня:',
    'Day sparkline': 'Денна діаграма',
    'City, region, or address…': 'Місто, регіон або адреса…',
    'Search': 'Пошук',
    'Using %1': 'Використовується %1',
    'Current place: %1': 'Поточне місце: %1',
    'Latitude:': 'Широта:',
    'Longitude:': 'Довгота:',
    'Panel (taskbar)': 'Панель (панель завдань)',
    'Show:': 'Показувати:',
    'Elapsed time': 'Минулий час',
    'Project name': 'Назва проєкту',
    'Activity name': 'Назва активності',
    'Panel flyout': 'Спливаюче вікно панелі',
    'Work summary (today / week / remaining)': 'Підсумок роботи (сьогодні / тиждень / залишилось)',
    'Recent list': 'Список нещодавніх',
    'Continue last activity': 'Продовжити останню активність',
    'Start / switch activity controls': 'Керування запуском / зміною активності',
    'Desktop widget': 'Віджет робочого столу',
    'New activity picker': 'Вибір нової активності',
    'Behavior': 'Поведінка',
    'Tracking:': 'Відстеження:',
    'Confirm before stopping the timer': 'Підтверджувати перед зупинкою таймера',
    'Idle detection:': 'Виявлення бездіяльності:',
    'Stop timer when idle': 'Зупиняти таймер при бездіяльності',
    'Idle threshold (minutes):': 'Поріг бездіяльності (хвилини):',
    'Notifications:': 'Сповіщення:',
    'Notify when tracking starts': 'Сповіщати про початок відстеження',
    'Notify when tracking stops': 'Сповіщати про зупинку відстеження',
    'Notify when stopped due to idle': 'Сповіщати про зупинку через бездіяльність',
    'Back': 'Назад',
    'Create a finished entry with project, activity, and time range.': 'Створити завершений запис із проєктом, активністю та часовим діапазоном.',
    'Begin': 'Початок',
    'End': 'Кінець',
    'Duration: %1': 'Тривалість: %1',
    'Duration: —': 'Тривалість: —',
    'Duration: invalid range': 'Тривалість: недійсний діапазон',
    'Save entry': 'Зберегти запис',
    'All': 'Усі',
    'Billable': 'Оплачувані',
    'Non-billable': 'Неоплачувані',
    'Today': 'Сьогодні',
    'This week': 'Цього тижня',
    'Time by hour': 'Час за годинами',
    'Previous day': 'Попередній день',
    'Yesterday': 'Вчора',
    'Next day': 'Наступний день',
    'No time logged this day': 'Цього дня час не записано',
    'Projects by day': 'Проєкти за днями',
    'Previous week': 'Попередній тиждень',
    'Next week': 'Наступний тиждень',
    'No time logged this week': 'Цього тижня час не записано',
    'Projects by hour': 'Проєкти за годинами',
    'Weekdays and weekend — segments placed by clock time.': 'Будні та вихідні — сегменти за годинником.',
    'Weekdays — segments placed by clock time. Weekend appears when tracked.': 'Будні — сегменти за годинником. Вихідні з’являються, якщо є записи.',
    'Axis shows business hours (%1–%2); expands if work falls outside.': 'Вісь показує робочі години (%1–%2); розширюється, якщо робота поза межами.',
    'Activity distribution': 'Розподіл активностей',
    'No activities today': 'Сьогодні немає активностей',
    'No activities this week': 'Цього тижня немає активностей',
    'Time': 'Час',
    'Pick date': 'Обрати дату',
    'Pick time': 'Обрати час',
    'Hours : Minutes': 'Години : Хвилини',
    'Select': 'Вибрати',
    'Clockify cloud API is prefilled. Change only for a regional endpoint (e.g. euc1).': 'Хмарний API Clockify заповнено. Змінюйте лише для регіональної кінцевої точки (напр. euc1).',
    'Toggl Track cloud API is prefilled. Use your personal API token from Profile settings.': 'Хмарний API Toggl Track заповнено. Використовуйте особистий API-токен із налаштувань профілю.',
    'SolidTime cloud API is prefilled. For self-hosting, replace with your instance base URL.': 'Хмарний API SolidTime заповнено. Для самостійного хостингу замініть на базову URL вашого екземпляра.',
    'Self-hosted Kimai or the official hosted service (kimai.cloud). Paste the instance URL.': 'Самостійно розміщений Kimai або офіційний хостинг (kimai.cloud). Вставте URL екземпляра.',
    'API URL:': 'URL API:',
    'https://api.solidtime.io or https://time.example.com': 'https://api.solidtime.io або https://time.example.com',
    'https://kimai.example.com or https://www.kimai.cloud': 'https://kimai.example.com або https://www.kimai.cloud',
    'API key:': 'Ключ API:',
    'Make similar colors distinctive within each category': 'Зробити подібні кольори розрізнюваними в кожній категорії',
    'Similarity threshold (%):': 'Поріг подібності (%):',
    'Configure a server URL on the Connection tab first.': 'Спочатку налаштуйте URL сервера на вкладці З’єднання.',
    'Loading customers, projects, and activities…': 'Завантаження клієнтів, проєктів і активностей…',
    'Color distinction is off. Enable it in Display settings to see clash groups.': 'Розрізнення кольорів вимкнено. Увімкніть його в налаштуваннях Відображення, щоб побачити групи конфліктів.',
    'Loaded %1 customers, %2 projects, %3 activities. No similar colors within a category.': 'Завантажено %1 клієнтів, %2 проєктів, %3 активностей. Немає подібних кольорів у категорії.',
    'Loaded %1 customers, %2 projects, %3 activities. %4 clash group(s), %5 color(s) shifted.': 'Завантажено %1 клієнтів, %2 проєктів, %3 активностей. %4 груп(и) конфліктів, %5 колір(ів) зсунуто.',
    'Only colors that clash within a category are listed. Each group starts with the entry that kept the Kimai color; shifted variants follow. Unique colors are hidden.': 'Показано лише кольори, що конфліктують у категорії. Кожна група починається з запису, який зберіг колір Kimai; далі — зсунуті варіанти. Унікальні кольори приховано.',
    'Reload from server': 'Перезавантажити з сервера',
    'Distinction on · configured %1% · effective customers %2% / projects %3% / activities %4%': 'Розрізнення увімкнено · налаштовано %1% · ефективно клієнти %2% / проєкти %3% / активності %4%',
    'Distinction off — enable it in Display settings.': 'Розрізнення вимкнено — увімкніть у налаштуваннях Відображення.',
    'Customers': 'Клієнти',
    'No similar colors in this category.': 'У цій категорії немає подібних кольорів.',
    'kept': 'збережено',
    'shifted': 'зсунуто',
    'Maintenance': 'Обслуговування',
    'Edit': 'Редагувати',
    'Edit start, project, and activity': 'Редагувати початок, проєкт і активність',
    'Elapsed time updates from the new start.': 'Час відліку оновлюється від нового початку.',
    'Start must be a valid time not in the future.': 'Початок має бути коректним часом і не в майбутньому.',
    'This provider cannot update the running entry.': 'Цей постачальник не може оновити поточний запис.',
    'Enter a valid start date/time.': 'Введіть коректну дату/час початку.',
    'Start must not be in the future.': 'Початок не може бути в майбутньому.',
    'Save': 'Зберегти',
    'Current': 'Поточна',
    'Switch to': 'Перейти до',
    'Could not resolve project or activity for that entry': 'Не вдалося визначити проєкт або активність для цього запису',
    'Edit start, project, activity, billable, and tags for the running entry.': 'Змінити початок, проєкт, діяльність, оплатність і теги поточного запису.',
    'Starts or switches this activity': 'Запускає або перемикає цю діяльність',
    'A profile named "%1" already exists.': 'Профіль з назвою «%1» уже існує.',
    'Appearance': 'Вигляд',
    'Updates': 'Оновлення',
    'Colors': 'Кольори',
    'Distinction:': 'Розрізнення:',
    'Higher similarity values treat more colors as too close. Clashing items get vivid, well-spaced replacement colors. See Maintenance for clash groups.': 'Вищі значення подібності вважають більше кольорів занадто близькими. Конфліктні елементи отримують яскраві, добре рознесені кольори. Див. Обслуговування для груп конфліктів.',
    'Color distinction is available for Kimai profiles (per-customer / project / activity colors).': 'Розрізнення кольорів доступне для профілів Kimai (кольори клієнта / проєкту / діяльності).',
    'Work hours': 'Робочі години',
    'Used for the sparkline zoom and remaining-time in the work summary.': 'Для масштабу спарклайна та залишку часу в підсумку роботи.',
    'Arcs:': 'Дуги:',
    'Show sun, moon, and work arcs': 'Показати дуги сонця, місяця та роботи',
    'Hide the whole sparkline under Panel flyout or Desktop widget below.': 'Приховати весь спарклайн у меню панелі або віджеті стільниці нижче.',
    'Find location:': 'Знайти місце:',
    'Search a place or enter coordinates for sunrise/sunset coloring. Powered by OpenStreetMap Nominatim.': 'Шукайте місце або введіть координати для кольорів сходу/заходу. На базі OpenStreetMap Nominatim.',
    'Customer color pill': 'Кольорова позначка клієнта',
    'Project color pill': 'Кольорова позначка проєкту',
    'Activities shown:': 'Показані діяльності:',
    'Applies to both the panel flyout and the desktop widget.': 'Стосується меню панелі та віджета стільниці.',
    'Loading projects': 'Завантаження проєктів',
    'Color distinction is only available for Kimai profiles.': 'Розрізнення кольорів доступне лише для профілів Kimai.',
    'Color maintenance is for Kimai': 'Обслуговування кольорів стосується Kimai',
    'Clockify, Toggl, and SolidTime do not expose Kimai-style customer / project / activity colors, so clash groups and color shifting are hidden for those profiles.': 'Clockify, Toggl і SolidTime не надають кольорів клієнта / проєкту / діяльності як у Kimai, тож групи конфліктів і зсув кольорів приховані для цих профілів.',
    'Select customer…': 'Вибрати клієнта…',
    'Today\'s tracked time': 'Облік часу за сьогодні',
    'This provider cannot update descriptions.': 'Цей сервіс не може оновлювати описи.',
    'Open or close the Plasmai popup': 'Відкрити або закрити спливне вікно Plasmai',
    'Add tag…': 'Додати тег…',
    'Add tags…': 'Додати теги…',
    'Tags': 'Теги',
    'Loading tags…': 'Завантаження тегів…',
    'No tags on the server yet.': 'На сервері ще немає тегів.',
    'Create tag “%1”': 'Створити тег «%1»',
    'Already running.': 'Уже запущено.',
    'Entry actions': 'Дії запису',
    'Edit entry': 'Редагувати запис',
    'Split entry': 'Розділити запис',
    'Delete entry': 'Видалити запис',
    'Idle detection uses the session idle hint on Wayland (loginctl / ScreenSaver) and xprintidle on X11.': 'Виявлення простою використовує підказку сеансу на Wayland (loginctl / ScreenSaver) і xprintidle на X11.',
    'While tracking, shutdown and reboot wait like an unsaved file. Closing the lid or sleep is not blocked.': 'Під час обліку вимкнення й перезапуск чекають, як для незбереженого файла. Закриття кришки чи сон не блокуються.',
    'Remind me once if nothing is tracking during work hours': 'Нагадати один раз, якщо в робочі години нічого не обліковується',
    'A timer is still running': 'Таймер ще працює',
    'Idle time discarded': 'Час простою відкинуто',
    'Nothing is tracking': 'Нічого не обліковується',
    'Work hours have started. Start a timer when you begin.': 'Робочі години почалися. Запустіть таймер, коли почнете.',
    'Customer created': 'Клієнта створено',
    'Project created': 'Проєкт створено',
    'Activity created': 'Діяльність створено',
    'Entry updated': 'Запис оновлено',
    'Timesheet updated': 'Табель оновлено',
    'This provider cannot update stopped entries.': 'Цей сервіс не може оновлювати зупинені записи.',
    'Tracking in progress': 'Облік триває',
    'This provider cannot delete entries.': 'Цей сервіс не може видаляти записи.',
    'Entry deleted': 'Запис видалено',
    'Split time must be between begin and end.': 'Час розділення має бути між початком і кінцем.',
    'This provider cannot split entries.': 'Цей сервіс не може розділяти записи.',
    'Entry split': 'Запис розділено',
    'The first half was saved, but the second half could not be created.': 'Першу половину збережено, але другу не вдалося створити.',
    'Delete entry?': 'Видалити запис?',
    'Delete this finished entry? This cannot be undone.': 'Видалити цей завершений запис? Це не можна скасувати.',
    'Delete "%1 · %2"? This cannot be undone.': 'Видалити «%1 · %2»? Це не можна скасувати.',
    'The first half keeps the original start. The second half starts at the split time.': 'Перша половина зберігає початковий старт. Друга починається в момент розділення.',
    'Split at': 'Розділити о',
    'Both halves will have a positive duration.': 'Обидві половини матимуть додатну тривалість.',
    'Timer still running': 'Таймер ще працює',
    'Stop the timer before shutdown, or shut down anyway and leave it running on the server.': 'Зупиніть таймер перед вимкненням або вимкніть усе одно й залиште його на сервері.',
    'Stop timer': 'Зупинити таймер',
    'Shut down anyway': 'Вимкнути все одно',
    'You were idle': 'Ви були в простої',
    'Keep the time, discard the idle gap, or discard and continue the same activity.': 'Залишити час, відкинути проміжок простою або відкинути й продовжити ту саму діяльність.',
    'Keep time': 'Залишити час',
    'Discard idle': 'Відкинути простій',
    'Discard and continue': 'Відкинути й продовжити',
    'Start · %1 · %2': 'Старт · %1 · %2',
    'Change project, activity, range, billable, and tags for this finished entry.': 'Змінити проєкт, діяльність, діапазон, оплатність і теги цього завершеного запису.',
    'Save changes': 'Зберегти зміни',
    'Create customer': 'Створити клієнта',
    'Create activity': 'Створити діяльність',
    'Create project': 'Створити проєкт',
    'Activity will be added to %1.': 'Діяльність буде додано до %1.',
    'Name': 'Назва',
    'Customer': 'Клієнт',
}

PLURALS = {
    '%1 minute ago': ['%1 хвилину тому', '%1 хвилини тому', '%1 хвилин тому'],
    '%1 hour ago': ['%1 годину тому', '%1 години тому', '%1 годин тому'],
    '%1 day ago': ['%1 день тому', '%1 дні тому', '%1 днів тому'],
    '%1 place found.': ['Знайдено %1 місце.', 'Знайдено %1 місця.', 'Знайдено %1 місць.'],
}
