# -*- coding: utf-8 -*-
T = {
    'Project-specific': 'Специфічні для проєкту',
    'Global activities': 'Глобальні активності',
    'Plasmai': 'Plasmai',
    'Toggle Plasmai tracking': 'Перемкнути відстеження Plasmai',
    'Stop Plasmai tracking': 'Зупинити відстеження Plasmai',
    'Loading…': 'Завантаження…',
    'Not configured — right-click to configure': 'Не налаштовано — клацніть правою кнопкою для налаштування',
    'just now': 'щойно',
    'yesterday': 'учора',
    'Not configured': 'Не налаштовано',
    'Connecting to %1…': 'Підключення до %1…',
    'Connection problem': 'Проблема з\'єднання',
    'Connected to %1 (%2)': 'Підключено до %1 (%2)',
    'Connected to %1': 'Підключено до %1',
    'Enter valid begin and end date/time.': 'Введіть коректні дату та час початку й кінця.',
    'End must be after begin.': 'Кінець має бути після початку.',
    'Entry added': 'Запис додано',
    'Manual time entry': 'Ручний запис часу',
    '%1 left today': 'Сьогодні залишилось %1',
    '%1 over today': 'Сьогодні перебіг %1',
    '%1 left this week': 'На цьому тижні залишилось %1',
    '%1 over this week': 'На цьому тижні перебіг %1',
    'Today %1': 'Сьогодні %1',
    'Week %1': 'Тиждень %1',
    'Tracking started': 'Відстеження розпочато',
    'Switched activity': 'Активність змінено',
    'Tracking stopped (idle)': 'Відстеження зупинено (бездіяльність)',
    'Tracking stopped': 'Відстеження зупинено',
    'Stop the current timer before starting another': 'Зупиніть поточний таймер перед запуском іншого',
    'Stop tracking?': 'Зупинити відстеження?',
    'Stop tracking %1 · %2?': 'Зупинити відстеження %1 · %2?',
    'Statistics': 'Статистика',
    'Add entry': 'Додати запис',
    'Add a manual time entry': 'Додати ручний запис часу',
    'Show statistics': 'Показати статистику',
    'Back to timer': 'Назад до таймера',
    'Connect a time tracker': 'Підключити облік часу',
    'Add your service, server URL (if needed), and API token to start tracking from the panel.': 'Додайте сервіс, URL сервера (за потреби) та API-токен, щоб розпочати відстеження з панелі.',
    'Configure Plasmai': 'Налаштувати Plasmai',
    'Retry': 'Повторити',
    'Configure': 'Налаштувати',
    'Not tracking': 'Не відстежується',
    'Description': 'Опис',
    'Save description': 'Зберегти опис',
    'Stop': 'Зупинити',
    'Continue · %1 · %2': 'Продовжити · %1 · %2',
    'Favorites': 'Обране',
    'No favorites yet': 'Ще немає обраного',
    'Pin frequent project/activity pairs in the widget settings.': 'Закріпіть часті пари проєкт/активність у налаштуваннях віджета.',
    'Configure favorites': 'Налаштувати обране',
    '+%1 more in settings': '+%1 більше в налаштуваннях',
    'Recent': 'Нещодавні',
    'No recent activities': 'Немає нещодавніх активностей',
    'Start tracking to build your recent list.': 'Почніть відстеження, щоб сформувати список нещодавніх.',
    'Switch to another activity…': 'Перейти до іншої активності…',
    'Start something else…': 'Почати щось інше…',
    'Switch activity': 'Змінити активність',
    'New activity': 'Нова активність',
    'Select project…': 'Оберіть проєкт…',
    'Select activity…': 'Оберіть активність…',
    'Description (optional)': 'Опис (необов\'язково)',
    'Start': 'Почати',
    'Switch': 'Змінити',
    'Cancel': 'Скасувати',
    'Unknown error': 'Невідома помилка',
    'URL and API token are required': 'Потрібні URL та API-токен',
    'Configure your time tracker URL and API token': 'Налаштуйте URL та API-токен обліку часу',
    'This action is not supported for the selected service yet.': 'Ця дія ще не підтримується для обраного сервісу.',
    'Cannot reach the server. Check your network, URL, or TLS certificate.': 'Не вдається досягти сервера. Перевірте мережу, URL або TLS-сертифікат.',
    'Authentication failed. Check your API token.': 'Помилка автентифікації. Перевірте API-токен.',
    'Server not found. Check your URL.': 'Сервер не знайдено. Перевірте URL.',
    'Access denied. Your token may lack required permissions.': 'Доступ заборонено. Можливо, у вашого токена немає потрібних прав.',
    'Server error (%1).': 'Помилка сервера (%1).',
    'Request failed: %1': 'Запит не вдався: %1',
    'Request failed (%1).': 'Запит не вдався (%1).',
    'Connection': 'З\'єднання',
    'Configure a time-tracking profile. Choose Kimai, Clockify, Toggl Track, or SolidTime.': 'Налаштуйте профіль обліку часу. Оберіть Kimai, Clockify, Toggl Track або SolidTime.',
    'Profile:': 'Профіль:',
    'Profile name:': 'Назва профілю:',
    'Service:': 'Сервіс:',
    'Server URL:': 'URL сервера:',
    'API token:': 'API-токен:',
    'Paste token to save in KWallet': 'Вставте токен для збереження в KWallet',
    'Add profile': 'Додати профіль',
    'Profile %1': 'Профіль %1',
    'Remove': 'Видалити',
    'Use this profile': 'Використовувати цей профіль',
    'none': 'немає',
    'Active profile: %1': 'Активний профіль: %1',
    'Saving…': 'Збереження…',
    'Save token': 'Зберегти токен',
    'Token saved to KWallet for this profile.': 'Токен збережено в KWallet для цього профілю.',
    'Failed to save token': 'Не вдалося зберегти токен',
    'Clear token': 'Очистити токен',
    'Token removed from KWallet.': 'Токен видалено з KWallet.',
    'Failed to clear token': 'Не вдалося очистити токен',
    'Test connection': 'Перевірити з\'єднання',
    'Testing connection…': 'Перевірка з\'єднання…',
    'No API token stored. Save a token first.': 'API-токен не збережено. Спочатку збережіть токен.',
    'ok': 'ok',
    'Connected to %1 (%2).': 'Підключено до %1 (%2).',
    'Configure a Kimai URL on the Connection tab first.': 'Спочатку налаштуйте URL Kimai на вкладці «З\'єднання».',
    'Loading projects…': 'Завантаження проєктів…',
    'Save an API token on the Connection tab first.': 'Спочатку збережіть API-токен на вкладці «З\'єднання».',
    'Loaded %1 projects.': 'Завантажено %1 проєктів.',
    'Select a project to pin activities.': 'Оберіть проєкт, щоб закріпити активності.',
    'Failed to load projects.': 'Не вдалося завантажити проєкти.',
    'Loading activities…': 'Завантаження активностей…',
    'No API token available.': 'API-токен недоступний.',
    '%1 project-specific, %2 global': '%1 для проєкту, %2 глобальних',
    'Failed to load activities.': 'Не вдалося завантажити активності.',
    'Projects': 'Проєкти',
    'Reload': 'Оновити',
    'Activities — %1': 'Активності — %1',
    'Activities': 'Активності',
    'Enter a city or place name to search.': 'Введіть назву міста або місця для пошуку.',
    'Searching…': 'Пошук…',
    'Location search failed. Check your network connection.': 'Пошук місця не вдався. Перевірте мережеве з\'єднання.',
    'No places found.': 'Місць не знайдено.',
    'Display': 'Відображення',
    'Refresh interval (seconds):': 'Інтервал оновлення (секунди):',
    'Recent activities shown:': 'Показано нещодавніх активностей:',
    'Appearance:': 'Вигляд:',
    'Use desktop blur (translucent background)': 'Розмиття робочого столу (напівпрозорий фон)',
    'Touch optimization:': 'Оптимізація для дотику:',
    'Automatic (follow Plasma tablet mode)': 'Автоматично (режим планшета Plasma)',
    'On': 'Увімкнено',
    'Off': 'Вимкнено',
    'Larger tap targets for buttons, lists, pickers, and date/time controls.': 'Більші зони дотику для кнопок, списків, вибору та дати/часу.',
    'Usual work day start:': 'Початок робочого дня:',
    'Usual work day end:': 'Кінець робочого дня:',
    'Day sparkline': 'Денна діаграма',
    'Find location': 'Знайти місцезнаходження',
    'Search for a city or place to set sunrise/sunset coloring. Powered by OpenStreetMap Nominatim.': 'Знайдіть місто або місце для забарвлення сходу/заходу сонця. На базі OpenStreetMap Nominatim.',
    'City, region, or address…': 'Місто, регіон або адреса…',
    'Search': 'Пошук',
    'Using %1': 'Використовується %1',
    'Current place: %1': 'Поточне місце: %1',
    'Custom coordinates': 'Власні координати',
    'Latitude:': 'Широта:',
    'Longitude:': 'Довгота:',
    'Used to color the sparkline for sunrise and sunset at your location.': 'Використовується для забарвлення діаграми за сходом і заходом сонця у вашому місці.',
    'Panel (taskbar)': 'Панель (панель завдань)',
    'Show:': 'Показувати:',
    'Elapsed time': 'Минулий час',
    'Project name': 'Назва проєкту',
    'Activity name': 'Назва активності',
    'Panel flyout': 'Спливаюче вікно панелі',
    'Work summary (today / week / remaining)': 'Підсумок роботи (сьогодні / тиждень / залишилось)',
    'Recent list': 'Список нещодавніх',
    'Continue last activity': 'Продовжити останню активність',
    'Start / switch activity controls': 'Керування запуском / зміною активності',
    'Desktop widget': 'Віджет робочого столу',
    'New activity picker': 'Вибір нової активності',
    'Behavior': 'Поведінка',
    'Tracking:': 'Відстеження:',
    'Confirm before stopping the timer': 'Підтверджувати перед зупинкою таймера',
    'Idle detection:': 'Виявлення бездіяльності:',
    'Stop timer when idle': 'Зупиняти таймер при бездіяльності',
    'Idle threshold (minutes):': 'Поріг бездіяльності (хвилини):',
    'Notifications:': 'Сповіщення:',
    'Notify when tracking starts': 'Сповіщати про початок відстеження',
    'Notify when tracking stops': 'Сповіщати про зупинку відстеження',
    'Notify when stopped due to idle': 'Сповіщати про зупинку через бездіяльність',
    'Idle detection requires xprintidle (X11/XWayland). It may not work on pure Wayland sessions.': 'Виявлення бездіяльності потребує xprintidle (X11/XWayland). Може не працювати в чистих Wayland-сесіях.',
    'Back': 'Назад',
    'Create a finished entry with project, activity, and time range.': 'Створити завершений запис із проєктом, активністю та часовим діапазоном.',
    'Begin': 'Початок',
    'End': 'Кінець',
    'Duration: %1': 'Тривалість: %1',
    'Duration: —': 'Тривалість: —',
    'Duration: invalid range': 'Тривалість: недійсний діапазон',
    'Save entry': 'Зберегти запис',
    'All': 'Усі',
    'Billable': 'Оплачувані',
    'Non-billable': 'Неоплачувані',
    'Charts for power users. Tracking stays on the main screen.': 'Діаграми для досвідчених користувачів. Відстеження лишається на головному екрані.',
    'Show': 'Показати',
    'Today': 'Сьогодні',
    'This week': 'Цього тижня',
    'Time by hour': 'Час за годинами',
    'Previous day': 'Попередній день',
    'Yesterday': 'Вчора',
    'Next day': 'Наступний день',
    'No time logged this day': 'Цього дня час не записано',
    'Projects by day': 'Проєкти за днями',
    'Previous week': 'Попередній тиждень',
    'Next week': 'Наступний тиждень',
    'No time logged this week': 'Цього тижня час не записано',
    'Projects by hour': 'Проєкти за годинами',
    'Weekdays and weekend — segments placed by clock time.': 'Будні та вихідні — сегменти за годинником.',
    'Weekdays — segments placed by clock time. Weekend appears when tracked.': 'Будні — сегменти за годинником. Вихідні з’являються, якщо є записи.',
    'Axis shows business hours (%1–%2); expands if work falls outside.': 'Вісь показує робочі години (%1–%2); розширюється, якщо робота поза межами.',
    'Activity distribution': 'Розподіл активностей',
    'No activities today': 'Сьогодні немає активностей',
    'No activities this week': 'Цього тижня немає активностей',
    'Time': 'Час',
    'Pick date': 'Обрати дату',
    'Pick time': 'Обрати час',
    'Hours : Minutes': 'Години : Хвилини',
    'Select': 'Вибрати',
    'Today\'s tracked time across 24 hours': 'Сьогоднішній записаний час за 24 години',
    'Clockify cloud API is prefilled. Change only for a regional endpoint (e.g. euc1).': 'Хмарний API Clockify заповнено. Змінюйте лише для регіональної кінцевої точки (напр. euc1).',
    'Toggl Track cloud API is prefilled. Use your personal API token from Profile settings.': 'Хмарний API Toggl Track заповнено. Використовуйте особистий API-токен із налаштувань профілю.',
    'SolidTime cloud API is prefilled. For self-hosting, replace with your instance base URL.': 'Хмарний API SolidTime заповнено. Для самостійного хостингу замініть на базову URL вашого екземпляра.',
    'Self-hosted Kimai or the official hosted service (kimai.cloud). Paste the instance URL.': 'Самостійно розміщений Kimai або офіційний хостинг (kimai.cloud). Вставте URL екземпляра.',
    'API URL:': 'URL API:',
    'https://api.solidtime.io or https://time.example.com': 'https://api.solidtime.io або https://time.example.com',
    'https://kimai.example.com or https://www.kimai.cloud': 'https://kimai.example.com або https://www.kimai.cloud',
    'API key:': 'Ключ API:',
    'Colors:': 'Кольори:',
    'Make similar colors distinctive within each category': 'Зробити подібні кольори розрізнюваними в кожній категорії',
    'Similarity threshold (%):': 'Поріг подібності (%):',
    'Higher similarity values treat more colors as too close. Clashing items get vivid, well-spaced replacement colors (not washed hue-shifts). If too many items cannot fit, the threshold is lowered automatically down to 12%. See Maintenance for clash groups.': 'Вищі значення подібності вважають більше кольорів занадто близькими. Конфліктні елементи отримують яскраві, добре рознесені замінні кольори (не бліді зсуви відтінку). Якщо занадто багато елементів не вміщується, поріг автоматично знижується до 12%. Див. Обслуговування для груп конфліктів.',
    'Configure a server URL on the Connection tab first.': 'Спочатку налаштуйте URL сервера на вкладці З’єднання.',
    'Loading customers, projects, and activities…': 'Завантаження клієнтів, проєктів і активностей…',
    'Color distinction is off. Enable it in Display settings to see clash groups.': 'Розрізнення кольорів вимкнено. Увімкніть його в налаштуваннях Відображення, щоб побачити групи конфліктів.',
    'Loaded %1 customers, %2 projects, %3 activities. No similar colors within a category.': 'Завантажено %1 клієнтів, %2 проєктів, %3 активностей. Немає подібних кольорів у категорії.',
    'Loaded %1 customers, %2 projects, %3 activities. %4 clash group(s), %5 color(s) shifted.': 'Завантажено %1 клієнтів, %2 проєктів, %3 активностей. %4 груп(и) конфліктів, %5 колір(ів) зсунуто.',
    'Only colors that clash within a category are listed. Each group starts with the entry that kept the Kimai color; shifted variants follow. Unique colors are hidden.': 'Показано лише кольори, що конфліктують у категорії. Кожна група починається з запису, який зберіг колір Kimai; далі — зсунуті варіанти. Унікальні кольори приховано.',
    'Reload from server': 'Перезавантажити з сервера',
    'Distinction on · configured %1% · effective customers %2% / projects %3% / activities %4%': 'Розрізнення увімкнено · налаштовано %1% · ефективно клієнти %2% / проєкти %3% / активності %4%',
    'Distinction off — enable it in Display settings.': 'Розрізнення вимкнено — увімкніть у налаштуваннях Відображення.',
    'Customers': 'Клієнти',
    'No similar colors in this category.': 'У цій категорії немає подібних кольорів.',
    'kept': 'збережено',
    'shifted': 'зсунуто',
    'Maintenance': 'Обслуговування',
    'Edit': 'Редагувати',
    'Edit start, project, and activity': 'Редагувати початок, проєкт і активність',
    'Edit start time, project, and activity for the running entry.': 'Редагувати час початку, проєкт і активність поточного запису.',
    'Elapsed time updates from the new start.': 'Час відліку оновлюється від нового початку.',
    'Start must be a valid time not in the future.': 'Початок має бути коректним часом і не в майбутньому.',
    'This provider cannot update the running entry.': 'Цей постачальник не може оновити поточний запис.',
    'Enter a valid start date/time.': 'Введіть коректну дату/час початку.',
    'Start must not be in the future.': 'Початок не може бути в майбутньому.',
    'Save': 'Зберегти',

    'Current': 'Поточна',
    'Switch to': 'Перейти до',
    'Already tracking this activity': 'Ця активність уже відстежується',
    'Could not resolve project or activity for that entry': 'Не вдалося визначити проєкт або активність для цього запису',
    'Switch activity?': 'Змінити активність?',
}

PLURALS = {
    '%1 minute ago': ['%1 хвилину тому', '%1 хвилини тому', '%1 хвилин тому'],
    '%1 hour ago': ['%1 годину тому', '%1 години тому', '%1 годин тому'],
    '%1 day ago': ['%1 день тому', '%1 дні тому', '%1 днів тому'],
    '%1 place found.': ['Знайдено %1 місце.', 'Знайдено %1 місця.', 'Знайдено %1 місць.'],
}
