# -*- coding: utf-8 -*-
T = {
    'Project-specific': '项目专用',
    'Global activities': '全局活动',
    'Plasmai': 'Plasmai',
    'Loading…': '加载中…',
    'Not configured — right-click to configure': '未配置 — 右键点击进行配置',
    'just now': '刚刚',
    'yesterday': '昨天',
    'Not configured': '未配置',
    'Connecting to %1…': '正在连接 %1…',
    'Connection problem': '连接问题',
    'Connected to %1 (%2)': '已连接到 %1 (%2)',
    'Connected to %1': '已连接到 %1',
    'Enter valid begin and end date/time.': '请输入有效的开始和结束日期/时间。',
    'End must be after begin.': '结束时间必须晚于开始时间。',
    'Entry added': '已添加条目',
    'Manual time entry': '手动时间条目',
    '%1 left today': '今日剩余 %1',
    '%1 over today': '今日超出 %1',
    '%1 left this week': '本周剩余 %1',
    '%1 over this week': '本周超出 %1',
    'Today %1': '今日 %1',
    'Week %1': '周 %1',
    'Tracking started': '已开始计时',
    'Switched activity': '已切换活动',
    'Tracking stopped (idle)': '计时已停止（空闲）',
    'Tracking stopped': '计时已停止',
    'Stop tracking?': '停止计时？',
    'Stop tracking %1 · %2?': '停止计时 %1 · %2？',
    'Statistics': '统计',
    'Add entry': '添加条目',
    'Add a manual time entry': '添加手动时间条目',
    'Show statistics': '显示统计',
    'Back to timer': '返回计时器',
    'Connect a time tracker': '连接时间跟踪服务',
    'Add your service, server URL (if needed), and API token to start tracking from the panel.': '添加您的服务、服务器 URL（如需要）和 API 令牌，即可从面板开始计时。',
    'Configure Plasmai': '配置 Plasmai',
    'Retry': '重试',
    'Configure': '配置',
    'Not tracking': '未在计时',
    'Description': '描述',
    'Save description': '保存描述',
    'Stop': '停止',
    'Continue · %1 · %2': '继续 · %1 · %2',
    'Favorites': '收藏',
    'No favorites yet': '尚无收藏',
    'Pin frequent project/activity pairs in the widget settings.': '在小部件设置中固定常用的项目/活动组合。',
    'Configure favorites': '配置收藏',
    '+%1 more in settings': '设置中还有 +%1 项',
    'Recent': '最近',
    'No recent activities': '无最近活动',
    'Start tracking to build your recent list.': '开始计时可建立最近列表。',
    'Switch to another activity…': '切换到其他活动…',
    'Start something else…': '开始其他工作…',
    'Switch activity': '切换活动',
    'New activity': '新活动',
    'Select project…': '选择项目…',
    'Select activity…': '选择活动…',
    'Description (optional)': '描述（可选）',
    'Start': '开始',
    'Switch': '切换',
    'Cancel': '取消',
    'Unknown error': '未知错误',
    'URL and API token are required': '需要 URL 和 API 令牌',
    'Configure your time tracker URL and API token': '配置时间跟踪服务的 URL 和 API 令牌',
    'This action is not supported for the selected service yet.': '所选服务尚不支持此操作。',
    'Cannot reach the server. Check your network, URL, or TLS certificate.': '无法访问服务器。请检查网络、URL 或 TLS 证书。',
    'Authentication failed. Check your API token.': '认证失败。请检查 API 令牌。',
    'Server not found. Check your URL.': '未找到服务器。请检查 URL。',
    'Access denied. Your token may lack required permissions.': '访问被拒绝。您的令牌可能缺少所需权限。',
    'Server error (%1).': '服务器错误 (%1)。',
    'Request failed: %1': '请求失败：%1',
    'Request failed (%1).': '请求失败 (%1)。',
    'Connection': '连接',
    'Configure a time-tracking profile. Choose Kimai, Clockify, Toggl Track, or SolidTime.': '配置时间跟踪配置文件。请选择 Kimai、Clockify、Toggl Track 或 SolidTime。',
    'Profile:': '配置文件：',
    'Profile name:': '配置文件名称：',
    'Service:': '服务：',
    'Server URL:': '服务器 URL：',
    'API token:': 'API 令牌：',
    'Paste token to save in KWallet': '粘贴令牌以保存到 KWallet',
    'Add profile': '添加配置文件',
    'Profile %1': '配置文件 %1',
    'Remove': '移除',
    'Use this profile': '使用此配置文件',
    'none': '无',
    'Active profile: %1': '活动配置文件：%1',
    'Saving…': '保存中…',
    'Save token': '保存令牌',
    'Token saved to KWallet for this profile.': '此配置文件的令牌已保存到 KWallet。',
    'Failed to save token': '保存令牌失败',
    'Clear token': '清除令牌',
    'Token removed from KWallet.': '令牌已从 KWallet 中移除。',
    'Failed to clear token': '清除令牌失败',
    'Test connection': '测试连接',
    'Testing connection…': '正在测试连接…',
    'No API token stored. Save a token first.': '未存储 API 令牌。请先保存令牌。',
    'ok': 'ok',
    'Connected to %1 (%2).': '已连接到 %1 (%2)。',
    'Configure a Kimai URL on the Connection tab first.': '请先在“连接”选项卡上配置 Kimai URL。',
    'Loading projects…': '正在加载项目…',
    'Save an API token on the Connection tab first.': '请先在“连接”选项卡上保存 API 令牌。',
    'Loaded %1 projects.': '已加载 %1 个项目。',
    'Select a project to pin activities.': '选择项目以固定活动。',
    'Failed to load projects.': '加载项目失败。',
    'Loading activities…': '正在加载活动…',
    'No API token available.': '无可用 API 令牌。',
    '%1 project-specific, %2 global': '%1 个项目专用，%2 个全局',
    'Failed to load activities.': '加载活动失败。',
    'Projects': '项目',
    'Reload': '重新加载',
    'Activities — %1': '活动 — %1',
    'Activities': '活动',
    'Enter a city or place name to search.': '输入城市或地名进行搜索。',
    'Searching…': '搜索中…',
    'Location search failed. Check your network connection.': '位置搜索失败。请检查网络连接。',
    'No places found.': '未找到地点。',
    'Display': '显示',
    'Refresh interval (seconds):': '刷新间隔（秒）：',
    'Touch optimization:': '触控优化：',
    'Automatic (follow Plasma tablet mode)': '自动（跟随 Plasma 平板模式）',
    'On': '开',
    'Off': '关',
    'Larger tap targets for buttons, lists, pickers, and date/time controls.': '为按钮、列表、选择器和日期/时间控件提供更大的触控目标。',
    'Usual work day start:': '通常工作日开始：',
    'Usual work day end:': '通常工作日结束：',
    'Day sparkline': '每日 sparkline',
    'City, region, or address…': '城市、地区或地址…',
    'Search': '搜索',
    'Using %1': '使用 %1',
    'Current place: %1': '当前地点：%1',
    'Latitude:': '纬度：',
    'Longitude:': '经度：',
    'Panel (taskbar)': '面板（任务栏）',
    'Show:': '显示：',
    'Elapsed time': '已用时间',
    'Project name': '项目名称',
    'Activity name': '活动名称',
    'Panel flyout': '面板弹出窗口',
    'Work summary (today / week / remaining)': '工作摘要（今日 / 本周 / 剩余）',
    'Recent list': '最近列表',
    'Continue last activity': '继续上次活动',
    'Start / switch activity controls': '开始 / 切换活动控件',
    'Desktop widget': '桌面小部件',
    'New activity picker': '新活动选择器',
    'Behavior': '行为',
    'Tracking:': '计时：',
    'Confirm before stopping the timer': '停止计时器前确认',
    'Idle detection:': '空闲检测：',
    'Stop timer when idle': '空闲时停止计时器',
    'Idle threshold (minutes):': '空闲阈值（分钟）：',
    'Notifications:': '通知：',
    'Notify when tracking starts': '开始计时时通知',
    'Notify when tracking stops': '停止计时时通知',
    'Notify when stopped due to idle': '因空闲停止时通知',
    'Back': '返回',
    'Create a finished entry with project, activity, and time range.': '创建包含项目、活动和时间范围的已完成条目。',
    'Begin': '开始',
    'End': '结束',
    'Duration: %1': '时长：%1',
    'Duration: —': '时长：—',
    'Duration: invalid range': '时长：无效范围',
    'Save entry': '保存条目',
    'All': '全部',
    'Billable': '可计费',
    'Non-billable': '不可计费',
    'Today': '今天',
    'This week': '本周',
    'Time by hour': '按小时统计',
    'Previous day': '上一天',
    'Yesterday': '昨天',
    'Next day': '下一天',
    'No time logged this day': '当天没有记录时间',
    'Projects by day': '按日项目',
    'Previous week': '上一周',
    'Next week': '下一周',
    'No time logged this week': '本周没有记录时间',
    'Projects by hour': '按小时项目',
    'Weekdays and weekend — segments placed by clock time.': '工作日与周末——按钟点放置时间段。',
    'Weekdays — segments placed by clock time. Weekend appears when tracked.': '工作日——按钟点放置时间段。有记录时显示周末。',
    'Axis shows business hours (%1–%2); expands if work falls outside.': '坐标轴显示工作时间（%1–%2）；若工作超出范围则扩展。',
    'Activity distribution': '活动分布',
    'No activities today': '今天没有活动',
    'No activities this week': '本周没有活动',
    'Time': '时间',
    'Pick date': '选择日期',
    'Pick time': '选择时间',
    'Hours : Minutes': '时 : 分',
    'Select': '选择',
    'Clockify cloud API is prefilled. Change only for a regional endpoint (e.g. euc1).': '已预填 Clockify 云 API。仅在使用区域端点（例如 euc1）时更改。',
    'Toggl Track cloud API is prefilled. Use your personal API token from Profile settings.': '已预填 Toggl Track 云 API。请使用个人资料设置中的个人 API 令牌。',
    'SolidTime cloud API is prefilled. For self-hosting, replace with your instance base URL.': '已预填 SolidTime 云 API。自托管时请替换为你的实例基址 URL。',
    'Self-hosted Kimai or the official hosted service (kimai.cloud). Paste the instance URL.': '自托管 Kimai 或官方托管服务（kimai.cloud）。粘贴实例 URL。',
    'API URL:': 'API URL：',
    'https://api.solidtime.io or https://time.example.com': 'https://api.solidtime.io 或 https://time.example.com',
    'https://kimai.example.com or https://www.kimai.cloud': 'https://kimai.example.com 或 https://www.kimai.cloud',
    'API key:': 'API 密钥：',
    'Make similar colors distinctive within each category': '在每个分类内让相近颜色更易区分',
    'Similarity threshold (%):': '相似度阈值（%）：',
    'Configure a server URL on the Connection tab first.': '请先在“连接”选项卡中配置服务器 URL。',
    'Loading customers, projects, and activities…': '正在加载客户、项目和活动…',
    'Color distinction is off. Enable it in Display settings to see clash groups.': '颜色区分已关闭。请在显示设置中启用以查看冲突分组。',
    'Loaded %1 customers, %2 projects, %3 activities. No similar colors within a category.': '已加载 %1 个客户、%2 个项目、%3 个活动。分类内没有相近颜色。',
    'Loaded %1 customers, %2 projects, %3 activities. %4 clash group(s), %5 color(s) shifted.': '已加载 %1 个客户、%2 个项目、%3 个活动。%4 个冲突组，%5 个颜色已偏移。',
    'Only colors that clash within a category are listed. Each group starts with the entry that kept the Kimai color; shifted variants follow. Unique colors are hidden.': '仅列出分类内冲突的颜色。每组以保留 Kimai 颜色的条目开头，其后为偏移变体。唯一颜色已隐藏。',
    'Reload from server': '从服务器重新加载',
    'Distinction on · configured %1% · effective customers %2% / projects %3% / activities %4%': '区分开启 · 配置 %1% · 实际 客户 %2% / 项目 %3% / 活动 %4%',
    'Distinction off — enable it in Display settings.': '区分关闭——请在显示设置中启用。',
    'Customers': '客户',
    'No similar colors in this category.': '此分类中没有相近颜色。',
    'kept': '保留',
    'shifted': '已偏移',
    'Maintenance': '维护',
    'Edit': '编辑',
    'Edit start, project, and activity': '编辑开始时间、项目和活动',
    'Elapsed time updates from the new start.': '已用时间会根据新的开始时间更新。',
    'Start must be a valid time not in the future.': '开始时间必须有效且不能是未来时间。',
    'This provider cannot update the running entry.': '此服务无法更新进行中的条目。',
    'Enter a valid start date/time.': '请输入有效的开始日期/时间。',
    'Start must not be in the future.': '开始时间不能是未来。',
    'Save': '保存',
    'Current': '当前',
    'Switch to': '切换到',
    'Could not resolve project or activity for that entry': '无法解析该条目的项目或活动',
    'Edit start, project, activity, billable, and tags for the running entry.': '编辑进行中条目的开始时间、项目、活动、计费和标签。',
    'Starts or switches this activity': '开始或切换到此活动',
    'A profile named "%1" already exists.': '已存在名为“%1”的配置文件。',
    'Appearance': '外观',
    'Updates': '更新',
    'Colors': '颜色',
    'Distinction:': '区分：',
    'Higher similarity values treat more colors as too close. Clashing items get vivid, well-spaced replacement colors. See Maintenance for clash groups.': '更高的相似度会把更多颜色视为过近。冲突项会换成鲜艳、间隔均匀的颜色。冲突组见“维护”。',
    'Color distinction is available for Kimai profiles (per-customer / project / activity colors).': '颜色区分适用于 Kimai 配置文件（按客户/项目/活动着色）。',
    'Work hours': '工作时间',
    'Used for the sparkline zoom and remaining-time in the work summary.': '用于迷你图缩放和工作摘要中的剩余时间。',
    'Arcs:': '弧线：',
    'Show sun, moon, and work arcs': '显示太阳、月亮和工作弧',
    'Hide the whole sparkline under Panel flyout or Desktop widget below.': '在下方的面板弹出或桌面小组件中隐藏整条迷你图。',
    'Find location:': '查找地点：',
    'Search a place or enter coordinates for sunrise/sunset coloring. Powered by OpenStreetMap Nominatim.': '搜索地点或输入坐标，用于日出/日落着色。由 OpenStreetMap Nominatim 提供。',
    'Customer color pill': '客户颜色点',
    'Project color pill': '项目颜色点',
    'Activities shown:': '显示的活动：',
    'Applies to both the panel flyout and the desktop widget.': '同时适用于面板弹出和桌面小组件。',
    'Loading projects': '正在加载项目',
    'Color distinction is only available for Kimai profiles.': '颜色区分仅适用于 Kimai 配置文件。',
    'Color maintenance is for Kimai': '颜色维护仅适用于 Kimai',
    'Clockify, Toggl, and SolidTime do not expose Kimai-style customer / project / activity colors, so clash groups and color shifting are hidden for those profiles.': 'Clockify、Toggl 和 SolidTime 没有 Kimai 那样的客户/项目/活动颜色，因此这些配置文件会隐藏冲突组和颜色偏移。',
    'Select customer…': '选择客户…',
    'Today\'s tracked time': '今日已记录时间',
    'This provider cannot update descriptions.': '此服务无法更新描述。',
    'Open or close the Plasmai popup': '打开或关闭 Plasmai 弹出窗口',
    'Add tag…': '添加标签…',
    'Add tags…': '添加标签…',
    'Tags': '标签',
    'Loading tags…': '正在加载标签…',
    'No tags on the server yet.': '服务器上还没有标签。',
    'Create tag “%1”': '创建标签“%1”',
    'Already running.': '已在进行中。',
    'Entry actions': '条目操作',
    'Edit entry': '编辑条目',
    'Split entry': '拆分条目',
    'Delete entry': '删除条目',
    'Idle detection uses the session idle hint on Wayland (loginctl / ScreenSaver) and xprintidle on X11.': '空闲检测在 Wayland 上使用会话空闲提示（loginctl / ScreenSaver），在 X11 上使用 xprintidle。',
    'Remind me once if nothing is tracking during work hours': '工作时间内若没有在计时，提醒一次',
    'Idle time discarded': '已丢弃空闲时间',
    'Nothing is tracking': '当前没有计时',
    'Work hours have started. Start a timer when you begin.': '工作时间已开始。开始工作时请启动计时器。',
    'Customer created': '已创建客户',
    'Project created': '已创建项目',
    'Activity created': '已创建活动',
    'Entry updated': '已更新条目',
    'Timesheet updated': '已更新工时表',
    'This provider cannot update stopped entries.': '此服务无法更新已停止的条目。',
    'Tracking in progress': '正在计时',
    'This provider cannot delete entries.': '此服务无法删除条目。',
    'Entry deleted': '已删除条目',
    'Split time must be between begin and end.': '拆分时间必须介于开始和结束之间。',
    'This provider cannot split entries.': '此服务无法拆分条目。',
    'Entry split': '已拆分条目',
    'The first half was saved, but the second half could not be created.': '前半段已保存，但无法创建后半段。',
    'Delete entry?': '删除此条目？',
    'Delete this finished entry? This cannot be undone.': '删除这条已结束的条目？此操作无法撤销。',
    'Delete "%1 · %2"? This cannot be undone.': '删除“%1 · %2”？此操作无法撤销。',
    'The first half keeps the original start. The second half starts at the split time.': '前半段保留原来的开始时间。后半段从拆分时刻开始。',
    'Split at': '拆分于',
    'Both halves will have a positive duration.': '两段都会有正的时长。',
    'You were idle': '你处于空闲状态',
    'Keep the time, discard the idle gap, or discard and continue the same activity.': '保留这段时间、丢弃空闲间隔，或丢弃后继续同一活动。',
    'Keep time': '保留时间',
    'Discard idle': '丢弃空闲',
    'Discard and continue': '丢弃并继续',
    'Start · %1 · %2': '开始 · %1 · %2',
    'Change project, activity, range, billable, and tags for this finished entry.': '更改这条已结束条目的项目、活动、时间范围、计费和标签。',
    'Save changes': '保存更改',
    'Create customer': '创建客户',
    'Create activity': '创建活动',
    'Create project': '创建项目',
    'Activity will be added to %1.': '活动将添加到 %1。',
    'Name': '名称',
    'Customer': '客户',
}

PLURALS = {
    '%1 minute ago': ['%1 分钟前'],
    '%1 hour ago': ['%1 小时前'],
    '%1 day ago': ['%1 天前'],
    '%1 place found.': ['找到 %1 个地点。'],
}
