#!/bin/sh
# Increment build.number and regenerate contents/code/buildInfo.js
set -eu

ROOT="$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

BUILD_FILE="$ROOT/build.number"
PREV="$(cat "$BUILD_FILE" 2>/dev/null || echo 0)"
BUILD=$((PREV + 1))
echo "$BUILD" > "$BUILD_FILE"

VERSION="$(sed -n 's/.*"Version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' metadata.json | head -n1)"
if [ -z "$VERSION" ]; then
    echo "error: could not read Version from metadata.json" >&2
    exit 1
fi

cat > "$ROOT/contents/code/buildInfo.js" <<EOF
.pragma library

/** Auto-generated by scripts/bump-build.sh — do not edit manually. */
var VERSION = "$VERSION"
var BUILD = $BUILD
EOF

# Keep metadata.json in sync for external tools (optional custom field).
python3 - <<PY
import json
from pathlib import Path

path = Path("$ROOT/metadata.json")
data = json.loads(path.read_text(encoding="utf-8"))
data.setdefault("KPlugin", {})["Build"] = "$BUILD"
path.write_text(json.dumps(data, indent=4, ensure_ascii=False) + "\n", encoding="utf-8")
PY

echo "$BUILD"
